city_streets["anjero"] = {builds: [{street: "Ангарская ул", build: "11"},
{street: "Беловская ул", build: "15"},
{street: "Беловская ул", build: "17"},
{street: "Беловская ул", build: "19А"},
{street: "Беловская ул", build: "20"},
{street: "Беловская ул", build: "21"},
{street: "Беловская ул", build: "22"},
{street: "Беловская ул", build: "22А"},
{street: "Беловская ул", build: "26"},
{street: "Ванцетти ул", build: "4"},
{street: "Ванцетти ул", build: "5"},
{street: "Ванцетти ул", build: "6"},
{street: "Ванцетти ул", build: "7"},
{street: "Ватутина ул", build: "1А"},
{street: "Ватутина ул", build: "25"},
{street: "Ватутина ул", build: "27"},
{street: "Ватутина ул", build: "29"},
{street: "Верный пер ", build: "1"},
{street: "Верный пер ", build: "5"},
{street: "Водоканальная ул", build: "27"},
{street: "Водоканальная ул", build: "27А"},
{street: "Водоканальная ул", build: "65"},
{street: "Водоканальная ул", build: "67"},
{street: "Водоканальная ул", build: "69"},
{street: "Водоканальная ул", build: "7"},
{street: "Водоканальная ул", build: "71"},
{street: "Водоканальная ул", build: "7А"},
{street: "Войкова ул", build: "3"},
{street: "Войкова ул", build: "5"},
{street: "Воронежская ул", build: "79"},
{street: "Воронежская ул", build: "80"},
{street: "Воронежская ул", build: "82"},
{street: "Воронежская ул", build: "84"},
{street: "Воронежский пер ", build: "2"},
{street: "Гагарина ул", build: "1"},
{street: "Газовый пер ", build: "1"},
{street: "Газовый пер ", build: "11"},
{street: "Газовый пер ", build: "15"},
{street: "Газовый пер ", build: "3"},
{street: "Газовый пер ", build: "5"},
{street: "Газовый пер ", build: "7"},
{street: "Газовый пер ", build: "9"},
{street: "Герцена ул", build: "30"},
{street: "Герцена ул", build: "34"},
{street: "Герцена ул", build: "36"},
{street: "Герцена ул", build: "6"},
{street: "Гурьевская ул", build: "11"},
{street: "Гурьевская ул", build: "5"},
{street: "Гурьевская ул", build: "7"},
{street: "Данковская ул", build: "8"},
{street: "Деповская ул", build: "1"},
{street: "Деповская ул", build: "2"},
{street: "Желябова ул", build: "1"},
{street: "Желябова ул", build: "11"},
{street: "Желябова ул", build: "13"},
{street: "Желябова ул", build: "15"},
{street: "Желябова ул", build: "17"},
{street: "Желябова ул", build: "19"},
{street: "Желябова ул", build: "3"},
{street: "Желябова ул", build: "30"},
{street: "Желябова ул", build: "32"},
{street: "Желябова ул", build: "34"},
{street: "Желябова ул", build: "34А"},
{street: "Желябова ул", build: "36"},
{street: "Желябова ул", build: "36А"},
{street: "Желябова ул", build: "38"},
{street: "Желябова ул", build: "3А"},
{street: "Желябова ул", build: "3Б"},
{street: "Желябова ул", build: "5"},
{street: "Желябова ул", build: "7"},
{street: "Желябова ул", build: "7А"},
{street: "Желябова ул", build: "9"},
{street: "Желябова ул", build: "9А"},
{street: "Заречная ул", build: "16"},
{street: "Им 137 Отдельной Стрелковой Бригады ул", build: "1"},
{street: "Им 137 Отдельной Стрелковой Бригады ул", build: "11"},
{street: "Им 137 Отдельной Стрелковой Бригады ул", build: "13"},
{street: "Им 137 Отдельной Стрелковой Бригады ул", build: "3"},
{street: "Им 137 Отдельной Стрелковой Бригады ул", build: "5"},
{street: "Им 137 Отдельной Стрелковой Бригады ул", build: "9"},
{street: "Им 50-Летия Влксм ул", build: "3"},
{street: "Им 50-Летия Влксм ул", build: "4"},
{street: "Им 50-Летия Влксм ул", build: "5"},
{street: "Им 50-Летия Октября ул", build: "1"},
{street: "Им 50-Летия Октября ул", build: "10"},
{street: "Им 50-Летия Октября ул", build: "11"},
{street: "Им 50-Летия Октября ул", build: "12"},
{street: "Им 50-Летия Октября ул", build: "13"},
{street: "Им 50-Летия Октября ул", build: "14"},
{street: "Им 50-Летия Октября ул", build: "15"},
{street: "Им 50-Летия Октября ул", build: "2"},
{street: "Им 50-Летия Октября ул", build: "2А"},
{street: "Им 50-Летия Октября ул", build: "3"},
{street: "Им 50-Летия Октября ул", build: "4"},
{street: "Им 50-Летия Октября ул", build: "5"},
{street: "Им 50-Летия Октября ул", build: "6"},
{street: "Им 50-Летия Октября ул", build: "6А"},
{street: "Им 50-Летия Октября ул", build: "7"},
{street: "Им 50-Летия Октября ул", build: "8"},
{street: "Им 50-Летия Октября ул", build: "9"},
{street: "К.Маркса ул", build: "10"},
{street: "К.Маркса ул", build: "11"},
{street: "К.Маркса ул", build: "12"},
{street: "К.Маркса ул", build: "14"},
{street: "К.Маркса ул", build: "16"},
{street: "К.Маркса ул", build: "18А"},
{street: "К.Маркса ул", build: "2"},
{street: "К.Маркса ул", build: "20"},
{street: "К.Маркса ул", build: "22"},
{street: "К.Маркса ул", build: "4"},
{street: "К.Маркса ул", build: "6"},
{street: "К.Маркса ул", build: "7"},
{street: "К.Маркса ул", build: "7Б"},
{street: "К.Маркса ул", build: "8"},
{street: "К.Маркса ул", build: "9"},
{street: "Кадровая ул", build: "15"},
{street: "Кадровая ул", build: "16"},
{street: "Кадровая ул", build: "49"},
{street: "Камышинская ул", build: "11"},
{street: "Камышинская ул", build: "13"},
{street: "Камышинская ул", build: "14"},
{street: "Камышинская ул", build: "16"},
{street: "Камышинская ул", build: "17"},
{street: "Кемсеть ул", build: "5"},
{street: "Киселевская ул", build: "10"},
{street: "Киселевская ул", build: "12"},
{street: "Киселевская ул", build: "15"},
{street: "Киселевская ул", build: "18"},
{street: "Киселевская ул", build: "18А"},
{street: "Киселевская ул", build: "20"},
{street: "Киселевская ул", build: "8"},
{street: "Киселевская ул", build: "9"},
{street: "Китатская ул", build: "14"},
{street: "Кольчугинская ул", build: "14"},
{street: "Кольчугинская ул", build: "16"},
{street: "Коминтерна ул", build: "10"},
{street: "Крайняя ул", build: "1"},
{street: "Крайняя ул", build: "3"},
{street: "Крайняя ул", build: "5"},
{street: "Крестьянская ул", build: "68А"},
{street: "Крестьянская ул", build: "68Б"},
{street: "Крестьянская ул", build: "84"},
{street: "Крестьянская ул", build: "86"},
{street: "Крестьянская ул", build: "88"},
{street: "Крылова пер ", build: "3"},
{street: "Крылова ул", build: "1"},
{street: "Крылова ул", build: "10"},
{street: "Крылова ул", build: "11"},
{street: "Крылова ул", build: "12"},
{street: "Крылова ул", build: "13"},
{street: "Крылова ул", build: "14"},
{street: "Крылова ул", build: "15"},
{street: "Крылова ул", build: "17"},
{street: "Крылова ул", build: "17А"},
{street: "Крылова ул", build: "19"},
{street: "Крылова ул", build: "21"},
{street: "Крылова ул", build: "23"},
{street: "Крылова ул", build: "25"},
{street: "Крылова ул", build: "27"},
{street: "Крылова ул", build: "29"},
{street: "Крылова ул", build: "5"},
{street: "Крылова ул", build: "7"},
{street: "Крылова ул", build: "8"},
{street: "Крылова ул", build: "9"},
{street: "Кубанская ул", build: "1"},
{street: "Кубанская ул", build: "2"},
{street: "Кубанская ул", build: "2А"},
{street: "Кубанская ул", build: "4"},
{street: "Кубанская ул", build: "6"},
{street: "Куйбышева ул", build: "51"},
{street: "Куйбышева ул", build: "63"},
{street: "Куйбышева ул", build: "65"},
{street: "Куйбышева ул", build: "65А"},
{street: "Куйбышева ул", build: "67"},
{street: "Куйбышева ул", build: "67А"},
{street: "Куйбышева ул", build: "69"},
{street: "Куйбышева ул", build: "71"},
{street: "Куйбышева ул", build: "73"},
{street: "Куйбышева ул", build: "90"},
{street: "Куйбышева ул", build: "92"},
{street: "Куйбышева ул", build: "94"},
{street: "Л.Чайкиной ул", build: "50"},
{street: "Лазо ул", build: "11"},
{street: "Лазо ул", build: "12"},
{street: "Лазо ул", build: "13"},
{street: "Лазо ул", build: "14"},
{street: "Лазо ул", build: "16"},
{street: "Лазо ул", build: "17"},
{street: "Лазо ул", build: "18"},
{street: "Лазо ул", build: "19"},
{street: "Лазо ул", build: "2"},
{street: "Лазо ул", build: "20"},
{street: "Лазо ул", build: "24"},
{street: "Лазо ул", build: "25"},
{street: "Лазо ул", build: "26"},
{street: "Лазо ул", build: "28"},
{street: "Лазо ул", build: "29"},
{street: "Лазо ул", build: "2А"},
{street: "Лазо ул", build: "30"},
{street: "Лазо ул", build: "31"},
{street: "Лазо ул", build: "32"},
{street: "Лазо ул", build: "34"},
{street: "Лазо ул", build: "35"},
{street: "Лазо ул", build: "4"},
{street: "Лазо ул", build: "6"},
{street: "Лазо ул", build: "8"},
{street: "Ленина ул", build: "12"},
{street: "Ленина ул", build: "20"},
{street: "Ленина ул", build: "22"},
{street: "Ленина ул", build: "24"},
{street: "Ленина ул", build: "26"},
{street: "Ленина ул", build: "28"},
{street: "Ленина ул", build: "28А"},
{street: "Ленина ул", build: "30"},
{street: "Ленина ул", build: "30А"},
{street: "Ленина ул", build: "32"},
{street: "Ленина ул", build: "34"},
{street: "Ленина ул", build: "36А"},
{street: "Ломоносова ул", build: "1"},
{street: "Ломоносова ул", build: "1А"},
{street: "Ломоносова ул", build: "3А"},
{street: "Ломоносова ул", build: "4А"},
{street: "Ломоносова ул", build: "5А"},
{street: "Ломоносова ул", build: "6А"},
{street: "М.Горького ул", build: "26"},
{street: "М.Горького ул", build: "31"},
{street: "М.Горького ул", build: "32"},
{street: "М.Горького ул", build: "33/1"},
{street: "М.Горького ул", build: "33/2"},
{street: "М.Горького ул", build: "34"},
{street: "М.Горького ул", build: "36"},
{street: "М.Горького ул", build: "38"},
{street: "М.Горького ул", build: "40"},
{street: "М.Горького ул", build: "62А"},
{street: "М.Расковой ул", build: "87"},
{street: "М.Расковой ул", build: "88"},
{street: "М.Расковой ул", build: "89"},
{street: "М.Расковой ул", build: "90"},
{street: "М.Расковой ул", build: "91"},
{street: "М.Расковой ул", build: "92"},
{street: "М.Расковой ул", build: "93стр"},
{street: "Магистральная ул", build: "6"},
{street: "Матросова ул", build: "101"},
{street: "Матросова ул", build: "103"},
{street: "Матросова ул", build: "104"},
{street: "Матросова ул", build: "105"},
{street: "Матросова ул", build: "106"},
{street: "Матросова ул", build: "108"},
{street: "Матросова ул", build: "109"},
{street: "Матросова ул", build: "110"},
{street: "Матросова ул", build: "111"},
{street: "Матросова ул", build: "112"},
{street: "Матросова ул", build: "113"},
{street: "Матросова ул", build: "114"},
{street: "Матросова ул", build: "115"},
{street: "Матросова ул", build: "119"},
{street: "Матросова ул", build: "123"},
{street: "Матросова ул", build: "125"},
{street: "Матросова ул", build: "99"},
{street: "Мира ул", build: "1"},
{street: "Мира ул", build: "10"},
{street: "Мира ул", build: "11"},
{street: "Мира ул", build: "12"},
{street: "Мира ул", build: "14"},
{street: "Мира ул", build: "16"},
{street: "Мира ул", build: "18"},
{street: "Мира ул", build: "1Б"},
{street: "Мира ул", build: "1В"},
{street: "Мира ул", build: "2"},
{street: "Мира ул", build: "24"},
{street: "Мира ул", build: "26"},
{street: "Мира ул", build: "3"},
{street: "Мира ул", build: "30"},
{street: "Мира ул", build: "31"},
{street: "Мира ул", build: "32"},
{street: "Мира ул", build: "35"},
{street: "Мира ул", build: "36"},
{street: "Мира ул", build: "38"},
{street: "Мира ул", build: "42"},
{street: "Мира ул", build: "45"},
{street: "Мира ул", build: "46"},
{street: "Мира ул", build: "47"},
{street: "Мира ул", build: "5"},
{street: "Мира ул", build: "6"},
{street: "Мира ул", build: "7А"},
{street: "Мира ул", build: "8"},
{street: "Мира ул", build: "9"},
{street: "Октябрьский Проезд ", build: "1"},
{street: "Октябрьский Проезд ", build: "10"},
{street: "Октябрьский Проезд ", build: "11"},
{street: "Октябрьский Проезд ", build: "2"},
{street: "Октябрьский Проезд ", build: "4"},
{street: "Октябрьский Проезд ", build: "6"},
{street: "Октябрьский Проезд ", build: "8"},
{street: "Парковая ул", build: "1"},
{street: "Парковая ул", build: "2"},
{street: "Парковая ул", build: "2А"},
{street: "Парковая ул", build: "3"},
{street: "Парковая ул", build: "5"},
{street: "Парковая ул", build: "7"},
{street: "Первомайская ул", build: "19"},
{street: "Первомайская ул", build: "29"},
{street: "Первомайская ул", build: "66"},
{street: "Первомайская ул", build: "70"},
{street: "Победы ул", build: "1"},
{street: "Победы ул", build: "2"},
{street: "Победы ул", build: "3"},
{street: "Прокопьевская ул", build: "112"},
{street: "Прокопьевская ул", build: "63"},
{street: "Просвещения ул", build: "174"},
{street: "Просвещения ул", build: "176"},
{street: "Просвещения ул", build: "176А"},
{street: "Просвещения ул", build: "178"},
{street: "Просвещения ул", build: "178А"},
{street: "Просвещения ул", build: "180"},
{street: "Просвещения ул", build: "201А"},
{street: "Просвещения ул", build: "215"},
{street: "Просвещения ул", build: "219"},
{street: "Просвещения ул", build: "227"},
{street: "Профессиональный пер ", build: "11"},
{street: "Профессиональный пер ", build: "3"},
{street: "Профессиональный пер ", build: "4"},
{street: "Профессиональный пер ", build: "5"},
{street: "Профессиональный пер ", build: "7"},
{street: "Пушкина пер ", build: "2"},
{street: "Пушкина ул", build: "3"},
{street: "Пушкина ул", build: "5"},
{street: "Пушкина ул", build: "7"},
{street: "Р.Люксембург ул", build: "1"},
{street: "С.Перовской ул", build: "3"},
{street: "С.Перовской ул", build: "30"},
{street: "С.Перовской ул", build: "32"},
{street: "С.Перовской ул", build: "33"},
{street: "С.Перовской ул", build: "5"},
{street: "Садовая ул", build: "4"},
{street: "Силовой пер ", build: "24"},
{street: "Силовой пер ", build: "26"},
{street: "Силовой пер ", build: "28"},
{street: "Силовой пер ", build: "30"},
{street: "Силовой пер ", build: "32"},
{street: "Силовой пер ", build: "34"},
{street: "Силовой пер ", build: "36"},
{street: "Силовой пер ", build: "5"},
{street: "Солнечная ул", build: "1"},
{street: "Солнечная ул", build: "3"},
{street: "Солнечная ул", build: "5"},
{street: "Сосновая ул", build: "10"},
{street: "Сосновая ул", build: "11"},
{street: "Сосновая ул", build: "12"},
{street: "Сосновая ул", build: "13"},
{street: "Сосновая ул", build: "14"},
{street: "Сосновая ул", build: "15"},
{street: "Сосновая ул", build: "16"},
{street: "Сосновая ул", build: "17"},
{street: "Сосновая ул", build: "18"},
{street: "Сосновая ул", build: "19"},
{street: "Сосновая ул", build: "20"},
{street: "Сосновая ул", build: "21"},
{street: "Сосновая ул", build: "22"},
{street: "Сосновая ул", build: "48"},
{street: "Сосновая ул", build: "49"},
{street: "Сосновая ул", build: "5"},
{street: "Сосновая ул", build: "50"},
{street: "Сосновая ул", build: "51"},
{street: "Сосновая ул", build: "52"},
{street: "Сосновая ул", build: "53"},
{street: "Сосновая ул", build: "54"},
{street: "Сосновая ул", build: "7"},
{street: "Сосновая ул", build: "8"},
{street: "Сосновая ул", build: "9"},
{street: "Станционная ул", build: "2А"},
{street: "Станционная ул", build: "2Б"},
{street: "Станционная ул", build: "2В"},
{street: "Станционная ул", build: "31"},
{street: "Станционная ул", build: "35А"},
{street: "Станционная ул", build: "41Б"},
{street: "Топкинская ул", build: "10"},
{street: "Топкинская ул", build: "12"},
{street: "Топкинская ул", build: "13"},
{street: "Топкинская ул", build: "14"},
{street: "Топкинская ул", build: "15"},
{street: "Топкинская ул", build: "16"},
{street: "Топкинская ул", build: "19"},
{street: "Топкинская ул", build: "20"},
{street: "Топкинская ул", build: "20А"},
{street: "Топкинская ул", build: "21"},
{street: "Топкинская ул", build: "22"},
{street: "Топкинская ул", build: "23"},
{street: "Топкинская ул", build: "27А"},
{street: "Трудовая ул", build: "55"},
{street: "Трудовая ул", build: "57"},
{street: "Трудовая ул", build: "59"},
{street: "Тырганская ул", build: "3"},
{street: "Тырганская ул", build: "5"},
{street: "Тырганская ул", build: "7"},
{street: "Тяжинская ул", build: "1"},
{street: "Тяжинская ул", build: "3"},
{street: "Угольная ул", build: "24"},
{street: "Угольная ул", build: "3"},
{street: "Угольная ул", build: "5"},
{street: "Угольная ул", build: "7"},
{street: "Урицкого ул", build: "48"},
{street: "Урицкого ул", build: "50"},
{street: "Урицкого ул", build: "52"},
{street: "Фасадный пер ", build: "2"},
{street: "Фурманова ул", build: "18"},
{street: "Чекистов ул", build: "10"},
{street: "Чекистов ул", build: "11"},
{street: "Чекистов ул", build: "9"},
{street: "Челинская ул", build: "11"},
{street: "Челинская ул", build: "13"},
{street: "Челинская ул", build: "15"},
{street: "Челинская ул", build: "17А"},
{street: "Челинская ул", build: "27А"},
{street: "Челинская ул", build: "40"},
{street: "Чередниченко ул", build: "11 строен.2"},
{street: "Чередниченко ул", build: "11/1"},
{street: "Чередниченко ул", build: "15"},
{street: "Чередниченко ул", build: "26"},
{street: "Чередниченко ул", build: "3"},
{street: "Чередниченко ул", build: "34"},
{street: "Чередниченко ул", build: "36"},
{street: "Чередниченко ул", build: "38"},
{street: "Чередниченко ул", build: "40"},
{street: "Чередниченко ул", build: "41"},
{street: "Чередниченко ул", build: "42"},
{street: "Чередниченко ул", build: "9/1"},
{street: "Чередниченко ул", build: "9/2"},
{street: "Шахтерская ул", build: "14А"},
{street: "Шахтерская ул", build: "15"},
{street: "Шахтерская ул", build: "16"},
{street: "Шахтерская ул", build: "18"},
{street: "Шахтерская ул", build: "28"},
{street: "Шахтерская ул", build: "30"},
{street: "Шевченко ул", build: "1"},
{street: "Шевченко ул", build: "2"},
{street: "Шоссейная ул", build: "1"},
{street: "Шоссейная ул", build: "2"},
{street: "Шоссейная ул", build: "4"},
{street: "Электрический пер ", build: "1"},
{street: "Электрический пер ", build: "7"},
{street: "Электрический пер ", build: "7А"},
{street: "Электрический пер ", build: "9"},
], streets: [{street: "Ангарская ул"},
{street: "Беловская ул"},
{street: "Ванцетти ул"},
{street: "Ватутина ул"},
{street: "Верный пер "},
{street: "Водоканальная ул"},
{street: "Войкова ул"},
{street: "Воронежская ул"},
{street: "Воронежский пер "},
{street: "Гагарина ул"},
{street: "Газовый пер "},
{street: "Герцена ул"},
{street: "Гурьевская ул"},
{street: "Данковская ул"},
{street: "Деповская ул"},
{street: "Желябова ул"},
{street: "Заречная ул"},
{street: "Им 137 Отдельной Стрелковой Бригады ул"},
{street: "Им 50-Летия Влксм ул"},
{street: "Им 50-Летия Октября ул"},
{street: "К.Маркса ул"},
{street: "Кадровая ул"},
{street: "Камышинская ул"},
{street: "Кемсеть ул"},
{street: "Киселевская ул"},
{street: "Китатская ул"},
{street: "Кольчугинская ул"},
{street: "Коминтерна ул"},
{street: "Крайняя ул"},
{street: "Крестьянская ул"},
{street: "Крылова пер "},
{street: "Крылова ул"},
{street: "Кубанская ул"},
{street: "Куйбышева ул"},
{street: "Л.Чайкиной ул"},
{street: "Лазо ул"},
{street: "Ленина ул"},
{street: "Ломоносова ул"},
{street: "М.Горького ул"},
{street: "М.Расковой ул"},
{street: "Магистральная ул"},
{street: "Матросова ул"},
{street: "Мира ул"},
{street: "Октябрьский Проезд "},
{street: "Парковая ул"},
{street: "Первомайская ул"},
{street: "Победы ул"},
{street: "Прокопьевская ул"},
{street: "Просвещения ул"},
{street: "Профессиональный пер "},
{street: "Пушкина пер "},
{street: "Пушкина ул"},
{street: "Р.Люксембург ул"},
{street: "С.Перовской ул"},
{street: "Садовая ул"},
{street: "Силовой пер "},
{street: "Солнечная ул"},
{street: "Сосновая ул"},
{street: "Станционная ул"},
{street: "Топкинская ул"},
{street: "Трудовая ул"},
{street: "Тырганская ул"},
{street: "Тяжинская ул"},
{street: "Угольная ул"},
{street: "Урицкого ул"},
{street: "Фасадный пер "},
{street: "Фурманова ул"},
{street: "Чекистов ул"},
{street: "Челинская ул"},
{street: "Чередниченко ул"},
{street: "Шахтерская ул"},
{street: "Шевченко ул"},
{street: "Шоссейная ул"},
{street: "Электрический пер "},
]};
