city_streets["belovo"] = {builds: [{street: "1-Я Боевая ул", build: "42"},
{street: "1-Я Боевая ул", build: "44"},
{street: "1-Я Боевая ул", build: "46"},
{street: "3-Й Микрорайон ", build: "1"},
{street: "3-Й Микрорайон ", build: "10"},
{street: "3-Й Микрорайон ", build: "104"},
{street: "3-Й Микрорайон ", build: "105"},
{street: "3-Й Микрорайон ", build: "11"},
{street: "3-Й Микрорайон ", build: "12"},
{street: "3-Й Микрорайон ", build: "13"},
{street: "3-Й Микрорайон ", build: "14"},
{street: "3-Й Микрорайон ", build: "15"},
{street: "3-Й Микрорайон ", build: "16"},
{street: "3-Й Микрорайон ", build: "17"},
{street: "3-Й Микрорайон ", build: "18"},
{street: "3-Й Микрорайон ", build: "19"},
{street: "3-Й Микрорайон ", build: "2"},
{street: "3-Й Микрорайон ", build: "20"},
{street: "3-Й Микрорайон ", build: "20А"},
{street: "3-Й Микрорайон ", build: "21"},
{street: "3-Й Микрорайон ", build: "22"},
{street: "3-Й Микрорайон ", build: "23"},
{street: "3-Й Микрорайон ", build: "24"},
{street: "3-Й Микрорайон ", build: "25"},
{street: "3-Й Микрорайон ", build: "26"},
{street: "3-Й Микрорайон ", build: "3"},
{street: "3-Й Микрорайон ", build: "4"},
{street: "3-Й Микрорайон ", build: "5"},
{street: "3-Й Микрорайон ", build: "6"},
{street: "3-Й Микрорайон ", build: "65"},
{street: "3-Й Микрорайон ", build: "67"},
{street: "3-Й Микрорайон ", build: "68"},
{street: "3-Й Микрорайон ", build: "69"},
{street: "3-Й Микрорайон ", build: "7"},
{street: "3-Й Микрорайон ", build: "70"},
{street: "3-Й Микрорайон ", build: "71"},
{street: "3-Й Микрорайон ", build: "72"},
{street: "3-Й Микрорайон ", build: "73"},
{street: "3-Й Микрорайон ", build: "74"},
{street: "3-Й Микрорайон ", build: "75"},
{street: "3-Й Микрорайон ", build: "76"},
{street: "3-Й Микрорайон ", build: "77"},
{street: "3-Й Микрорайон ", build: "78"},
{street: "3-Й Микрорайон ", build: "79"},
{street: "3-Й Микрорайон ", build: "8"},
{street: "3-Й Микрорайон ", build: "80"},
{street: "3-Й Микрорайон ", build: "81"},
{street: "3-Й Микрорайон ", build: "82"},
{street: "3-Й Микрорайон ", build: "83"},
{street: "3-Й Микрорайон ", build: "84"},
{street: "3-Й Микрорайон ", build: "85"},
{street: "3-Й Микрорайон ", build: "86"},
{street: "3-Й Микрорайон ", build: "9"},
{street: "3-Й Микрорайон ", build: "93"},
{street: "3-Й Микрорайон ", build: "93А"},
{street: "3-Й Микрорайон ", build: "94"},
{street: "3-Й Микрорайон ", build: "95"},
{street: "3-Й Микрорайон ", build: "97"},
{street: "3-Й Микрорайон ", build: "98"},
{street: "6-Й Микрорайон ", build: "1"},
{street: "Беловская ул", build: "15"},
{street: "Беловская ул", build: "2А"},
{street: "Беловская ул", build: "2Б"},
{street: "Весенний пер ", build: "6"},
{street: "Весенний пер ", build: "8"},
{street: "Волошиной ул", build: "4"},
{street: "Волошиной ул", build: "6"},
{street: "Волошиной ул", build: "8"},
{street: "Доватора ул", build: "11"},
{street: "Доватора ул", build: "13"},
{street: "Доватора ул", build: "15"},
{street: "Доватора ул", build: "17"},
{street: "Доватора ул", build: "2"},
{street: "Доватора ул", build: "4"},
{street: "Доватора ул", build: "6"},
{street: "Доватора ул", build: "7"},
{street: "Доватора ул", build: "8"},
{street: "Доватора ул", build: "9"},
{street: "Железнодорожная ул", build: "11"},
{street: "Железнодорожная ул", build: "15"},
{street: "Железнодорожная ул", build: "17"},
{street: "Железнодорожная ул", build: "21"},
{street: "Железнодорожная ул", build: "23"},
{street: "Железнодорожная ул", build: "28"},
{street: "Железнодорожная ул", build: "30"},
{street: "Железнодорожная ул", build: "32"},
{street: "Железнодорожная ул", build: "40"},
{street: "Железнодорожная ул", build: "54"},
{street: "Железнодорожная ул", build: "56"},
{street: "Железнодорожная ул", build: "9А"},
{street: "Каховская ул", build: "4"},
{street: "Клубный пер ", build: "1"},
{street: "Козлова ул", build: "3"},
{street: "Ленина ул", build: "1Б"},
{street: "Ленина ул", build: "14"},
{street: "Ленина ул", build: "14А"},
{street: "Ленина ул", build: "17"},
{street: "Ленина ул", build: "2"},
{street: "Ленина ул", build: "26"},
{street: "Ленина ул", build: "26А"},
{street: "Ленина ул", build: "27"},
{street: "Ленина ул", build: "28"},
{street: "Ленина ул", build: "29"},
{street: "Ленина ул", build: "33"},
{street: "Ленина ул", build: "34"},
{street: "Ленина ул", build: "36Б"},
{street: "Ленина ул", build: "36В"},
{street: "Ленина ул", build: "36Г"},
{street: "Ленина ул", build: "4"},
{street: "Ленина ул", build: "41"},
{street: "Ленина ул", build: "42"},
{street: "Ленина ул", build: "49"},
{street: "Ленина ул", build: "59"},
{street: "Ленина ул", build: "6"},
{street: "Ленина ул", build: "61"},
{street: "Ленина ул", build: "67А"},
{street: "Ленина ул", build: "8"},
{street: "Люксембург ул", build: "34А"},
{street: "Люксембург ул", build: "34Б"},
{street: "Люксембург ул", build: "34Г"},
{street: "Маркса ул", build: "10"},
{street: "Маркса ул", build: "12"},
{street: "Маркса ул", build: "6"},
{street: "Маркса ул", build: "8"},
{street: "Морозова ул", build: "10"},
{street: "Морозова ул", build: "11"},
{street: "Морозова ул", build: "12"},
{street: "Морозова ул", build: "13"},
{street: "Морозова ул", build: "14"},
{street: "Морозова ул", build: "5"},
{street: "Морозова ул", build: "6"},
{street: "Морозова ул", build: "7"},
{street: "Морозова ул", build: "8"},
{street: "Морозова ул", build: "9"},
{street: "Московская ул", build: "4"},
{street: "Московская ул", build: "6"},
{street: "Новогодняя ул", build: "1А"},
{street: "Октябрьская ул", build: "13"},
{street: "Октябрьская ул", build: "14"},
{street: "Октябрьская ул", build: "15"},
{street: "Октябрьская ул", build: "21"},
{street: "Октябрьская ул", build: "23"},
{street: "Октябрьская ул", build: "25"},
{street: "Октябрьская ул", build: "27"},
{street: "Октябрьская ул", build: "29"},
{street: "Октябрьская ул", build: "31"},
{street: "Октябрьская ул", build: "35"},
{street: "Октябрьская ул", build: "37"},
{street: "Октябрьская ул", build: "39"},
{street: "Октябрьская ул", build: "41"},
{street: "Октябрьская ул", build: "43"},
{street: "Октябрьская ул", build: "45"},
{street: "Октябрьская ул", build: "47"},
{street: "Октябрьская ул", build: "5"},
{street: "Октябрьская ул", build: "51"},
{street: "Октябрьская ул", build: "53"},
{street: "Октябрьская ул", build: "55"},
{street: "Октябрьская ул", build: "59"},
{street: "Октябрьская ул", build: "63"},
{street: "Октябрьская ул", build: "65"},
{street: "Октябрьская ул", build: "7"},
{street: "Полярная ул", build: "1"},
{street: "Почтовый пер ", build: "2"},
{street: "Почтовый пер ", build: "6"},
{street: "Почтовый пер ", build: "8"},
{street: "Пролетарская ул", build: "1Б"},
{street: "Пролетарская ул", build: "1А"},
{street: "Советская ул", build: "10"},
{street: "Советская ул", build: "11"},
{street: "Советская ул", build: "12"},
{street: "Советская ул", build: "13"},
{street: "Советская ул", build: "15"},
{street: "Советская ул", build: "16"},
{street: "Советская ул", build: "17"},
{street: "Советская ул", build: "18"},
{street: "Советская ул", build: "19"},
{street: "Советская ул", build: "2"},
{street: "Советская ул", build: "22"},
{street: "Советская ул", build: "26"},
{street: "Советская ул", build: "32"},
{street: "Советская ул", build: "33"},
{street: "Советская ул", build: "34"},
{street: "Советская ул", build: "35"},
{street: "Советская ул", build: "36"},
{street: "Советская ул", build: "37"},
{street: "Советская ул", build: "38"},
{street: "Советская ул", build: "39"},
{street: "Советская ул", build: "4"},
{street: "Советская ул", build: "40"},
{street: "Советская ул", build: "41А"},
{street: "Советская ул", build: "41Б"},
{street: "Советская ул", build: "41В"},
{street: "Советская ул", build: "42"},
{street: "Советская ул", build: "43"},
{street: "Советская ул", build: "45"},
{street: "Советская ул", build: "46"},
{street: "Советская ул", build: "47"},
{street: "Советская ул", build: "48"},
{street: "Советская ул", build: "49"},
{street: "Советская ул", build: "50"},
{street: "Советская ул", build: "51"},
{street: "Советская ул", build: "53"},
{street: "Советская ул", build: "55"},
{street: "Советская ул", build: "56"},
{street: "Советская ул", build: "58"},
{street: "Советская ул", build: "62"},
{street: "Советская ул", build: "63"},
{street: "Советская ул", build: "65"},
{street: "Советская ул", build: "67"},
{street: "Советская ул", build: "69"},
{street: "Советская ул", build: "71"},
{street: "Советская ул", build: "9"},
{street: "Советский пер ", build: "1А"},
{street: "Сосновый Квартал ", build: "2А"},
{street: "Сосновый Квартал ", build: "2Б"},
{street: "Сосновый Квартал ", build: "3"},
{street: "Сосновый Квартал ", build: "4"},
{street: "Сосновый Квартал ", build: "5"},
{street: "Сосновый Квартал ", build: "6"},
{street: "Спортивный пер ", build: "1"},
{street: "Тельмана ул", build: "10"},
{street: "Тельмана ул", build: "11"},
{street: "Тельмана ул", build: "12"},
{street: "Тельмана ул", build: "13"},
{street: "Тельмана ул", build: "14"},
{street: "Тельмана ул", build: "6"},
{street: "Тельмана ул", build: "7"},
{street: "Тельмана ул", build: "8"},
{street: "Тельмана ул", build: "9"},
{street: "Толстого пер ", build: "1"},
{street: "Толстого пер ", build: "10"},
{street: "Толстого пер ", build: "11"},
{street: "Толстого пер ", build: "12"},
{street: "Толстого пер ", build: "13"},
{street: "Толстого пер ", build: "14"},
{street: "Толстого пер ", build: "15"},
{street: "Толстого пер ", build: "15А"},
{street: "Толстого пер ", build: "2"},
{street: "Толстого пер ", build: "6"},
{street: "Толстого пер ", build: "9"},
{street: "Халтурина ул", build: "34в"},
{street: "Хмельницкого ул", build: "1"},
{street: "Хмельницкого ул", build: "11"},
{street: "Хмельницкого ул", build: "13"},
{street: "Хмельницкого ул", build: "15"},
{street: "Хмельницкого ул", build: "17"},
{street: "Хмельницкого ул", build: "19"},
{street: "Хмельницкого ул", build: "21"},
{street: "Хмельницкого ул", build: "25"},
{street: "Хмельницкого ул", build: "27"},
{street: "Хмельницкого ул", build: "29"},
{street: "Хмельницкого ул", build: "4"},
{street: "Хмельницкого ул", build: "5"},
{street: "Хмельницкого ул", build: "6"},
{street: "Хмельницкого ул", build: "7"},
{street: "Хмельницкого ул", build: "9"},
{street: "Цинкзаводской пер ", build: "1"},
{street: "Цинкзаводской пер ", build: "11"},
{street: "Цинкзаводской пер ", build: "13"},
{street: "Цинкзаводской пер ", build: "15"},
{street: "Цинкзаводской пер ", build: "19"},
{street: "Цинкзаводской пер ", build: "6"},
{street: "Цинкзаводской пер ", build: "8"},
{street: "Цинкзаводской пер ", build: "9"},
{street: "Чкалова ул", build: "13"},
{street: "Чкалова ул", build: "15"},
{street: "Чкалова ул", build: "17"},
{street: "Чкалова ул", build: "18"},
{street: "Чкалова ул", build: "19"},
{street: "Чкалова ул", build: "21"},
{street: "Чкалова ул", build: "23"},
{street: "Чкалова ул", build: "29"},
{street: "Чкалова ул", build: "31"},
{street: "Юбилейная ул", build: "10А"},
{street: "Юбилейная ул", build: "12"},
{street: "Юбилейная ул", build: "13"},
{street: "Юбилейная ул", build: "14"},
{street: "Юбилейная ул", build: "15"},
{street: "Юбилейная ул", build: "16"},
{street: "Юбилейная ул", build: "17"},
{street: "Юбилейная ул", build: "18"},
{street: "Юбилейная ул", build: "19"},
{street: "Юбилейная ул", build: "4"},
{street: "Юбилейная ул", build: "5"},
{street: "Юбилейная ул", build: "6"},
{street: "Юбилейная ул", build: "7"},
{street: "Юбилейная ул", build: "8"},
{street: "Юбилейная ул", build: "9"},
{street: "Юности ул", build: "10А"},
{street: "Юности ул", build: "11"},
{street: "Юности ул", build: "12"},
{street: "Юности ул", build: "13"},
{street: "Юности ул", build: "15"},
{street: "Юности ул", build: "20"},
{street: "Юности ул", build: "21"},
{street: "Юности ул", build: "22"},
{street: "Юности ул", build: "24"},
{street: "Юности ул", build: "5"},
{street: "Юности ул", build: "7"},
{street: "Юности ул", build: "8"},
{street: "Юности ул", build: "9"},
], streets: [{street: "1-Я Боевая ул"},
{street: "3-Й Микрорайон "},
{street: "6-Й Микрорайон "},
{street: "Беловская ул"},
{street: "Весенний пер "},
{street: "Волошиной ул"},
{street: "Доватора ул"},
{street: "Железнодорожная ул"},
{street: "Каховская ул"},
{street: "Клубный пер "},
{street: "Козлова ул"},
{street: "Ленина ул"},
{street: "Люксембург ул"},
{street: "Маркса ул"},
{street: "Морозова ул"},
{street: "Московская ул"},
{street: "Новогодняя ул"},
{street: "Октябрьская ул"},
{street: "Полярная ул"},
{street: "Почтовый пер "},
{street: "Пролетарская ул"},
{street: "Советская ул"},
{street: "Советский пер "},
{street: "Сосновый Квартал "},
{street: "Спортивный пер "},
{street: "Тельмана ул"},
{street: "Толстого пер "},
{street: "Халтурина ул"},
{street: "Хмельницкого ул"},
{street: "Цинкзаводской пер "},
{street: "Чкалова ул"},
{street: "Юбилейная ул"},
{street: "Юности ул"},
]};
