city_streets["berezovsky"] = {builds: [{street: "40 Лет Октября ул", build: "22"},
{street: "40 Лет Октября ул", build: "24"},
{street: "40 Лет Победы ул", build: "4"},
{street: "40 Лет Победы ул", build: "6"},
{street: "8 Марта ул", build: "1"},
{street: "8 Марта ул", build: "10"},
{street: "8 Марта ул", build: "12"},
{street: "8 Марта ул", build: "2"},
{street: "8 Марта ул", build: "3"},
{street: "8 Марта ул", build: "4"},
{street: "8 Марта ул", build: "5"},
{street: "8 Марта ул", build: "6"},
{street: "8 Марта ул", build: "8"},
{street: "А.Лужбина ул", build: "1"},
{street: "А.Лужбина ул", build: "13А"},
{street: "А.Лужбина ул", build: "1А"},
{street: "А.Лужбина ул", build: "3"},
{street: "А.Лужбина ул", build: "38"},
{street: "А.Лужбина ул", build: "39"},
{street: "Больничная ул", build: "8"},
{street: "Вахрушева ул", build: "1"},
{street: "Вахрушева ул", build: "13"},
{street: "Вахрушева ул", build: "21"},
{street: "Вахрушева ул", build: "23"},
{street: "Вахрушева ул", build: "3"},
{street: "Вахрушева ул", build: "31"},
{street: "Вахрушева ул", build: "33"},
{street: "Вахрушева ул", build: "6"},
{street: "Волкова ул", build: "1"},
{street: "Волкова ул", build: "10"},
{street: "Волкова ул", build: "11"},
{street: "Волкова ул", build: "12"},
{street: "Волкова ул", build: "14"},
{street: "Волкова ул", build: "16"},
{street: "Волкова ул", build: "18"},
{street: "Волкова ул", build: "1А"},
{street: "Волкова ул", build: "2"},
{street: "Волкова ул", build: "3"},
{street: "Волкова ул", build: "4"},
{street: "Волкова ул", build: "5"},
{street: "Волкова ул", build: "6"},
{street: "Волкова ул", build: "7"},
{street: "Волкова ул", build: "8"},
{street: "Волкова ул", build: "9"},
{street: "Иркутская ул", build: "43"},
{street: "Карбышева ул", build: "10"},
{street: "Карбышева ул", build: "11"},
{street: "Карбышева ул", build: "11А"},
{street: "Карбышева ул", build: "12"},
{street: "Карбышева ул", build: "14"},
{street: "Карбышева ул", build: "18"},
{street: "Карбышева ул", build: "20"},
{street: "Карбышева ул", build: "22"},
{street: "Карбышева ул", build: "3"},
{street: "Карбышева ул", build: "4"},
{street: "Карбышева ул", build: "5"},
{street: "Карбышева ул", build: "6"},
{street: "Карбышева ул", build: "7"},
{street: "Карбышева ул", build: "9"},
{street: "Кирова ул", build: "1"},
{street: "Кирова ул", build: "2"},
{street: "Кирова ул", build: "3"},
{street: "Кирова ул", build: "4"},
{street: "Кирова ул", build: "5"},
{street: "Кирова ул", build: "7"},
{street: "Кирова ул", build: "9"},
{street: "Комсомольский Бульвар ", build: "1"},
{street: "Комсомольский Бульвар ", build: "10"},
{street: "Комсомольский Бульвар ", build: "11"},
{street: "Комсомольский Бульвар ", build: "12"},
{street: "Комсомольский Бульвар ", build: "13"},
{street: "Комсомольский Бульвар ", build: "14"},
{street: "Комсомольский Бульвар ", build: "15"},
{street: "Комсомольский Бульвар ", build: "2"},
{street: "Комсомольский Бульвар ", build: "3"},
{street: "Комсомольский Бульвар ", build: "4"},
{street: "Комсомольский Бульвар ", build: "5"},
{street: "Комсомольский Бульвар ", build: "6"},
{street: "Комсомольский Бульвар ", build: "7"},
{street: "Комсомольский Бульвар ", build: "8"},
{street: "Комсомольский Бульвар ", build: "9"},
{street: "Лазурная ул", build: "22"},
{street: "Ленина пр ", build: "1"},
{street: "Ленина пр ", build: "10"},
{street: "Ленина пр ", build: "12"},
{street: "Ленина пр ", build: "14"},
{street: "Ленина пр ", build: "15"},
{street: "Ленина пр ", build: "16"},
{street: "Ленина пр ", build: "17"},
{street: "Ленина пр ", build: "2"},
{street: "Ленина пр ", build: "21"},
{street: "Ленина пр ", build: "23"},
{street: "Ленина пр ", build: "24"},
{street: "Ленина пр ", build: "26"},
{street: "Ленина пр ", build: "26А"},
{street: "Ленина пр ", build: "27"},
{street: "Ленина пр ", build: "28"},
{street: "Ленина пр ", build: "28А"},
{street: "Ленина пр ", build: "29"},
{street: "Ленина пр ", build: "3"},
{street: "Ленина пр ", build: "30"},
{street: "Ленина пр ", build: "31"},
{street: "Ленина пр ", build: "32"},
{street: "Ленина пр ", build: "33"},
{street: "Ленина пр ", build: "34"},
{street: "Ленина пр ", build: "35"},
{street: "Ленина пр ", build: "36"},
{street: "Ленина пр ", build: "37"},
{street: "Ленина пр ", build: "38"},
{street: "Ленина пр ", build: "4"},
{street: "Ленина пр ", build: "40"},
{street: "Ленина пр ", build: "44"},
{street: "Ленина пр ", build: "46"},
{street: "Ленина пр ", build: "48"},
{street: "Ленина пр ", build: "5"},
{street: "Ленина пр ", build: "5А"},
{street: "Ленина пр ", build: "50"},
{street: "Ленина пр ", build: "52"},
{street: "Ленина пр ", build: "53"},
{street: "Ленина пр ", build: "54"},
{street: "Ленина пр ", build: "56"},
{street: "Ленина пр ", build: "58"},
{street: "Ленина пр ", build: "6"},
{street: "Ленина пр ", build: "60"},
{street: "Ленина пр ", build: "62"},
{street: "Ленина пр ", build: "64"},
{street: "Ленина пр ", build: "7"},
{street: "Ленина пр ", build: "7А"},
{street: "Ленина пр ", build: "8"},
{street: "Ленина пр ", build: "9"},
{street: "Ленина ул", build: "1"},
{street: "Ленина ул", build: "10"},
{street: "Ленина ул", build: "11"},
{street: "Ленина ул", build: "12"},
{street: "Ленина ул", build: "15"},
{street: "Ленина ул", build: "16"},
{street: "Ленина ул", build: "18"},
{street: "Ленина ул", build: "2"},
{street: "Ленина ул", build: "2А"},
{street: "Ленина ул", build: "20"},
{street: "Ленина ул", build: "3"},
{street: "Ленина ул", build: "4"},
{street: "Ленина ул", build: "5"},
{street: "Ленина ул", build: "6"},
{street: "Ленина ул", build: "7"},
{street: "Ленина ул", build: "8"},
{street: "Ленина ул", build: "9"},
{street: "Линейная ул", build: "3"},
{street: "Мира ул", build: "10"},
{street: "Мира ул", build: "14"},
{street: "Мира ул", build: "18"},
{street: "Мира ул", build: "2"},
{street: "Мира ул", build: "20"},
{street: "Мира ул", build: "22"},
{street: "Мира ул", build: "23"},
{street: "Мира ул", build: "26"},
{street: "Мира ул", build: "30"},
{street: "Мира ул", build: "32"},
{street: "Мира ул", build: "34"},
{street: "Мира ул", build: "36"},
{street: "Мира ул", build: "4"},
{street: "Мира ул", build: "40"},
{street: "Мира ул", build: "42"},
{street: "Мира ул", build: "46"},
{street: "Мира ул", build: "50"},
{street: "Молодежный Бульвар ", build: "1"},
{street: "Молодежный Бульвар ", build: "10"},
{street: "Молодежный Бульвар ", build: "11"},
{street: "Молодежный Бульвар ", build: "12"},
{street: "Молодежный Бульвар ", build: "13"},
{street: "Молодежный Бульвар ", build: "14"},
{street: "Молодежный Бульвар ", build: "15"},
{street: "Молодежный Бульвар ", build: "17"},
{street: "Молодежный Бульвар ", build: "2"},
{street: "Молодежный Бульвар ", build: "21"},
{street: "Молодежный Бульвар ", build: "23"},
{street: "Молодежный Бульвар ", build: "23А"},
{street: "Молодежный Бульвар ", build: "23Б"},
{street: "Молодежный Бульвар ", build: "25"},
{street: "Молодежный Бульвар ", build: "3"},
{street: "Молодежный Бульвар ", build: "4"},
{street: "Молодежный Бульвар ", build: "5"},
{street: "Молодежный Бульвар ", build: "6"},
{street: "Молодежный Бульвар ", build: "7"},
{street: "Молодежный Бульвар ", build: "8"},
{street: "Строителей ул", build: "1"},
{street: "Строителей ул", build: "3"},
{street: "Строителей ул", build: "5"},
{street: "Строителей ул", build: "7"},
{street: "Фрунзе ул", build: "1"},
{street: "Фрунзе ул", build: "10"},
{street: "Фрунзе ул", build: "11"},
{street: "Фрунзе ул", build: "12"},
{street: "Фрунзе ул", build: "37"},
{street: "Фрунзе ул", build: "39"},
{street: "Фрунзе ул", build: "40"},
{street: "Фрунзе ул", build: "41"},
{street: "Фрунзе ул", build: "42"},
{street: "Фрунзе ул", build: "9"},
{street: "Фурманова ул", build: "1"},
{street: "Фурманова ул", build: "10"},
{street: "Фурманова ул", build: "14"},
{street: "Фурманова ул", build: "16"},
{street: "Фурманова ул", build: "18"},
{street: "Фурманова ул", build: "3"},
{street: "Фурманова ул", build: "8"},
{street: "Черняховского ул", build: "10"},
{street: "Черняховского ул", build: "10А"},
{street: "Черняховского ул", build: "12"},
{street: "Черняховского ул", build: "16"},
{street: "Черняховского ул", build: "2"},
{street: "Черняховского ул", build: "20"},
{street: "Черняховского ул", build: "22"},
{street: "Черняховского ул", build: "4"},
{street: "Черняховского ул", build: "4А"},
{street: "Черняховского ул", build: "8"},
{street: "Шахтеров пр ", build: "1"},
{street: "Шахтеров пр ", build: "10"},
{street: "Шахтеров пр ", build: "11"},
{street: "Шахтеров пр ", build: "12"},
{street: "Шахтеров пр ", build: "14"},
{street: "Шахтеров пр ", build: "17"},
{street: "Шахтеров пр ", build: "2"},
{street: "Шахтеров пр ", build: "21"},
{street: "Шахтеров пр ", build: "25"},
{street: "Шахтеров пр ", build: "25А"},
{street: "Шахтеров пр ", build: "25Б"},
{street: "Шахтеров пр ", build: "25В"},
{street: "Шахтеров пр ", build: "27"},
{street: "Шахтеров пр ", build: "3"},
{street: "Шахтеров пр ", build: "6"},
{street: "Шахтеров пр ", build: "8"},
{street: "Шахтеров пр ", build: "9"},
{street: "Школьная ул", build: "1"},
{street: "Школьная ул", build: "3"},
{street: "Школьная ул", build: "7"},
], streets: [{street: "40 Лет Октября ул"},
{street: "40 Лет Победы ул"},
{street: "8 Марта ул"},
{street: "А.Лужбина ул"},
{street: "Больничная ул"},
{street: "Вахрушева ул"},
{street: "Волкова ул"},
{street: "Иркутская ул"},
{street: "Карбышева ул"},
{street: "Кирова ул"},
{street: "Комсомольский Бульвар "},
{street: "Лазурная ул"},
{street: "Ленина пр "},
{street: "Ленина ул"},
{street: "Линейная ул"},
{street: "Мира ул"},
{street: "Молодежный Бульвар "},
{street: "Строителей ул"},
{street: "Фрунзе ул"},
{street: "Фурманова ул"},
{street: "Черняховского ул"},
{street: "Шахтеров пр "},
{street: "Школьная ул"},
] };
