city_streets["gurevsk"] = {builds: [{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "2"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "4"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "5"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "7"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "9"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "11"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "15"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "36"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "38"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "40"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "42"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "44"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "46"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "62"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "64"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "66"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "68"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "70"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "72"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "74"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "76"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: "78"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: " 13/1"},
{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА ", build: " 17/1"},
{street: "АВТОМОБИЛИСТОВ ПЕРЕУЛОК ", build: "1"},
{street: "ДРУЖБЫ ПЕРЕУЛОК ", build: "2"},
{street: "ДРУЖБЫ ПЕРЕУЛОК ", build: "4"},
{street: "ДРУЖБЫ ПЕРЕУЛОК ", build: "6"},
{street: "ДРУЖБЫ ПЕРЕУЛОК ", build: "8"},
{street: "ДРУЖБЫ ПЕРЕУЛОК ", build: "10"},
{street: "ЕСЕНИНА УЛИЦА ", build: "9"},
{street: "ЕСЕНИНА УЛИЦА ", build: "10"},
{street: "ЕСЕНИНА УЛИЦА ", build: "11"},
{street: "ЕСЕНИНА УЛИЦА ", build: "12"},
{street: "ЕСЕНИНА УЛИЦА ", build: "13"},
{street: "ЕСЕНИНА УЛИЦА ", build: "14"},
{street: "ЕСЕНИНА УЛИЦА ", build: "15"},
{street: "ЕСЕНИНА УЛИЦА ", build: "16"},
{street: "ЕСЕНИНА УЛИЦА ", build: "17"},
{street: "ЕСЕНИНА УЛИЦА ", build: " 12 А"},
{street: "КИРОВА УЛИЦА ", build: "1"},
{street: "КИРОВА УЛИЦА ", build: "2"},
{street: "КИРОВА УЛИЦА ", build: "6"},
{street: "КИРОВА УЛИЦА ", build: "32"},
{street: "КИРОВА УЛИЦА ", build: "34"},
{street: "КИРОВА УЛИЦА ", build: "35"},
{street: "КИРОВА УЛИЦА ", build: "38"},
{street: "КИРОВА УЛИЦА ", build: "39"},
{street: "КИРОВА УЛИЦА ", build: "40"},
{street: "КИРОВА УЛИЦА ", build: "42"},
{street: "КИРОВА УЛИЦА ", build: "43"},
{street: "КИРОВА УЛИЦА ", build: "44"},
{street: "КИРОВА УЛИЦА ", build: "45"},
{street: "КИРОВА УЛИЦА ", build: "46"},
{street: "КИРОВА УЛИЦА ", build: "47"},
{street: "КИРОВА УЛИЦА ", build: "49"},
{street: "КИРОВА УЛИЦА ", build: "50"},
{street: "КИРОВА УЛИЦА ", build: "51"},
{street: "КИРОВА УЛИЦА ", build: "52"},
{street: "КИРОВА УЛИЦА ", build: "53"},
{street: "КИРОВА УЛИЦА ", build: "55"},
{street: "КИРОВА УЛИЦА ", build: "59"},
{street: "КИРОВА УЛИЦА ", build: "61"},
{street: "КИРОВА УЛИЦА ", build: " 5/1"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "14"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "16"},
{street: "ЛЕНИНА УЛИЦА ", build: "1"},
{street: "ЛЕНИНА УЛИЦА ", build: "3"},
{street: "ЛЕНИНА УЛИЦА ", build: "4"},
{street: "ЛЕНИНА УЛИЦА ", build: "5"},
{street: "ЛЕНИНА УЛИЦА ", build: "31"},
{street: "ЛЕНИНА УЛИЦА ", build: "32"},
{street: "ЛЕНИНА УЛИЦА ", build: "38"},
{street: "ЛЕНИНА УЛИЦА ", build: "39"},
{street: "ЛЕНИНА УЛИЦА ", build: "40"},
{street: "ЛЕНИНА УЛИЦА ", build: "42"},
{street: "ЛЕНИНА УЛИЦА ", build: "44"},
{street: "ЛЕНИНА УЛИЦА ", build: "46"},
{street: "ЛЕНИНА УЛИЦА ", build: "48"},
{street: "ЛЕНИНА УЛИЦА ", build: "58"},
{street: "ЛЕНИНА УЛИЦА ", build: "60"},
{street: "ЛЕНИНА УЛИЦА ", build: "62"},
{street: "ЛЕНИНА УЛИЦА ", build: "66"},
{street: "ЛЕНИНА УЛИЦА ", build: "68"},
{street: "ЛЕНИНА УЛИЦА ", build: "69"},
{street: "ЛЕНИНА УЛИЦА ", build: "71"},
{street: "ЛЕНИНА УЛИЦА ", build: "72"},
{street: "ЛЕНИНА УЛИЦА ", build: "75"},
{street: "ЛЕНИНА УЛИЦА ", build: "79"},
{street: "ЛЕНИНА УЛИЦА ", build: "80"},
{street: "ЛЕНИНА УЛИЦА ", build: "82"},
{street: "ЛЕНИНА УЛИЦА ", build: "83"},
{street: "ЛЕНИНА УЛИЦА ", build: "85"},
{street: "ЛЕНИНА УЛИЦА ", build: "86"},
{street: "ЛЕНИНА УЛИЦА ", build: "87"},
{street: "ЛЕНИНА УЛИЦА ", build: "91"},
{street: "ЛЕНИНА УЛИЦА ", build: "92"},
{street: "ЛЕНИНА УЛИЦА ", build: "97"},
{street: "ЛЕНИНА УЛИЦА ", build: "99"},
{street: "ЛЕНИНА УЛИЦА ", build: "100"},
{street: "ЛЕНИНА УЛИЦА ", build: "102"},
{street: "ЛЕНИНА УЛИЦА ", build: "103"},
{street: "ЛЕНИНА УЛИЦА ", build: " 105 А"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "2"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "6"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "8"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "10"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "16"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "18"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "21"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "33"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: "51"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: " 20А"},
{street: "ПАРТИЗАНСКАЯ УЛИЦА ", build: " 49Б"},
{street: "Р.ЛЮКСЕМБУРГ УЛИЦА ", build: "63"},
{street: "Р.ЛЮКСЕМБУРГ УЛИЦА ", build: "65"},
{street: "Р.ЛЮКСЕМБУРГ УЛИЦА ", build: "101"},
{street: "САВЕЛЬЕВА УЛИЦА ", build: "1"},
{street: "САВЕЛЬЕВА УЛИЦА ", build: "2"},
{street: "САВЕЛЬЕВА УЛИЦА ", build: "3"},
{street: "ЧАПАЕВА УЛИЦА ", build: "4"},
{street: "ЧАПАЕВА УЛИЦА ", build: "6"},
{street: "ЧАПАЕВА УЛИЦА ", build: "8"},
], streets: [{street: "30 ЛЕТ ПОБЕДЫ УЛИЦА "},
{street: "АВТОМОБИЛИСТОВ ПЕРЕУЛОК "},
{street: "ДРУЖБЫ ПЕРЕУЛОК "},
{street: "ЕСЕНИНА УЛИЦА "},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА "},
{street: "ПАРТИЗАНСКАЯ УЛИЦА "},
{street: "САВЕЛЬЕВА УЛИЦА "},
{street: "ЧАПАЕВА УЛИЦА "},
] };
