city_streets["gurevsk"] = {builds: [{street: "30 Лет Победы ул", build: "11"},
{street: "30 Лет Победы ул", build: "13/1"},
{street: "30 Лет Победы ул", build: "15"},
{street: "30 Лет Победы ул", build: "17/1"},
{street: "30 Лет Победы ул", build: "2"},
{street: "30 Лет Победы ул", build: "36"},
{street: "30 Лет Победы ул", build: "38"},
{street: "30 Лет Победы ул", build: "4"},
{street: "30 Лет Победы ул", build: "40"},
{street: "30 Лет Победы ул", build: "42"},
{street: "30 Лет Победы ул", build: "44"},
{street: "30 Лет Победы ул", build: "46"},
{street: "30 Лет Победы ул", build: "5"},
{street: "30 Лет Победы ул", build: "62"},
{street: "30 Лет Победы ул", build: "64"},
{street: "30 Лет Победы ул", build: "66"},
{street: "30 Лет Победы ул", build: "68"},
{street: "30 Лет Победы ул", build: "7"},
{street: "30 Лет Победы ул", build: "70"},
{street: "30 Лет Победы ул", build: "72"},
{street: "30 Лет Победы ул", build: "74"},
{street: "30 Лет Победы ул", build: "76"},
{street: "30 Лет Победы ул", build: "78"},
{street: "30 Лет Победы ул", build: "9"},
{street: "Автомобилистов пер ", build: "1"},
{street: "Дружбы пер ", build: "10"},
{street: "Дружбы пер ", build: "2"},
{street: "Дружбы пер ", build: "4"},
{street: "Дружбы пер ", build: "6"},
{street: "Дружбы пер ", build: "8"},
{street: "Есенина ул", build: "10"},
{street: "Есенина ул", build: "11"},
{street: "Есенина ул", build: "12"},
{street: "Есенина ул", build: "12А"},
{street: "Есенина ул", build: "13"},
{street: "Есенина ул", build: "14"},
{street: "Есенина ул", build: "15"},
{street: "Есенина ул", build: "16"},
{street: "Есенина ул", build: "17"},
{street: "Есенина ул", build: "9"},
{street: "Кирова ул", build: "1"},
{street: "Кирова ул", build: "2"},
{street: "Кирова ул", build: "32"},
{street: "Кирова ул", build: "34"},
{street: "Кирова ул", build: "35"},
{street: "Кирова ул", build: "38"},
{street: "Кирова ул", build: "39"},
{street: "Кирова ул", build: "40"},
{street: "Кирова ул", build: "42"},
{street: "Кирова ул", build: "43"},
{street: "Кирова ул", build: "44"},
{street: "Кирова ул", build: "45"},
{street: "Кирова ул", build: "46"},
{street: "Кирова ул", build: "47"},
{street: "Кирова ул", build: "48"},
{street: "Кирова ул", build: "49"},
{street: "Кирова ул", build: "5/1"},
{street: "Кирова ул", build: "50"},
{street: "Кирова ул", build: "51"},
{street: "Кирова ул", build: "52"},
{street: "Кирова ул", build: "53"},
{street: "Кирова ул", build: "55"},
{street: "Кирова ул", build: "59"},
{street: "Кирова ул", build: "6"},
{street: "Кирова ул", build: "61"},
{street: "Коммунистическая ул", build: "14"},
{street: "Коммунистическая ул", build: "16"},
{street: "Ленина ул", build: "1"},
{street: "Ленина ул", build: "100"},
{street: "Ленина ул", build: "102"},
{street: "Ленина ул", build: "103"},
{street: "Ленина ул", build: "105А"},
{street: "Ленина ул", build: "3"},
{street: "Ленина ул", build: "31"},
{street: "Ленина ул", build: "32"},
{street: "Ленина ул", build: "38"},
{street: "Ленина ул", build: "39"},
{street: "Ленина ул", build: "4"},
{street: "Ленина ул", build: "40"},
{street: "Ленина ул", build: "42"},
{street: "Ленина ул", build: "44"},
{street: "Ленина ул", build: "46"},
{street: "Ленина ул", build: "48"},
{street: "Ленина ул", build: "5"},
{street: "Ленина ул", build: "56"},
{street: "Ленина ул", build: "58"},
{street: "Ленина ул", build: "60"},
{street: "Ленина ул", build: "62"},
{street: "Ленина ул", build: "66"},
{street: "Ленина ул", build: "68"},
{street: "Ленина ул", build: "69"},
{street: "Ленина ул", build: "71"},
{street: "Ленина ул", build: "72"},
{street: "Ленина ул", build: "73"},
{street: "Ленина ул", build: "75"},
{street: "Ленина ул", build: "79"},
{street: "Ленина ул", build: "80"},
{street: "Ленина ул", build: "82"},
{street: "Ленина ул", build: "83"},
{street: "Ленина ул", build: "85"},
{street: "Ленина ул", build: "86"},
{street: "Ленина ул", build: "87"},
{street: "Ленина ул", build: "89"},
{street: "Ленина ул", build: "91"},
{street: "Ленина ул", build: "92"},
{street: "Ленина ул", build: "97"},
{street: "Ленина ул", build: "99"},
{street: "Партизанская ул", build: "10"},
{street: "Партизанская ул", build: "16"},
{street: "Партизанская ул", build: "18"},
{street: "Партизанская ул", build: "2"},
{street: "Партизанская ул", build: "20А"},
{street: "Партизанская ул", build: "21"},
{street: "Партизанская ул", build: "33"},
{street: "Партизанская ул", build: "49Б"},
{street: "Партизанская ул", build: "51"},
{street: "Партизанская ул", build: "6"},
{street: "Партизанская ул", build: "8"},
{street: "Р.Люксембург ул", build: "101"},
{street: "Р.Люксембург ул", build: "63"},
{street: "Р.Люксембург ул", build: "65"},
{street: "Савельева ул", build: "1"},
{street: "Савельева ул", build: "2"},
{street: "Савельева ул", build: "3"},
{street: "Чапаева ул", build: "4"},
{street: "Чапаева ул", build: "6"},
{street: "Чапаева ул", build: "8"},
], streets: [{street: "30 Лет Победы ул"},
{street: "Автомобилистов пер "},
{street: "Дружбы пер "},
{street: "Есенина ул"},
{street: "Кирова ул"},
{street: "Коммунистическая ул"},
{street: "Ленина ул"},
{street: "Партизанская ул"},
{street: "Р.Люксембург ул"},
{street: "Савельева ул"},
{street: "Чапаева ул"},
] };
