city_streets["kaltan"] = {builds: [{street: "Базарная ул", build: "6"},
{street: "Горького ул", build: "14"},
{street: "Горького ул", build: "16"},
{street: "Горького ул", build: "18"},
{street: "Горького ул", build: "20"},
{street: "Горького ул", build: "22"},
{street: "Горького ул", build: "24а"},
{street: "Горького ул", build: "26"},
{street: "Горького ул", build: "30"},
{street: "Горького ул", build: "32"},
{street: "Горького ул", build: "34"},
{street: "Горького ул", build: "34а"},
{street: "Горького ул", build: "38"},
{street: "Дзержинского ул", build: "21А"},
{street: "Дзержинского ул", build: "26/1"},
{street: "Дзержинского ул", build: "49А"},
{street: "Калинина ул", build: "16"},
{street: "Калинина ул", build: "4"},
{street: "Калинина ул", build: "6"},
{street: "Калинина ул", build: "60"},
{street: "Комсомольская ул", build: "1"},
{street: "Комсомольская ул", build: "11"},
{street: "Комсомольская ул", build: "13"},
{street: "Комсомольская ул", build: "15"},
{street: "Комсомольская ул", build: "19"},
{street: "Комсомольская ул", build: "21"},
{street: "Комсомольская ул", build: "27"},
{street: "Комсомольская ул", build: "3"},
{street: "Комсомольская ул", build: "33А"},
{street: "Комсомольская ул", build: "35"},
{street: "Комсомольская ул", build: "37"},
{street: "Комсомольская ул", build: "39"},
{street: "Комсомольская ул", build: "49"},
{street: "Комсомольская ул", build: "5"},
{street: "Комсомольская ул", build: "51"},
{street: "Комсомольская ул", build: "55"},
{street: "Комсомольская ул", build: "57"},
{street: "Комсомольская ул", build: "65"},
{street: "Комсомольская ул", build: "83"},
{street: "Комсомольская ул", build: "87"},
{street: "Комсомольская ул", build: "89"},
{street: "Комсомольская ул", build: "93"},
{street: "Комсомольская ул", build: "93А"},
{street: "Мира пр ", build: "11"},
{street: "Мира пр ", build: "2"},
{street: "Мира пр ", build: "33а"},
{street: "Мира пр ", build: "33б"},
{street: "Мира пр ", build: "35а"},
{street: "Мира пр ", build: "37а"},
{street: "Мира пр ", build: "37Б"},
{street: "Мира пр ", build: "39"},
{street: "Мира пр ", build: "39б"},
{street: "Мира пр ", build: "41а"},
{street: "Мира пр ", build: "43"},
{street: "Мира пр ", build: "45а"},
{street: "Мира пр ", build: "45б"},
{street: "Мира пр ", build: "65а"},
{street: "Мира пр ", build: "71"},
], streets: [{street: "Базарная ул"},
{street: "Горького ул"},
{street: "Дзержинского ул"},
{street: "Калинина ул"},
{street: "Комсомольская ул"},
{street: "Мира пр "},
] };
