var selected_street ='';var selected_build = '';var city_streets = Object();
city_streets["kemerovo"] = {builds: [{street: "1-Й Квартал", build: "1"},
{street: "1-Й Квартал", build: "2"},
{street: "2-Й Квартал", build: "1"},
{street: "2-Й Квартал", build: "10"},
{street: "2-Й Квартал", build: "2"},
{street: "2-Й Квартал", build: "3"},
{street: "2-Й Квартал", build: "4"},
{street: "2-Й Квартал", build: "5"},
{street: "2-Й Квартал", build: "6"},
{street: "2-Й Квартал", build: "7"},
{street: "2-Й Квартал", build: "8"},
{street: "2-Й Квартал", build: "9"},
{street: "40 Лет Октября Улица", build: "11"},
{street: "40 Лет Октября Улица", build: "13"},
{street: "40 Лет Октября Улица", build: "15"},
{street: "40 Лет Октября Улица", build: "17"},
{street: "40 Лет Октября Улица", build: "19"},
{street: "40 Лет Октября Улица", build: "20"},
{street: "40 Лет Октября Улица", build: "23"},
{street: "40 Лет Октября Улица", build: "25"},
{street: "40 Лет Октября Улица", build: "27"},
{street: "40 Лет Октября Улица", build: "29"},
{street: "40 Лет Октября Улица", build: "3"},
{street: "40 Лет Октября Улица", build: "5"},
{street: "40 Лет Октября Улица", build: "7"},
{street: "40 Лет Октября Улица", build: "8"},
{street: "40 Лет Октября Улица", build: "9/2"},
{street: "40 Лет Октября Улица", build: "9/4"},
{street: "50 Лет Октября Улица", build: "12"},
{street: "50 Лет Октября Улица", build: "13"},
{street: "50 Лет Октября Улица", build: "14"},
{street: "50 Лет Октября Улица", build: "15_ETTH"},
{street: "50 Лет Октября Улица", build: "16"},
{street: "50 Лет Октября Улица", build: "18"},
{street: "50 Лет Октября Улица", build: "6"},
{street: "50 Лет Октября Улица", build: "8"},
{street: "Авроры Улица", build: "10"},
{street: "Авроры Улица", build: "14"},
{street: "Авроры Улица", build: "4"},
{street: "Авроры Улица", build: "6"},
{street: "Александрова Улица", build: "11"},
{street: "Александрова Улица", build: "12А"},
{street: "Александрова Улица", build: "13А"},
{street: "Александрова Улица", build: "14"},
{street: "Александрова Улица", build: "14А"},
{street: "Александрова Улица", build: "15"},
{street: "Александрова Улица", build: "15А"},
{street: "Александрова Улица", build: "16"},
{street: "Александрова Улица", build: "17"},
{street: "Александрова Улица", build: "2"},
{street: "Александрова Улица", build: "4"},
{street: "Александрова Улица", build: "6А"},
{street: "Александрова Улица", build: "8"},
{street: "Аллейная Улица", build: "2"},
{street: "Аллейная Улица", build: "7"},
{street: "Аллейная Улица", build: "9"},
{street: "Аллейная Улица", build: "9А"},
{street: "Арочная Улица", build: "33"},
{street: "Арочная Улица", build: "39"},
{street: "Арочная Улица", build: "41А"},
{street: "Базовая Улица", build: "12"},
{street: "Базовая Улица", build: "4б"},
{street: "Базовая Улица", build: "4в"},
{street: "Базовая Улица", build: "6"},
{street: "Базовая Улица", build: "6б"},
{street: "Барнаульская Улица", build: "27"},
{street: "Барнаульская Улица", build: "29"},
{street: "Барнаульская Улица", build: "31"},
{street: "Барнаульская Улица", build: "31А"},
{street: "Барнаульская Улица", build: "33"},
{street: "Белозерная Улица", build: "11"},
{street: "Белозерная Улица", build: "13"},
{street: "Белозерная Улица", build: "13А"},
{street: "Белозерная Улица", build: "13Б"},
{street: "Белозерная Улица", build: "15"},
{street: "Белозерная Улица", build: "17"},
{street: "Белозерная Улица", build: "19"},
{street: "Белозерная Улица", build: "21"},
{street: "Белозерная Улица", build: "23"},
{street: "Белозерная Улица", build: "25"},
{street: "Белозерная Улица", build: "31"},
{street: "Белозерная Улица", build: "33"},
{street: "Белозерная Улица", build: "40А"},
{street: "Белозерная Улица", build: "44"},
{street: "Белозерная Улица", build: "44А"},
{street: "Белозерная Улица", build: "44Б"},
{street: "Беломорский 1-Й пер", build: "7"},
{street: "Большевистская Улица", build: "2"},
{street: "Буденного Улица", build: "33"},
{street: "В.В.Михайлова пр", build: "3А"},
{street: "В.В.Михайлова пр", build: "3А/1"},
{street: "В.В.Михайлова пр", build: "3А/2"},
{street: "В.В.Михайлова пр", build: "3Б/1"},
{street: "В.В.Михайлова пр", build: "3Б/2"},
{street: "В.В.Михайлова пр", build: "3Б/3"},
{street: "В.В.Михайлова пр", build: "3Б/4"},
{street: "В.В.Михайлова пр", build: "3Б/5"},
{street: "Варяжская Улица", build: "1"},
{street: "Варяжская Улица", build: "13"},
{street: "Варяжская Улица", build: "15"},
{street: "Варяжская Улица", build: "19"},
{street: "Варяжская Улица", build: "21"},
{street: "Варяжская Улица", build: "25"},
{street: "Варяжская Улица", build: "27"},
{street: "Варяжская Улица", build: "3"},
{street: "Варяжская Улица", build: "5"},
{street: "Варяжская Улица", build: "7"},
{street: "Васильева Улица", build: "11"},
{street: "Васильева Улица", build: "7"},
{street: "Васильева Улица", build: "9"},
{street: "Вельская Улица", build: "1"},
{street: "Вельская Улица", build: "10а"},
{street: "Вельская Улица", build: "1А"},
{street: "Вельская Улица", build: "1Б"},
{street: "Вельская Улица", build: "1В"},
{street: "Веры Волошиной Улица", build: "10"},
{street: "Веры Волошиной Улица", build: "12_ETTH"},
{street: "Веры Волошиной Улица", build: "13Б"},
{street: "Веры Волошиной Улица", build: "16_ETTH"},
{street: "Веры Волошиной Улица", build: "20_ETTH"},
{street: "Веры Волошиной Улица", build: "22_ETTH"},
{street: "Веры Волошиной Улица", build: "25_ETTH"},
{street: "Веры Волошиной Улица", build: "28_ETTH"},
{street: "Веры Волошиной Улица", build: "28Б_ETTH"},
{street: "Веры Волошиной Улица", build: "29_ETTH"},
{street: "Веры Волошиной Улица", build: "30_ETTH"},
{street: "Веры Волошиной Улица", build: "32"},
{street: "Веры Волошиной Улица", build: "33_ETTH"},
{street: "Веры Волошиной Улица", build: "37_ETTH"},
{street: "Веры Волошиной Улица", build: "38А"},
{street: "Веры Волошиной Улица", build: "38Б"},
{street: "Веры Волошиной Улица", build: "39_ETTH"},
{street: "Веры Волошиной Улица", build: "41_ETTH"},
{street: "Веры Волошиной Улица", build: "41/1_ETTH"},
{street: "Веры Волошиной Улица", build: "41А_ETTH"},
{street: "Веры Волошиной Улица", build: "41Б_ETTH"},
{street: "Веры Волошиной Улица", build: "43_ETTH"},
{street: "Веры Волошиной Улица", build: "45_ETTH"},
{street: "Веры Волошиной Улица", build: "45А_ETTH"},
{street: "Веры Волошиной Улица", build: "47_ETTH"},
{street: "Весенняя Улица", build: "18"},
{street: "Весенняя Улица", build: "2"},
{street: "Весенняя Улица", build: "21_ETTH"},
{street: "Весенняя Улица", build: "22_ETTH"},
{street: "Весенняя Улица", build: "23"},
{street: "Весенняя Улица", build: "25"},
{street: "Весенняя Улица", build: "26_ETTH"},
{street: "Водонасосная Станция", build: "46"},
{street: "Волгоградская Улица", build: "1"},
{street: "Волгоградская Улица", build: "11"},
{street: "Волгоградская Улица", build: "13"},
{street: "Волгоградская Улица", build: "14"},
{street: "Волгоградская Улица", build: "15"},
{street: "Волгоградская Улица", build: "16"},
{street: "Волгоградская Улица", build: "17"},
{street: "Волгоградская Улица", build: "18"},
{street: "Волгоградская Улица", build: "20"},
{street: "Волгоградская Улица", build: "21"},
{street: "Волгоградская Улица", build: "21А"},
{street: "Волгоградская Улица", build: "23"},
{street: "Волгоградская Улица", build: "24"},
{street: "Волгоградская Улица", build: "24А"},
{street: "Волгоградская Улица", build: "24Б"},
{street: "Волгоградская Улица", build: "25"},
{street: "Волгоградская Улица", build: "26"},
{street: "Волгоградская Улица", build: "26А"},
{street: "Волгоградская Улица", build: "27"},
{street: "Волгоградская Улица", build: "28"},
{street: "Волгоградская Улица", build: "28А"},
{street: "Волгоградская Улица", build: "28Б"},
{street: "Волгоградская Улица", build: "29"},
{street: "Волгоградская Улица", build: "30"},
{street: "Волгоградская Улица", build: "31"},
{street: "Волгоградская Улица", build: "31А"},
{street: "Волгоградская Улица", build: "32"},
{street: "Волгоградская Улица", build: "32А"},
{street: "Волгоградская Улица", build: "32Б"},
{street: "Волгоградская Улица", build: "32В"},
{street: "Волгоградская Улица", build: "33"},
{street: "Волгоградская Улица", build: "34"},
{street: "Волгоградская Улица", build: "34А"},
{street: "Волгоградская Улица", build: "34Б"},
{street: "Волгоградская Улица", build: "34В"},
{street: "Волгоградская Улица", build: "4"},
{street: "Волгоградская Улица", build: "6"},
{street: "Волгоградская Улица", build: "8"},
{street: "Волгоградская Улица", build: "9"},
{street: "Волкова Улица", build: "36"},
{street: "Ворошилова Улица", build: "1"},
{street: "Ворошилова Улица", build: "10А"},
{street: "Ворошилова Улица", build: "11"},
{street: "Ворошилова Улица", build: "11А"},
{street: "Ворошилова Улица", build: "11Б"},
{street: "Ворошилова Улица", build: "12"},
{street: "Ворошилова Улица", build: "14А"},
{street: "Ворошилова Улица", build: "16"},
{street: "Ворошилова Улица", build: "16А"},
{street: "Ворошилова Улица", build: "18"},
{street: "Ворошилова Улица", build: "18А"},
{street: "Ворошилова Улица", build: "1А"},
{street: "Ворошилова Улица", build: "1Б"},
{street: "Ворошилова Улица", build: "1В"},
{street: "Ворошилова Улица", build: "2"},
{street: "Ворошилова Улица", build: "20"},
{street: "Ворошилова Улица", build: "24А"},
{street: "Ворошилова Улица", build: "24Б"},
{street: "Ворошилова Улица", build: "24В"},
{street: "Ворошилова Улица", build: "2А"},
{street: "Ворошилова Улица", build: "3"},
{street: "Ворошилова Улица", build: "3А"},
{street: "Ворошилова Улица", build: "3Б"},
{street: "Ворошилова Улица", build: "4"},
{street: "Ворошилова Улица", build: "40"},
{street: "Ворошилова Улица", build: "4А"},
{street: "Ворошилова Улица", build: "4Б"},
{street: "Ворошилова Улица", build: "5"},
{street: "Ворошилова Улица", build: "5А"},
{street: "Ворошилова Улица", build: "5Б"},
{street: "Ворошилова Улица", build: "6"},
{street: "Ворошилова Улица", build: "6А"},
{street: "Ворошилова Улица", build: "7"},
{street: "Ворошилова Улица", build: "7А"},
{street: "Ворошилова Улица", build: "7Б"},
{street: "Ворошилова Улица", build: "8"},
{street: "Ворошилова Улица", build: "9"},
{street: "Ворошилова Улица", build: "9Б"},
{street: "Ворошилова Улица", build: "9В"},
{street: "Восточный пр", build: "21/1"},
{street: "Восточный пр", build: "21/2"},
{street: "Восточный пр", build: "21/3"},
{street: "Восточный пр", build: "23"},
{street: "Восточный пр", build: "25"},
{street: "Восточный пр", build: "29"},
{street: "Восточный пр", build: "29А"},
{street: "Восточный пр", build: "31"},
{street: "Гагарина Улица", build: "108"},
{street: "Гагарина Улица", build: "120"},
{street: "Гагарина Улица", build: "122"},
{street: "Гагарина Улица", build: "128"},
{street: "Гагарина Улица", build: "130"},
{street: "Гагарина Улица", build: "132"},
{street: "Гагарина Улица", build: "136"},
{street: "Гагарина Улица", build: "138"},
{street: "Гагарина Улица", build: "140"},
{street: "Гагарина Улица", build: "142"},
{street: "Гагарина Улица", build: "144"},
{street: "Гагарина Улица", build: "148"},
{street: "Гагарина Улица", build: "151"},
{street: "Гагарина Улица", build: "153"},
{street: "Гагарина Улица", build: "155"},
{street: "Гагарина Улица", build: "157"},
{street: "Гагарина Улица", build: "159"},
{street: "Гурьевская Улица", build: "14"},
{street: "Гурьевская Улица", build: "15"},
{street: "Гурьевская Улица", build: "17"},
{street: "Гурьевская Улица", build: "18"},
{street: "Дегтярева Улица", build: "1"},
{street: "Дегтярева Улица", build: "3"},
{street: "Дегтярева Улица", build: "5"},
{street: "Дегтярева Улица", build: "6"},
{street: "Дегтярева Улица", build: "7"},
{street: "Дзержинского Улица", build: "11"},
{street: "Дзержинского Улица", build: "13"},
{street: "Дзержинского Улица", build: "2Б_ETTH"},
{street: "Дзержинского Улица", build: "3"},
{street: "Дзержинского Улица", build: "4_ETTH"},
{street: "Дзержинского Улица", build: "5"},
{street: "Дзержинского Улица", build: "5А"},
{street: "Дзержинского Улица", build: "6_ETTH"},
{street: "Дзержинского Улица", build: "7"},
{street: "Дзержинского Улица", build: "9А"},
{street: "Докучаева Улица", build: "12"},
{street: "Дружбы Улица", build: "1_ETTH"},
{street: "Дружбы Улица", build: "17"},
{street: "Дружбы Улица", build: "19"},
{street: "Дружбы Улица", build: "1А_ETTH"},
{street: "Дружбы Улица", build: "1Б"},
{street: "Дружбы Улица", build: "27"},
{street: "Дружбы Улица", build: "27А_ETTH"},
{street: "Дружбы Улица", build: "29"},
{street: "Дружбы Улица", build: "3_ETTH"},
{street: "Дружбы Улица", build: "30"},
{street: "Дружбы Улица", build: "30/1"},
{street: "Дружбы Улица", build: "30/8"},
{street: "Дружбы Улица", build: "31"},
{street: "Дружбы Улица", build: "31А"},
{street: "Дружбы Улица", build: "33"},
{street: "Дружбы Улица", build: "35"},
{street: "Дружбы Улица", build: "35А"},
{street: "Дружбы Улица", build: "35Б"},
{street: "Дружбы Улица", build: "3А_ETTH"},
{street: "Дружбы Улица", build: "3Б"},
{street: "Дружбы Улица", build: "5_ETTH"},
{street: "Дружбы Улица", build: "9/1"},
{street: "Дружбы Улица", build: "9/2"},
{street: "Ермака Улица", build: "2"},
{street: "Ермака Улица", build: "5"},
{street: "Железнякова Улица", build: "10"},
{street: "Железнякова Улица", build: "10_ETTH"},
{street: "Железнякова Улица", build: "17"},
{street: "Железнякова Улица", build: "18"},
{street: "Железнякова Улица", build: "9_ETTH"},
{street: "Заречная 1-Я Улица", build: "10"},
{street: "Заречная 1-Я Улица", build: "6"},
{street: "Заречная 1-Я Улица", build: "9"},
{street: "Заречная 1-Я Улица", build: "9/1"},
{street: "Заречная 2-Я Улица", build: "11"},
{street: "Заречная 2-Я Улица", build: "2"},
{street: "Заречная 2-Я Улица", build: "3"},
{street: "Заречная 2-Я Улица", build: "3А"},
{street: "Заречная 2-Я Улица", build: "4"},
{street: "Заречная 2-Я Улица", build: "5"},
{street: "Заречная 2-Я Улица", build: "5А"},
{street: "Заречная 2-Я Улица", build: "5Б"},
{street: "Заречная 2-Я Улица", build: "6"},
{street: "Заречная 2-Я Улица", build: "7"},
{street: "Заречная 2-Я Улица", build: "7а"},
{street: "Заречная 2-Я Улица", build: "8"},
{street: "Заречная 2-Я Улица", build: "9"},
{street: "Заречная 2-Я Улица", build: "9а"},
{street: "Иланский 3-Й пер", build: "1"},
{street: "Иланский 3-Й пер", build: "11"},
{street: "Иланский 3-Й пер", build: "2"},
{street: "Иланский 3-Й пер", build: "3"},
{street: "Иланский 3-Й пер", build: "3А"},
{street: "Иланский 3-Й пер", build: "3Б"},
{street: "Иланский 3-Й пер", build: "9"},
{street: "Инженерная Улица", build: "18"},
{street: "Инженерная Улица", build: "20"},
{street: "Инженерная Улица", build: "20А"},
{street: "Инженерная Улица", build: "20Б"},
{street: "Инициативная Улица", build: "1"},
{street: "Инициативная Улица", build: "10"},
{street: "Инициативная Улица", build: "101А"},
{street: "Инициативная Улица", build: "103А"},
{street: "Инициативная Улица", build: "105"},
{street: "Инициативная Улица", build: "109"},
{street: "Инициативная Улица", build: "10А"},
{street: "Инициативная Улица", build: "111"},
{street: "Инициативная Улица", build: "117"},
{street: "Инициативная Улица", build: "12"},
{street: "Инициативная Улица", build: "123"},
{street: "Инициативная Улица", build: "16А"},
{street: "Инициативная Улица", build: "16Б"},
{street: "Инициативная Улица", build: "16В"},
{street: "Инициативная Улица", build: "18А"},
{street: "Инициативная Улица", build: "1А"},
{street: "Инициативная Улица", build: "1Б"},
{street: "Инициативная Улица", build: "1В"},
{street: "Инициативная Улица", build: "1Г"},
{street: "Инициативная Улица", build: "20А"},
{street: "Инициативная Улица", build: "21"},
{street: "Инициативная Улица", build: "22"},
{street: "Инициативная Улица", build: "23"},
{street: "Инициативная Улица", build: "25"},
{street: "Инициативная Улица", build: "25А"},
{street: "Инициативная Улица", build: "26А"},
{street: "Инициативная Улица", build: "27А"},
{street: "Инициативная Улица", build: "28А"},
{street: "Инициативная Улица", build: "29"},
{street: "Инициативная Улица", build: "29А"},
{street: "Инициативная Улица", build: "32"},
{street: "Инициативная Улица", build: "34"},
{street: "Инициативная Улица", build: "34А"},
{street: "Инициативная Улица", build: "36"},
{street: "Инициативная Улица", build: "38"},
{street: "Инициативная Улица", build: "40"},
{street: "Инициативная Улица", build: "44"},
{street: "Инициативная Улица", build: "48А"},
{street: "Инициативная Улица", build: "50А"},
{street: "Инициативная Улица", build: "8"},
{street: "Инициативная Улица", build: "81А"},
{street: "Инициативная Улица", build: "83А"},
{street: "Инициативная Улица", build: "85А"},
{street: "Инициативная Улица", build: "87А"},
{street: "Институтская Улица", build: "11"},
{street: "Институтская Улица", build: "12"},
{street: "Институтская Улица", build: "12А"},
{street: "Институтская Улица", build: "12Б"},
{street: "Институтская Улица", build: "14"},
{street: "Институтская Улица", build: "16"},
{street: "Институтская Улица", build: "16А"},
{street: "Институтская Улица", build: "18"},
{street: "Институтская Улица", build: "2"},
{street: "Институтская Улица", build: "24"},
{street: "Институтская Улица", build: "4"},
{street: "Институтская Улица", build: "6"},
{street: "Калинина Улица", build: "1"},
{street: "Калинина Улица", build: "3"},
{street: "Калинина Улица", build: "5"},
{street: "Калинина Улица", build: "7"},
{street: "Каркасная Улица", build: "10"},
{street: "Каркасная Улица", build: "13"},
{street: "Кедровый Бульвар", build: "1"},
{street: "Кедровый Бульвар", build: "10"},
{street: "Кедровый Бульвар", build: "12"},
{street: "Кедровый Бульвар", build: "2"},
{street: "Кедровый Бульвар", build: "3"},
{street: "Кедровый Бульвар", build: "4"},
{street: "Кедровый Бульвар", build: "5"},
{street: "Кедровый Бульвар", build: "6"},
{street: "Кедровый Бульвар", build: "7"},
{street: "Кедровый Бульвар", build: "8"},
{street: "Кирова Улица", build: "28"},
{street: "Кирова Улица", build: "30"},
{street: "Кирова Улица", build: "34"},
{street: "Кирова Улица", build: "36"},
{street: "Кирова Улица", build: "38"},
{street: "Кирова Улица", build: "49"},
{street: "Кирова Улица", build: "51"},
{street: "Коломейцева Улица", build: "3"},
{street: "Коломейцева Улица", build: "4"},
{street: "Коломейцева Улица", build: "5"},
{street: "Коломейцева Улица", build: "6"},
{street: "Коломейцева Улица", build: "7"},
{street: "Коломейцева Улица", build: "8"},
{street: "Комсомольский пр", build: "11_ETTH"},
{street: "Комсомольский пр", build: "11А_ETTH"},
{street: "Комсомольский пр", build: "13_ETTH"},
{street: "Комсомольский пр", build: "15_ETTH"},
{street: "Комсомольский пр", build: "25_ETTH"},
{street: "Комсомольский пр", build: "27"},
{street: "Комсомольский пр", build: "29"},
{street: "Комсомольский пр", build: "34"},
{street: "Комсомольский пр", build: "36"},
{street: "Комсомольский пр", build: "38"},
{street: "Комсомольский пр", build: "39А"},
{street: "Комсомольский пр", build: "40"},
{street: "Комсомольский пр", build: "42"},
{street: "Комсомольский пр", build: "43"},
{street: "Комсомольский пр", build: "43А"},
{street: "Комсомольский пр", build: "43Б"},
{street: "Комсомольский пр", build: "44"},
{street: "Комсомольский пр", build: "46"},
{street: "Комсомольский пр", build: "49"},
{street: "Комсомольский пр", build: "49А"},
{street: "Комсомольский пр", build: "49Б"},
{street: "Комсомольский пр", build: "49В"},
{street: "Комсомольский пр", build: "49Г"},
{street: "Комсомольский пр", build: "51"},
{street: "Комсомольский пр", build: "53"},
{street: "Комсомольский пр", build: "53А"},
{street: "Комсомольский пр", build: "53Б"},
{street: "Комсомольский пр", build: "53В"},
{street: "Комсомольский пр", build: "57"},
{street: "Комсомольский пр", build: "59"},
{street: "Комсомольский пр", build: "63"},
{street: "Комсомольский пр", build: "65"},
{street: "Комсомольский пр", build: "67"},
{street: "Комсомольский пр", build: "69"},
{street: "Комсомольский пр", build: "71"},
{street: "Космическая Улица", build: "16/1"},
{street: "Космическая Улица", build: "22"},
{street: "Космическая Улица", build: "22А"},
{street: "Космическая Улица", build: "24"},
{street: "Космическая Улица", build: "24А"},
{street: "Космическая Улица", build: "25_ETTH"},
{street: "Космическая Улица", build: "28"},
{street: "Космическая Улица", build: "37"},
{street: "Космическая Улица", build: "37_ETTH"},
{street: "Космическая Улица", build: "4в/1"},
{street: "Космическая Улица", build: "4В/2"},
{street: "Красная Улица", build: "10"},
{street: "Красная Улица", build: "10А"},
{street: "Красная Улица", build: "10Б"},
{street: "Красная Улица", build: "12"},
{street: "Красная Улица", build: "12А"},
{street: "Красная Улица", build: "13"},
{street: "Красная Улица", build: "14"},
{street: "Красная Улица", build: "15"},
{street: "Красная Улица", build: "16"},
{street: "Красная Улица", build: "19"},
{street: "Красная Улица", build: "2"},
{street: "Красная Улица", build: "21"},
{street: "Красная Улица", build: "25"},
{street: "Красная Улица", build: "27"},
{street: "Красная Улица", build: "2Б"},
{street: "Красная Улица", build: "3"},
{street: "Красная Улица", build: "4"},
{street: "Красная Улица", build: "4/1"},
{street: "Красная Улица", build: "5"},
{street: "Красноармейская Улица", build: "105"},
{street: "Красноармейская Улица", build: "112"},
{street: "Красноармейская Улица", build: "116"},
{street: "Красноармейская Улица", build: "118"},
{street: "Красноармейская Улица", build: "122"},
{street: "Красноармейская Улица", build: "124"},
{street: "Красноармейская Улица", build: "128_ETTH"},
{street: "Красноармейская Улица", build: "134А"},
{street: "Красноармейская Улица", build: "135"},
{street: "Красноармейская Улица", build: "137"},
{street: "Красноармейская Улица", build: "138"},
{street: "Красноармейская Улица", build: "139"},
{street: "Красноармейская Улица", build: "140"},
{street: "Красноармейская Улица", build: "142"},
{street: "Красноармейская Улица", build: "142А"},
{street: "Красноармейская Улица", build: "144"},
{street: "Красноармейская Улица", build: "95"},
{street: "Красноармейская Улица", build: "95А"},
{street: "Красноармейская Улица", build: "97"},
{street: "Красноармейская Улица", build: "97А"},
{street: "Красноармейская Улица", build: "99А"},
{street: "Кузнецкий пр", build: "118_ETTH"},
{street: "Кузнецкий пр", build: "120_ETTH"},
{street: "Кузнецкий пр", build: "122_ETTH"},
{street: "Кузнецкий пр", build: "158"},
{street: "Кузнецкий пр", build: "160"},
{street: "Кузнецкий пр", build: "162"},
{street: "Кузнецкий пр", build: "262/1"},
{street: "Кузнецкий пр", build: "264"},
{street: "Кузнецкий пр", build: "266"},
{street: "Кузнецкий пр", build: "272"},
{street: "Кузнецкий пр", build: "276"},
{street: "Кузнецкий пр", build: "278"},
{street: "Кузнецкий пр", build: "282"},
{street: "Кузнецкий пр", build: "40"},
{street: "Кузнецкий пр", build: "95"},
{street: "Ленина пр", build: "100"},
{street: "Ленина пр", build: "100А"},
{street: "Ленина пр", build: "102"},
{street: "Ленина пр", build: "102А"},
{street: "Ленина пр", build: "103"},
{street: "Ленина пр", build: "103А"},
{street: "Ленина пр", build: "104"},
{street: "Ленина пр", build: "105"},
{street: "Ленина пр", build: "105А"},
{street: "Ленина пр", build: "106"},
{street: "Ленина пр", build: "106А"},
{street: "Ленина пр", build: "107А"},
{street: "Ленина пр", build: "107Б"},
{street: "Ленина пр", build: "108"},
{street: "Ленина пр", build: "108А"},
{street: "Ленина пр", build: "109"},
{street: "Ленина пр", build: "109А"},
{street: "Ленина пр", build: "109Б"},
{street: "Ленина пр", build: "110"},
{street: "Ленина пр", build: "111"},
{street: "Ленина пр", build: "111А"},
{street: "Ленина пр", build: "112"},
{street: "Ленина пр", build: "113"},
{street: "Ленина пр", build: "113А"},
{street: "Ленина пр", build: "113Б"},
{street: "Ленина пр", build: "114"},
{street: "Ленина пр", build: "115"},
{street: "Ленина пр", build: "115А"},
{street: "Ленина пр", build: "117"},
{street: "Ленина пр", build: "117А"},
{street: "Ленина пр", build: "117Б"},
{street: "Ленина пр", build: "118"},
{street: "Ленина пр", build: "118А"},
{street: "Ленина пр", build: "119"},
{street: "Ленина пр", build: "119А"},
{street: "Ленина пр", build: "120"},
{street: "Ленина пр", build: "121"},
{street: "Ленина пр", build: "121А"},
{street: "Ленина пр", build: "122"},
{street: "Ленина пр", build: "122А"},
{street: "Ленина пр", build: "123"},
{street: "Ленина пр", build: "124"},
{street: "Ленина пр", build: "125"},
{street: "Ленина пр", build: "125А"},
{street: "Ленина пр", build: "126"},
{street: "Ленина пр", build: "128"},
{street: "Ленина пр", build: "128А"},
{street: "Ленина пр", build: "130"},
{street: "Ленина пр", build: "131"},
{street: "Ленина пр", build: "132"},
{street: "Ленина пр", build: "132А"},
{street: "Ленина пр", build: "133"},
{street: "Ленина пр", build: "133А"},
{street: "Ленина пр", build: "133Б"},
{street: "Ленина пр", build: "134"},
{street: "Ленина пр", build: "135А"},
{street: "Ленина пр", build: "135Б"},
{street: "Ленина пр", build: "136"},
{street: "Ленина пр", build: "136А"},
{street: "Ленина пр", build: "137А"},
{street: "Ленина пр", build: "137Б"},
{street: "Ленина пр", build: "138"},
{street: "Ленина пр", build: "138А"},
{street: "Ленина пр", build: "139"},
{street: "Ленина пр", build: "139А"},
{street: "Ленина пр", build: "139Б"},
{street: "Ленина пр", build: "139В"},
{street: "Ленина пр", build: "140А"},
{street: "Ленина пр", build: "141"},
{street: "Ленина пр", build: "141А"},
{street: "Ленина пр", build: "142А"},
{street: "Ленина пр", build: "142Б"},
{street: "Ленина пр", build: "143"},
{street: "Ленина пр", build: "144А"},
{street: "Ленина пр", build: "146"},
{street: "Ленина пр", build: "146/1"},
{street: "Ленина пр", build: "148"},
{street: "Ленина пр", build: "150А"},
{street: "Ленина пр", build: "150Б"},
{street: "Ленина пр", build: "152Б"},
{street: "Ленина пр", build: "152В"},
{street: "Ленина пр", build: "158"},
{street: "Ленина пр", build: "160"},
{street: "Ленина пр", build: "162"},
{street: "Ленина пр", build: "164"},
{street: "Ленина пр", build: "164А"},
{street: "Ленина пр", build: "34"},
{street: "Ленина пр", build: "36"},
{street: "Ленина пр", build: "37"},
{street: "Ленина пр", build: "38"},
{street: "Ленина пр", build: "39"},
{street: "Ленина пр", build: "39А"},
{street: "Ленина пр", build: "39Б"},
{street: "Ленина пр", build: "41"},
{street: "Ленина пр", build: "41А"},
{street: "Ленина пр", build: "41Б"},
{street: "Ленина пр", build: "42"},
{street: "Ленина пр", build: "43"},
{street: "Ленина пр", build: "44"},
{street: "Ленина пр", build: "45"},
{street: "Ленина пр", build: "45А"},
{street: "Ленина пр", build: "46"},
{street: "Ленина пр", build: "47"},
{street: "Ленина пр", build: "48"},
{street: "Ленина пр", build: "49"},
{street: "Ленина пр", build: "50"},
{street: "Ленина пр", build: "51"},
{street: "Ленина пр", build: "51А"},
{street: "Ленина пр", build: "52"},
{street: "Ленина пр", build: "53"},
{street: "Ленина пр", build: "55Б"},
{street: "Ленина пр", build: "58"},
{street: "Ленина пр", build: "60"},
{street: "Ленина пр", build: "60А"},
{street: "Ленина пр", build: "60Б"},
{street: "Ленина пр", build: "60В"},
{street: "Ленина пр", build: "62А"},
{street: "Ленина пр", build: "63"},
{street: "Ленина пр", build: "63А"},
{street: "Ленина пр", build: "63Б"},
{street: "Ленина пр", build: "64"},
{street: "Ленина пр", build: "65А"},
{street: "Ленина пр", build: "65Б"},
{street: "Ленина пр", build: "66"},
{street: "Ленина пр", build: "66А"},
{street: "Ленина пр", build: "66Б"},
{street: "Ленина пр", build: "67"},
{street: "Ленина пр", build: "67А"},
{street: "Ленина пр", build: "68"},
{street: "Ленина пр", build: "69"},
{street: "Ленина пр", build: "69А"},
{street: "Ленина пр", build: "70"},
{street: "Ленина пр", build: "70А"},
{street: "Ленина пр", build: "70Б"},
{street: "Ленина пр", build: "70В"},
{street: "Ленина пр", build: "71"},
{street: "Ленина пр", build: "71А"},
{street: "Ленина пр", build: "72"},
{street: "Ленина пр", build: "73"},
{street: "Ленина пр", build: "74"},
{street: "Ленина пр", build: "75"},
{street: "Ленина пр", build: "75А"},
{street: "Ленина пр", build: "76"},
{street: "Ленина пр", build: "76А"},
{street: "Ленина пр", build: "76Б"},
{street: "Ленина пр", build: "76В"},
{street: "Ленина пр", build: "77А"},
{street: "Ленина пр", build: "77Б"},
{street: "Ленина пр", build: "77Г"},
{street: "Ленина пр", build: "78"},
{street: "Ленина пр", build: "80"},
{street: "Ленина пр", build: "82"},
{street: "Ленина пр", build: "82А"},
{street: "Ленина пр", build: "82Б"},
{street: "Ленина пр", build: "82В"},
{street: "Ленина пр", build: "82Г"},
{street: "Ленина пр", build: "84"},
{street: "Ленина пр", build: "86"},
{street: "Ленина пр", build: "86А"},
{street: "Ленина пр", build: "90А"},
{street: "Ленина пр", build: "90Б"},
{street: "Ленина пр", build: "92"},
{street: "Ленина пр", build: "94"},
{street: "Ленина пр", build: "95"},
{street: "Ленина пр", build: "96"},
{street: "Ленина пр", build: "97"},
{street: "Ленина пр", build: "98"},
{street: "Ленина пр", build: "99"},
{street: "Ленинградский пр", build: "13"},
{street: "Ленинградский пр", build: "13А"},
{street: "Ленинградский пр", build: "13Б"},
{street: "Ленинградский пр", build: "14_ETTH"},
{street: "Ленинградский пр", build: "15"},
{street: "Ленинградский пр", build: "15А"},
{street: "Ленинградский пр", build: "18_ETTH"},
{street: "Ленинградский пр", build: "18А_ETTH"},
{street: "Ленинградский пр", build: "21"},
{street: "Ленинградский пр", build: "21А"},
{street: "Ленинградский пр", build: "21Б"},
{street: "Ленинградский пр", build: "21В"},
{street: "Ленинградский пр", build: "21Г"},
{street: "Ленинградский пр", build: "22"},
{street: "Ленинградский пр", build: "23"},
{street: "Ленинградский пр", build: "23А"},
{street: "Ленинградский пр", build: "23Б"},
{street: "Ленинградский пр", build: "23В"},
{street: "Ленинградский пр", build: "24"},
{street: "Ленинградский пр", build: "24А"},
{street: "Ленинградский пр", build: "25"},
{street: "Ленинградский пр", build: "25А"},
{street: "Ленинградский пр", build: "25Б"},
{street: "Ленинградский пр", build: "25В"},
{street: "Ленинградский пр", build: "27"},
{street: "Ленинградский пр", build: "27А"},
{street: "Ленинградский пр", build: "28"},
{street: "Ленинградский пр", build: "28А"},
{street: "Ленинградский пр", build: "3"},
{street: "Ленинградский пр", build: "30"},
{street: "Ленинградский пр", build: "30/1"},
{street: "Ленинградский пр", build: "30/2"},
{street: "Ленинградский пр", build: "30А"},
{street: "Ленинградский пр", build: "30Б"},
{street: "Ленинградский пр", build: "30В"},
{street: "Ленинградский пр", build: "31"},
{street: "Ленинградский пр", build: "31А"},
{street: "Ленинградский пр", build: "32/2"},
{street: "Ленинградский пр", build: "32А"},
{street: "Ленинградский пр", build: "33"},
{street: "Ленинградский пр", build: "34"},
{street: "Ленинградский пр", build: "34А"},
{street: "Ленинградский пр", build: "36"},
{street: "Ленинградский пр", build: "36А"},
{street: "Ленинградский пр", build: "36Б"},
{street: "Ленинградский пр", build: "38"},
{street: "Ленинградский пр", build: "38А"},
{street: "Ленинградский пр", build: "38Б"},
{street: "Ленинградский пр", build: "39"},
{street: "Ленинградский пр", build: "39А"},
{street: "Ленинградский пр", build: "3А"},
{street: "Ленинградский пр", build: "40"},
{street: "Ленинградский пр", build: "40А"},
{street: "Ленинградский пр", build: "40Б"},
{street: "Ленинградский пр", build: "40В"},
{street: "Ленинградский пр", build: "41"},
{street: "Ленинградский пр", build: "41А"},
{street: "Ленинградский пр", build: "43"},
{street: "Ленинградский пр", build: "45"},
{street: "Ленинградский пр", build: "45Б"},
{street: "Ленинградский пр", build: "47"},
{street: "Ленинградский пр", build: "47А"},
{street: "Ленинградский пр", build: "47Б"},
{street: "Ленинградский пр", build: "47В"},
{street: "Ленинградский пр", build: "49"},
{street: "Ленинградский пр", build: "49Б"},
{street: "Ленинградский пр", build: "5_ETTH"},
{street: "Ленинградский пр", build: "51"},
{street: "Ленинградский пр", build: "5А"},
{street: "Ленинградский пр", build: "7"},
{street: "Ленинградский пр", build: "7А"},
{street: "Леонова пер", build: "4"},
{street: "Леонова пер", build: "7"},
{street: "Леонова Улица", build: "1"},
{street: "Леонова Улица", build: "10"},
{street: "Леонова Улица", build: "11"},
{street: "Леонова Улица", build: "11А"},
{street: "Леонова Улица", build: "14"},
{street: "Леонова Улица", build: "16"},
{street: "Леонова Улица", build: "16А"},
{street: "Леонова Улица", build: "17"},
{street: "Леонова Улица", build: "18"},
{street: "Леонова Улица", build: "19"},
{street: "Леонова Улица", build: "2"},
{street: "Леонова Улица", build: "20"},
{street: "Леонова Улица", build: "22"},
{street: "Леонова Улица", build: "24"},
{street: "Леонова Улица", build: "26"},
{street: "Леонова Улица", build: "26А"},
{street: "Леонова Улица", build: "28"},
{street: "Леонова Улица", build: "3"},
{street: "Леонова Улица", build: "4"},
{street: "Леонова Улица", build: "5"},
{street: "Леонова Улица", build: "6"},
{street: "Леонова Улица", build: "7"},
{street: "Леонова Улица", build: "8"},
{street: "Леонова Улица", build: "9"},
{street: "Леонова Улица", build: "9А"},
{street: "Леонова Улица", build: "9Б"},
{street: "Линия 1-Я Улица", build: "10_ETTH"},
{street: "Линия 1-Я Улица", build: "10А_ETTH"},
{street: "Линия 1-Я Улица", build: "14_ETTH"},
{street: "Линия 1-Я Улица", build: "2"},
{street: "Линия 1-Я Улица", build: "20А"},
{street: "Линия 1-Я Улица", build: "20Б"},
{street: "Линия 1-Я Улица", build: "20В"},
{street: "Линия 1-Я Улица", build: "20Д"},
{street: "Линия 1-Я Улица", build: "4_ETTH"},
{street: "Линия 1-Я Улица", build: "6_ETTH"},
{street: "Линия 1-Я Улица", build: "8"},
{street: "Марковцева Улица", build: "12"},
{street: "Марковцева Улица", build: "12/1"},
{street: "Марковцева Улица", build: "12А"},
{street: "Марковцева Улица", build: "12Б"},
{street: "Марковцева Улица", build: "14"},
{street: "Марковцева Улица", build: "16"},
{street: "Марковцева Улица", build: "16А"},
{street: "Марковцева Улица", build: "18"},
{street: "Марковцева Улица", build: "22"},
{street: "Марковцева Улица", build: "22А"},
{street: "Марковцева Улица", build: "24"},
{street: "Марковцева Улица", build: "6"},
{street: "Масальская Улица", build: "56"},
{street: "Масальская Улица", build: "58"},
{street: "Металлистов Улица", build: "20"},
{street: "Металлистов Улица", build: "4"},
{street: "Металлистов Улица", build: "4А"},
{street: "Металлистов Улица", build: "7"},
{street: "Металлистов Улица", build: "9"},
{street: "Мирная Улица", build: "15"},
{street: "Мирная Улица", build: "17"},
{street: "Мирная Улица", build: "19"},
{street: "Мичурина пер", build: "5"},
{street: "Мичурина пер", build: "5А"},
{street: "Мичурина Улица", build: "15"},
{street: "Мичурина Улица", build: "21"},
{street: "Мичурина Улица", build: "23"},
{street: "Мичурина Улица", build: "29"},
{street: "Мичурина Улица", build: "31"},
{street: "Мичурина Улица", build: "33"},
{street: "Мичурина Улица", build: "35"},
{street: "Мичурина Улица", build: "37"},
{street: "Мичурина Улица", build: "37А"},
{street: "Мичурина Улица", build: "39"},
{street: "Мичурина Улица", build: "41"},
{street: "Мичурина Улица", build: "41А"},
{street: "Мичурина Улица", build: "55_ETTH"},
{street: "Мичурина Улица", build: "56"},
{street: "Мичурина Улица", build: "57_ETTH"},
{street: "Мичурина Улица", build: "57А_ETTH"},
{street: "Мичурина Улица", build: "58"},
{street: "Мичурина Улица", build: "58стр/3"},
{street: "Мичурина Улица", build: "61_ETTH"},
{street: "Молодежный пр", build: "10"},
{street: "Молодежный пр", build: "11"},
{street: "Молодежный пр", build: "11А"},
{street: "Молодежный пр", build: "11Б"},
{street: "Молодежный пр", build: "12А"},
{street: "Молодежный пр", build: "12Б"},
{street: "Молодежный пр", build: "12В"},
{street: "Молодежный пр", build: "13"},
{street: "Молодежный пр", build: "13Б"},
{street: "Молодежный пр", build: "15"},
{street: "Молодежный пр", build: "15А"},
{street: "Молодежный пр", build: "15Б"},
{street: "Молодежный пр", build: "25"},
{street: "Молодежный пр", build: "27"},
{street: "Молодежный пр", build: "27А"},
{street: "Молодежный пр", build: "29"},
{street: "Молодежный пр", build: "29а"},
{street: "Молодежный пр", build: "3"},
{street: "Молодежный пр", build: "31"},
{street: "Молодежный пр", build: "33/1"},
{street: "Молодежный пр", build: "3А"},
{street: "Молодежный пр", build: "4"},
{street: "Молодежный пр", build: "4А"},
{street: "Молодежный пр", build: "5"},
{street: "Молодежный пр", build: "5/1"},
{street: "Молодежный пр", build: "6"},
{street: "Молодежный пр", build: "6А"},
{street: "Молодежный пр", build: "7"},
{street: "Молодежный пр", build: "7/1"},
{street: "Молодежный пр", build: "7В"},
{street: "Молодежный пр", build: "7Г"},
{street: "Молодежный пр", build: "8"},
{street: "Молодежный пр", build: "9"},
{street: "Молодежный пр", build: "9/1"},
{street: "Молодежный пр", build: "9А"},
{street: "Молодежный пр", build: "9В"},
{street: "Молодежный пр", build: "9Г"},
{street: "Московский пр", build: "12"},
{street: "Московский пр", build: "13"},
{street: "Московский пр", build: "13А"},
{street: "Московский пр", build: "14"},
{street: "Московский пр", build: "15"},
{street: "Московский пр", build: "15А"},
{street: "Московский пр", build: "16"},
{street: "Московский пр", build: "17"},
{street: "Московский пр", build: "17Б"},
{street: "Московский пр", build: "18/1"},
{street: "Московский пр", build: "18/2"},
{street: "Московский пр", build: "18/3"},
{street: "Московский пр", build: "18/4"},
{street: "Московский пр", build: "18/5"},
{street: "Московский пр", build: "18/6"},
{street: "Московский пр", build: "21_ETTH"},
{street: "Московский пр", build: "23_ETTH"},
{street: "Московский пр", build: "23Б"},
{street: "Московский пр", build: "25_ETTH"},
{street: "Московский пр", build: "27_ETTH"},
{street: "Московский пр", build: "29_ETTH"},
{street: "Московский пр", build: "29А"},
{street: "Московский пр", build: "2Б"},
{street: "Московский пр", build: "3"},
{street: "Московский пр", build: "31_ETTH"},
{street: "Московский пр", build: "35_ETTH"},
{street: "Московский пр", build: "35А_ETTH"},
{street: "Московский пр", build: "39Б_ETTH"},
{street: "Московский пр", build: "39В_ETTH"},
{street: "Московский пр", build: "39Г_ETTH"},
{street: "Московский пр", build: "41_ETTH"},
{street: "Московский пр", build: "41А_ETTH"},
{street: "Московский пр", build: "45_ETTH"},
{street: "Московский пр", build: "45Б_ETTH"},
{street: "Московский пр", build: "5"},
{street: "Московский пр", build: "7"},
{street: "Московский пр", build: "8"},
{street: "Московский пр", build: "8/1"},
{street: "Московский пр", build: "8/2"},
{street: "Московский пр", build: "9"},
{street: "Московский пр", build: "9Б"},
{street: "Мостовая Улица", build: "87"},
{street: "Мостовая Улица", build: "87А"},
{street: "Мостовая Улица", build: "87Б"},
{street: "Муромцева Улица", build: "10"},
{street: "Муромцева Улица", build: "11"},
{street: "Муромцева Улица", build: "13"},
{street: "Муромцева Улица", build: "13А"},
{street: "Муромцева Улица", build: "16"},
{street: "Муромцева Улица", build: "2"},
{street: "Муромцева Улица", build: "4"},
{street: "Муромцева Улица", build: "4А"},
{street: "Муромцева Улица", build: "6"},
{street: "Муромцева Улица", build: "8"},
{street: "Муромцева Улица", build: "9"},
{street: "Нахимова Улица", build: "260"},
{street: "Нахимова Улица", build: "262"},
{street: "Нахимова Улица", build: "262Б"},
{street: "Нахимова Улица", build: "264А"},
{street: "Нахимова Улица", build: "31"},
{street: "Новогодняя Улица", build: "11"},
{street: "Новогодняя Улица", build: "13"},
{street: "Новогодняя Улица", build: "15"},
{street: "Новогодняя Улица", build: "19"},
{street: "Новогодняя Улица", build: "2"},
{street: "Новогодняя Улица", build: "21"},
{street: "Новогодняя Улица", build: "23"},
{street: "Новогодняя Улица", build: "4"},
{street: "Новогодняя Улица", build: "7"},
{street: "Новогодняя Улица", build: "9"},
{street: "Ногинская Улица", build: "10"},
{street: "Ногинская Улица", build: "10А"},
{street: "Ногинская Улица", build: "8"},
{street: "Ноградская Улица", build: "10"},
{street: "Ноградская Улица", build: "13"},
{street: "Ноградская Улица", build: "15"},
{street: "Ноградская Улица", build: "17"},
{street: "Ноградская Улица", build: "19А"},
{street: "Ноградская Улица", build: "21"},
{street: "Окружная Улица", build: "28"},
{street: "Окружная Улица", build: "30"},
{street: "Окружная Улица", build: "32"},
{street: "Октябрьский пр", build: "101А"},
{street: "Октябрьский пр", build: "101Б"},
{street: "Октябрьский пр", build: "103_ETTH"},
{street: "Октябрьский пр", build: "105_ETTH"},
{street: "Октябрьский пр", build: "13"},
{street: "Октябрьский пр", build: "15"},
{street: "Октябрьский пр", build: "16А"},
{street: "Октябрьский пр", build: "17"},
{street: "Октябрьский пр", build: "18"},
{street: "Октябрьский пр", build: "20"},
{street: "Октябрьский пр", build: "20А"},
{street: "Октябрьский пр", build: "20Б"},
{street: "Октябрьский пр", build: "20В"},
{street: "Октябрьский пр", build: "21"},
{street: "Октябрьский пр", build: "23"},
{street: "Октябрьский пр", build: "23А"},
{street: "Октябрьский пр", build: "23Б"},
{street: "Октябрьский пр", build: "25"},
{street: "Октябрьский пр", build: "33"},
{street: "Октябрьский пр", build: "33А"},
{street: "Октябрьский пр", build: "33Б"},
{street: "Октябрьский пр", build: "35"},
{street: "Октябрьский пр", build: "36"},
{street: "Октябрьский пр", build: "36А"},
{street: "Октябрьский пр", build: "36В"},
{street: "Октябрьский пр", build: "36Г"},
{street: "Октябрьский пр", build: "37"},
{street: "Октябрьский пр", build: "38"},
{street: "Октябрьский пр", build: "38А"},
{street: "Октябрьский пр", build: "38Б"},
{street: "Октябрьский пр", build: "38В"},
{street: "Октябрьский пр", build: "40"},
{street: "Октябрьский пр", build: "41"},
{street: "Октябрьский пр", build: "42"},
{street: "Октябрьский пр", build: "43"},
{street: "Октябрьский пр", build: "44"},
{street: "Октябрьский пр", build: "47"},
{street: "Октябрьский пр", build: "49"},
{street: "Октябрьский пр", build: "51"},
{street: "Октябрьский пр", build: "52"},
{street: "Октябрьский пр", build: "52А"},
{street: "Октябрьский пр", build: "54"},
{street: "Октябрьский пр", build: "56"},
{street: "Октябрьский пр", build: "56А"},
{street: "Октябрьский пр", build: "58"},
{street: "Октябрьский пр", build: "59"},
{street: "Октябрьский пр", build: "60"},
{street: "Октябрьский пр", build: "61"},
{street: "Октябрьский пр", build: "61А"},
{street: "Октябрьский пр", build: "61Б"},
{street: "Октябрьский пр", build: "62"},
{street: "Октябрьский пр", build: "63"},
{street: "Октябрьский пр", build: "64"},
{street: "Октябрьский пр", build: "64А"},
{street: "Октябрьский пр", build: "64Б"},
{street: "Октябрьский пр", build: "66"},
{street: "Октябрьский пр", build: "66А"},
{street: "Октябрьский пр", build: "67"},
{street: "Октябрьский пр", build: "67А"},
{street: "Октябрьский пр", build: "68"},
{street: "Октябрьский пр", build: "69"},
{street: "Октябрьский пр", build: "69А"},
{street: "Октябрьский пр", build: "7"},
{street: "Октябрьский пр", build: "70"},
{street: "Октябрьский пр", build: "71"},
{street: "Октябрьский пр", build: "71А"},
{street: "Октябрьский пр", build: "72"},
{street: "Октябрьский пр", build: "73"},
{street: "Октябрьский пр", build: "73А"},
{street: "Октябрьский пр", build: "74"},
{street: "Октябрьский пр", build: "75"},
{street: "Октябрьский пр", build: "75А"},
{street: "Октябрьский пр", build: "77"},
{street: "Октябрьский пр", build: "77А"},
{street: "Октябрьский пр", build: "77Б"},
{street: "Октябрьский пр", build: "78_ETTH"},
{street: "Октябрьский пр", build: "78А_ETTH"},
{street: "Октябрьский пр", build: "79"},
{street: "Октябрьский пр", build: "7А"},
{street: "Октябрьский пр", build: "8"},
{street: "Октябрьский пр", build: "80А_ETTH"},
{street: "Октябрьский пр", build: "80Б_ETTH"},
{street: "Октябрьский пр", build: "80Г_ETTH"},
{street: "Октябрьский пр", build: "81"},
{street: "Октябрьский пр", build: "82_ETTH"},
{street: "Октябрьский пр", build: "83"},
{street: "Октябрьский пр", build: "84_ETTH"},
{street: "Октябрьский пр", build: "85"},
{street: "Октябрьский пр", build: "87"},
{street: "Октябрьский пр", build: "89"},
{street: "Октябрьский пр", build: "9"},
{street: "Октябрьский пр", build: "91"},
{street: "Октябрьский пр", build: "93"},
{street: "Октябрьский пр", build: "95_ETTH"},
{street: "Октябрьский пр", build: "97"},
{street: "Октябрьский пр", build: "99"},
{street: "Октябрьский пр", build: "99А"},
{street: "Орджоникидзе Улица", build: "3"},
{street: "Орджоникидзе Улица", build: "4"},
{street: "Орджоникидзе Улица", build: "5"},
{street: "Орджоникидзе Улица", build: "7"},
{street: "Осенний Бульвар", build: "1"},
{street: "Осенний Бульвар", build: "10"},
{street: "Осенний Бульвар", build: "11"},
{street: "Осенний Бульвар", build: "11А"},
{street: "Осенний Бульвар", build: "12"},
{street: "Осенний Бульвар", build: "13"},
{street: "Осенний Бульвар", build: "14"},
{street: "Осенний Бульвар", build: "15/1"},
{street: "Осенний Бульвар", build: "15/2"},
{street: "Осенний Бульвар", build: "15/3"},
{street: "Осенний Бульвар", build: "16"},
{street: "Осенний Бульвар", build: "18"},
{street: "Осенний Бульвар", build: "1А"},
{street: "Осенний Бульвар", build: "2"},
{street: "Осенний Бульвар", build: "20/1"},
{street: "Осенний Бульвар", build: "20/2"},
{street: "Осенний Бульвар", build: "2А"},
{street: "Осенний Бульвар", build: "3"},
{street: "Осенний Бульвар", build: "4"},
{street: "Осенний Бульвар", build: "5"},
{street: "Осенний Бульвар", build: "5А"},
{street: "Осенний Бульвар", build: "6"},
{street: "Осенний Бульвар", build: "7"},
{street: "Осенний Бульвар", build: "8"},
{street: "Осенний Бульвар", build: "9"},
{street: "Осенний Бульвар", build: "9А"},
{street: "Патриотов Улица", build: "18_ETTH"},
{street: "Патриотов Улица", build: "18А"},
{street: "Патриотов Улица", build: "18Б"},
{street: "Патриотов Улица", build: "27А_ETTH"},
{street: "Патриотов Улица", build: "29_ETTH"},
{street: "Патриотов Улица", build: "30_ETTH"},
{street: "Патриотов Улица", build: "31_ETTH"},
{street: "Патриотов Улица", build: "32_ETTH"},
{street: "Патриотов Улица", build: "33"},
{street: "Патриотов Улица", build: "33_ETTH"},
{street: "Патриотов Улица", build: "33А_ETTH"},
{street: "Патриотов Улица", build: "34_ETTH"},
{street: "Патриотов Улица", build: "34А_ETTH"},
{street: "Патриотов Улица", build: "35"},
{street: "Патриотов Улица", build: "35_ETTH"},
{street: "Патриотов Улица", build: "35А_ETTH"},
{street: "Патриотов Улица", build: "36_ETTH"},
{street: "Патриотов Улица", build: "5"},
{street: "Пионерский Бульвар", build: "10А"},
{street: "Пионерский Бульвар", build: "11"},
{street: "Пионерский Бульвар", build: "11А"},
{street: "Пионерский Бульвар", build: "12"},
{street: "Пионерский Бульвар", build: "12А"},
{street: "Пионерский Бульвар", build: "14"},
{street: "Пионерский Бульвар", build: "2"},
{street: "Пионерский Бульвар", build: "2А"},
{street: "Пионерский Бульвар", build: "4"},
{street: "Пионерский Бульвар", build: "6"},
{street: "Пионерский Бульвар", build: "8А"},
{street: "Пионерский Бульвар", build: "9"},
{street: "Пионерский Бульвар", build: "9А"},
{street: "Попова Улица", build: "11"},
{street: "Попова Улица", build: "1А"},
{street: "Попова Улица", build: "1Б"},
{street: "Попова Улица", build: "3"},
{street: "Попова Улица", build: "3Б"},
{street: "Попова Улица", build: "5"},
{street: "Попова Улица", build: "9"},
{street: "Потемкина Улица", build: "1"},
{street: "Потемкина Улица", build: "7"},
{street: "Предзаводская Улица", build: "1Б_ETTH"},
{street: "Предзаводская Улица", build: "2А_ETTH"},
{street: "Пригородная Улица", build: "23"},
{street: "Притомская Набережная Улица", build: "11"},
{street: "Притомская Набережная Улица", build: "13"},
{street: "Притомская Набережная Улица", build: "17"},
{street: "Притомская Набережная Улица", build: "19"},
{street: "Притомская Набережная Улица", build: "1А"},
{street: "Притомская Набережная Улица", build: "21"},
{street: "Притомская Набережная Улица", build: "21А"},
{street: "Притомская Набережная Улица", build: "23"},
{street: "Притомская Набережная Улица", build: "25"},
{street: "Притомский пр", build: "11"},
{street: "Притомский пр", build: "11/1"},
{street: "Притомский пр", build: "13"},
{street: "Притомский пр", build: "15"},
{street: "Притомский пр", build: "15/1"},
{street: "Притомский пр", build: "25"},
{street: "Притомский пр", build: "25/1"},
{street: "Притомский пр", build: "25/2"},
{street: "Притомский пр", build: "25/3"},
{street: "Притомский пр", build: "25/4"},
{street: "Притомский пр", build: "29"},
{street: "Притомский пр", build: "3"},
{street: "Притомский пр", build: "31/1"},
{street: "Притомский пр", build: "31/2"},
{street: "Притомский пр", build: "35/2"},
{street: "Притомский пр", build: "35/1"},
{street: "Притомский пр", build: "3а"},
{street: "Притомский пр", build: "7/1"},
{street: "Притомский пр", build: "7/3"},
{street: "Притомский пр", build: "7/5"},
{street: "Притомский пр", build: "7/6"},
{street: "Притомский пр", build: "7/7"},
{street: "Притомский пр", build: "7А"},
{street: "Притомский пр", build: "9"},
{street: "Пролетарская Улица", build: "12"},
{street: "Пролетарская Улица", build: "14"},
{street: "Пролетарская Улица", build: "16"},
{street: "Пролетарская Улица", build: "18"},
{street: "Пролетарская Улица", build: "20_ETTH"},
{street: "Пролетарская Улица", build: "22_ETTH"},
{street: "Пролетарская Улица", build: "29"},
{street: "Пролетарская Улица", build: "29/1"},
{street: "Пролетарская Улица", build: "29/2"},
{street: "Пролетарская Улица", build: "29/3"},
{street: "Пролетарская Улица", build: "29/4"},
{street: "Пролетарская Улица", build: "3"},
{street: "Пролетарская Улица", build: "4"},
{street: "Пролетарская Улица", build: "5"},
{street: "Пролетарская Улица", build: "6"},
{street: "Пролетарская Улица", build: "7"},
{street: "Пролетарская Улица", build: "8"},
{street: "Пролетарская Улица", build: "9"},
{street: "Промышленновский Проезд", build: "1"},
{street: "Промышленновский Проезд", build: "2"},
{street: "Промышленновское Шоссе", build: "46"},
{street: "Промышленновское Шоссе", build: "54"},
{street: "Промышленновское Шоссе", build: "56"},
{street: "Промышленновское Шоссе", build: "56Б"},
{street: "Радищева Улица", build: "11_ETTH"},
{street: "Радищева Улица", build: "15_ETTH"},
{street: "Радищева Улица", build: "17А_ETTH"},
{street: "Радищева Улица", build: "4_ETTH"},
{street: "Радищева Улица", build: "4А_ETTH"},
{street: "Радищева Улица", build: "6_ETTH"},
{street: "Рекордная Улица", build: "19"},
{street: "Рекордная Улица", build: "27"},
{street: "Рекордная Улица", build: "27А"},
{street: "Рекордная Улица", build: "29А"},
{street: "Рекордная Улица", build: "2А"},
{street: "Рекордная Улица", build: "31А"},
{street: "Рекордная Улица", build: "33А"},
{street: "Рекордная Улица", build: "35"},
{street: "Рекордная Улица", build: "3А"},
{street: "Рекордный пер", build: "5"},
{street: "Сарыгина Улица", build: "12А"},
{street: "Сарыгина Улица", build: "26"},
{street: "Сарыгина Улица", build: "28"},
{street: "Сарыгина Улица", build: "33"},
{street: "Сарыгина Улица", build: "33А"},
{street: "Сарыгина Улица", build: "34"},
{street: "Сарыгина Улица", build: "35"},
{street: "Сарыгина Улица", build: "37"},
{street: "Сарыгина Улица", build: "40"},
{street: "Сарыгина Улица", build: "42"},
{street: "Свободы Улица", build: "11"},
{street: "Свободы Улица", build: "11А"},
{street: "Свободы Улица", build: "13"},
{street: "Свободы Улица", build: "13А"},
{street: "Свободы Улица", build: "15"},
{street: "Свободы Улица", build: "17"},
{street: "Свободы Улица", build: "17А"},
{street: "Свободы Улица", build: "19"},
{street: "Свободы Улица", build: "19А"},
{street: "Свободы Улица", build: "21"},
{street: "Свободы Улица", build: "23"},
{street: "Свободы Улица", build: "23А"},
{street: "Свободы Улица", build: "23Б"},
{street: "Свободы Улица", build: "25"},
{street: "Свободы Улица", build: "25А"},
{street: "Свободы Улица", build: "27"},
{street: "Свободы Улица", build: "27А"},
{street: "Свободы Улица", build: "27Б"},
{street: "Свободы Улица", build: "29"},
{street: "Свободы Улица", build: "29А"},
{street: "Свободы Улица", build: "3"},
{street: "Свободы Улица", build: "31"},
{street: "Свободы Улица", build: "31А"},
{street: "Свободы Улица", build: "33"},
{street: "Свободы Улица", build: "33А"},
{street: "Свободы Улица", build: "35"},
{street: "Свободы Улица", build: "37"},
{street: "Свободы Улица", build: "6"},
{street: "Свободы Улица", build: "6Б"},
{street: "Свободы Улица", build: "7"},
{street: "Севастопольская Улица", build: "1"},
{street: "Севастопольская Улица", build: "2"},
{street: "Севастопольская Улица", build: "3"},
{street: "Севастопольская Улица", build: "4"},
{street: "Севастопольская Улица", build: "5"},
{street: "Севастопольская Улица", build: "6"},
{street: "Сергея Тюленина Улица", build: "1Б_ETTH"},
{street: "Сергея Тюленина Улица", build: "7"},
{street: "Серебряный Бор Улица", build: "1"},
{street: "Серебряный Бор Улица", build: "10"},
{street: "Серебряный Бор Улица", build: "11"},
{street: "Серебряный Бор Улица", build: "12"},
{street: "Серебряный Бор Улица", build: "13"},
{street: "Серебряный Бор Улица", build: "13А"},
{street: "Серебряный Бор Улица", build: "14"},
{street: "Серебряный Бор Улица", build: "15"},
{street: "Серебряный Бор Улица", build: "15А"},
{street: "Серебряный Бор Улица", build: "16"},
{street: "Серебряный Бор Улица", build: "18"},
{street: "Серебряный Бор Улица", build: "19"},
{street: "Серебряный Бор Улица", build: "19А"},
{street: "Серебряный Бор Улица", build: "21"},
{street: "Серебряный Бор Улица", build: "24/1"},
{street: "Серебряный Бор Улица", build: "24/3"},
{street: "Серебряный Бор Улица", build: "25"},
{street: "Серебряный Бор Улица", build: "27"},
{street: "Серебряный Бор Улица", build: "3"},
{street: "Серебряный Бор Улица", build: "3А"},
{street: "Серебряный Бор Улица", build: "3Б"},
{street: "Серебряный Бор Улица", build: "4"},
{street: "Серебряный Бор Улица", build: "4А"},
{street: "Серебряный Бор Улица", build: "5"},
{street: "Серебряный Бор Улица", build: "6/1"},
{street: "Серебряный Бор Улица", build: "6/2"},
{street: "Серебряный Бор Улица", build: "7"},
{street: "Серебряный Бор Улица", build: "8"},
{street: "Серебряный Бор Улица", build: "9"},
{street: "Сибиряков-Гвардейцев Улица", build: "1_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "11_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "12"},
{street: "Сибиряков-Гвардейцев Улица", build: "13_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "13А_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "14"},
{street: "Сибиряков-Гвардейцев Улица", build: "16"},
{street: "Сибиряков-Гвардейцев Улица", build: "17_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "18"},
{street: "Сибиряков-Гвардейцев Улица", build: "18А_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "19_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "21_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "22А_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "22Б"},
{street: "Сибиряков-Гвардейцев Улица", build: "24"},
{street: "Сибиряков-Гвардейцев Улица", build: "24_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "24А_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "24Б"},
{street: "Сибиряков-Гвардейцев Улица", build: "24Д"},
{street: "Сибиряков-Гвардейцев Улица", build: "273"},
{street: "Сибиряков-Гвардейцев Улица", build: "28"},
{street: "Сибиряков-Гвардейцев Улица", build: "28А"},
{street: "Сибиряков-Гвардейцев Улица", build: "296"},
{street: "Сибиряков-Гвардейцев Улица", build: "298"},
{street: "Сибиряков-Гвардейцев Улица", build: "3_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "300"},
{street: "Сибиряков-Гвардейцев Улица", build: "302"},
{street: "Сибиряков-Гвардейцев Улица", build: "308"},
{street: "Сибиряков-Гвардейцев Улица", build: "310"},
{street: "Сибиряков-Гвардейцев Улица", build: "312"},
{street: "Сибиряков-Гвардейцев Улица", build: "314"},
{street: "Сибиряков-Гвардейцев Улица", build: "316"},
{street: "Сибиряков-Гвардейцев Улица", build: "320"},
{street: "Сибиряков-Гвардейцев Улица", build: "322"},
{street: "Сибиряков-Гвардейцев Улица", build: "324"},
{street: "Сибиряков-Гвардейцев Улица", build: "326"},
{street: "Сибиряков-Гвардейцев Улица", build: "328"},
{street: "Сибиряков-Гвардейцев Улица", build: "328А"},
{street: "Сибиряков-Гвардейцев Улица", build: "330"},
{street: "Сибиряков-Гвардейцев Улица", build: "334"},
{street: "Сибиряков-Гвардейцев Улица", build: "4"},
{street: "Сибиряков-Гвардейцев Улица", build: "5"},
{street: "Сибиряков-Гвардейцев Улица", build: "6"},
{street: "Сибиряков-Гвардейцев Улица", build: "7_ETTH"},
{street: "Сибиряков-Гвардейцев Улица", build: "8"},
{street: "Соборная Улица", build: "10"},
{street: "Соборная Улица", build: "12"},
{street: "Соборная Улица", build: "14"},
{street: "Соборная Улица", build: "14А"},
{street: "Соборная Улица", build: "3"},
{street: "Соборная Улица", build: "5"},
{street: "Соборная Улица", build: "6"},
{street: "Соборная Улица", build: "7"},
{street: "Советская Улица", build: "4"},
{street: "Советский пр", build: "24"},
{street: "Советский пр", build: "33"},
{street: "Советский пр", build: "34"},
{street: "Советский пр", build: "39"},
{street: "Советский пр", build: "47_ETTH"},
{street: "Советский пр", build: "49_ETTH"},
{street: "Советский пр", build: "67"},
{street: "Советский пр", build: "69"},
{street: "Советский пр", build: "70А"},
{street: "Спартака Улица", build: "21"},
{street: "Спартака Улица", build: "8"},
{street: "Спортивная Улица", build: "16А"},
{street: "Спортивная Улица", build: "17"},
{street: "Спортивная Улица", build: "20"},
{street: "Спортивная Улица", build: "20А"},
{street: "Спортивная Улица", build: "22"},
{street: "Спортивная Улица", build: "24"},
{street: "Спортивная Улица", build: "30"},
{street: "Спортивная Улица", build: "34"},
{street: "Спортивная Улица", build: "34Б"},
{street: "Спортивная Улица", build: "38"},
{street: "Спортивная Улица", build: "40"},
{street: "Стадионная Улица", build: "4А"},
{street: "Стадионная Улица", build: "4Б"},
{street: "Стадионная Улица", build: "6"},
{street: "Стахановская Улица", build: "23"},
{street: "Стахановская Улица", build: "23А"},
{street: "Стахановская Улица", build: "23Б"},
{street: "Строителей Бульвар", build: "11"},
{street: "Строителей Бульвар", build: "12"},
{street: "Строителей Бульвар", build: "12А"},
{street: "Строителей Бульвар", build: "13"},
{street: "Строителей Бульвар", build: "14"},
{street: "Строителей Бульвар", build: "14А"},
{street: "Строителей Бульвар", build: "15"},
{street: "Строителей Бульвар", build: "16"},
{street: "Строителей Бульвар", build: "16А"},
{street: "Строителей Бульвар", build: "16Б"},
{street: "Строителей Бульвар", build: "19"},
{street: "Строителей Бульвар", build: "20"},
{street: "Строителей Бульвар", build: "21"},
{street: "Строителей Бульвар", build: "21А"},
{street: "Строителей Бульвар", build: "21Б"},
{street: "Строителей Бульвар", build: "22А"},
{street: "Строителей Бульвар", build: "22Б"},
{street: "Строителей Бульвар", build: "23"},
{street: "Строителей Бульвар", build: "23А"},
{street: "Строителей Бульвар", build: "24"},
{street: "Строителей Бульвар", build: "24А"},
{street: "Строителей Бульвар", build: "25"},
{street: "Строителей Бульвар", build: "25А"},
{street: "Строителей Бульвар", build: "25Б"},
{street: "Строителей Бульвар", build: "25В"},
{street: "Строителей Бульвар", build: "25г"},
{street: "Строителей Бульвар", build: "26"},
{street: "Строителей Бульвар", build: "26/1"},
{street: "Строителей Бульвар", build: "26/2"},
{street: "Строителей Бульвар", build: "26А"},
{street: "Строителей Бульвар", build: "26Б"},
{street: "Строителей Бульвар", build: "26В"},
{street: "Строителей Бульвар", build: "26Г"},
{street: "Строителей Бульвар", build: "27"},
{street: "Строителей Бульвар", build: "27А"},
{street: "Строителей Бульвар", build: "27Б"},
{street: "Строителей Бульвар", build: "27В"},
{street: "Строителей Бульвар", build: "28"},
{street: "Строителей Бульвар", build: "28/1"},
{street: "Строителей Бульвар", build: "28А"},
{street: "Строителей Бульвар", build: "28Б"},
{street: "Строителей Бульвар", build: "29"},
{street: "Строителей Бульвар", build: "29А"},
{street: "Строителей Бульвар", build: "3"},
{street: "Строителей Бульвар", build: "30"},
{street: "Строителей Бульвар", build: "30А"},
{street: "Строителей Бульвар", build: "30Б"},
{street: "Строителей Бульвар", build: "31"},
{street: "Строителей Бульвар", build: "31Б"},
{street: "Строителей Бульвар", build: "32"},
{street: "Строителей Бульвар", build: "32/1"},
{street: "Строителей Бульвар", build: "32/3"},
{street: "Строителей Бульвар", build: "32А"},
{street: "Строителей Бульвар", build: "33"},
{street: "Строителей Бульвар", build: "33А"},
{street: "Строителей Бульвар", build: "34А"},
{street: "Строителей Бульвар", build: "35"},
{street: "Строителей Бульвар", build: "36"},
{street: "Строителей Бульвар", build: "37_ETTH"},
{street: "Строителей Бульвар", build: "39"},
{street: "Строителей Бульвар", build: "4"},
{street: "Строителей Бульвар", build: "40"},
{street: "Строителей Бульвар", build: "41"},
{street: "Строителей Бульвар", build: "42"},
{street: "Строителей Бульвар", build: "42Б"},
{street: "Строителей Бульвар", build: "43"},
{street: "Строителей Бульвар", build: "44"},
{street: "Строителей Бульвар", build: "44А"},
{street: "Строителей Бульвар", build: "45_ETTH"},
{street: "Строителей Бульвар", build: "46"},
{street: "Строителей Бульвар", build: "46А"},
{street: "Строителей Бульвар", build: "46Б"},
{street: "Строителей Бульвар", build: "5"},
{street: "Строителей Бульвар", build: "50"},
{street: "Строителей Бульвар", build: "50/2"},
{street: "Строителей Бульвар", build: "52А"},
{street: "Строителей Бульвар", build: "56"},
{street: "Строителей Бульвар", build: "56/2"},
{street: "Строителей Бульвар", build: "57/1"},
{street: "Строителей Бульвар", build: "57/2"},
{street: "Строителей Бульвар", build: "59/1"},
{street: "Строителей Бульвар", build: "59/2"},
{street: "Строителей Бульвар", build: "6"},
{street: "Строителей Бульвар", build: "61"},
{street: "Строителей Бульвар", build: "63"},
{street: "Строителей Бульвар", build: "7"},
{street: "Суворова Улица", build: "3"},
{street: "Тайгинская Улица", build: "12"},
{street: "Тайгинская Улица", build: "8А"},
{street: "Тайгинская Улица", build: "8Б"},
{street: "Телецентр Улица", build: "1"},
{street: "Терешковой Улица", build: "18Б"},
{street: "Терешковой Улица", build: "18В"},
{street: "Терешковой Улица", build: "19"},
{street: "Терешковой Улица", build: "2"},
{street: "Терешковой Улица", build: "21"},
{street: "Терешковой Улица", build: "22"},
{street: "Терешковой Улица", build: "22Б"},
{street: "Терешковой Улица", build: "23"},
{street: "Терешковой Улица", build: "24"},
{street: "Терешковой Улица", build: "24А"},
{street: "Терешковой Улица", build: "25"},
{street: "Терешковой Улица", build: "25А"},
{street: "Терешковой Улица", build: "26"},
{street: "Терешковой Улица", build: "27"},
{street: "Терешковой Улица", build: "28"},
{street: "Терешковой Улица", build: "28А"},
{street: "Терешковой Улица", build: "28Б"},
{street: "Терешковой Улица", build: "29"},
{street: "Терешковой Улица", build: "31"},
{street: "Терешковой Улица", build: "32"},
{street: "Терешковой Улица", build: "34"},
{street: "Терешковой Улица", build: "36"},
{street: "Терешковой Улица", build: "38"},
{street: "Терешковой Улица", build: "4"},
{street: "Терешковой Улица", build: "40А"},
{street: "Терешковой Улица", build: "42"},
{street: "Терешковой Улица", build: "44"},
{street: "Тухачевского Улица", build: "12"},
{street: "Тухачевского Улица", build: "14"},
{street: "Тухачевского Улица", build: "14А"},
{street: "Тухачевского Улица", build: "16"},
{street: "Тухачевского Улица", build: "2"},
{street: "Тухачевского Улица", build: "27"},
{street: "Тухачевского Улица", build: "28"},
{street: "Тухачевского Улица", build: "29"},
{street: "Тухачевского Улица", build: "29А"},
{street: "Тухачевского Улица", build: "29Б"},
{street: "Тухачевского Улица", build: "29Б/1"},
{street: "Тухачевского Улица", build: "31"},
{street: "Тухачевского Улица", build: "31А"},
{street: "Тухачевского Улица", build: "31Б"},
{street: "Тухачевского Улица", build: "31В"},
{street: "Тухачевского Улица", build: "31Г"},
{street: "Тухачевского Улица", build: "31Д"},
{street: "Тухачевского Улица", build: "33А"},
{street: "Тухачевского Улица", build: "35"},
{street: "Тухачевского Улица", build: "35А"},
{street: "Тухачевского Улица", build: "37А"},
{street: "Тухачевского Улица", build: "39"},
{street: "Тухачевского Улица", build: "4"},
{street: "Тухачевского Улица", build: "41А"},
{street: "Тухачевского Улица", build: "43"},
{street: "Тухачевского Улица", build: "45"},
{street: "Тухачевского Улица", build: "45А"},
{street: "Тухачевского Улица", build: "45Б"},
{street: "Тухачевского Улица", build: "45В"},
{street: "Тухачевского Улица", build: "47"},
{street: "Тухачевского Улица", build: "47А"},
{street: "Тухачевского Улица", build: "47Б"},
{street: "Тухачевского Улица", build: "49"},
{street: "Тухачевского Улица", build: "49А"},
{street: "Тухачевского Улица", build: "49Б"},
{street: "Тухачевского Улица", build: "8"},
{street: "Ульяны Громовой Улица", build: "7А"},
{street: "Ушакова Улица", build: "1"},
{street: "Ушакова Улица", build: "3"},
{street: "Ушакова Улица", build: "5"},
{street: "Федоровского Улица", build: "22_ETTH"},
{street: "Федоровского Улица", build: "24_ETTH"},
{street: "Федоровского Улица", build: "26_ETTH"},
{street: "Федоровского Улица", build: "4_ETTH"},
{street: "Федоровского Улица", build: "8"},
{street: "Халтурина Улица", build: "21Б"},
{street: "Халтурина Улица", build: "27"},
{street: "Халтурина Улица", build: "29А"},
{street: "Халтурина Улица", build: "29Б"},
{street: "Халтурина Улица", build: "35А"},
{street: "Халтурина Улица", build: "37А"},
{street: "Халтурина Улица", build: "39Б"},
{street: "Халтурина Улица", build: "45"},
{street: "Химиков пр", build: "12"},
{street: "Химиков пр", build: "12А"},
{street: "Химиков пр", build: "14"},
{street: "Химиков пр", build: "14А"},
{street: "Химиков пр", build: "14Б"},
{street: "Химиков пр", build: "15"},
{street: "Химиков пр", build: "16"},
{street: "Химиков пр", build: "16А"},
{street: "Химиков пр", build: "17"},
{street: "Химиков пр", build: "19"},
{street: "Химиков пр", build: "19А"},
{street: "Химиков пр", build: "21"},
{street: "Химиков пр", build: "22"},
{street: "Химиков пр", build: "23"},
{street: "Химиков пр", build: "23А"},
{street: "Химиков пр", build: "24"},
{street: "Химиков пр", build: "24А"},
{street: "Химиков пр", build: "25"},
{street: "Химиков пр", build: "26"},
{street: "Химиков пр", build: "26А"},
{street: "Химиков пр", build: "34"},
{street: "Химиков пр", build: "34/1"},
{street: "Химиков пр", build: "34/2"},
{street: "Химиков пр", build: "36"},
{street: "Химиков пр", build: "36/1"},
{street: "Химиков пр", build: "36/2"},
{street: "Химиков пр", build: "43"},
{street: "Химиков пр", build: "43А"},
{street: "Химиков пр", build: "43Б"},
{street: "Химиков пр", build: "43В"},
{street: "Химиков пр", build: "47"},
{street: "Химиков пр", build: "47А"},
{street: "Химиков пр", build: "49"},
{street: "Химиков пр", build: "49А"},
{street: "Химиков пр", build: "51"},
{street: "Черемховская Улица", build: "2"},
{street: "Черемховская Улица", build: "4"},
{street: "Черняховского Улица", build: "1А"},
{street: "Шахтеров пр", build: "101А"},
{street: "Шахтеров пр", build: "103"},
{street: "Шахтеров пр", build: "107А"},
{street: "Шахтеров пр", build: "109"},
{street: "Шахтеров пр", build: "115"},
{street: "Шахтеров пр", build: "117"},
{street: "Шахтеров пр", build: "119"},
{street: "Шахтеров пр", build: "119А"},
{street: "Шахтеров пр", build: "121"},
{street: "Шахтеров пр", build: "123"},
{street: "Шахтеров пр", build: "32"},
{street: "Шахтеров пр", build: "32А"},
{street: "Шахтеров пр", build: "34"},
{street: "Шахтеров пр", build: "34А"},
{street: "Шахтеров пр", build: "36"},
{street: "Шахтеров пр", build: "36А"},
{street: "Шахтеров пр", build: "36Б"},
{street: "Шахтеров пр", build: "37"},
{street: "Шахтеров пр", build: "38"},
{street: "Шахтеров пр", build: "38А"},
{street: "Шахтеров пр", build: "38Б"},
{street: "Шахтеров пр", build: "40"},
{street: "Шахтеров пр", build: "40А"},
{street: "Шахтеров пр", build: "41"},
{street: "Шахтеров пр", build: "42"},
{street: "Шахтеров пр", build: "43"},
{street: "Шахтеров пр", build: "44"},
{street: "Шахтеров пр", build: "44А"},
{street: "Шахтеров пр", build: "45"},
{street: "Шахтеров пр", build: "46"},
{street: "Шахтеров пр", build: "47"},
{street: "Шахтеров пр", build: "48"},
{street: "Шахтеров пр", build: "48А"},
{street: "Шахтеров пр", build: "49"},
{street: "Шахтеров пр", build: "51"},
{street: "Шахтеров пр", build: "53"},
{street: "Шахтеров пр", build: "55"},
{street: "Шахтеров пр", build: "57"},
{street: "Шахтеров пр", build: "57А"},
{street: "Шахтеров пр", build: "58"},
{street: "Шахтеров пр", build: "58А"},
{street: "Шахтеров пр", build: "59"},
{street: "Шахтеров пр", build: "59А"},
{street: "Шахтеров пр", build: "60"},
{street: "Шахтеров пр", build: "60А"},
{street: "Шахтеров пр", build: "60Б"},
{street: "Шахтеров пр", build: "61"},
{street: "Шахтеров пр", build: "61А"},
{street: "Шахтеров пр", build: "61Б"},
{street: "Шахтеров пр", build: "62"},
{street: "Шахтеров пр", build: "62А"},
{street: "Шахтеров пр", build: "62Б"},
{street: "Шахтеров пр", build: "63"},
{street: "Шахтеров пр", build: "64"},
{street: "Шахтеров пр", build: "65"},
{street: "Шахтеров пр", build: "65А"},
{street: "Шахтеров пр", build: "66"},
{street: "Шахтеров пр", build: "67"},
{street: "Шахтеров пр", build: "68"},
{street: "Шахтеров пр", build: "68А"},
{street: "Шахтеров пр", build: "69"},
{street: "Шахтеров пр", build: "70"},
{street: "Шахтеров пр", build: "70А"},
{street: "Шахтеров пр", build: "71"},
{street: "Шахтеров пр", build: "72"},
{street: "Шахтеров пр", build: "72А"},
{street: "Шахтеров пр", build: "73"},
{street: "Шахтеров пр", build: "75"},
{street: "Шахтеров пр", build: "77"},
{street: "Шахтеров пр", build: "79"},
{street: "Шахтеров пр", build: "80"},
{street: "Шахтеров пр", build: "81"},
{street: "Шахтеров пр", build: "82"},
{street: "Шахтеров пр", build: "82А"},
{street: "Шахтеров пр", build: "82Б"},
{street: "Шахтеров пр", build: "83"},
{street: "Шахтеров пр", build: "83А"},
{street: "Шахтеров пр", build: "84"},
{street: "Шахтеров пр", build: "84А"},
{street: "Шахтеров пр", build: "85"},
{street: "Шахтеров пр", build: "85А"},
{street: "Шахтеров пр", build: "86"},
{street: "Шахтеров пр", build: "88"},
{street: "Шахтеров пр", build: "90"},
{street: "Шахтеров пр", build: "91"},
{street: "Шахтеров пр", build: "91А"},
{street: "Шахтеров пр", build: "92"},
{street: "Шахтеров пр", build: "93"},
{street: "Шахтеров пр", build: "93А"},
{street: "Шахтеров пр", build: "93Д"},
{street: "Шахтеров пр", build: "95"},
{street: "Шахтеров пр", build: "97"},
{street: "Шахтеров пр", build: "99"},
{street: "Шорникова Улица", build: "11"},
{street: "Шорникова Улица", build: "13"},
{street: "Шорникова Улица", build: "15"},
{street: "Щегловский пер", build: "10"},
{street: "Щегловский пер", build: "10А"},
{street: "Щегловский пер", build: "12"},
{street: "Щегловский пер", build: "38"},
{street: "Щегловский пер", build: "4/1"},
{street: "Щегловский пер", build: "40"},
{street: "Щегловский пер", build: "6"},
{street: "Щегловский пер", build: "8"},
{street: "Юрия Двужильного Улица", build: "10А"},
{street: "Юрия Двужильного Улица", build: "10Б"},
{street: "Юрия Двужильного Улица", build: "10В"},
{street: "Юрия Двужильного Улица", build: "12_ETTH"},
{street: "Юрия Двужильного Улица", build: "12Б"},
{street: "Юрия Двужильного Улица", build: "14_ETTH"},
{street: "Юрия Двужильного Улица", build: "16А_ETTH"},
{street: "Юрия Двужильного Улица", build: "24/1_ETTH"},
{street: "Юрия Двужильного Улица", build: "24/2_ETTH"},
{street: "Юрия Двужильного Улица", build: "26А"},
{street: "Юрия Двужильного Улица", build: "26Б"},
{street: "Юрия Двужильного Улица", build: "30А"},
{street: "Юрия Двужильного Улица", build: "32/1"},
{street: "Юрия Двужильного Улица", build: "32/2"},
{street: "Юрия Двужильного Улица", build: "32А_ETTH"},
{street: "Юрия Двужильного Улица", build: "32Б"},
{street: "Юрия Двужильного Улица", build: "36"},
{street: "Юрия Двужильного Улица", build: "36А_ETTH"},
{street: "Юрия Смирнова Улица", build: "27"},
], streets: [{street: "1-Й Квартал"},
{street: "2-Й Квартал"},
{street: "40 Лет Октября Улица"},
{street: "50 Лет Октября Улица"},
{street: "Авроры Улица"},
{street: "Александрова Улица"},
{street: "Аллейная Улица"},
{street: "Арочная Улица"},
{street: "Базовая Улица"},
{street: "Барнаульская Улица"},
{street: "Белозерная Улица"},
{street: "Беломорский 1-Й пер"},
{street: "Большевистская Улица"},
{street: "Буденного Улица"},
{street: "В.В.Михайлова пр"},
{street: "Варяжская Улица"},
{street: "Васильева Улица"},
{street: "Вельская Улица"},
{street: "Веры Волошиной Улица"},
{street: "Весенняя Улица"},
{street: "Водонасосная Станция"},
{street: "Волгоградская Улица"},
{street: "Волкова Улица"},
{street: "Ворошилова Улица"},
{street: "Восточный пр"},
{street: "Гагарина Улица"},
{street: "Гурьевская Улица"},
{street: "Дегтярева Улица"},
{street: "Дзержинского Улица"},
{street: "Докучаева Улица"},
{street: "Дружбы Улица"},
{street: "Ермака Улица"},
{street: "Железнякова Улица"},
{street: "Заречная 1-Я Улица"},
{street: "Заречная 2-Я Улица"},
{street: "Иланский 3-Й пер"},
{street: "Инженерная Улица"},
{street: "Инициативная Улица"},
{street: "Институтская Улица"},
{street: "Калинина Улица"},
{street: "Каркасная Улица"},
{street: "Кедровый Бульвар"},
{street: "Кирова Улица"},
{street: "Коломейцева Улица"},
{street: "Комсомольский пр"},
{street: "Космическая Улица"},
{street: "Красная Улица"},
{street: "Красноармейская Улица"},
{street: "Кузнецкий пр"},
{street: "Ленина пр"},
{street: "Ленинградский пр"},
{street: "Леонова пер"},
{street: "Леонова Улица"},
{street: "Линия 1-Я Улица"},
{street: "Марковцева Улица"},
{street: "Масальская Улица"},
{street: "Металлистов Улица"},
{street: "Мирная Улица"},
{street: "Мичурина пер"},
{street: "Мичурина Улица"},
{street: "Молодежный пр"},
{street: "Московский пр"},
{street: "Мостовая Улица"},
{street: "Муромцева Улица"},
{street: "Нахимова Улица"},
{street: "Новогодняя Улица"},
{street: "Ногинская Улица"},
{street: "Ноградская Улица"},
{street: "Окружная Улица"},
{street: "Октябрьский пр"},
{street: "Орджоникидзе Улица"},
{street: "Осенний Бульвар"},
{street: "Патриотов Улица"},
{street: "Пионерский Бульвар"},
{street: "Попова Улица"},
{street: "Потемкина Улица"},
{street: "Предзаводская Улица"},
{street: "Пригородная Улица"},
{street: "Притомская Набережная Улица"},
{street: "Притомский пр"},
{street: "Пролетарская Улица"},
{street: "Промышленновский Проезд"},
{street: "Промышленновское Шоссе"},
{street: "Радищева Улица"},
{street: "Рекордная Улица"},
{street: "Рекордный пер"},
{street: "Сарыгина Улица"},
{street: "Свободы Улица"},
{street: "Севастопольская Улица"},
{street: "Сергея Тюленина Улица"},
{street: "Серебряный Бор Улица"},
{street: "Сибиряков-Гвардейцев Улица"},
{street: "Соборная Улица"},
{street: "Советская Улица"},
{street: "Советский пр"},
{street: "Спартака Улица"},
{street: "Спортивная Улица"},
{street: "Стадионная Улица"},
{street: "Стахановская Улица"},
{street: "Строителей Бульвар"},
{street: "Суворова Улица"},
{street: "Тайгинская Улица"},
{street: "Телецентр Улица"},
{street: "Терешковой Улица"},
{street: "Тухачевского Улица"},
{street: "Ульяны Громовой Улица"},
{street: "Ушакова Улица"},
{street: "Федоровского Улица"},
{street: "Халтурина Улица"},
{street: "Химиков пр"},
{street: "Черемховская Улица"},
{street: "Черняховского Улица"},
{street: "Шахтеров пр"},
{street: "Шорникова Улица"},
{street: "Щегловский пер"},
{street: "Юрия Двужильного Улица"},
{street: "Юрия Смирнова Улица"},
] };
