var selected_street ='';var selected_build = '';var city_streets = Object();
city_streets["kemerovo"] = {builds: [
{street: "1-й Беломорский переулок", build: "7"},
{street: "1-й Квартал", build: "1"},
{street: "1-й Квартал", build: "2"},
{street: "1-я Заречная", build: "6"},
{street: "1-я Заречная", build: "10"},
{street: "1-я Линия", build: "2"},
{street: "1-я Линия", build: "4 (ETTH)"},
{street: "1-я Линия", build: "6 (ETTH)"},
{street: "1-я Линия", build: "8"},
{street: "1-я Линия", build: "10 (ETTH)"},
{street: "1-я Линия", build: "14 (ETTH)"},
{street: "1-я Линия", build: " 10А (ETTH)"},
{street: "1-я Линия", build: " 20А"},
{street: "1-я Линия", build: " 20Б"},
{street: "1-я Линия", build: " 20В"},
{street: "1-я Линия", build: " 20Д"},
{street: "2-й Квартал", build: "1"},
{street: "2-й Квартал", build: "2"},
{street: "2-й Квартал", build: "3"},
{street: "2-й Квартал", build: "4"},
{street: "2-й Квартал", build: "5"},
{street: "2-й Квартал", build: "6"},
{street: "2-й Квартал", build: "7"},
{street: "2-й Квартал", build: "8"},
{street: "2-й Квартал", build: "9"},
{street: "2-й Квартал", build: "10"},
{street: "2-я Заречная", build: "2"},
{street: "2-я Заречная", build: "3"},
{street: "2-я Заречная", build: "4"},
{street: "2-я Заречная", build: "5"},
{street: "2-я Заречная", build: "6"},
{street: "2-я Заречная", build: "7"},
{street: "2-я Заречная", build: "8"},
{street: "2-я Заречная", build: "9"},
{street: "2-я Заречная", build: "11"},
{street: "2-я Заречная", build: " 3А"},
{street: "2-я Заречная", build: " 5А"},
{street: "2-я Заречная", build: " 5Б"},
{street: "2-я Заречная", build: " 7А"},
{street: "2-я Заречная", build: " 9А"},
{street: "3-й Иланский переулок", build: "2"},
{street: "3-й Иланский переулок", build: "3"},
{street: "3-й Иланский переулок", build: "9"},
{street: "3-й Иланский переулок", build: "11"},
{street: "3-й Иланский переулок", build: " 3А"},
{street: "3-й Иланский переулок", build: " 3Б"},
{street: "40 лет Октября", build: "3"},
{street: "40 лет Октября", build: "5"},
{street: "40 лет Октября", build: "7"},
{street: "40 лет Октября", build: "8"},
{street: "40 лет Октября", build: "8"},
{street: "40 лет Октября", build: "11"},
{street: "40 лет Октября", build: "13"},
{street: "40 лет Октября", build: "15"},
{street: "40 лет Октября", build: "17"},
{street: "40 лет Октября", build: "19"},
{street: "40 лет Октября", build: "20"},
{street: "40 лет Октября", build: "23"},
{street: "40 лет Октября", build: "25"},
{street: "40 лет Октября", build: "27"},
{street: "40 лет Октября", build: "29"},
{street: "40 лет Октября", build: " 9/2"},
{street: "40 лет Октября", build: " 9/4"},
{street: "50 лет Октября", build: "6"},
{street: "50 лет Октября", build: "8"},
{street: "50 лет Октября", build: "12"},
{street: "50 лет Октября", build: "13"},
{street: "50 лет Октября", build: "14"},
{street: "50 лет Октября", build: "16"},
{street: "50 лет Октября", build: "18"},
{street: "Авроры", build: "4"},
{street: "Авроры", build: "6"},
{street: "Авроры", build: "10"},
{street: "Авроры", build: "14"},
{street: "Александрова", build: "2"},
{street: "Александрова", build: "4"},
{street: "Александрова", build: "8"},
{street: "Александрова", build: "11"},
{street: "Александрова", build: "14"},
{street: "Александрова", build: "15"},
{street: "Александрова", build: "16"},
{street: "Александрова", build: "17"},
{street: "Александрова", build: " 12А"},
{street: "Александрова", build: " 13А"},
{street: "Александрова", build: " 14А"},
{street: "Александрова", build: " 15А"},
{street: "Александрова", build: " 6А"},
{street: "Аллейная", build: "2"},
{street: "Аллейная", build: "7"},
{street: "Аллейная", build: "9"},
{street: "Аллейная", build: " 9А"},
{street: "Арочная", build: "33"},
{street: "Арочная", build: "39"},
{street: "Арочная", build: " 41А"},
{street: "Базовая", build: "6"},
{street: "Базовая", build: "12"},
{street: "Базовая", build: " 4Б"},
{street: "Базовая", build: " 4В"},
{street: "Базовая", build: " 6Б"},
{street: "Барнаульская", build: "27"},
{street: "Барнаульская", build: "29"},
{street: "Барнаульская", build: "31"},
{street: "Барнаульская", build: "33"},
{street: "Барнаульская", build: " 31А"},
{street: "Белозёрная", build: "11"},
{street: "Белозёрная", build: "13"},
{street: "Белозёрная", build: "15"},
{street: "Белозёрная", build: "17"},
{street: "Белозёрная", build: "19"},
{street: "Белозёрная", build: "21"},
{street: "Белозёрная", build: "23"},
{street: "Белозёрная", build: "25"},
{street: "Белозёрная", build: "31"},
{street: "Белозёрная", build: "33"},
{street: "Белозёрная", build: "44"},
{street: "Белозёрная", build: " 13А"},
{street: "Белозёрная", build: " 13Б"},
{street: "Белозёрная", build: " 40А"},
{street: "Белозёрная", build: " 44А"},
{street: "Белозёрная", build: " 44Б"},
{street: "Большевистская", build: "2"},
{street: "Будённого", build: "33"},
{street: "В.В. Михайлова", build: " 3Бк1"},
{street: "В.В. Михайлова", build: " 3Бк2"},
{street: "В.В. Михайлова", build: " 3Бк3"},
{street: "В.В. Михайлова", build: " 3Бк4"},
{street: "В.В. Михайлова", build: " 3Бк5"},
{street: "Варяжская", build: "1"},
{street: "Варяжская", build: "3"},
{street: "Варяжская", build: "5"},
{street: "Варяжская", build: "7"},
{street: "Варяжская", build: "13"},
{street: "Варяжская", build: "15"},
{street: "Варяжская", build: "19"},
{street: "Варяжская", build: "21"},
{street: "Варяжская", build: "25"},
{street: "Варяжская", build: "27"},
{street: "Васильева", build: "7"},
{street: "Васильева", build: "9"},
{street: "Васильева", build: "11"},
{street: "Вельская", build: "1"},
{street: "Вельская", build: " 10А"},
{street: "Вельская", build: " 1А"},
{street: "Вельская", build: " 1Б"},
{street: "Вельская", build: " 1В"},
{street: "Веры Волошиной", build: "10"},
{street: "Веры Волошиной", build: "12 (ETTH)"},
{street: "Веры Волошиной", build: "16 (ETTH)"},
{street: "Веры Волошиной", build: "20 (ETTH)"},
{street: "Веры Волошиной", build: "22 (ETTH)"},
{street: "Веры Волошиной", build: "25 (ETTH)"},
{street: "Веры Волошиной", build: "28 (ETTH)"},
{street: "Веры Волошиной", build: "29 (ETTH)"},
{street: "Веры Волошиной", build: "30 (ETTH)"},
{street: "Веры Волошиной", build: "32"},
{street: "Веры Волошиной", build: "33 (ETTH)"},
{street: "Веры Волошиной", build: "37 (ETTH)"},
{street: "Веры Волошиной", build: "39 (ETTH)"},
{street: "Веры Волошиной", build: "41 (ETTH)"},
{street: "Веры Волошиной", build: "43 (ETTH)"},
{street: "Веры Волошиной", build: "45 (ETTH)"},
{street: "Веры Волошиной", build: "47 (ETTH)"},
{street: "Веры Волошиной", build: " 13Б"},
{street: "Веры Волошиной", build: " 28Б (ETTH)"},
{street: "Веры Волошиной", build: " 38А"},
{street: "Веры Волошиной", build: " 38Б"},
{street: "Веры Волошиной", build: " 41/1 (ETTH)"},
{street: "Веры Волошиной", build: " 41А (ETTH)"},
{street: "Веры Волошиной", build: " 41Б (ETTH)"},
{street: "Веры Волошиной", build: " 45А (ETTH)"},
{street: "Весенняя", build: "2"},
{street: "Весенняя", build: "18"},
{street: "Весенняя", build: "21 (ETTH)"},
{street: "Весенняя", build: "22 (ETTH)"},
{street: "Весенняя", build: "23"},
{street: "Весенняя", build: "25"},
{street: "Весенняя", build: "26 (ETTH)"},
{street: "Волгоградская", build: "1"},
{street: "Волгоградская", build: "4"},
{street: "Волгоградская", build: "6"},
{street: "Волгоградская", build: "8"},
{street: "Волгоградская", build: "9"},
{street: "Волгоградская", build: "11"},
{street: "Волгоградская", build: "13"},
{street: "Волгоградская", build: "14"},
{street: "Волгоградская", build: "15"},
{street: "Волгоградская", build: "16"},
{street: "Волгоградская", build: "17"},
{street: "Волгоградская", build: "18"},
{street: "Волгоградская", build: "20"},
{street: "Волгоградская", build: "21"},
{street: "Волгоградская", build: "23"},
{street: "Волгоградская", build: "24"},
{street: "Волгоградская", build: "25"},
{street: "Волгоградская", build: "26"},
{street: "Волгоградская", build: "27"},
{street: "Волгоградская", build: "28"},
{street: "Волгоградская", build: "29"},
{street: "Волгоградская", build: "30"},
{street: "Волгоградская", build: "31"},
{street: "Волгоградская", build: "32"},
{street: "Волгоградская", build: "33"},
{street: "Волгоградская", build: "34"},
{street: "Волгоградская", build: " 21А"},
{street: "Волгоградская", build: " 24А"},
{street: "Волгоградская", build: " 24Б"},
{street: "Волгоградская", build: " 26А"},
{street: "Волгоградская", build: " 28А"},
{street: "Волгоградская", build: " 28Б"},
{street: "Волгоградская", build: " 31А"},
{street: "Волгоградская", build: " 32А"},
{street: "Волгоградская", build: " 32Б"},
{street: "Волгоградская", build: " 32В"},
{street: "Волгоградская", build: " 34А"},
{street: "Волгоградская", build: " 34Б"},
{street: "Волгоградская", build: " 34В"},
{street: "Волкова", build: "36"},
{street: "Ворошилова", build: "1"},
{street: "Ворошилова", build: "2"},
{street: "Ворошилова", build: "3"},
{street: "Ворошилова", build: "4"},
{street: "Ворошилова", build: "5"},
{street: "Ворошилова", build: "6"},
{street: "Ворошилова", build: "7"},
{street: "Ворошилова", build: "8"},
{street: "Ворошилова", build: "9"},
{street: "Ворошилова", build: "11"},
{street: "Ворошилова", build: "12"},
{street: "Ворошилова", build: "16"},
{street: "Ворошилова", build: "18"},
{street: "Ворошилова", build: "20"},
{street: "Ворошилова", build: "40"},
{street: "Ворошилова", build: " 10А"},
{street: "Ворошилова", build: " 11А"},
{street: "Ворошилова", build: " 11Б"},
{street: "Ворошилова", build: " 14А"},
{street: "Ворошилова", build: " 16А"},
{street: "Ворошилова", build: " 18А"},
{street: "Ворошилова", build: " 1А"},
{street: "Ворошилова", build: " 1Б"},
{street: "Ворошилова", build: " 1В"},
{street: "Ворошилова", build: " 24А"},
{street: "Ворошилова", build: " 24Б"},
{street: "Ворошилова", build: " 24В"},
{street: "Ворошилова", build: " 2А"},
{street: "Ворошилова", build: " 3А"},
{street: "Ворошилова", build: " 3Б"},
{street: "Ворошилова", build: " 4А"},
{street: "Ворошилова", build: " 4Б"},
{street: "Ворошилова", build: " 5А"},
{street: "Ворошилова", build: " 5Б"},
{street: "Ворошилова", build: " 6А"},
{street: "Ворошилова", build: " 7А"},
{street: "Ворошилова", build: " 7Б"},
{street: "Ворошилова", build: " 9Б"},
{street: "Ворошилова", build: " 9В"},
{street: "Восточный", build: "23"},
{street: "Восточный", build: "25"},
{street: "Восточный", build: "29"},
{street: "Восточный", build: "31"},
{street: "Восточный", build: " 21к1"},
{street: "Восточный", build: " 21к2"},
{street: "Восточный", build: " 21к3"},
{street: "Восточный", build: " 29А"},
{street: "Гагарина", build: "108"},
{street: "Гагарина", build: "120"},
{street: "Гагарина", build: "122"},
{street: "Гагарина", build: "128"},
{street: "Гагарина", build: "130"},
{street: "Гагарина", build: "132"},
{street: "Гагарина", build: "136"},
{street: "Гагарина", build: "138"},
{street: "Гагарина", build: "140"},
{street: "Гагарина", build: "142"},
{street: "Гагарина", build: "144"},
{street: "Гагарина", build: "148"},
{street: "Гагарина", build: "151"},
{street: "Гагарина", build: "153"},
{street: "Гагарина", build: "155"},
{street: "Гагарина", build: "157"},
{street: "Гагарина", build: "159"},
{street: "Гурьевская", build: "14"},
{street: "Гурьевская", build: "15"},
{street: "Гурьевская", build: "17"},
{street: "Гурьевская", build: "18"},
{street: "Дегтярёва", build: "1"},
{street: "Дегтярёва", build: "3"},
{street: "Дегтярёва", build: "5"},
{street: "Дегтярёва", build: "6"},
{street: "Дегтярёва", build: "7"},
{street: "Дзержинского", build: "3"},
{street: "Дзержинского", build: "4 (ETTH)"},
{street: "Дзержинского", build: "5"},
{street: "Дзержинского", build: "6 (ETTH)"},
{street: "Дзержинского", build: "7"},
{street: "Дзержинского", build: "11"},
{street: "Дзержинского", build: "13"},
{street: "Дзержинского", build: " 2Б (ETTH)"},
{street: "Дзержинского", build: " 5А"},
{street: "Дзержинского", build: " 9А"},
{street: "Докучаева", build: "12"},
{street: "Дружбы", build: "1 (ETTH)"},
{street: "Дружбы", build: "3 (ETTH)"},
{street: "Дружбы", build: "5 (ETTH)"},
{street: "Дружбы", build: "17"},
{street: "Дружбы", build: "19"},
{street: "Дружбы", build: "27"},
{street: "Дружбы", build: "29"},
{street: "Дружбы", build: "31"},
{street: "Дружбы", build: "33"},
{street: "Дружбы", build: "35"},
{street: "Дружбы", build: " 1А (ETTH)"},
{street: "Дружбы", build: " 1Б"},
{street: "Дружбы", build: " 27А (ETTH)"},
{street: "Дружбы", build: " 31А"},
{street: "Дружбы", build: " 35А"},
{street: "Дружбы", build: " 35Б"},
{street: "Дружбы", build: " 3А (ETTH)"},
{street: "Дружбы", build: " 3Б"},
{street: "Дружбы", build: " 9/1"},
{street: "Дружбы", build: " 9/2"},
{street: "Ермака", build: "2"},
{street: "Ермака", build: "5"},
{street: "Железнякова", build: "9 (ETTH)"},
{street: "Железнякова", build: "10 (ETTH)"},
{street: "Железнякова", build: "10"},
{street: "Железнякова", build: "17"},
{street: "Железнякова", build: "18"},
{street: "Инженерная", build: "18"},
{street: "Инженерная", build: "20"},
{street: "Инженерная", build: " 20А"},
{street: "Инженерная", build: " 20Б"},
{street: "Инициативная", build: "1"},
{street: "Инициативная", build: "8"},
{street: "Инициативная", build: "10"},
{street: "Инициативная", build: "12"},
{street: "Инициативная", build: "21"},
{street: "Инициативная", build: "22"},
{street: "Инициативная", build: "23"},
{street: "Инициативная", build: "25"},
{street: "Инициативная", build: "29"},
{street: "Инициативная", build: "32"},
{street: "Инициативная", build: "34"},
{street: "Инициативная", build: "36"},
{street: "Инициативная", build: "38"},
{street: "Инициативная", build: "40"},
{street: "Инициативная", build: "44"},
{street: "Инициативная", build: "105"},
{street: "Инициативная", build: "109"},
{street: "Инициативная", build: "111"},
{street: "Инициативная", build: "117"},
{street: "Инициативная", build: "123"},
{street: "Инициативная", build: " 101А"},
{street: "Инициативная", build: " 103А"},
{street: "Инициативная", build: " 10А"},
{street: "Инициативная", build: " 16А"},
{street: "Инициативная", build: " 16Б"},
{street: "Инициативная", build: " 16В"},
{street: "Инициативная", build: " 18А"},
{street: "Инициативная", build: " 1А"},
{street: "Инициативная", build: " 1Б"},
{street: "Инициативная", build: " 1В"},
{street: "Инициативная", build: " 1Г"},
{street: "Инициативная", build: " 20А"},
{street: "Инициативная", build: " 25А"},
{street: "Инициативная", build: " 26А"},
{street: "Инициативная", build: " 27А"},
{street: "Инициативная", build: " 28А"},
{street: "Инициативная", build: " 29А"},
{street: "Инициативная", build: " 34А"},
{street: "Инициативная", build: " 48А"},
{street: "Инициативная", build: " 50А"},
{street: "Инициативная", build: " 81А"},
{street: "Инициативная", build: " 83А"},
{street: "Инициативная", build: " 85А"},
{street: "Инициативная", build: " 87А"},
{street: "Институтская", build: "2"},
{street: "Институтская", build: "4"},
{street: "Институтская", build: "6"},
{street: "Институтская", build: "11"},
{street: "Институтская", build: "12"},
{street: "Институтская", build: "14"},
{street: "Институтская", build: "16"},
{street: "Институтская", build: "18"},
{street: "Институтская", build: "24"},
{street: "Институтская", build: " 12А"},
{street: "Институтская", build: " 12Б"},
{street: "Институтская", build: " 16А"},
{street: "Калинина", build: "1"},
{street: "Калинина", build: "3"},
{street: "Калинина", build: "5"},
{street: "Калинина", build: "7"},
{street: "Каркасная", build: "10"},
{street: "Каркасная", build: "13"},
{street: "Кедровый бульвар", build: "1"},
{street: "Кедровый бульвар", build: "2"},
{street: "Кедровый бульвар", build: "3"},
{street: "Кедровый бульвар", build: "4"},
{street: "Кедровый бульвар", build: "5"},
{street: "Кедровый бульвар", build: "6"},
{street: "Кедровый бульвар", build: "6"},
{street: "Кедровый бульвар", build: "7"},
{street: "Кедровый бульвар", build: "8"},
{street: "Кедровый бульвар", build: "10"},
{street: "Кедровый бульвар", build: "12"},
{street: "Кирова", build: "28"},
{street: "Кирова", build: "30"},
{street: "Кирова", build: "34"},
{street: "Кирова", build: "36"},
{street: "Кирова", build: "38"},
{street: "Кирова", build: "49"},
{street: "Кирова", build: "51"},
{street: "Коломейцева", build: "3"},
{street: "Коломейцева", build: "4"},
{street: "Коломейцева", build: "5"},
{street: "Коломейцева", build: "6"},
{street: "Коломейцева", build: "7"},
{street: "Коломейцева", build: "8"},
{street: "Комсомольский", build: "11 (ETTH)"},
{street: "Комсомольский", build: "13 (ETTH)"},
{street: "Комсомольский", build: "15 (ETTH)"},
{street: "Комсомольский", build: "25 (ETTH)"},
{street: "Комсомольский", build: "27"},
{street: "Комсомольский", build: "29"},
{street: "Комсомольский", build: "34"},
{street: "Комсомольский", build: "36"},
{street: "Комсомольский", build: "38"},
{street: "Комсомольский", build: "40"},
{street: "Комсомольский", build: "42"},
{street: "Комсомольский", build: "43"},
{street: "Комсомольский", build: "44"},
{street: "Комсомольский", build: "46"},
{street: "Комсомольский", build: "49"},
{street: "Комсомольский", build: "51"},
{street: "Комсомольский", build: "53"},
{street: "Комсомольский", build: "57"},
{street: "Комсомольский", build: "59"},
{street: "Комсомольский", build: "59"},
{street: "Комсомольский", build: "63"},
{street: "Комсомольский", build: "65"},
{street: "Комсомольский", build: "67"},
{street: "Комсомольский", build: "69"},
{street: "Комсомольский", build: "71"},
{street: "Комсомольский", build: " 11А (ETTH)"},
{street: "Комсомольский", build: " 39А"},
{street: "Комсомольский", build: " 43А"},
{street: "Комсомольский", build: " 43Б"},
{street: "Комсомольский", build: " 49А"},
{street: "Комсомольский", build: " 49Б"},
{street: "Комсомольский", build: " 49В"},
{street: "Комсомольский", build: " 49Г"},
{street: "Комсомольский", build: " 53А"},
{street: "Комсомольский", build: " 53Б"},
{street: "Комсомольский", build: " 53В"},
{street: "Космическая", build: "22"},
{street: "Космическая", build: "24"},
{street: "Космическая", build: "25 (ETTH)"},
{street: "Космическая", build: "28"},
{street: "Космическая", build: "37 (ETTH)"},
{street: "Космическая", build: "37"},
{street: "Космическая", build: " 16/1"},
{street: "Космическая", build: " 22А"},
{street: "Космическая", build: " 24А"},
{street: "Космическая", build: " 4В/1"},
{street: "Космическая", build: " 4В/2"},
{street: "Красная", build: "2"},
{street: "Красная", build: "3"},
{street: "Красная", build: "4"},
{street: "Красная", build: "5"},
{street: "Красная", build: "10"},
{street: "Красная", build: "12"},
{street: "Красная", build: "13"},
{street: "Красная", build: "14"},
{street: "Красная", build: "15"},
{street: "Красная", build: "16"},
{street: "Красная", build: "19"},
{street: "Красная", build: "21"},
{street: "Красная", build: "25"},
{street: "Красная", build: "27"},
{street: "Красная", build: " 10А"},
{street: "Красная", build: " 10Б"},
{street: "Красная", build: " 12А"},
{street: "Красная", build: " 2Б"},
{street: "Красная", build: " 4/1"},
{street: "Красноармейская", build: "95"},
{street: "Красноармейская", build: "97"},
{street: "Красноармейская", build: "105"},
{street: "Красноармейская", build: "112"},
{street: "Красноармейская", build: "116"},
{street: "Красноармейская", build: "118"},
{street: "Красноармейская", build: "122"},
{street: "Красноармейская", build: "124"},
{street: "Красноармейская", build: "128 (ETTH)"},
{street: "Красноармейская", build: "135"},
{street: "Красноармейская", build: "137"},
{street: "Красноармейская", build: "138"},
{street: "Красноармейская", build: "139"},
{street: "Красноармейская", build: "140"},
{street: "Красноармейская", build: "142"},
{street: "Красноармейская", build: "144"},
{street: "Красноармейская", build: " 134А"},
{street: "Красноармейская", build: " 142А"},
{street: "Красноармейская", build: " 95А"},
{street: "Красноармейская", build: " 97А"},
{street: "Кузнецкий", build: "40"},
{street: "Кузнецкий", build: "95"},
{street: "Кузнецкий", build: "118 (ETTH)"},
{street: "Кузнецкий", build: "120 (ETTH)"},
{street: "Кузнецкий", build: "122 (ETTH)"},
{street: "Кузнецкий", build: "158"},
{street: "Кузнецкий", build: "160"},
{street: "Кузнецкий", build: "162"},
{street: "Кузнецкий", build: "264"},
{street: "Кузнецкий", build: "266"},
{street: "Кузнецкий", build: "272"},
{street: "Кузнецкий", build: "276"},
{street: "Кузнецкий", build: "278"},
{street: "Кузнецкий", build: "282"},
{street: "Кузнецкий", build: " 262/1"},
{street: "Ленина", build: "34"},
{street: "Ленина", build: "36"},
{street: "Ленина", build: "37"},
{street: "Ленина", build: "38"},
{street: "Ленина", build: "39"},
{street: "Ленина", build: "41"},
{street: "Ленина", build: "42"},
{street: "Ленина", build: "43"},
{street: "Ленина", build: "44"},
{street: "Ленина", build: "45"},
{street: "Ленина", build: "46"},
{street: "Ленина", build: "47"},
{street: "Ленина", build: "48"},
{street: "Ленина", build: "49"},
{street: "Ленина", build: "50"},
{street: "Ленина", build: "51"},
{street: "Ленина", build: "52"},
{street: "Ленина", build: "53"},
{street: "Ленина", build: "58"},
{street: "Ленина", build: "60"},
{street: "Ленина", build: "63"},
{street: "Ленина", build: "64"},
{street: "Ленина", build: "66"},
{street: "Ленина", build: "67"},
{street: "Ленина", build: "68"},
{street: "Ленина", build: "69"},
{street: "Ленина", build: "70"},
{street: "Ленина", build: "71"},
{street: "Ленина", build: "72"},
{street: "Ленина", build: "73"},
{street: "Ленина", build: "74"},
{street: "Ленина", build: "75"},
{street: "Ленина", build: "76"},
{street: "Ленина", build: "78"},
{street: "Ленина", build: "80"},
{street: "Ленина", build: "82"},
{street: "Ленина", build: "84"},
{street: "Ленина", build: "86"},
{street: "Ленина", build: "92"},
{street: "Ленина", build: "94"},
{street: "Ленина", build: "95"},
{street: "Ленина", build: "96"},
{street: "Ленина", build: "97"},
{street: "Ленина", build: "98"},
{street: "Ленина", build: "99"},
{street: "Ленина", build: "100"},
{street: "Ленина", build: "102"},
{street: "Ленина", build: "103"},
{street: "Ленина", build: "104"},
{street: "Ленина", build: "105"},
{street: "Ленина", build: "106"},
{street: "Ленина", build: "108"},
{street: "Ленина", build: "109"},
{street: "Ленина", build: "110"},
{street: "Ленина", build: "111"},
{street: "Ленина", build: "112"},
{street: "Ленина", build: "113"},
{street: "Ленина", build: "114"},
{street: "Ленина", build: "115"},
{street: "Ленина", build: "117"},
{street: "Ленина", build: "118"},
{street: "Ленина", build: "119"},
{street: "Ленина", build: "120"},
{street: "Ленина", build: "121"},
{street: "Ленина", build: "122"},
{street: "Ленина", build: "123"},
{street: "Ленина", build: "124"},
{street: "Ленина", build: "125"},
{street: "Ленина", build: "126"},
{street: "Ленина", build: "128"},
{street: "Ленина", build: "130"},
{street: "Ленина", build: "131"},
{street: "Ленина", build: "132"},
{street: "Ленина", build: "133"},
{street: "Ленина", build: "134"},
{street: "Ленина", build: "136"},
{street: "Ленина", build: "138"},
{street: "Ленина", build: "139"},
{street: "Ленина", build: "141"},
{street: "Ленина", build: "143"},
{street: "Ленина", build: "146"},
{street: "Ленина", build: "148"},
{street: "Ленина", build: "158"},
{street: "Ленина", build: "160"},
{street: "Ленина", build: "162"},
{street: "Ленина", build: "164"},
{street: "Ленина", build: " 100А"},
{street: "Ленина", build: " 102А"},
{street: "Ленина", build: " 103А"},
{street: "Ленина", build: " 105А"},
{street: "Ленина", build: " 106А"},
{street: "Ленина", build: " 107А"},
{street: "Ленина", build: " 107Б"},
{street: "Ленина", build: " 108А"},
{street: "Ленина", build: " 109А"},
{street: "Ленина", build: " 109Б"},
{street: "Ленина", build: " 111А"},
{street: "Ленина", build: " 113А"},
{street: "Ленина", build: " 113Б"},
{street: "Ленина", build: " 115А"},
{street: "Ленина", build: " 117А"},
{street: "Ленина", build: " 117Б"},
{street: "Ленина", build: " 118А"},
{street: "Ленина", build: " 119А"},
{street: "Ленина", build: " 121А"},
{street: "Ленина", build: " 122А"},
{street: "Ленина", build: " 125А"},
{street: "Ленина", build: " 128А"},
{street: "Ленина", build: " 132А"},
{street: "Ленина", build: " 133А"},
{street: "Ленина", build: " 133Б"},
{street: "Ленина", build: " 135А"},
{street: "Ленина", build: " 135Б"},
{street: "Ленина", build: " 136А"},
{street: "Ленина", build: " 137А"},
{street: "Ленина", build: " 137Б"},
{street: "Ленина", build: " 138А"},
{street: "Ленина", build: " 139А"},
{street: "Ленина", build: " 139Б"},
{street: "Ленина", build: " 139В"},
{street: "Ленина", build: " 140А"},
{street: "Ленина", build: " 141А"},
{street: "Ленина", build: " 142А"},
{street: "Ленина", build: " 142Б"},
{street: "Ленина", build: " 144А"},
{street: "Ленина", build: " 146/1"},
{street: "Ленина", build: " 150А"},
{street: "Ленина", build: " 150Б"},
{street: "Ленина", build: " 152Б"},
{street: "Ленина", build: " 152В"},
{street: "Ленина", build: " 164А"},
{street: "Ленина", build: " 39А"},
{street: "Ленина", build: " 39Б"},
{street: "Ленина", build: " 41А"},
{street: "Ленина", build: " 41Б"},
{street: "Ленина", build: " 45А"},
{street: "Ленина", build: " 51А"},
{street: "Ленина", build: " 55Б"},
{street: "Ленина", build: " 60А"},
{street: "Ленина", build: " 60Б"},
{street: "Ленина", build: " 60В"},
{street: "Ленина", build: " 62А"},
{street: "Ленина", build: " 63А"},
{street: "Ленина", build: " 63Б"},
{street: "Ленина", build: " 65А"},
{street: "Ленина", build: " 65Б"},
{street: "Ленина", build: " 66А"},
{street: "Ленина", build: " 66Б"},
{street: "Ленина", build: " 67А"},
{street: "Ленина", build: " 69А"},
{street: "Ленина", build: " 70А"},
{street: "Ленина", build: " 70Б"},
{street: "Ленина", build: " 70В"},
{street: "Ленина", build: " 71А"},
{street: "Ленина", build: " 75А"},
{street: "Ленина", build: " 76А"},
{street: "Ленина", build: " 76Б"},
{street: "Ленина", build: " 76В"},
{street: "Ленина", build: " 77А"},
{street: "Ленина", build: " 77Б"},
{street: "Ленина", build: " 77Г"},
{street: "Ленина", build: " 82А"},
{street: "Ленина", build: " 82Б"},
{street: "Ленина", build: " 82В"},
{street: "Ленина", build: " 82Г"},
{street: "Ленина", build: " 86А"},
{street: "Ленина", build: " 90А"},
{street: "Ленина", build: " 90Б"},
{street: "Ленинградский", build: "3"},
{street: "Ленинградский", build: "5 (ETTH)"},
{street: "Ленинградский", build: "7"},
{street: "Ленинградский", build: "13"},
{street: "Ленинградский", build: "14 (ETTH)"},
{street: "Ленинградский", build: "15"},
{street: "Ленинградский", build: "18 (ETTH)"},
{street: "Ленинградский", build: "21"},
{street: "Ленинградский", build: "22"},
{street: "Ленинградский", build: "23"},
{street: "Ленинградский", build: "24"},
{street: "Ленинградский", build: "25"},
{street: "Ленинградский", build: "27"},
{street: "Ленинградский", build: "28"},
{street: "Ленинградский", build: "30"},
{street: "Ленинградский", build: "31"},
{street: "Ленинградский", build: "33"},
{street: "Ленинградский", build: "34"},
{street: "Ленинградский", build: "36"},
{street: "Ленинградский", build: "38"},
{street: "Ленинградский", build: "39"},
{street: "Ленинградский", build: "40"},
{street: "Ленинградский", build: "41"},
{street: "Ленинградский", build: "43"},
{street: "Ленинградский", build: "45"},
{street: "Ленинградский", build: "47"},
{street: "Ленинградский", build: "49"},
{street: "Ленинградский", build: "51"},
{street: "Ленинградский", build: " 13А"},
{street: "Ленинградский", build: " 13Б"},
{street: "Ленинградский", build: " 15А"},
{street: "Ленинградский", build: " 18А (ETTH)"},
{street: "Ленинградский", build: " 21А"},
{street: "Ленинградский", build: " 21Б"},
{street: "Ленинградский", build: " 21В"},
{street: "Ленинградский", build: " 21Г"},
{street: "Ленинградский", build: " 23А"},
{street: "Ленинградский", build: " 23Б"},
{street: "Ленинградский", build: " 23В"},
{street: "Ленинградский", build: " 24А"},
{street: "Ленинградский", build: " 25А"},
{street: "Ленинградский", build: " 25Б"},
{street: "Ленинградский", build: " 25В"},
{street: "Ленинградский", build: " 27А"},
{street: "Ленинградский", build: " 28А"},
{street: "Ленинградский", build: " 30/1"},
{street: "Ленинградский", build: " 30/2"},
{street: "Ленинградский", build: " 30А"},
{street: "Ленинградский", build: " 30Б"},
{street: "Ленинградский", build: " 30В"},
{street: "Ленинградский", build: " 31А"},
{street: "Ленинградский", build: " 32А"},
{street: "Ленинградский", build: " 34А"},
{street: "Ленинградский", build: " 36А"},
{street: "Ленинградский", build: " 36Б"},
{street: "Ленинградский", build: " 38А"},
{street: "Ленинградский", build: " 38Б"},
{street: "Ленинградский", build: " 39А"},
{street: "Ленинградский", build: " 3А"},
{street: "Ленинградский", build: " 40А"},
{street: "Ленинградский", build: " 40Б"},
{street: "Ленинградский", build: " 40В"},
{street: "Ленинградский", build: " 41А"},
{street: "Ленинградский", build: " 45Б"},
{street: "Ленинградский", build: " 47А"},
{street: "Ленинградский", build: " 47Б"},
{street: "Ленинградский", build: " 47В"},
{street: "Ленинградский", build: " 49Б"},
{street: "Ленинградский", build: " 5А"},
{street: "Ленинградский", build: " 7А"},
{street: "Леонова", build: "1"},
{street: "Леонова", build: "2"},
{street: "Леонова", build: "3"},
{street: "Леонова", build: "4"},
{street: "Леонова", build: "5"},
{street: "Леонова", build: "6"},
{street: "Леонова", build: "7"},
{street: "Леонова", build: "8"},
{street: "Леонова", build: "9"},
{street: "Леонова", build: "10"},
{street: "Леонова", build: "11"},
{street: "Леонова", build: "14"},
{street: "Леонова", build: "16"},
{street: "Леонова", build: "17"},
{street: "Леонова", build: "18"},
{street: "Леонова", build: "19"},
{street: "Леонова", build: "20"},
{street: "Леонова", build: "22"},
{street: "Леонова", build: "24"},
{street: "Леонова", build: "26"},
{street: "Леонова", build: "28"},
{street: "Леонова", build: " 11А"},
{street: "Леонова", build: " 16А"},
{street: "Леонова", build: " 26А"},
{street: "Леонова", build: " 9А"},
{street: "Леонова", build: " 9Б"},
{street: "Марковцева", build: "6"},
{street: "Марковцева", build: "12"},
{street: "Марковцева", build: "14"},
{street: "Марковцева", build: "16"},
{street: "Марковцева", build: "18"},
{street: "Марковцева", build: "22"},
{street: "Марковцева", build: "24"},
{street: "Марковцева", build: " 12/1"},
{street: "Марковцева", build: " 12А"},
{street: "Марковцева", build: " 12Б"},
{street: "Марковцева", build: " 16А"},
{street: "Марковцева", build: " 22А"},
{street: "Масальская", build: "56"},
{street: "Масальская", build: "58"},
{street: "Металлистов", build: "4"},
{street: "Металлистов", build: "7"},
{street: "Металлистов", build: "9"},
{street: "Металлистов", build: "20"},
{street: "Металлистов", build: " 4А"},
{street: "Мирная", build: "15"},
{street: "Мирная", build: "17"},
{street: "Мирная", build: "19"},
{street: "Мичурина", build: "15"},
{street: "Мичурина", build: "21"},
{street: "Мичурина", build: "23"},
{street: "Мичурина", build: "29"},
{street: "Мичурина", build: "31"},
{street: "Мичурина", build: "33"},
{street: "Мичурина", build: "35"},
{street: "Мичурина", build: "37"},
{street: "Мичурина", build: "39"},
{street: "Мичурина", build: "41"},
{street: "Мичурина", build: "55 (ETTH)"},
{street: "Мичурина", build: "56"},
{street: "Мичурина", build: "57 (ETTH)"},
{street: "Мичурина", build: "58"},
{street: "Мичурина", build: "61 (ETTH)"},
{street: "Мичурина", build: " 37А"},
{street: "Мичурина", build: " 41А"},
{street: "Мичурина", build: " 57А (ETTH)"},
{street: "Молодёжный", build: "3"},
{street: "Молодёжный", build: "4"},
{street: "Молодёжный", build: "5"},
{street: "Молодёжный", build: "6"},
{street: "Молодёжный", build: "7"},
{street: "Молодёжный", build: "8"},
{street: "Молодёжный", build: "9"},
{street: "Молодёжный", build: "10"},
{street: "Молодёжный", build: "11"},
{street: "Молодёжный", build: "13"},
{street: "Молодёжный", build: "15"},
{street: "Молодёжный", build: "25"},
{street: "Молодёжный", build: "27"},
{street: "Молодёжный", build: "27"},
{street: "Молодёжный", build: "27"},
{street: "Молодёжный", build: "27"},
{street: "Молодёжный", build: "27"},
{street: "Молодёжный", build: "27"},
{street: "Молодёжный", build: "29"},
{street: "Молодёжный", build: "31"},
{street: "Молодёжный", build: " 11А"},
{street: "Молодёжный", build: " 11Б"},
{street: "Молодёжный", build: " 12А"},
{street: "Молодёжный", build: " 12Б"},
{street: "Молодёжный", build: " 12В"},
{street: "Молодёжный", build: " 13Б"},
{street: "Молодёжный", build: " 15А"},
{street: "Молодёжный", build: " 15Б"},
{street: "Молодёжный", build: " 27А"},
{street: "Молодёжный", build: " 29А"},
{street: "Молодёжный", build: " 33к1"},
{street: "Молодёжный", build: " 3А"},
{street: "Молодёжный", build: " 4А"},
{street: "Молодёжный", build: " 5/1"},
{street: "Молодёжный", build: " 6А"},
{street: "Молодёжный", build: " 7/1"},
{street: "Молодёжный", build: " 7В"},
{street: "Молодёжный", build: " 7Г"},
{street: "Молодёжный", build: " 9/1"},
{street: "Молодёжный", build: " 9А"},
{street: "Молодёжный", build: " 9В"},
{street: "Молодёжный", build: " 9Г"},
{street: "Московский", build: "3"},
{street: "Московский", build: "5"},
{street: "Московский", build: "7"},
{street: "Московский", build: "8"},
{street: "Московский", build: "9"},
{street: "Московский", build: "12"},
{street: "Московский", build: "13"},
{street: "Московский", build: "14"},
{street: "Московский", build: "15"},
{street: "Московский", build: "16"},
{street: "Московский", build: "17"},
{street: "Московский", build: "21 (ETTH)"},
{street: "Московский", build: "23 (ETTH)"},
{street: "Московский", build: "25 (ETTH)"},
{street: "Московский", build: "27 (ETTH)"},
{street: "Московский", build: "29 (ETTH)"},
{street: "Московский", build: "31 (ETTH)"},
{street: "Московский", build: "35 (ETTH)"},
{street: "Московский", build: "41 (ETTH)"},
{street: "Московский", build: "45 (ETTH)"},
{street: "Московский", build: " 13А"},
{street: "Московский", build: " 15А"},
{street: "Московский", build: " 17Б"},
{street: "Московский", build: " 18к1"},
{street: "Московский", build: " 18к2"},
{street: "Московский", build: " 18к3"},
{street: "Московский", build: " 18к4"},
{street: "Московский", build: " 18к5"},
{street: "Московский", build: " 18к6"},
{street: "Московский", build: " 23Б"},
{street: "Московский", build: " 29А"},
{street: "Московский", build: " 2Б"},
{street: "Московский", build: " 35А (ETTH)"},
{street: "Московский", build: " 39Б (ETTH)"},
{street: "Московский", build: " 39В (ETTH)"},
{street: "Московский", build: " 39Г (ETTH)"},
{street: "Московский", build: " 41А (ETTH)"},
{street: "Московский", build: " 45Б (ETTH)"},
{street: "Московский", build: " 8к1"},
{street: "Московский", build: " 8к2"},
{street: "Московский", build: " 9Б"},
{street: "Мостовая", build: "87"},
{street: "Мостовая", build: " 87А"},
{street: "Мостовая", build: " 87Б"},
{street: "Муромцева", build: "2"},
{street: "Муромцева", build: "4"},
{street: "Муромцева", build: "6"},
{street: "Муромцева", build: "9"},
{street: "Муромцева", build: "10"},
{street: "Муромцева", build: "11"},
{street: "Муромцева", build: "13"},
{street: "Муромцева", build: "16"},
{street: "Муромцева", build: " 13А"},
{street: "Муромцева", build: " 4А"},
{street: "Нахимова", build: "31"},
{street: "Нахимова", build: "262"},
{street: "Нахимова", build: " 262Б"},
{street: "Нахимова", build: " 264А"},
{street: "Ногинская", build: "8"},
{street: "Ногинская", build: "10"},
{street: "Ногинская", build: " 10А"},
{street: "Ноградская", build: "10"},
{street: "Ноградская", build: "13"},
{street: "Ноградская", build: "15"},
{street: "Ноградская", build: "17"},
{street: "Ноградская", build: "21"},
{street: "Ноградская", build: " 15А"},
{street: "Ноградская", build: " 19А"},
{street: "Окружная", build: "28"},
{street: "Окружная", build: "30"},
{street: "Окружная", build: "32"},
{street: "Октябрьский", build: "7"},
{street: "Октябрьский", build: "8"},
{street: "Октябрьский", build: "9"},
{street: "Октябрьский", build: "13"},
{street: "Октябрьский", build: "15"},
{street: "Октябрьский", build: "17"},
{street: "Октябрьский", build: "18"},
{street: "Октябрьский", build: "20"},
{street: "Октябрьский", build: "21"},
{street: "Октябрьский", build: "23"},
{street: "Октябрьский", build: "25"},
{street: "Октябрьский", build: "33"},
{street: "Октябрьский", build: "35"},
{street: "Октябрьский", build: "36"},
{street: "Октябрьский", build: "37"},
{street: "Октябрьский", build: "38"},
{street: "Октябрьский", build: "40"},
{street: "Октябрьский", build: "41"},
{street: "Октябрьский", build: "42"},
{street: "Октябрьский", build: "43"},
{street: "Октябрьский", build: "44"},
{street: "Октябрьский", build: "47"},
{street: "Октябрьский", build: "49"},
{street: "Октябрьский", build: "51"},
{street: "Октябрьский", build: "52"},
{street: "Октябрьский", build: "54"},
{street: "Октябрьский", build: "56"},
{street: "Октябрьский", build: "58"},
{street: "Октябрьский", build: "59"},
{street: "Октябрьский", build: "60"},
{street: "Октябрьский", build: "61"},
{street: "Октябрьский", build: "62"},
{street: "Октябрьский", build: "63"},
{street: "Октябрьский", build: "64"},
{street: "Октябрьский", build: "66"},
{street: "Октябрьский", build: "67"},
{street: "Октябрьский", build: "68"},
{street: "Октябрьский", build: "69"},
{street: "Октябрьский", build: "70"},
{street: "Октябрьский", build: "71"},
{street: "Октябрьский", build: "72"},
{street: "Октябрьский", build: "73"},
{street: "Октябрьский", build: "74"},
{street: "Октябрьский", build: "75"},
{street: "Октябрьский", build: "77"},
{street: "Октябрьский", build: "78 (ETTH)"},
{street: "Октябрьский", build: "79"},
{street: "Октябрьский", build: "81"},
{street: "Октябрьский", build: "82 (ETTH)"},
{street: "Октябрьский", build: "83"},
{street: "Октябрьский", build: "84 (ETTH)"},
{street: "Октябрьский", build: "85"},
{street: "Октябрьский", build: "87"},
{street: "Октябрьский", build: "89"},
{street: "Октябрьский", build: "91"},
{street: "Октябрьский", build: "93"},
{street: "Октябрьский", build: "95 (ETTH)"},
{street: "Октябрьский", build: "97"},
{street: "Октябрьский", build: "99"},
{street: "Октябрьский", build: "103 (ETTH)"},
{street: "Октябрьский", build: "105 (ETTH)"},
{street: "Октябрьский", build: " 101А"},
{street: "Октябрьский", build: " 101Б"},
{street: "Октябрьский", build: " 16А"},
{street: "Октябрьский", build: " 20А"},
{street: "Октябрьский", build: " 20Б"},
{street: "Октябрьский", build: " 20В"},
{street: "Октябрьский", build: " 23А"},
{street: "Октябрьский", build: " 23Б"},
{street: "Октябрьский", build: " 33А"},
{street: "Октябрьский", build: " 33Б"},
{street: "Октябрьский", build: " 36А"},
{street: "Октябрьский", build: " 36В"},
{street: "Октябрьский", build: " 36Г"},
{street: "Октябрьский", build: " 38А"},
{street: "Октябрьский", build: " 38Б"},
{street: "Октябрьский", build: " 38В"},
{street: "Октябрьский", build: " 52А"},
{street: "Октябрьский", build: " 56А"},
{street: "Октябрьский", build: " 61А"},
{street: "Октябрьский", build: " 61Б"},
{street: "Октябрьский", build: " 64А"},
{street: "Октябрьский", build: " 64Б"},
{street: "Октябрьский", build: " 66А"},
{street: "Октябрьский", build: " 67А"},
{street: "Октябрьский", build: " 69А"},
{street: "Октябрьский", build: " 71А"},
{street: "Октябрьский", build: " 73А"},
{street: "Октябрьский", build: " 75А"},
{street: "Октябрьский", build: " 77А"},
{street: "Октябрьский", build: " 77Б"},
{street: "Октябрьский", build: " 78А (ETTH)"},
{street: "Октябрьский", build: " 7А"},
{street: "Октябрьский", build: " 80А (ETTH)"},
{street: "Октябрьский", build: " 80Б (ETTH)"},
{street: "Октябрьский", build: " 80Г (ETTH)"},
{street: "Октябрьский", build: " 99А"},
{street: "Орджоникидзе", build: "3"},
{street: "Орджоникидзе", build: "4"},
{street: "Орджоникидзе", build: "5"},
{street: "Орджоникидзе", build: "7"},
{street: "Осенний бульвар", build: "1"},
{street: "Осенний бульвар", build: "2"},
{street: "Осенний бульвар", build: "3"},
{street: "Осенний бульвар", build: "4"},
{street: "Осенний бульвар", build: "5"},
{street: "Осенний бульвар", build: "6"},
{street: "Осенний бульвар", build: "7"},
{street: "Осенний бульвар", build: "8"},
{street: "Осенний бульвар", build: "9"},
{street: "Осенний бульвар", build: "10"},
{street: "Осенний бульвар", build: "11"},
{street: "Осенний бульвар", build: "12"},
{street: "Осенний бульвар", build: "13"},
{street: "Осенний бульвар", build: "14"},
{street: "Осенний бульвар", build: "16"},
{street: "Осенний бульвар", build: "18"},
{street: "Осенний бульвар", build: " 11А"},
{street: "Осенний бульвар", build: " 15/1"},
{street: "Осенний бульвар", build: " 15/2"},
{street: "Осенний бульвар", build: " 15/3"},
{street: "Осенний бульвар", build: " 1А"},
{street: "Осенний бульвар", build: " 20/1"},
{street: "Осенний бульвар", build: " 20/2"},
{street: "Осенний бульвар", build: " 2А"},
{street: "Осенний бульвар", build: " 5А"},
{street: "Осенний бульвар", build: " 9А"},
{street: "Патриотов", build: "5"},
{street: "Патриотов", build: "18 (ETTH)"},
{street: "Патриотов", build: "29 (ETTH)"},
{street: "Патриотов", build: "30 (ETTH)"},
{street: "Патриотов", build: "31 (ETTH)"},
{street: "Патриотов", build: "32 (ETTH)"},
{street: "Патриотов", build: "33 (ETTH)"},
{street: "Патриотов", build: "33"},
{street: "Патриотов", build: "34 (ETTH)"},
{street: "Патриотов", build: "35 (ETTH)"},
{street: "Патриотов", build: "35"},
{street: "Патриотов", build: "36 (ETTH)"},
{street: "Патриотов", build: " 18А"},
{street: "Патриотов", build: " 18Б"},
{street: "Патриотов", build: " 27А (ETTH)"},
{street: "Патриотов", build: " 33А (ETTH)"},
{street: "Патриотов", build: " 34А (ETTH)"},
{street: "Патриотов", build: " 35А (ETTH)"},
{street: "переулок Леонова", build: "4"},
{street: "переулок Леонова", build: "7"},
{street: "переулок Мичурина", build: "5"},
{street: "переулок Мичурина", build: " 5А"},
{street: "Пионерский бульвар", build: "2"},
{street: "Пионерский бульвар", build: "4"},
{street: "Пионерский бульвар", build: "6"},
{street: "Пионерский бульвар", build: "9"},
{street: "Пионерский бульвар", build: "11"},
{street: "Пионерский бульвар", build: "12"},
{street: "Пионерский бульвар", build: "14"},
{street: "Пионерский бульвар", build: " 10А"},
{street: "Пионерский бульвар", build: " 11А"},
{street: "Пионерский бульвар", build: " 12А"},
{street: "Пионерский бульвар", build: " 2А"},
{street: "Пионерский бульвар", build: " 8А"},
{street: "Пионерский бульвар", build: " 9А"},
{street: "Попова", build: "3"},
{street: "Попова", build: "5"},
{street: "Попова", build: "9"},
{street: "Попова", build: "11"},
{street: "Попова", build: " 1А"},
{street: "Попова", build: " 1Б"},
{street: "Попова", build: " 3Б"},
{street: "Потёмкина", build: "1"},
{street: "Потёмкина", build: "7"},
{street: "Предзаводская", build: " 1Б (ETTH)"},
{street: "Предзаводская", build: " 2А (ETTH)"},
{street: "Пригородная", build: "23"},
{street: "Притомская Набережная", build: "11"},
{street: "Притомская Набережная", build: "13"},
{street: "Притомская Набережная", build: "17"},
{street: "Притомская Набережная", build: "19"},
{street: "Притомская Набережная", build: "21"},
{street: "Притомская Набережная", build: "23"},
{street: "Притомская Набережная", build: "25"},
{street: "Притомская Набережная", build: " 1А"},
{street: "Притомская Набережная", build: " 21А"},
{street: "Притомский", build: "3"},
{street: "Притомский", build: "9"},
{street: "Притомский", build: "11"},
{street: "Притомский", build: "13"},
{street: "Притомский", build: "15"},
{street: "Притомский", build: "29"},
{street: "Притомский", build: " 11/1"},
{street: "Притомский", build: " 15к1"},
{street: "Притомский", build: " 25к1"},
{street: "Притомский", build: " 25к2"},
{street: "Притомский", build: " 25к3"},
{street: "Притомский", build: " 31к1"},
{street: "Притомский", build: " 31к2"},
{street: "Притомский", build: " 35к1"},
{street: "Притомский", build: " 35к2"},
{street: "Притомский", build: " 3А"},
{street: "Притомский", build: " 7/1"},
{street: "Притомский", build: " 7/3"},
{street: "Притомский", build: " 7/5"},
{street: "Притомский", build: " 7/6"},
{street: "Притомский", build: " 7/7"},
{street: "Притомский", build: " 7А"},
{street: "Пролетарская", build: "3"},
{street: "Пролетарская", build: "4"},
{street: "Пролетарская", build: "5"},
{street: "Пролетарская", build: "6"},
{street: "Пролетарская", build: "7"},
{street: "Пролетарская", build: "8"},
{street: "Пролетарская", build: "9"},
{street: "Пролетарская", build: "12"},
{street: "Пролетарская", build: "14"},
{street: "Пролетарская", build: "16"},
{street: "Пролетарская", build: "18"},
{street: "Пролетарская", build: "20 (ETTH)"},
{street: "Пролетарская", build: "22 (ETTH)"},
{street: "Пролетарская", build: " 29/2"},
{street: "Промышленновский проезд", build: "1"},
{street: "Промышленновский проезд", build: "2"},
{street: "Промышлённовское шоссе", build: "46"},
{street: "Промышлённовское шоссе", build: "54"},
{street: "Промышлённовское шоссе", build: "56"},
{street: "Промышлённовское шоссе", build: " 56Б"},
{street: "Радищева", build: "4 (ETTH)"},
{street: "Радищева", build: "6 (ETTH)"},
{street: "Радищева", build: "11 (ETTH)"},
{street: "Радищева", build: "15 (ETTH)"},
{street: "Радищева", build: " 17А (ETTH)"},
{street: "Радищева", build: " 4А (ETTH)"},
{street: "Рекордная", build: "19"},
{street: "Рекордная", build: "27"},
{street: "Рекордная", build: "35"},
{street: "Рекордная", build: " 27А"},
{street: "Рекордная", build: " 29А"},
{street: "Рекордная", build: " 2А"},
{street: "Рекордная", build: " 31А"},
{street: "Рекордная", build: " 33А"},
{street: "Рекордная", build: " 3А"},
{street: "Рекордный переулок", build: "5"},
{street: "Сарыгина", build: "26"},
{street: "Сарыгина", build: "28"},
{street: "Сарыгина", build: "33"},
{street: "Сарыгина", build: "34"},
{street: "Сарыгина", build: "35"},
{street: "Сарыгина", build: "37"},
{street: "Сарыгина", build: "40"},
{street: "Сарыгина", build: "42"},
{street: "Сарыгина", build: " 12А"},
{street: "Сарыгина", build: " 33А"},
{street: "Свободы", build: "3"},
{street: "Свободы", build: "6"},
{street: "Свободы", build: "7"},
{street: "Свободы", build: "11"},
{street: "Свободы", build: "13"},
{street: "Свободы", build: "15"},
{street: "Свободы", build: "17"},
{street: "Свободы", build: "19"},
{street: "Свободы", build: "21"},
{street: "Свободы", build: "23"},
{street: "Свободы", build: "25"},
{street: "Свободы", build: "27"},
{street: "Свободы", build: "29"},
{street: "Свободы", build: "31"},
{street: "Свободы", build: "33"},
{street: "Свободы", build: "35"},
{street: "Свободы", build: "37"},
{street: "Свободы", build: " 11А"},
{street: "Свободы", build: " 13А"},
{street: "Свободы", build: " 17А"},
{street: "Свободы", build: " 19А"},
{street: "Свободы", build: " 23А"},
{street: "Свободы", build: " 23Б"},
{street: "Свободы", build: " 25А"},
{street: "Свободы", build: " 27А"},
{street: "Свободы", build: " 27Б"},
{street: "Свободы", build: " 29А"},
{street: "Свободы", build: " 31А"},
{street: "Свободы", build: " 33А"},
{street: "Свободы", build: " 6Б"},
{street: "Севастопольская", build: "1"},
{street: "Севастопольская", build: "2"},
{street: "Севастопольская", build: "3"},
{street: "Севастопольская", build: "4"},
{street: "Севастопольская", build: "5"},
{street: "Севастопольская", build: "6"},
{street: "Сергея Тюленина", build: "7"},
{street: "Сергея Тюленина", build: " 1Б (ETTH)"},
{street: "Серебряный Бор", build: "1"},
{street: "Серебряный Бор", build: "3"},
{street: "Серебряный Бор", build: "4"},
{street: "Серебряный Бор", build: "5"},
{street: "Серебряный Бор", build: "7"},
{street: "Серебряный Бор", build: "8"},
{street: "Серебряный Бор", build: "9"},
{street: "Серебряный Бор", build: "10"},
{street: "Серебряный Бор", build: "11"},
{street: "Серебряный Бор", build: "12"},
{street: "Серебряный Бор", build: "13"},
{street: "Серебряный Бор", build: "14"},
{street: "Серебряный Бор", build: "15"},
{street: "Серебряный Бор", build: "16"},
{street: "Серебряный Бор", build: "18"},
{street: "Серебряный Бор", build: "19"},
{street: "Серебряный Бор", build: "21"},
{street: "Серебряный Бор", build: "25"},
{street: "Серебряный Бор", build: "27"},
{street: "Серебряный Бор", build: " 13А"},
{street: "Серебряный Бор", build: " 15А"},
{street: "Серебряный Бор", build: " 19А"},
{street: "Серебряный Бор", build: " 24к1"},
{street: "Серебряный Бор", build: " 24к3"},
{street: "Серебряный Бор", build: " 3А"},
{street: "Серебряный Бор", build: " 3Б"},
{street: "Серебряный Бор", build: " 4А"},
{street: "Серебряный Бор", build: " 6/1"},
{street: "Серебряный Бор", build: " 6/2"},
{street: "Сибиряков-Гвардейцев", build: "1 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "3 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "4"},
{street: "Сибиряков-Гвардейцев", build: "5"},
{street: "Сибиряков-Гвардейцев", build: "6"},
{street: "Сибиряков-Гвардейцев", build: "7 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "8"},
{street: "Сибиряков-Гвардейцев", build: "11 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "12"},
{street: "Сибиряков-Гвардейцев", build: "13 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "14"},
{street: "Сибиряков-Гвардейцев", build: "16"},
{street: "Сибиряков-Гвардейцев", build: "17 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "18"},
{street: "Сибиряков-Гвардейцев", build: "19 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "21 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "24 (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: "24"},
{street: "Сибиряков-Гвардейцев", build: "28"},
{street: "Сибиряков-Гвардейцев", build: "273"},
{street: "Сибиряков-Гвардейцев", build: "296"},
{street: "Сибиряков-Гвардейцев", build: "298"},
{street: "Сибиряков-Гвардейцев", build: "300"},
{street: "Сибиряков-Гвардейцев", build: "302"},
{street: "Сибиряков-Гвардейцев", build: "308"},
{street: "Сибиряков-Гвардейцев", build: "310"},
{street: "Сибиряков-Гвардейцев", build: "312"},
{street: "Сибиряков-Гвардейцев", build: "314"},
{street: "Сибиряков-Гвардейцев", build: "316"},
{street: "Сибиряков-Гвардейцев", build: "320"},
{street: "Сибиряков-Гвардейцев", build: "322"},
{street: "Сибиряков-Гвардейцев", build: "324"},
{street: "Сибиряков-Гвардейцев", build: "326"},
{street: "Сибиряков-Гвардейцев", build: "328"},
{street: "Сибиряков-Гвардейцев", build: "330"},
{street: "Сибиряков-Гвардейцев", build: "334"},
{street: "Сибиряков-Гвардейцев", build: " 13А (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: " 18А (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: " 22А (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: " 22Б"},
{street: "Сибиряков-Гвардейцев", build: " 24А (ETTH)"},
{street: "Сибиряков-Гвардейцев", build: " 24Б"},
{street: "Сибиряков-Гвардейцев", build: " 28А"},
{street: "Сибиряков-Гвардейцев", build: " 328А"},
{street: "Соборная", build: "3"},
{street: "Соборная", build: "5"},
{street: "Соборная", build: "5"},
{street: "Соборная", build: "6"},
{street: "Соборная", build: "7"},
{street: "Соборная", build: "10"},
{street: "Соборная", build: "12"},
{street: "Соборная", build: "14"},
{street: "Соборная", build: " 14А"},
{street: "Советский", build: "24"},
{street: "Советский", build: "33"},
{street: "Советский", build: "39"},
{street: "Советский", build: "47 (ETTH)"},
{street: "Советский", build: "49 (ETTH)"},
{street: "Советский", build: "67"},
{street: "Советский", build: " 70А"},
{street: "Спартака", build: "8"},
{street: "Спартака", build: "21"},
{street: "Спортивная", build: "17"},
{street: "Спортивная", build: "22"},
{street: "Спортивная", build: "24"},
{street: "Спортивная", build: "30"},
{street: "Спортивная", build: "34"},
{street: "Спортивная", build: "38"},
{street: "Спортивная", build: "40"},
{street: "Спортивная", build: " 16А"},
{street: "Спортивная", build: " 20А"},
{street: "Спортивная", build: " 20А"},
{street: "Спортивная", build: " 34Б"},
{street: "Строителей", build: "3"},
{street: "Строителей", build: "4"},
{street: "Строителей", build: "5"},
{street: "Строителей", build: "6"},
{street: "Строителей", build: "7"},
{street: "Строителей", build: "11"},
{street: "Строителей", build: "12"},
{street: "Строителей", build: "13"},
{street: "Строителей", build: "14"},
{street: "Строителей", build: "15"},
{street: "Строителей", build: "16"},
{street: "Строителей", build: "19"},
{street: "Строителей", build: "20"},
{street: "Строителей", build: "21"},
{street: "Строителей", build: "23"},
{street: "Строителей", build: "24"},
{street: "Строителей", build: "25"},
{street: "Строителей", build: "26"},
{street: "Строителей", build: "27"},
{street: "Строителей", build: "28"},
{street: "Строителей", build: "29"},
{street: "Строителей", build: "30"},
{street: "Строителей", build: "31"},
{street: "Строителей", build: "32"},
{street: "Строителей", build: "33"},
{street: "Строителей", build: "35"},
{street: "Строителей", build: "36"},
{street: "Строителей", build: "37 (ETTH)"},
{street: "Строителей", build: "39"},
{street: "Строителей", build: "40"},
{street: "Строителей", build: "41"},
{street: "Строителей", build: "42"},
{street: "Строителей", build: "43"},
{street: "Строителей", build: "44"},
{street: "Строителей", build: "45 (ETTH)"},
{street: "Строителей", build: "46"},
{street: "Строителей", build: "56"},
{street: "Строителей", build: "61"},
{street: "Строителей", build: "63"},
{street: "Строителей", build: " 12А"},
{street: "Строителей", build: " 14А"},
{street: "Строителей", build: " 16А"},
{street: "Строителей", build: " 16Б"},
{street: "Строителей", build: " 21А"},
{street: "Строителей", build: " 21Б"},
{street: "Строителей", build: " 22А"},
{street: "Строителей", build: " 22Б"},
{street: "Строителей", build: " 23А"},
{street: "Строителей", build: " 24А"},
{street: "Строителей", build: " 25А"},
{street: "Строителей", build: " 25Б"},
{street: "Строителей", build: " 25В"},
{street: "Строителей", build: " 25Г"},
{street: "Строителей", build: " 26/1"},
{street: "Строителей", build: " 26/2"},
{street: "Строителей", build: " 26А"},
{street: "Строителей", build: " 26Б"},
{street: "Строителей", build: " 26В"},
{street: "Строителей", build: " 26Г"},
{street: "Строителей", build: " 27А"},
{street: "Строителей", build: " 27Б"},
{street: "Строителей", build: " 27В"},
{street: "Строителей", build: " 28/1"},
{street: "Строителей", build: " 28А"},
{street: "Строителей", build: " 28Б"},
{street: "Строителей", build: " 29А"},
{street: "Строителей", build: " 30А"},
{street: "Строителей", build: " 30Б"},
{street: "Строителей", build: " 31Б"},
{street: "Строителей", build: " 32/1"},
{street: "Строителей", build: " 32/3"},
{street: "Строителей", build: " 32А"},
{street: "Строителей", build: " 33А"},
{street: "Строителей", build: " 34А"},
{street: "Строителей", build: " 42Б"},
{street: "Строителей", build: " 44А"},
{street: "Строителей", build: " 46А"},
{street: "Строителей", build: " 46Б"},
{street: "Строителей", build: " 50/2"},
{street: "Строителей", build: " 52А"},
{street: "Строителей", build: " 56/2"},
{street: "Строителей", build: " 57/1"},
{street: "Строителей", build: " 57/2"},
{street: "Строителей", build: " 59/1"},
{street: "Строителей", build: " 59/2"},
{street: "Суворова", build: "3"},
{street: "Тайгинская", build: "12"},
{street: "Тайгинская", build: " 8А"},
{street: "Тайгинская", build: " 8Б"},
{street: "Телецентр", build: "1"},
{street: "Терешковой", build: "2"},
{street: "Терешковой", build: "4"},
{street: "Терешковой", build: "19"},
{street: "Терешковой", build: "21"},
{street: "Терешковой", build: "22"},
{street: "Терешковой", build: "23"},
{street: "Терешковой", build: "24"},
{street: "Терешковой", build: "25"},
{street: "Терешковой", build: "26"},
{street: "Терешковой", build: "27"},
{street: "Терешковой", build: "28"},
{street: "Терешковой", build: "29"},
{street: "Терешковой", build: "31"},
{street: "Терешковой", build: "32"},
{street: "Терешковой", build: "34"},
{street: "Терешковой", build: "36"},
{street: "Терешковой", build: "38"},
{street: "Терешковой", build: "42"},
{street: "Терешковой", build: "44"},
{street: "Терешковой", build: " 18Б"},
{street: "Терешковой", build: " 18В"},
{street: "Терешковой", build: " 22Б"},
{street: "Терешковой", build: " 24А"},
{street: "Терешковой", build: " 25А"},
{street: "Терешковой", build: " 28А"},
{street: "Терешковой", build: " 28Б"},
{street: "Терешковой", build: " 40А"},
{street: "Тухачевского", build: "2"},
{street: "Тухачевского", build: "4"},
{street: "Тухачевского", build: "8"},
{street: "Тухачевского", build: "12"},
{street: "Тухачевского", build: "14"},
{street: "Тухачевского", build: "16"},
{street: "Тухачевского", build: "27"},
{street: "Тухачевского", build: "28"},
{street: "Тухачевского", build: "29"},
{street: "Тухачевского", build: "31"},
{street: "Тухачевского", build: "35"},
{street: "Тухачевского", build: "39"},
{street: "Тухачевского", build: "43"},
{street: "Тухачевского", build: "45"},
{street: "Тухачевского", build: "47"},
{street: "Тухачевского", build: "49"},
{street: "Тухачевского", build: " 14А"},
{street: "Тухачевского", build: " 29А"},
{street: "Тухачевского", build: " 31А"},
{street: "Тухачевского", build: " 31Б"},
{street: "Тухачевского", build: " 31В"},
{street: "Тухачевского", build: " 31Г"},
{street: "Тухачевского", build: " 31Д"},
{street: "Тухачевского", build: " 33А"},
{street: "Тухачевского", build: " 35А"},
{street: "Тухачевского", build: " 37А"},
{street: "Тухачевского", build: " 41А"},
{street: "Тухачевского", build: " 45А"},
{street: "Тухачевского", build: " 45Б"},
{street: "Тухачевского", build: " 45В"},
{street: "Тухачевского", build: " 47А"},
{street: "Тухачевского", build: " 47Б"},
{street: "Тухачевского", build: " 49А"},
{street: "Тухачевского", build: " 49Б"},
{street: "Ульяны Громовой", build: " 7А"},
{street: "Ушакова", build: "1"},
{street: "Ушакова", build: "3"},
{street: "Ушакова", build: "5"},
{street: "Федоровского", build: "8"},
{street: "Федоровского", build: "22 (ETTH)"},
{street: "Федоровского", build: "24 (ETTH)"},
{street: "Федоровского", build: "26 (ETTH)"},
{street: "Халтурина", build: "27"},
{street: "Халтурина", build: "45"},
{street: "Халтурина", build: " 21Б"},
{street: "Халтурина", build: " 29А"},
{street: "Халтурина", build: " 29Б"},
{street: "Халтурина", build: " 35А"},
{street: "Халтурина", build: " 37А"},
{street: "Халтурина", build: " 39Б"},
{street: "Химиков", build: "12"},
{street: "Химиков", build: "14"},
{street: "Химиков", build: "15"},
{street: "Химиков", build: "16"},
{street: "Химиков", build: "17"},
{street: "Химиков", build: "19"},
{street: "Химиков", build: "21"},
{street: "Химиков", build: "22"},
{street: "Химиков", build: "23"},
{street: "Химиков", build: "24"},
{street: "Химиков", build: "25"},
{street: "Химиков", build: "26"},
{street: "Химиков", build: "34"},
{street: "Химиков", build: "36"},
{street: "Химиков", build: "43"},
{street: "Химиков", build: "47"},
{street: "Химиков", build: "49"},
{street: "Химиков", build: "51"},
{street: "Химиков", build: " 12А"},
{street: "Химиков", build: " 14А"},
{street: "Химиков", build: " 14Б"},
{street: "Химиков", build: " 16А"},
{street: "Химиков", build: " 19А"},
{street: "Химиков", build: " 23А"},
{street: "Химиков", build: " 24А"},
{street: "Химиков", build: " 26А"},
{street: "Химиков", build: " 34к1"},
{street: "Химиков", build: " 34к2"},
{street: "Химиков", build: " 36к2"},
{street: "Химиков", build: " 43А"},
{street: "Химиков", build: " 43Б"},
{street: "Химиков", build: " 43В"},
{street: "Химиков", build: " 47А"},
{street: "Химиков", build: " 49А"},
{street: "Черемховская", build: "2"},
{street: "Черемховская", build: "4"},
{street: "Черняховского", build: " 1А"},
{street: "Шахтёров", build: "32"},
{street: "Шахтёров", build: "34"},
{street: "Шахтёров", build: "36"},
{street: "Шахтёров", build: "37"},
{street: "Шахтёров", build: "38"},
{street: "Шахтёров", build: "40"},
{street: "Шахтёров", build: "41"},
{street: "Шахтёров", build: "42"},
{street: "Шахтёров", build: "43"},
{street: "Шахтёров", build: "44"},
{street: "Шахтёров", build: "45"},
{street: "Шахтёров", build: "46"},
{street: "Шахтёров", build: "47"},
{street: "Шахтёров", build: "48"},
{street: "Шахтёров", build: "49"},
{street: "Шахтёров", build: "51"},
{street: "Шахтёров", build: "53"},
{street: "Шахтёров", build: "55"},
{street: "Шахтёров", build: "57"},
{street: "Шахтёров", build: "58"},
{street: "Шахтёров", build: "59"},
{street: "Шахтёров", build: "60"},
{street: "Шахтёров", build: "61"},
{street: "Шахтёров", build: "62"},
{street: "Шахтёров", build: "63"},
{street: "Шахтёров", build: "64"},
{street: "Шахтёров", build: "65"},
{street: "Шахтёров", build: "66"},
{street: "Шахтёров", build: "67"},
{street: "Шахтёров", build: "68"},
{street: "Шахтёров", build: "69"},
{street: "Шахтёров", build: "70"},
{street: "Шахтёров", build: "71"},
{street: "Шахтёров", build: "72"},
{street: "Шахтёров", build: "73"},
{street: "Шахтёров", build: "75"},
{street: "Шахтёров", build: "77"},
{street: "Шахтёров", build: "79"},
{street: "Шахтёров", build: "80"},
{street: "Шахтёров", build: "81"},
{street: "Шахтёров", build: "82"},
{street: "Шахтёров", build: "83"},
{street: "Шахтёров", build: "84"},
{street: "Шахтёров", build: "85"},
{street: "Шахтёров", build: "86"},
{street: "Шахтёров", build: "88"},
{street: "Шахтёров", build: "90"},
{street: "Шахтёров", build: "91"},
{street: "Шахтёров", build: "92"},
{street: "Шахтёров", build: "93"},
{street: "Шахтёров", build: "95"},
{street: "Шахтёров", build: "97"},
{street: "Шахтёров", build: "99"},
{street: "Шахтёров", build: "103"},
{street: "Шахтёров", build: "115"},
{street: "Шахтёров", build: "117"},
{street: "Шахтёров", build: "119"},
{street: "Шахтёров", build: "121"},
{street: "Шахтёров", build: "123"},
{street: "Шахтёров", build: " 101А"},
{street: "Шахтёров", build: " 107А"},
{street: "Шахтёров", build: " 107А"},
{street: "Шахтёров", build: " 119А"},
{street: "Шахтёров", build: " 32А"},
{street: "Шахтёров", build: " 34А"},
{street: "Шахтёров", build: " 36А"},
{street: "Шахтёров", build: " 36Б"},
{street: "Шахтёров", build: " 38А"},
{street: "Шахтёров", build: " 38Б"},
{street: "Шахтёров", build: " 40А"},
{street: "Шахтёров", build: " 44А"},
{street: "Шахтёров", build: " 48А"},
{street: "Шахтёров", build: " 57А"},
{street: "Шахтёров", build: " 58А"},
{street: "Шахтёров", build: " 59А"},
{street: "Шахтёров", build: " 60А"},
{street: "Шахтёров", build: " 60Б"},
{street: "Шахтёров", build: " 61А"},
{street: "Шахтёров", build: " 61Б"},
{street: "Шахтёров", build: " 62А"},
{street: "Шахтёров", build: " 62Б"},
{street: "Шахтёров", build: " 65А"},
{street: "Шахтёров", build: " 68А"},
{street: "Шахтёров", build: " 70А"},
{street: "Шахтёров", build: " 72А"},
{street: "Шахтёров", build: " 82А"},
{street: "Шахтёров", build: " 82Б"},
{street: "Шахтёров", build: " 83А"},
{street: "Шахтёров", build: " 84А"},
{street: "Шахтёров", build: " 85А"},
{street: "Шахтёров", build: " 91А"},
{street: "Шахтёров", build: " 93А"},
{street: "Шахтёров", build: " 93Д"},
{street: "Шорникова", build: "11"},
{street: "Шорникова", build: "13"},
{street: "Шорникова", build: "15"},
{street: "Щегловский переулок", build: "6"},
{street: "Щегловский переулок", build: "8"},
{street: "Щегловский переулок", build: "10"},
{street: "Щегловский переулок", build: "12"},
{street: "Щегловский переулок", build: "38"},
{street: "Щегловский переулок", build: "40"},
{street: "Щегловский переулок", build: " 10А"},
{street: "Щегловский переулок", build: " 4/1"},
{street: "Юрия Двужильного", build: "12 (ETTH)"},
{street: "Юрия Двужильного", build: "14 (ETTH)"},
{street: "Юрия Двужильного", build: "36"},
{street: "Юрия Двужильного", build: " 10А"},
{street: "Юрия Двужильного", build: " 10Б"},
{street: "Юрия Двужильного", build: " 10В"},
{street: "Юрия Двужильного", build: " 12Б"},
{street: "Юрия Двужильного", build: " 16А (ETTH)"},
{street: "Юрия Двужильного", build: " 24/1 (ETTH)"},
{street: "Юрия Двужильного", build: " 24/2 (ETTH)"},
{street: "Юрия Двужильного", build: " 26А"},
{street: "Юрия Двужильного", build: " 26Б"},
{street: "Юрия Двужильного", build: " 30А"},
{street: "Юрия Двужильного", build: " 32/1"},
{street: "Юрия Двужильного", build: " 32/2"},
{street: "Юрия Двужильного", build: " 32А (ETTH)"},
{street: "Юрия Двужильного", build: " 32Б"},
{street: "Юрия Двужильного", build: " 36А (ETTH)"},
{street: "Юрия Смирнова", build: "27"}], streets: [{street: "1-й Беломорский переулок"},
{street: "1-й Квартал"},
{street: "1-я Заречная"},
{street: "1-я Линия"},
{street: "2-й Квартал"},
{street: "2-я Заречная"},
{street: "3-й Иланский переулок"},
{street: "40 лет Октября"},
{street: "50 лет Октября"},
{street: "Авроры"},
{street: "Александрова"},
{street: "Аллейная"},
{street: "Арочная"},
{street: "Базовая"},
{street: "Барнаульская"},
{street: "Белозёрная"},
{street: "Большевистская"},
{street: "Будённого"},
{street: "В.В. Михайлова"},
{street: "Варяжская"},
{street: "Васильева"},
{street: "Вельская"},
{street: "Веры Волошиной"},
{street: "Весенняя"},
{street: "Волгоградская"},
{street: "Волкова"},
{street: "Ворошилова"},
{street: "Восточный"},
{street: "Гагарина"},
{street: "Гурьевская"},
{street: "Дегтярёва"},
{street: "Дзержинского"},
{street: "Докучаева"},
{street: "Дружбы"},
{street: "Ермака"},
{street: "Железнякова"},
{street: "Инженерная"},
{street: "Инициативная"},
{street: "Институтская"},
{street: "Калинина"},
{street: "Каркасная"},
{street: "Кедровый бульвар"},
{street: "Кирова"},
{street: "Коломейцева"},
{street: "Комсомольский"},
{street: "Космическая"},
{street: "Красная"},
{street: "Красноармейская"},
{street: "Кузнецкий"},
{street: "Ленина"},
{street: "Ленинградский"},
{street: "Леонова"},
{street: "Марковцева"},
{street: "Масальская"},
{street: "Металлистов"},
{street: "Мирная"},
{street: "Мичурина"},
{street: "Молодёжный"},
{street: "Московский"},
{street: "Мостовая"},
{street: "Муромцева"},
{street: "Нахимова"},
{street: "Ногинская"},
{street: "Ноградская"},
{street: "Окружная"},
{street: "Октябрьский"},
{street: "Орджоникидзе"},
{street: "Осенний бульвар"},
{street: "Патриотов"},
{street: "переулок Леонова"},
{street: "переулок Мичурина"},
{street: "Пионерский бульвар"},
{street: "Попова"},
{street: "Потёмкина"},
{street: "Предзаводская"},
{street: "Пригородная"},
{street: "Притомская Набережная"},
{street: "Притомский"},
{street: "Пролетарская"},
{street: "Промышленновский проезд"},
{street: "Промышлённовское шоссе"},
{street: "Радищева"},
{street: "Рекордная"},
{street: "Рекордный переулок"},
{street: "Сарыгина"},
{street: "Свободы"},
{street: "Севастопольская"},
{street: "Сергея Тюленина"},
{street: "Серебряный Бор"},
{street: "Сибиряков-Гвардейцев"},
{street: "Соборная"},
{street: "Советский"},
{street: "Спартака"},
{street: "Спортивная"},
{street: "Строителей"},
{street: "Суворова"},
{street: "Тайгинская"},
{street: "Телецентр"},
{street: "Терешковой"},
{street: "Тухачевского"},
{street: "Ульяны Громовой"},
{street: "Ушакова"},
{street: "Федоровского"},
{street: "Халтурина"},
{street: "Химиков"},
{street: "Черемховская"},
{street: "Черняховского"},
{street: "Шахтёров"},
{street: "Шорникова"},
{street: "Щегловский переулок"},
{street: "Юрия Двужильного"},
{street: "Юрия Смирнова"},
] };
