city_streets["kiselevsk"] = {builds: [{street: "1 МАЯ ПЕРЕУЛОК ", build: "8"},
{street: "1 МАЯ ПЕРЕУЛОК ", build: " 2А"},
{street: "1 МАЯ ПЕРЕУЛОК ", build: " 2Б"},
{street: "1 МАЯ ПЕРЕУЛОК ", build: " 4А"},
{street: "1 МАЯ УЛИЦА ", build: "3"},
{street: "1 МАЯ УЛИЦА ", build: "5"},
{street: "1 МАЯ УЛИЦА ", build: "7"},
{street: "1 МАЯ УЛИЦА ", build: "13"},
{street: "1 МАЯ УЛИЦА ", build: "15"},
{street: "1 МАЯ УЛИЦА ", build: "23"},
{street: "1 МАЯ УЛИЦА ", build: "44"},
{street: "1 МАЯ УЛИЦА ", build: "46"},
{street: "1 МАЯ УЛИЦА ", build: "58"},
{street: "1 МАЯ УЛИЦА ", build: "62"},
{street: "1 МАЯ УЛИЦА ", build: " 11/1"},
{street: "1 МАЯ УЛИЦА ", build: " 11/2"},
{street: "1 МАЯ УЛИЦА ", build: " 11/3"},
{street: "1 МАЯ УЛИЦА ", build: " 11А"},
{street: "1 МАЯ УЛИЦА ", build: " 3А"},
{street: "1 МАЯ УЛИЦА ", build: " 9/1"},
{street: "1 МАЯ УЛИЦА ", build: " 9/2"},
{street: "1 МАЯ УЛИЦА ", build: " 9Б"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "45"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: " 11А (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: " 3/1 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: " 3/2 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: " 5А (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "1 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "10 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "11 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "12 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "13 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "14 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "16 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "17 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "18 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "19 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "2 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "20 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "22 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "23 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "24 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "25 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "26 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "27 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "28 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "29 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "30 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "31 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "33 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "34 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "35 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "36 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "37 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "39 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "4 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "40 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "41 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "42 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "47 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "49 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "5 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "6 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "8 (ETTH)"},
{street: "50 ЛЕТ ГОРОДА УЛИЦА ", build: "9 (ETTH)"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "7"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "9"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "10"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "11"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "12"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "15"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "18"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "19"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "22"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "23"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "24"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "25"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "26"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "27"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "28"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "29"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "30"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "31"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "32"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "33"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "35"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "36"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "38"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "40"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "41"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "43"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "45"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "46"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "48"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "50"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "54"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "56"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "58"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "60"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "62"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "64"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 27А"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 39/1"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 39/2"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 41/2"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 43/2"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 43/3"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 8А"},
{street: "БАГРАТИОНА УЛИЦА ", build: "15"},
{street: "БАГРАТИОНА УЛИЦА ", build: "19"},
{street: "БАГРАТИОНА УЛИЦА ", build: "21"},
{street: "БАГРАТИОНА УЛИЦА ", build: "23"},
{street: "БАГРАТИОНА УЛИЦА ", build: "25"},
{street: "БАГРАТИОНА УЛИЦА ", build: "38"},
{street: "БАГРАТИОНА УЛИЦА ", build: "42"},
{street: "БАГРАТИОНА УЛИЦА ", build: "13 (ETTH)"},
{street: "БАГРАТИОНА УЛИЦА ", build: "17 (ETTH)"},
{street: "БАГРАТИОНА УЛИЦА ", build: "34 (ETTH)"},
{street: "БАГРАТИОНА УЛИЦА ", build: "37 (ETTH)"},
{street: "БАГРАТИОНА УЛИЦА ", build: "41 (ETTH)"},
{street: "БОЕВАЯ УЛИЦА ", build: "2"},
{street: "БОЕВАЯ УЛИЦА ", build: "4"},
{street: "БОЕВАЯ УЛИЦА ", build: "12"},
{street: "БОЕВАЯ УЛИЦА ", build: "14"},
{street: "БОЕВАЯ УЛИЦА ", build: "20"},
{street: "БОЕВАЯ УЛИЦА ", build: "22"},
{street: "БОЕВАЯ УЛИЦА ", build: " 12А"},
{street: "БОЕВАЯ УЛИЦА ", build: " 14А"},
{street: "БОЕВАЯ УЛИЦА ", build: " 16А"},
{street: "БОЕВАЯ УЛИЦА ", build: " 20/2"},
{street: "БОЕВАЯ УЛИЦА ", build: " 6А"},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА ", build: "60"},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА ", build: "62"},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА ", build: "63"},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА ", build: "64"},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА ", build: "65"},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА ", build: "67"},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА ", build: "69"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "4"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "6"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "8"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "12"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "14"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "16"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "17"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "18"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "19"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "21"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "23"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "25"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "27"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "29"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "31"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "33"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: "35"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: " 12/2"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: " 12/3"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: " 16/2"},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА ", build: " 16/3"},
{street: "ВАХРУШЕВА УЛИЦА ", build: " 1А"},
{street: "ВАХРУШЕВА УЛИЦА ", build: " 2А"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: " 14А (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: " 2/2 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: " 29А"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: " 4/2 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "1 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "10 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "11 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "12 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "13 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "14 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "15 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "16 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "17 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "19 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "2 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "29 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "3 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "31 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "33 (ETTH)"},
{street: "ВЕСЕННЯЯ УЛИЦА ", build: "4 (ETTH)"},
{street: "ВОДОПРОВОДНАЯ УЛИЦА ", build: "5"},
{street: "ГАГАРИНА УЛИЦА ", build: "1"},
{street: "ГАГАРИНА УЛИЦА ", build: "2"},
{street: "ГАГАРИНА УЛИЦА ", build: "3"},
{street: "ГАГАРИНА УЛИЦА ", build: "6"},
{street: "ГАГАРИНА УЛИЦА ", build: "7"},
{street: "ГАГАРИНА УЛИЦА ", build: "8"},
{street: "ГАГАРИНА УЛИЦА ", build: "11"},
{street: "ГАГАРИНА УЛИЦА ", build: "12"},
{street: "ГАГАРИНА УЛИЦА ", build: "14"},
{street: "ГАГАРИНА УЛИЦА ", build: "17"},
{street: "ГАГАРИНА УЛИЦА ", build: "21"},
{street: "ГАГАРИНА УЛИЦА ", build: "25"},
{street: "ГАГАРИНА УЛИЦА ", build: "27"},
{street: "ГАГАРИНА УЛИЦА ", build: "41"},
{street: "ГАГАРИНА УЛИЦА ", build: " 17А (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "18 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "19 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "20 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "24 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "28 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "29 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "30 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "31 (ETTH)"},
{street: "ГАГАРИНА УЛИЦА ", build: "33 (ETTH)"},
{street: "ГОРМАШЕВСКАЯ УЛИЦА ", build: "5"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "1"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "8"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "10"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "17"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "19"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "21"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "23"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "24"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "30"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: "32"},
{street: "ДЗЕРЖИНСКОГО УЛИЦА ", build: " 24А"},
{street: "ДРУЖБЫ УЛИЦА ", build: "1"},
{street: "ДРУЖБЫ УЛИЦА ", build: "3"},
{street: "ДРУЖБЫ УЛИЦА ", build: " 2/2"},
{street: "ЗАБАЙКАЛЬСКАЯ УЛИЦА ", build: "4"},
{street: "ЗАГАРАЖНАЯ УЛИЦА ", build: "9"},
{street: "ЗАПАДНЫЙ ПРОЕЗД ", build: "9"},
{street: "ЗАПАДНЫЙ ПРОЕЗД ", build: " 10/1"},
{street: "ЗАПАДНЫЙ ПРОЕЗД ", build: " 7/1"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: "31"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: "33"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: "35"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: "37"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: "41"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: "43"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: "47"},
{street: "ЗЕМЛЯЧКИ УЛИЦА ", build: " 43Б"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: "2"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: "3"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: "4"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: "6"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: "8"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: "9"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: " 11А"},
{street: "И.ЧЕРНЫХ УЛИЦА ", build: " 13А"},
{street: "ИНЖЕНЕРНАЯ УЛИЦА ", build: "7"},
{street: "ИНЖЕНЕРНАЯ УЛИЦА ", build: "10"},
{street: "ИНЖЕНЕРНАЯ УЛИЦА ", build: "11"},
{street: "ИНЖЕНЕРНАЯ УЛИЦА ", build: "13"},
{street: "ИНЖЕНЕРНАЯ УЛИЦА ", build: "14"},
{street: "ИНЖЕНЕРНАЯ УЛИЦА ", build: " 4А"},
{street: "ИНЖЕНЕРНАЯ УЛИЦА ", build: " 6А"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "2"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "3"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "4"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "5"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "7"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "8"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "9"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: "10"},
{street: "КАЗАНСКАЯ УЛИЦА ", build: " 17Б"},
{street: "КАЛИНИНА УЛИЦА ", build: "10"},
{street: "КИРОВА УЛИЦА ", build: "1"},
{street: "КИРОВА УЛИЦА ", build: "3"},
{street: "КИРОВА УЛИЦА ", build: "5"},
{street: "КИРОВА УЛИЦА ", build: "6"},
{street: "КИРОВА УЛИЦА ", build: "7"},
{street: "КИРОВА УЛИЦА ", build: "8"},
{street: "КИРОВА УЛИЦА ", build: "12"},
{street: "КИРПИЧНЫЙ ПЕРЕУЛОК ", build: "9"},
{street: "КИРПИЧНЫЙ ПЕРЕУЛОК ", build: "27"},
{street: "КИРПИЧНЫЙ ПЕРЕУЛОК ", build: "29"},
{street: "КИРПИЧНЫЙ ПЕРЕУЛОК ", build: "33"},
{street: "КИРПИЧНЫЙ ПЕРЕУЛОК ", build: "37"},
{street: "КИРПИЧНЫЙ ПЕРЕУЛОК ", build: " 37А"},
{street: "КИСЕЛЕВСКАЯ УЛИЦА ", build: "50"},
{street: "КИСЕЛЕВСКАЯ УЛИЦА ", build: "51"},
{street: "КИСЕЛЕВСКАЯ УЛИЦА ", build: " 51А"},
{street: "КОВАЛЕНКО УЛИЦА ", build: "4"},
{street: "КОВАЛЕНКО УЛИЦА ", build: "7"},
{street: "КОВАЛЕНКО УЛИЦА ", build: "12"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "1"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "3"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "5"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "7"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "9"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "11"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "12"},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ ", build: "14"},
{street: "КРАСИНА УЛИЦА ", build: "2"},
{street: "КУЛЬТУРНАЯ УЛИЦА ", build: "9"},
{street: "КУЛЬТУРНАЯ УЛИЦА ", build: "11"},
{street: "КУЛЬТУРНАЯ УЛИЦА ", build: "13"},
{street: "КУЛЬТУРНАЯ УЛИЦА ", build: "26"},
{street: "КУЛЬТУРНАЯ УЛИЦА ", build: "28"},
{street: "ЛЕНИНА УЛИЦА ", build: "12"},
{street: "ЛЕНИНА УЛИЦА ", build: "24"},
{street: "ЛЕНИНА УЛИЦА ", build: "25"},
{street: "ЛЕНИНА УЛИЦА ", build: "26"},
{street: "ЛЕНИНА УЛИЦА ", build: "38"},
{street: "ЛЕНИНА УЛИЦА ", build: "39"},
{street: "ЛЕНИНА УЛИЦА ", build: "43"},
{street: "ЛЕНИНА УЛИЦА ", build: "45"},
{street: "ЛЕНИНА УЛИЦА ", build: "46"},
{street: "ЛЕНИНА УЛИЦА ", build: "47"},
{street: "ЛЕНИНА УЛИЦА ", build: "49"},
{street: "ЛЕНИНА УЛИЦА ", build: "51"},
{street: "ЛЕНИНА УЛИЦА ", build: "52"},
{street: "ЛЕНИНА УЛИЦА ", build: "53"},
{street: "ЛЕНИНА УЛИЦА ", build: "54"},
{street: "ЛЕНИНА УЛИЦА ", build: "56"},
{street: "ЛЕНИНА УЛИЦА ", build: " 46А"},
{street: "ЛЕНИНА УЛИЦА ", build: "41 (ETTH)"},
{street: "ЛЕНИНА УЛИЦА ", build: "42 (ETTH)"},
{street: "ЛУТУГИНА УЛИЦА ", build: "9"},
{street: "ЛУТУГИНА УЛИЦА ", build: "13"},
{street: "ЛУТУГИНА УЛИЦА ", build: "15"},
{street: "ЛУТУГИНА УЛИЦА ", build: "26"},
{street: "ЛУТУГИНА УЛИЦА ", build: "27"},
{street: "ЛУТУГИНА УЛИЦА ", build: "45"},
{street: "ЛУТУГИНА УЛИЦА ", build: "47"},
{street: "ЛУТУГИНА УЛИЦА ", build: " 24А"},
{street: "ЛУТУГИНА УЛИЦА ", build: " 26А"},
{street: "ЛУТУГИНА УЛИЦА ", build: " 28А"},
{street: "МАЙКОПСКАЯ УЛИЦА ", build: "1"},
{street: "МАЙКОПСКАЯ УЛИЦА ", build: "2"},
{street: "МАЙКОПСКАЯ УЛИЦА ", build: "5"},
{street: "МАЙКОПСКАЯ УЛИЦА ", build: "11"},
{street: "МАКАРОВА УЛИЦА ", build: "23 (ETTH)"},
{street: "МАКАРОВА УЛИЦА ", build: "25 (ETTH)"},
{street: "МАТРОСОВА УЛИЦА ", build: "2"},
{street: "МАТРОСОВА УЛИЦА ", build: "13"},
{street: "МАТРОСОВА УЛИЦА ", build: "15"},
{street: "МАТРОСОВА УЛИЦА ", build: "21"},
{street: "МАТРОСОВА УЛИЦА ", build: "25"},
{street: "МАТРОСОВА УЛИЦА ", build: "27"},
{street: "МАТРОСОВА УЛИЦА ", build: "4 (ETTH)"},
{street: "МАТРОСОВА УЛИЦА ", build: "6 (ETTH)"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "2"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "4"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "5"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "12"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "15"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "20"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "21"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "23"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: "26"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: " 15А"},
{street: "МАЯКОВСКОГО УЛИЦА ", build: " 2А"},
{street: "МИРА УЛИЦА ", build: " 12/1 (ETTH)"},
{street: "МИРА УЛИЦА ", build: " 12/2 (ETTH)"},
{street: "МИРА УЛИЦА ", build: " 2/1 (ETTH)"},
{street: "МИРА УЛИЦА ", build: " 4/1 (ETTH)"},
{street: "МИРА УЛИЦА ", build: " 46А (ETTH)"},
{street: "МИРА УЛИЦА ", build: " 56/1 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "10 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "14 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "16 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "2 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "20 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "22 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "24 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "26 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "30 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "32 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "34 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "36 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "38 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "42 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "44 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "48 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "50 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "52 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "54 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "6 (ETTH)"},
{street: "МИРА УЛИЦА ", build: "8 (ETTH)"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "4"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "11"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "13"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "14"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "15"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "16"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "17"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "18"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "19"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "20"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "22"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "24"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "25"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "26"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "28"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "30 (ETTH)"},
{street: "МОСКОВСКАЯ УЛИЦА ", build: "7 (ETTH)"},
{street: "МУРМАНСКИЙ ПЕРЕУЛОК ", build: "16"},
{street: "МУРМАНСКИЙ ПЕРЕУЛОК ", build: " 22/2"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "6"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "8"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "10"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "12"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "14"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "16"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "18"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: " 10А"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: " 13А (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "11 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "13 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "15 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "17 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "2 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "3 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "4 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "5 (ETTH)"},
{street: "НОВОСТРОЙКА УЛИЦА ", build: "7 (ETTH)"},
{street: "ОДЕССКАЯ УЛИЦА ", build: "12"},
{street: "ОДЕССКАЯ УЛИЦА ", build: "14"},
{street: "ОДЕССКАЯ УЛИЦА ", build: "20"},
{street: "ОДЕССКАЯ УЛИЦА ", build: "22"},
{street: "ОДЕССКАЯ УЛИЦА ", build: "26"},
{street: "ОДЕССКАЯ УЛИЦА ", build: "28"},
{street: "ОДЕССКАЯ УЛИЦА ", build: "46"},
{street: "ОДЕССКАЯ УЛИЦА ", build: " 14А"},
{street: "ОДЕССКАЯ УЛИЦА ", build: " 48А"},
{street: "ОДЕССКАЯ УЛИЦА ", build: " 50А"},
{street: "ОХОТСКАЯ УЛИЦА ", build: "4"},
{street: "ОХОТСКАЯ УЛИЦА ", build: "6"},
{street: "ОХОТСКАЯ УЛИЦА ", build: "12"},
{street: "ОХОТСКАЯ УЛИЦА ", build: "14"},
{street: "ПАНФИЛОВА УЛИЦА ", build: "1"},
{street: "ПАНФИЛОВА УЛИЦА ", build: "3"},
{street: "ПАНФИЛОВА УЛИЦА ", build: "4"},
{street: "ПАНФИЛОВА УЛИЦА ", build: "6"},
{street: "ПАНФИЛОВА УЛИЦА ", build: "11"},
{street: "ПАНФИЛОВА УЛИЦА ", build: " 6А"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "1 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "2 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "3 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "4 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "5 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "6 (ETTH)"},
{street: "ПОЛЕВАЯ УЛИЦА ", build: "45"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "1"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "5"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "7"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "15"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "17"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "21"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "23"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "25"},
{street: "ПРОГРЕССИВНАЯ УЛИЦА ", build: "27"},
{street: "ПРОГРЕССИВНЫЙ ПРОЕЗД ", build: "5"},
{street: "ПРОГРЕССИВНЫЙ ПРОЕЗД ", build: "6"},
{street: "ПРОГРЕССИВНЫЙ ПРОЕЗД ", build: "8"},
{street: "ПРОМЫШЛЕННАЯ УЛИЦА ", build: " 1А"},
{street: "ПРОМЫШЛЕННАЯ УЛИЦА ", build: "1 (ETTH)"},
{street: "ПРОМЫШЛЕННАЯ УЛИЦА ", build: "3 (ETTH)"},
{street: "ПРОМЫШЛЕННАЯ УЛИЦА ", build: "6 (ETTH)"},
{street: "ПУТЕЙСКАЯ УЛИЦА ", build: "29"},
{street: "ПУТЕЙСКАЯ УЛИЦА ", build: "31"},
{street: "ПУТЕЙСКАЯ УЛИЦА ", build: "44"},
{street: "ПУТЕЙСКАЯ УЛИЦА ", build: "46"},
{street: "ПУТЕЙСКАЯ УЛИЦА ", build: " 44А"},
{street: "РАЩУПКИНА УЛИЦА ", build: "3"},
{street: "РАЩУПКИНА УЛИЦА ", build: "7"},
{street: "РАЩУПКИНА УЛИЦА ", build: "10"},
{street: "РАЩУПКИНА УЛИЦА ", build: "12"},
{street: "РАЩУПКИНА УЛИЦА ", build: "14"},
{street: "РАЩУПКИНА УЛИЦА ", build: " 10/2"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "3"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "9"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "11"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "13"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "15"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "19"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "23"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "25"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "27"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "31"},
{street: "РЕЙДОВАЯ УЛИЦА ", build: "33"},
{street: "САДОВАЯ УЛИЦА ", build: "9"},
{street: "САНДАЛОВА УЛИЦА ", build: "15"},
{street: "САНДАЛОВА УЛИЦА ", build: "17"},
{street: "СЕДОВА УЛИЦА ", build: "2"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "3"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "4"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "5"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "6"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "8"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "9"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "10"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "12"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "14"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "16"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "18"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "20"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "24"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 16А"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 2А"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 3А"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 3Б"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 4А"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 5А"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 8А"},
{street: "СОСНОВАЯ УЛИЦА ", build: "7 (ETTH)"},
{street: "СОСНОВАЯ УЛИЦА ", build: "8 (ETTH)"},
{street: "СОСНОВАЯ УЛИЦА ", build: "9 (ETTH)"},
{street: "СТАВРОПОЛЬСКАЯ УЛИЦА ", build: "2"},
{street: "СТАВРОПОЛЬСКАЯ УЛИЦА ", build: "3"},
{street: "СТАВРОПОЛЬСКАЯ УЛИЦА ", build: "7"},
{street: "СТРОИТЕЛЕЙ ПРОЕЗД ", build: "2 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОЕЗД ", build: "3 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОЕЗД ", build: "4 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОЕЗД ", build: "7 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОЕЗД ", build: "9 (ETTH)"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "9"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "10"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "11"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "12"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "13"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "14"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "15"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "16"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "18"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "19"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "21"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: " 1/1"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: " 1/2"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: " 14/2"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: " 16/2"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: " 18/2"},
{street: "ТАЙБИНЦЕВ УЛИЦА ", build: "36"},
{street: "ТОЛСТОГО УЛИЦА ", build: "1"},
{street: "ТОЛСТОГО УЛИЦА ", build: "3"},
{street: "ТОЛСТОГО УЛИЦА ", build: "5"},
{street: "ТОЛСТОГО УЛИЦА ", build: "7"},
{street: "ТОЛСТОГО УЛИЦА ", build: "9"},
{street: "ТОМСКАЯ УЛИЦА ", build: "3"},
{street: "ТОМСКАЯ УЛИЦА ", build: "4"},
{street: "ТОМСКАЯ УЛИЦА ", build: "5"},
{street: "ТОМСКАЯ УЛИЦА ", build: "6"},
{street: "ТОМСКАЯ УЛИЦА ", build: "7"},
{street: "ТОМСКАЯ УЛИЦА ", build: "8"},
{street: "ТОМСКАЯ УЛИЦА ", build: "9"},
{street: "ТОМСКАЯ УЛИЦА ", build: "10"},
{street: "ТОМСКАЯ УЛИЦА ", build: "14"},
{street: "ТОМСКАЯ УЛИЦА ", build: "16"},
{street: "ТОМСКАЯ УЛИЦА ", build: "17"},
{street: "ТОМСКАЯ УЛИЦА ", build: "18"},
{street: "ТОМСКАЯ УЛИЦА ", build: "19"},
{street: "ТОМСКАЯ УЛИЦА ", build: "21"},
{street: "ТОМСКАЯ УЛИЦА ", build: "23"},
{street: "ТОМСКАЯ УЛИЦА ", build: "25 (ETTH)"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "7"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "9"},
{street: "ТРАНСПОРТНЫЙ ПЕРЕУЛОК ", build: "1"},
{street: "ТРАНСПОРТНЫЙ ПЕРЕУЛОК ", build: "6"},
{street: "ТРАНСПОРТНЫЙ ПЕРЕУЛОК ", build: "8"},
{street: "ТРАНСПОРТНЫЙ ПЕРЕУЛОК ", build: "4 (ETTH)"},
{street: "ТРУДОВАЯ УЛИЦА ", build: "6"},
{street: "ТРУДОВАЯ УЛИЦА ", build: "16"},
{street: "ТРУДОВАЯ УЛИЦА ", build: "20"},
{street: "ТРУДОВАЯ УЛИЦА ", build: "22"},
{street: "ТРУДОВАЯ УЛИЦА ", build: "23"},
{street: "ТРУДОВАЯ УЛИЦА ", build: " 22А"},
{street: "ТРУДОВАЯ УЛИЦА ", build: " 22Б"},
{street: "ТУЛЬСКАЯ УЛИЦА ", build: "5"},
{street: "ТУЛЬСКАЯ УЛИЦА ", build: "13"},
{street: "ТУЛЬСКАЯ УЛИЦА ", build: "15"},
{street: "ТУЛЬСКАЯ УЛИЦА ", build: "20 (ETTH)"},
{street: "ТУЛЬСКАЯ УЛИЦА ", build: "21 (ETTH)"},
{street: "ТУЛЬСКАЯ УЛИЦА ", build: "23 (ETTH)"},
{street: "УНЖАКОВА УЛИЦА ", build: "3"},
{street: "УНЖАКОВА УЛИЦА ", build: "5"},
{street: "УНЖАКОВА УЛИЦА ", build: "6"},
{street: "УНЖАКОВА УЛИЦА ", build: "9"},
{street: "УНЖАКОВА УЛИЦА ", build: "10"},
{street: "УНЖАКОВА УЛИЦА ", build: "12"},
{street: "УНЖАКОВА УЛИЦА ", build: "14"},
{street: "УНЖАКОВА УЛИЦА ", build: "16"},
{street: "УНЖАКОВА УЛИЦА ", build: "18"},
{street: "УНЖАКОВА УЛИЦА ", build: "19"},
{street: "УСКАТНАЯ УЛИЦА ", build: " 17А (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: " 27А (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "17 (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "23 (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "25 (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "33 (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "35 (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "37 (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "4 (ETTH)"},
{street: "УСКАТНАЯ УЛИЦА ", build: "5 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: " 1А (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: " 4/2 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: " 6/2 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: " 6/3 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: " 6/4 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: "1 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: "2 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: "3 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: "4 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: "5 (ETTH)"},
{street: "УТРЕННЯЯ УЛИЦА ", build: "6 (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 10А (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 10Б (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 10В (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 12 А (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 14Б (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 16 Б (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 6 В (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 6А (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 6Б (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 8 А (ETTH)"},
{street: "ФАДЕЕВА УЛИЦА ", build: " 8 Б (ETTH)"},
{street: "ЧАЙКОВСКОГО УЛИЦА ", build: "1"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: "21"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: "23"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: "27"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: "29"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: "31"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: " 17/2"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: " 21/2"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: " 23/2"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: " 25/2"},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА ", build: " 31/2"},
{street: "ЧЕРНЯХОВСКОГО УЛИЦА ", build: "2"},
{street: "ЧЕРНЯХОВСКОГО УЛИЦА ", build: "17 (ETTH)"},
{street: "ЧУМОВА УЛИЦА ", build: "1"},
{street: "ЧУМОВА УЛИЦА ", build: "3"},
{street: "ЧУМОВА УЛИЦА ", build: "5"},
{street: "ЧУМОВА УЛИЦА ", build: "15"},
{street: "ЧУМОВА УЛИЦА ", build: "19"},
{street: "ЧУМОВА УЛИЦА ", build: "21"},
{street: "ЧУМОВА УЛИЦА ", build: "27"},
{street: "ЧУМОВА УЛИЦА ", build: "29"},
{street: "ЧУМОВА УЛИЦА ", build: "31"},
{street: "ЧУМОВА УЛИЦА ", build: "42"},
], streets: [{street: "1 МАЯ ПЕРЕУЛОК "},
{street: "1 МАЯ УЛИЦА "},
{street: "50 ЛЕТ ГОРОДА УЛИЦА "},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА "},
{street: "БАГРАТИОНА УЛИЦА "},
{street: "БОЕВАЯ УЛИЦА "},
{street: "БОЛЬШАЯ ДАЧНАЯ УЛИЦА "},
{street: "БОЛЬШЕВИСТСКАЯ УЛИЦА "},
{street: "ВЕСЕННЯЯ УЛИЦА "},
{street: "ВОДОПРОВОДНАЯ УЛИЦА "},
{street: "ГОРМАШЕВСКАЯ УЛИЦА "},
{street: "ДРУЖБЫ УЛИЦА "},
{street: "ЗАБАЙКАЛЬСКАЯ УЛИЦА "},
{street: "ЗАГАРАЖНАЯ УЛИЦА "},
{street: "ЗАПАДНЫЙ ПРОЕЗД "},
{street: "ЗЕМЛЯЧКИ УЛИЦА "},
{street: "И.ЧЕРНЫХ УЛИЦА "},
{street: "ИНЖЕНЕРНАЯ УЛИЦА "},
{street: "КАЗАНСКАЯ УЛИЦА "},
{street: "КИРПИЧНЫЙ ПЕРЕУЛОК "},
{street: "КОВАЛЕНКО УЛИЦА "},
{street: "КОМСОМОЛЬСКИЙ ПРОСПЕКТ "},
{street: "КРАСИНА УЛИЦА "},
{street: "КУЛЬТУРНАЯ УЛИЦА "},
{street: "ЛУТУГИНА УЛИЦА "},
{street: "МАЙКОПСКАЯ УЛИЦА "},
{street: "МАКАРОВА УЛИЦА "},
{street: "МАЯКОВСКОГО УЛИЦА "},
{street: "МУРМАНСКИЙ ПЕРЕУЛОК "},
{street: "НОВОСТРОЙКА УЛИЦА "},
{street: "ОДЕССКАЯ УЛИЦА "},
{street: "ОХОТСКАЯ УЛИЦА "},
{street: "ПАНФИЛОВА УЛИЦА "},
{street: "ПИОНЕРСКАЯ УЛИЦА "},
{street: "ПОЛЕВАЯ УЛИЦА "},
{street: "ПРОГРЕССИВНАЯ УЛИЦА "},
{street: "ПРОГРЕССИВНЫЙ ПРОЕЗД "},
{street: "ПРОМЫШЛЕННАЯ УЛИЦА "},
{street: "ПУТЕЙСКАЯ УЛИЦА "},
{street: "РАЩУПКИНА УЛИЦА "},
{street: "РЕЙДОВАЯ УЛИЦА "},
{street: "САНДАЛОВА УЛИЦА "},
{street: "СЕДОВА УЛИЦА "},
{street: "СТАВРОПОЛЬСКАЯ УЛИЦА "},
{street: "СТРОИТЕЛЕЙ ПРОЕЗД "},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА "},
{street: "ТАЙБИНЦЕВ УЛИЦА "},
{street: "ТОЛСТОГО УЛИЦА "},
{street: "ТОМСКАЯ УЛИЦА "},
{street: "ТРАНСПОРТНАЯ УЛИЦА "},
{street: "ТРАНСПОРТНЫЙ ПЕРЕУЛОК "},
{street: "ТУЛЬСКАЯ УЛИЦА "},
{street: "УНЖАКОВА УЛИЦА "},
{street: "УСКАТНАЯ УЛИЦА "},
{street: "УТРЕННЯЯ УЛИЦА "},
{street: "ФАДЕЕВА УЛИЦА "},
{street: "ЧАЙКОВСКОГО УЛИЦА "},
{street: "ЧЕРНОМОРСКАЯ УЛИЦА "},
{street: "ЧУМОВА УЛИЦА "},
] };
