city_streets["kiselevsk"] = {builds: [{street: "1 Мая пер ", build: "2А"},
{street: "1 Мая пер ", build: "2Б"},
{street: "1 Мая пер ", build: "4А"},
{street: "1 Мая пер ", build: "8"},
{street: "1 Мая ул", build: "11/1"},
{street: "1 Мая ул", build: "11/2"},
{street: "1 Мая ул", build: "11/3"},
{street: "1 Мая ул", build: "11А"},
{street: "1 Мая ул", build: "13"},
{street: "1 Мая ул", build: "15"},
{street: "1 Мая ул", build: "23"},
{street: "1 Мая ул", build: "3"},
{street: "1 Мая ул", build: "3А"},
{street: "1 Мая ул", build: "44"},
{street: "1 Мая ул", build: "46"},
{street: "1 Мая ул", build: "5"},
{street: "1 Мая ул", build: "58"},
{street: "1 Мая ул", build: "62"},
{street: "1 Мая ул", build: "7"},
{street: "1 Мая ул", build: "9/1"},
{street: "1 Мая ул", build: "9/2"},
{street: "1 Мая ул", build: "9Б"},
{street: "50 Лет Города ул", build: "1_ETTH"},
{street: "50 Лет Города ул", build: "10_ETTH"},
{street: "50 Лет Города ул", build: "11_ETTH"},
{street: "50 Лет Города ул", build: "11А_ETTH"},
{street: "50 Лет Города ул", build: "12_ETTH"},
{street: "50 Лет Города ул", build: "13_ETTH"},
{street: "50 Лет Города ул", build: "14_ETTH"},
{street: "50 Лет Города ул", build: "16_ETTH"},
{street: "50 Лет Города ул", build: "17_ETTH"},
{street: "50 Лет Города ул", build: "18_ETTH"},
{street: "50 Лет Города ул", build: "19_ETTH"},
{street: "50 Лет Города ул", build: "2_ETTH"},
{street: "50 Лет Города ул", build: "20_ETTH"},
{street: "50 Лет Города ул", build: "22_ETTH"},
{street: "50 Лет Города ул", build: "23_ETTH"},
{street: "50 Лет Города ул", build: "24_ETTH"},
{street: "50 Лет Города ул", build: "25_ETTH"},
{street: "50 Лет Города ул", build: "26_ETTH"},
{street: "50 Лет Города ул", build: "27_ETTH"},
{street: "50 Лет Города ул", build: "28_ETTH"},
{street: "50 Лет Города ул", build: "29_ETTH"},
{street: "50 Лет Города ул", build: "3/1_ETTH"},
{street: "50 Лет Города ул", build: "3/2_ETTH"},
{street: "50 Лет Города ул", build: "30_ETTH"},
{street: "50 Лет Города ул", build: "31_ETTH"},
{street: "50 Лет Города ул", build: "33_ETTH"},
{street: "50 Лет Города ул", build: "34_ETTH"},
{street: "50 Лет Города ул", build: "35_ETTH"},
{street: "50 Лет Города ул", build: "36_ETTH"},
{street: "50 Лет Города ул", build: "37_ETTH"},
{street: "50 Лет Города ул", build: "39_ETTH"},
{street: "50 Лет Города ул", build: "4_ETTH"},
{street: "50 Лет Города ул", build: "40_ETTH"},
{street: "50 Лет Города ул", build: "41_ETTH"},
{street: "50 Лет Города ул", build: "42_ETTH"},
{street: "50 Лет Города ул", build: "45"},
{street: "50 Лет Города ул", build: "47_ETTH"},
{street: "50 Лет Города ул", build: "49_ETTH"},
{street: "50 Лет Города ул", build: "5_ETTH"},
{street: "50 Лет Города ул", build: "5А_ETTH"},
{street: "50 Лет Города ул", build: "6_ETTH"},
{street: "50 Лет Города ул", build: "8_ETTH"},
{street: "50 Лет Города ул", build: "9_ETTH"},
{street: "50 Лет Октября ул", build: "10"},
{street: "50 Лет Октября ул", build: "11"},
{street: "50 Лет Октября ул", build: "12"},
{street: "50 Лет Октября ул", build: "15"},
{street: "50 Лет Октября ул", build: "18"},
{street: "50 Лет Октября ул", build: "19"},
{street: "50 Лет Октября ул", build: "22"},
{street: "50 Лет Октября ул", build: "23"},
{street: "50 Лет Октября ул", build: "24"},
{street: "50 Лет Октября ул", build: "25"},
{street: "50 Лет Октября ул", build: "26"},
{street: "50 Лет Октября ул", build: "27"},
{street: "50 Лет Октября ул", build: "27А"},
{street: "50 Лет Октября ул", build: "28"},
{street: "50 Лет Октября ул", build: "29"},
{street: "50 Лет Октября ул", build: "30"},
{street: "50 Лет Октября ул", build: "31"},
{street: "50 Лет Октября ул", build: "32"},
{street: "50 Лет Октября ул", build: "33"},
{street: "50 Лет Октября ул", build: "35"},
{street: "50 Лет Октября ул", build: "36"},
{street: "50 Лет Октября ул", build: "38"},
{street: "50 Лет Октября ул", build: "39/1"},
{street: "50 Лет Октября ул", build: "39/2"},
{street: "50 Лет Октября ул", build: "40"},
{street: "50 Лет Октября ул", build: "41"},
{street: "50 Лет Октября ул", build: "41/2"},
{street: "50 Лет Октября ул", build: "43"},
{street: "50 Лет Октября ул", build: "43/2"},
{street: "50 Лет Октября ул", build: "43/3"},
{street: "50 Лет Октября ул", build: "45"},
{street: "50 Лет Октября ул", build: "46"},
{street: "50 Лет Октября ул", build: "48"},
{street: "50 Лет Октября ул", build: "50"},
{street: "50 Лет Октября ул", build: "54"},
{street: "50 Лет Октября ул", build: "56"},
{street: "50 Лет Октября ул", build: "58"},
{street: "50 Лет Октября ул", build: "60"},
{street: "50 Лет Октября ул", build: "62"},
{street: "50 Лет Октября ул", build: "64"},
{street: "50 Лет Октября ул", build: "7"},
{street: "50 Лет Октября ул", build: "8А"},
{street: "50 Лет Октября ул", build: "9"},
{street: "Багратиона ул", build: "13_ETTH"},
{street: "Багратиона ул", build: "15"},
{street: "Багратиона ул", build: "17_ETTH"},
{street: "Багратиона ул", build: "19"},
{street: "Багратиона ул", build: "21"},
{street: "Багратиона ул", build: "23"},
{street: "Багратиона ул", build: "25"},
{street: "Багратиона ул", build: "34_ETTH"},
{street: "Багратиона ул", build: "37_ETTH"},
{street: "Багратиона ул", build: "38"},
{street: "Багратиона ул", build: "41_ETTH"},
{street: "Багратиона ул", build: "42"},
{street: "Боевая ул", build: "12"},
{street: "Боевая ул", build: "12А"},
{street: "Боевая ул", build: "14"},
{street: "Боевая ул", build: "14А"},
{street: "Боевая ул", build: "16А"},
{street: "Боевая ул", build: "2"},
{street: "Боевая ул", build: "20"},
{street: "Боевая ул", build: "20/2"},
{street: "Боевая ул", build: "22"},
{street: "Боевая ул", build: "4"},
{street: "Боевая ул", build: "6А"},
{street: "Большая Дачная ул", build: "60"},
{street: "Большая Дачная ул", build: "62"},
{street: "Большая Дачная ул", build: "63"},
{street: "Большая Дачная ул", build: "64"},
{street: "Большая Дачная ул", build: "65"},
{street: "Большая Дачная ул", build: "67"},
{street: "Большая Дачная ул", build: "69"},
{street: "Большевистская ул", build: "12"},
{street: "Большевистская ул", build: "12/2"},
{street: "Большевистская ул", build: "12/3"},
{street: "Большевистская ул", build: "14"},
{street: "Большевистская ул", build: "16"},
{street: "Большевистская ул", build: "16/2"},
{street: "Большевистская ул", build: "16/3"},
{street: "Большевистская ул", build: "17"},
{street: "Большевистская ул", build: "18"},
{street: "Большевистская ул", build: "19"},
{street: "Большевистская ул", build: "21"},
{street: "Большевистская ул", build: "23"},
{street: "Большевистская ул", build: "25"},
{street: "Большевистская ул", build: "27"},
{street: "Большевистская ул", build: "29"},
{street: "Большевистская ул", build: "31"},
{street: "Большевистская ул", build: "33"},
{street: "Большевистская ул", build: "35"},
{street: "Большевистская ул", build: "4"},
{street: "Большевистская ул", build: "6"},
{street: "Большевистская ул", build: "8"},
{street: "Вахрушева ул", build: "1А"},
{street: "Вахрушева ул", build: "2А"},
{street: "Весенняя ул", build: "1_ETTH"},
{street: "Весенняя ул", build: "10_ETTH"},
{street: "Весенняя ул", build: "11_ETTH"},
{street: "Весенняя ул", build: "12_ETTH"},
{street: "Весенняя ул", build: "13_ETTH"},
{street: "Весенняя ул", build: "14_ETTH"},
{street: "Весенняя ул", build: "14А_ETTH"},
{street: "Весенняя ул", build: "15_ETTH"},
{street: "Весенняя ул", build: "16_ETTH"},
{street: "Весенняя ул", build: "17_ETTH"},
{street: "Весенняя ул", build: "19_ETTH"},
{street: "Весенняя ул", build: "2_ETTH"},
{street: "Весенняя ул", build: "2/2_ETTH"},
{street: "Весенняя ул", build: "29_ETTH"},
{street: "Весенняя ул", build: "29А"},
{street: "Весенняя ул", build: "3_ETTH"},
{street: "Весенняя ул", build: "31_ETTH"},
{street: "Весенняя ул", build: "33_ETTH"},
{street: "Весенняя ул", build: "4_ETTH"},
{street: "Весенняя ул", build: "4/2_ETTH"},
{street: "Водопроводная ул", build: "1"},
{street: "Водопроводная ул", build: "5"},
{street: "Гагарина ул", build: "1"},
{street: "Гагарина ул", build: "11"},
{street: "Гагарина ул", build: "12"},
{street: "Гагарина ул", build: "14"},
{street: "Гагарина ул", build: "17"},
{street: "Гагарина ул", build: "17А_ETTH"},
{street: "Гагарина ул", build: "18_ETTH"},
{street: "Гагарина ул", build: "19_ETTH"},
{street: "Гагарина ул", build: "2"},
{street: "Гагарина ул", build: "20_ETTH"},
{street: "Гагарина ул", build: "21"},
{street: "Гагарина ул", build: "24_ETTH"},
{street: "Гагарина ул", build: "25"},
{street: "Гагарина ул", build: "27"},
{street: "Гагарина ул", build: "28_ETTH"},
{street: "Гагарина ул", build: "29_ETTH"},
{street: "Гагарина ул", build: "3"},
{street: "Гагарина ул", build: "30_ETTH"},
{street: "Гагарина ул", build: "31_ETTH"},
{street: "Гагарина ул", build: "33_ETTH"},
{street: "Гагарина ул", build: "41"},
{street: "Гагарина ул", build: "6"},
{street: "Гагарина ул", build: "7"},
{street: "Гагарина ул", build: "8"},
{street: "Гормашевская ул", build: "5"},
{street: "Дзержинского ул", build: "1"},
{street: "Дзержинского ул", build: "10"},
{street: "Дзержинского ул", build: "17"},
{street: "Дзержинского ул", build: "19"},
{street: "Дзержинского ул", build: "21"},
{street: "Дзержинского ул", build: "23"},
{street: "Дзержинского ул", build: "24"},
{street: "Дзержинского ул", build: "24А"},
{street: "Дзержинского ул", build: "30"},
{street: "Дзержинского ул", build: "32"},
{street: "Дзержинского ул", build: "8"},
{street: "Дружбы ул", build: "1"},
{street: "Дружбы ул", build: "2/2"},
{street: "Дружбы ул", build: "3"},
{street: "Забайкальская ул", build: "4"},
{street: "Загаражная ул", build: "9"},
{street: "Западный Проезд ", build: "10/1"},
{street: "Западный Проезд ", build: "7/1"},
{street: "Западный Проезд ", build: "9"},
{street: "Землячки ул", build: "31"},
{street: "Землячки ул", build: "33"},
{street: "Землячки ул", build: "35"},
{street: "Землячки ул", build: "37"},
{street: "Землячки ул", build: "41"},
{street: "Землячки ул", build: "43"},
{street: "Землячки ул", build: "43Б"},
{street: "Землячки ул", build: "47"},
{street: "И.Черных ул", build: "11А"},
{street: "И.Черных ул", build: "13А"},
{street: "И.Черных ул", build: "2"},
{street: "И.Черных ул", build: "3"},
{street: "И.Черных ул", build: "4"},
{street: "И.Черных ул", build: "6"},
{street: "И.Черных ул", build: "8"},
{street: "И.Черных ул", build: "9"},
{street: "Инженерная ул", build: "10"},
{street: "Инженерная ул", build: "11"},
{street: "Инженерная ул", build: "13"},
{street: "Инженерная ул", build: "14"},
{street: "Инженерная ул", build: "4А"},
{street: "Инженерная ул", build: "6А"},
{street: "Инженерная ул", build: "7"},
{street: "Казанская ул", build: "10"},
{street: "Казанская ул", build: "17Б"},
{street: "Казанская ул", build: "2"},
{street: "Казанская ул", build: "3"},
{street: "Казанская ул", build: "4"},
{street: "Казанская ул", build: "5"},
{street: "Казанская ул", build: "7"},
{street: "Казанская ул", build: "8"},
{street: "Казанская ул", build: "9"},
{street: "Калинина ул", build: "10"},
{street: "Кирова ул", build: "1"},
{street: "Кирова ул", build: "12"},
{street: "Кирова ул", build: "3"},
{street: "Кирова ул", build: "5"},
{street: "Кирова ул", build: "6"},
{street: "Кирова ул", build: "7"},
{street: "Кирова ул", build: "8"},
{street: "Кирпичный пер ", build: "27"},
{street: "Кирпичный пер ", build: "29"},
{street: "Кирпичный пер ", build: "33"},
{street: "Кирпичный пер ", build: "37"},
{street: "Кирпичный пер ", build: "37А"},
{street: "Кирпичный пер ", build: "9"},
{street: "Киселевская ул", build: "50"},
{street: "Киселевская ул", build: "51"},
{street: "Киселевская ул", build: "51А"},
{street: "Коваленко ул", build: "12"},
{street: "Коваленко ул", build: "4"},
{street: "Коваленко ул", build: "7"},
{street: "Комсомольский пр ", build: "1"},
{street: "Комсомольский пр ", build: "11"},
{street: "Комсомольский пр ", build: "12"},
{street: "Комсомольский пр ", build: "14"},
{street: "Комсомольский пр ", build: "3"},
{street: "Комсомольский пр ", build: "5"},
{street: "Комсомольский пр ", build: "7"},
{street: "Комсомольский пр ", build: "9"},
{street: "Красина ул", build: "2"},
{street: "Культурная ул", build: "11"},
{street: "Культурная ул", build: "13"},
{street: "Культурная ул", build: "26"},
{street: "Культурная ул", build: "28"},
{street: "Культурная ул", build: "9"},
{street: "Ленина ул", build: "12"},
{street: "Ленина ул", build: "24"},
{street: "Ленина ул", build: "25"},
{street: "Ленина ул", build: "26"},
{street: "Ленина ул", build: "38"},
{street: "Ленина ул", build: "39"},
{street: "Ленина ул", build: "41_ETTH"},
{street: "Ленина ул", build: "42_ETTH"},
{street: "Ленина ул", build: "43"},
{street: "Ленина ул", build: "45"},
{street: "Ленина ул", build: "46"},
{street: "Ленина ул", build: "46А"},
{street: "Ленина ул", build: "47"},
{street: "Ленина ул", build: "49"},
{street: "Ленина ул", build: "51"},
{street: "Ленина ул", build: "52"},
{street: "Ленина ул", build: "53"},
{street: "Ленина ул", build: "54"},
{street: "Ленина ул", build: "56"},
{street: "Лутугина ул", build: "13"},
{street: "Лутугина ул", build: "15"},
{street: "Лутугина ул", build: "24А"},
{street: "Лутугина ул", build: "26"},
{street: "Лутугина ул", build: "26А"},
{street: "Лутугина ул", build: "27"},
{street: "Лутугина ул", build: "28А"},
{street: "Лутугина ул", build: "45"},
{street: "Лутугина ул", build: "47"},
{street: "Лутугина ул", build: "9"},
{street: "Майкопская ул", build: "1"},
{street: "Майкопская ул", build: "11"},
{street: "Майкопская ул", build: "2"},
{street: "Майкопская ул", build: "5"},
{street: "Макарова ул", build: "23_ETTH"},
{street: "Макарова ул", build: "25_ETTH"},
{street: "Матросова ул", build: "13"},
{street: "Матросова ул", build: "15"},
{street: "Матросова ул", build: "2"},
{street: "Матросова ул", build: "21"},
{street: "Матросова ул", build: "25"},
{street: "Матросова ул", build: "27"},
{street: "Матросова ул", build: "4_ETTH"},
{street: "Матросова ул", build: "6_ETTH"},
{street: "Маяковского ул", build: "12"},
{street: "Маяковского ул", build: "15"},
{street: "Маяковского ул", build: "15А"},
{street: "Маяковского ул", build: "2"},
{street: "Маяковского ул", build: "20"},
{street: "Маяковского ул", build: "21"},
{street: "Маяковского ул", build: "23"},
{street: "Маяковского ул", build: "26"},
{street: "Маяковского ул", build: "2А"},
{street: "Маяковского ул", build: "4"},
{street: "Маяковского ул", build: "5"},
{street: "Мира ул", build: "10_ETTH"},
{street: "Мира ул", build: "12/1_ETTH"},
{street: "Мира ул", build: "12/2_ETTH"},
{street: "Мира ул", build: "14_ETTH"},
{street: "Мира ул", build: "16_ETTH"},
{street: "Мира ул", build: "2_ETTH"},
{street: "Мира ул", build: "2/1_ETTH"},
{street: "Мира ул", build: "20_ETTH"},
{street: "Мира ул", build: "22_ETTH"},
{street: "Мира ул", build: "24_ETTH"},
{street: "Мира ул", build: "26_ETTH"},
{street: "Мира ул", build: "30_ETTH"},
{street: "Мира ул", build: "32_ETTH"},
{street: "Мира ул", build: "34_ETTH"},
{street: "Мира ул", build: "36_ETTH"},
{street: "Мира ул", build: "38_ETTH"},
{street: "Мира ул", build: "4/1_ETTH"},
{street: "Мира ул", build: "42_ETTH"},
{street: "Мира ул", build: "44_ETTH"},
{street: "Мира ул", build: "46А_ETTH"},
{street: "Мира ул", build: "48_ETTH"},
{street: "Мира ул", build: "50_ETTH"},
{street: "Мира ул", build: "52_ETTH"},
{street: "Мира ул", build: "54_ETTH"},
{street: "Мира ул", build: "56/1_ETTH"},
{street: "Мира ул", build: "6_ETTH"},
{street: "Мира ул", build: "8_ETTH"},
{street: "Московская ул", build: "11"},
{street: "Московская ул", build: "12"},
{street: "Московская ул", build: "13"},
{street: "Московская ул", build: "14"},
{street: "Московская ул", build: "15"},
{street: "Московская ул", build: "16"},
{street: "Московская ул", build: "17"},
{street: "Московская ул", build: "18"},
{street: "Московская ул", build: "19"},
{street: "Московская ул", build: "20"},
{street: "Московская ул", build: "22"},
{street: "Московская ул", build: "24"},
{street: "Московская ул", build: "25"},
{street: "Московская ул", build: "26"},
{street: "Московская ул", build: "28"},
{street: "Московская ул", build: "30_ETTH"},
{street: "Московская ул", build: "4"},
{street: "Московская ул", build: "7_ETTH"},
{street: "Мурманский пер ", build: "16"},
{street: "Мурманский пер ", build: "22/2"},
{street: "Новостройка ул", build: "10"},
{street: "Новостройка ул", build: "10А"},
{street: "Новостройка ул", build: "11_ETTH"},
{street: "Новостройка ул", build: "12"},
{street: "Новостройка ул", build: "13_ETTH"},
{street: "Новостройка ул", build: "13А_ETTH"},
{street: "Новостройка ул", build: "14"},
{street: "Новостройка ул", build: "15_ETTH"},
{street: "Новостройка ул", build: "16"},
{street: "Новостройка ул", build: "17_ETTH"},
{street: "Новостройка ул", build: "18"},
{street: "Новостройка ул", build: "2_ETTH"},
{street: "Новостройка ул", build: "3_ETTH"},
{street: "Новостройка ул", build: "4_ETTH"},
{street: "Новостройка ул", build: "5_ETTH"},
{street: "Новостройка ул", build: "6"},
{street: "Новостройка ул", build: "7_ETTH"},
{street: "Новостройка ул", build: "8"},
{street: "Одесская ул", build: "12"},
{street: "Одесская ул", build: "14"},
{street: "Одесская ул", build: "14А"},
{street: "Одесская ул", build: "20"},
{street: "Одесская ул", build: "22"},
{street: "Одесская ул", build: "26"},
{street: "Одесская ул", build: "28"},
{street: "Одесская ул", build: "46"},
{street: "Одесская ул", build: "48А"},
{street: "Одесская ул", build: "50А"},
{street: "Охотская ул", build: "12"},
{street: "Охотская ул", build: "14"},
{street: "Охотская ул", build: "4"},
{street: "Охотская ул", build: "6"},
{street: "Панфилова ул", build: "1"},
{street: "Панфилова ул", build: "11"},
{street: "Панфилова ул", build: "3"},
{street: "Панфилова ул", build: "4"},
{street: "Панфилова ул", build: "6"},
{street: "Панфилова ул", build: "6А"},
{street: "Пионерская ул", build: "1_ETTH"},
{street: "Пионерская ул", build: "2_ETTH"},
{street: "Пионерская ул", build: "3_ETTH"},
{street: "Пионерская ул", build: "4_ETTH"},
{street: "Пионерская ул", build: "5_ETTH"},
{street: "Пионерская ул", build: "6_ETTH"},
{street: "Полевая ул", build: "45"},
{street: "Прогрессивная ул", build: "1"},
{street: "Прогрессивная ул", build: "15"},
{street: "Прогрессивная ул", build: "17"},
{street: "Прогрессивная ул", build: "21"},
{street: "Прогрессивная ул", build: "23"},
{street: "Прогрессивная ул", build: "25"},
{street: "Прогрессивная ул", build: "27"},
{street: "Прогрессивная ул", build: "5"},
{street: "Прогрессивная ул", build: "7"},
{street: "Прогрессивный Проезд ", build: "5"},
{street: "Прогрессивный Проезд ", build: "6"},
{street: "Прогрессивный Проезд ", build: "8"},
{street: "Промышленная ул", build: "1_ETTH"},
{street: "Промышленная ул", build: "1А"},
{street: "Промышленная ул", build: "3_ETTH"},
{street: "Промышленная ул", build: "6_ETTH"},
{street: "Путейская ул", build: "29"},
{street: "Путейская ул", build: "31"},
{street: "Путейская ул", build: "44"},
{street: "Путейская ул", build: "44А"},
{street: "Путейская ул", build: "46"},
{street: "Ращупкина ул", build: "10"},
{street: "Ращупкина ул", build: "10/2"},
{street: "Ращупкина ул", build: "12"},
{street: "Ращупкина ул", build: "14"},
{street: "Ращупкина ул", build: "3"},
{street: "Ращупкина ул", build: "7"},
{street: "Рейдовая ул", build: "11"},
{street: "Рейдовая ул", build: "13"},
{street: "Рейдовая ул", build: "15"},
{street: "Рейдовая ул", build: "19"},
{street: "Рейдовая ул", build: "23"},
{street: "Рейдовая ул", build: "25"},
{street: "Рейдовая ул", build: "27"},
{street: "Рейдовая ул", build: "3"},
{street: "Рейдовая ул", build: "31"},
{street: "Рейдовая ул", build: "33"},
{street: "Рейдовая ул", build: "9"},
{street: "Садовая ул", build: "9"},
{street: "Сандалова ул", build: "15"},
{street: "Сандалова ул", build: "17"},
{street: "Седова ул", build: "2"},
{street: "Советская ул", build: "10"},
{street: "Советская ул", build: "12"},
{street: "Советская ул", build: "14"},
{street: "Советская ул", build: "16"},
{street: "Советская ул", build: "16А"},
{street: "Советская ул", build: "18"},
{street: "Советская ул", build: "20"},
{street: "Советская ул", build: "24"},
{street: "Советская ул", build: "2А"},
{street: "Советская ул", build: "3"},
{street: "Советская ул", build: "3А"},
{street: "Советская ул", build: "3Б"},
{street: "Советская ул", build: "4"},
{street: "Советская ул", build: "4А"},
{street: "Советская ул", build: "5"},
{street: "Советская ул", build: "5А"},
{street: "Советская ул", build: "6"},
{street: "Советская ул", build: "8"},
{street: "Советская ул", build: "8А"},
{street: "Советская ул", build: "9"},
{street: "Сосновая ул", build: "7_ETTH"},
{street: "Сосновая ул", build: "8_ETTH"},
{street: "Сосновая ул", build: "9_ETTH"},
{street: "Ставропольская ул", build: "2"},
{street: "Ставропольская ул", build: "3"},
{street: "Ставропольская ул", build: "7"},
{street: "Строителей Проезд ", build: "2_ETTH"},
{street: "Строителей Проезд ", build: "3_ETTH"},
{street: "Строителей Проезд ", build: "4_ETTH"},
{street: "Строителей Проезд ", build: "7_ETTH"},
{street: "Строителей Проезд ", build: "9_ETTH"},
{street: "Студенческая ул", build: "1/1"},
{street: "Студенческая ул", build: "1/2"},
{street: "Студенческая ул", build: "10"},
{street: "Студенческая ул", build: "11"},
{street: "Студенческая ул", build: "12"},
{street: "Студенческая ул", build: "13"},
{street: "Студенческая ул", build: "14"},
{street: "Студенческая ул", build: "14/2"},
{street: "Студенческая ул", build: "15"},
{street: "Студенческая ул", build: "16"},
{street: "Студенческая ул", build: "16/2"},
{street: "Студенческая ул", build: "18"},
{street: "Студенческая ул", build: "18/2"},
{street: "Студенческая ул", build: "19"},
{street: "Студенческая ул", build: "21"},
{street: "Студенческая ул", build: "9"},
{street: "Тайбинцев ул", build: "36"},
{street: "Толстого ул", build: "1"},
{street: "Толстого ул", build: "3"},
{street: "Толстого ул", build: "5"},
{street: "Толстого ул", build: "7"},
{street: "Толстого ул", build: "9"},
{street: "Томская ул", build: "10"},
{street: "Томская ул", build: "14"},
{street: "Томская ул", build: "16"},
{street: "Томская ул", build: "17"},
{street: "Томская ул", build: "18"},
{street: "Томская ул", build: "19"},
{street: "Томская ул", build: "21"},
{street: "Томская ул", build: "23"},
{street: "Томская ул", build: "25_ETTH"},
{street: "Томская ул", build: "3"},
{street: "Томская ул", build: "4"},
{street: "Томская ул", build: "5"},
{street: "Томская ул", build: "6"},
{street: "Томская ул", build: "7"},
{street: "Томская ул", build: "8"},
{street: "Томская ул", build: "9"},
{street: "Транспортная ул", build: "7"},
{street: "Транспортная ул", build: "9"},
{street: "Транспортный пер ", build: "1"},
{street: "Транспортный пер ", build: "4_ETTH"},
{street: "Транспортный пер ", build: "6"},
{street: "Транспортный пер ", build: "8"},
{street: "Трудовая ул", build: "16"},
{street: "Трудовая ул", build: "20"},
{street: "Трудовая ул", build: "22"},
{street: "Трудовая ул", build: "22А"},
{street: "Трудовая ул", build: "22Б"},
{street: "Трудовая ул", build: "23"},
{street: "Трудовая ул", build: "6"},
{street: "Тульская ул", build: "13"},
{street: "Тульская ул", build: "15"},
{street: "Тульская ул", build: "20_ETTH"},
{street: "Тульская ул", build: "21_ETTH"},
{street: "Тульская ул", build: "23_ETTH"},
{street: "Тульская ул", build: "5"},
{street: "Тульская ул", build: "7"},
{street: "Унжакова ул", build: "10"},
{street: "Унжакова ул", build: "12"},
{street: "Унжакова ул", build: "14"},
{street: "Унжакова ул", build: "16"},
{street: "Унжакова ул", build: "18"},
{street: "Унжакова ул", build: "19"},
{street: "Унжакова ул", build: "3"},
{street: "Унжакова ул", build: "5"},
{street: "Унжакова ул", build: "6"},
{street: "Унжакова ул", build: "9"},
{street: "Ускатная ул", build: "17_ETTH"},
{street: "Ускатная ул", build: "17А_ETTH"},
{street: "Ускатная ул", build: "23_ETTH"},
{street: "Ускатная ул", build: "25_ETTH"},
{street: "Ускатная ул", build: "27А_ETTH"},
{street: "Ускатная ул", build: "33_ETTH"},
{street: "Ускатная ул", build: "35_ETTH"},
{street: "Ускатная ул", build: "37_ETTH"},
{street: "Ускатная ул", build: "4_ETTH"},
{street: "Ускатная ул", build: "5_ETTH"},
{street: "Утренняя ул", build: "1_ETTH"},
{street: "Утренняя ул", build: "1А_ETTH"},
{street: "Утренняя ул", build: "2_ETTH"},
{street: "Утренняя ул", build: "3_ETTH"},
{street: "Утренняя ул", build: "4_ETTH"},
{street: "Утренняя ул", build: "4/2_ETTH"},
{street: "Утренняя ул", build: "5_ETTH"},
{street: "Утренняя ул", build: "6_ETTH"},
{street: "Утренняя ул", build: "6/2_ETTH"},
{street: "Утренняя ул", build: "6/3_ETTH"},
{street: "Утренняя ул", build: "6/4_ETTH"},
{street: "Фадеева ул", build: "10А_ETTH"},
{street: "Фадеева ул", build: "10Б_ETTH"},
{street: "Фадеева ул", build: "10В_ETTH"},
{street: "Фадеева ул", build: "12А_ETTH"},
{street: "Фадеева ул", build: "14Б_ETTH"},
{street: "Фадеева ул", build: "16Б_ETTH"},
{street: "Фадеева ул", build: "6В_ETTH"},
{street: "Фадеева ул", build: "6А_ETTH"},
{street: "Фадеева ул", build: "6Б_ETTH"},
{street: "Фадеева ул", build: "8А_ETTH"},
{street: "Фадеева ул", build: "8Б_ETTH"},
{street: "Чайковского ул", build: "1"},
{street: "Черноморская ул", build: "17/2"},
{street: "Черноморская ул", build: "21"},
{street: "Черноморская ул", build: "21/2"},
{street: "Черноморская ул", build: "23"},
{street: "Черноморская ул", build: "23/2"},
{street: "Черноморская ул", build: "25/2"},
{street: "Черноморская ул", build: "27"},
{street: "Черноморская ул", build: "29"},
{street: "Черноморская ул", build: "31"},
{street: "Черноморская ул", build: "31/2"},
{street: "Черняховского ул", build: "17_ETTH"},
{street: "Черняховского ул", build: "2"},
{street: "Чумова ул", build: "1"},
{street: "Чумова ул", build: "15"},
{street: "Чумова ул", build: "19"},
{street: "Чумова ул", build: "21"},
{street: "Чумова ул", build: "27"},
{street: "Чумова ул", build: "29"},
{street: "Чумова ул", build: "3"},
{street: "Чумова ул", build: "31"},
{street: "Чумова ул", build: "42"},
{street: "Чумова ул", build: "5"},
], streets: [{street: "1 Мая пер "},
{street: "1 Мая ул"},
{street: "50 Лет Города ул"},
{street: "50 Лет Октября ул"},
{street: "Багратиона ул"},
{street: "Боевая ул"},
{street: "Большая Дачная ул"},
{street: "Большевистская ул"},
{street: "Вахрушева ул"},
{street: "Весенняя ул"},
{street: "Водопроводная ул"},
{street: "Гагарина ул"},
{street: "Гормашевская ул"},
{street: "Дзержинского ул"},
{street: "Дружбы ул"},
{street: "Забайкальская ул"},
{street: "Загаражная ул"},
{street: "Западный Проезд "},
{street: "Землячки ул"},
{street: "И.Черных ул"},
{street: "Инженерная ул"},
{street: "Казанская ул"},
{street: "Калинина ул"},
{street: "Кирова ул"},
{street: "Кирпичный пер "},
{street: "Киселевская ул"},
{street: "Коваленко ул"},
{street: "Комсомольский пр "},
{street: "Красина ул"},
{street: "Культурная ул"},
{street: "Ленина ул"},
{street: "Лутугина ул"},
{street: "Майкопская ул"},
{street: "Макарова ул"},
{street: "Матросова ул"},
{street: "Маяковского ул"},
{street: "Мира ул"},
{street: "Московская ул"},
{street: "Мурманский пер "},
{street: "Новостройка ул"},
{street: "Одесская ул"},
{street: "Охотская ул"},
{street: "Панфилова ул"},
{street: "Пионерская ул"},
{street: "Полевая ул"},
{street: "Прогрессивная ул"},
{street: "Прогрессивный Проезд "},
{street: "Промышленная ул"},
{street: "Путейская ул"},
{street: "Ращупкина ул"},
{street: "Рейдовая ул"},
{street: "Садовая ул"},
{street: "Сандалова ул"},
{street: "Седова ул"},
{street: "Советская ул"},
{street: "Сосновая ул"},
{street: "Ставропольская ул"},
{street: "Строителей Проезд "},
{street: "Студенческая ул"},
{street: "Тайбинцев ул"},
{street: "Толстого ул"},
{street: "Томская ул"},
{street: "Транспортная ул"},
{street: "Транспортный пер "},
{street: "Трудовая ул"},
{street: "Тульская ул"},
{street: "Унжакова ул"},
{street: "Ускатная ул"},
{street: "Утренняя ул"},
{street: "Фадеева ул"},
{street: "Чайковского ул"},
{street: "Черноморская ул"},
{street: "Черняховского ул"},
{street: "Чумова ул"},
] };
