city_streets["leninsk"] = {builds: [{street: "7 Ноября ул", build: "1"},
{street: "8 Марта ул", build: "26"},
{street: "8 Марта ул", build: "28"},
{street: "8 Марта ул", build: "31"},
{street: "8 Марта ул", build: "32"},
{street: "8 Марта ул", build: "33"},
{street: "8 Марта ул", build: "35"},
{street: "Абрамцева ул", build: "11А"},
{street: "Абрамцева ул", build: "13"},
{street: "Абрамцева ул", build: "23"},
{street: "Абрамцева ул", build: "25"},
{street: "Абрамцева ул", build: "27"},
{street: "Абрамцева ул", build: "27А"},
{street: "Абрамцева ул", build: "29"},
{street: "Белинского ул", build: "21"},
{street: "Белинского ул", build: "5"},
{street: "Белинского ул", build: "7"},
{street: "Васильева ул", build: "12"},
{street: "Васильева ул", build: "13"},
{street: "Васильева ул", build: "14"},
{street: "Васильева ул", build: "3"},
{street: "Васильева ул", build: "5"},
{street: "Васильева ул", build: "7"},
{street: "Васильева ул", build: "9"},
{street: "Водопьянова пер ", build: "14"},
{street: "Вокзальная ул", build: "24"},
{street: "Гагарина ул", build: "11"},
{street: "Гагарина ул", build: "12"},
{street: "Гагарина ул", build: "13"},
{street: "Гагарина ул", build: "4"},
{street: "Гагарина ул", build: "8"},
{street: "Гагарина ул", build: "9"},
{street: "Гастелло пер ", build: "4"},
{street: "Гастелло пер ", build: "6"},
{street: "Гастелло пер ", build: "9"},
{street: "Горького ул", build: "10"},
{street: "Горького ул", build: "12"},
{street: "Горького ул", build: "19"},
{street: "Горького ул", build: "2"},
{street: "Горького ул", build: "24"},
{street: "Горького ул", build: "26"},
{street: "Горького ул", build: "28"},
{street: "Горького ул", build: "28а"},
{street: "Горького ул", build: "39"},
{street: "Горького ул", build: "4"},
{street: "Горького ул", build: "40"},
{street: "Горького ул", build: "41"},
{street: "Горького ул", build: "45"},
{street: "Горького ул", build: "47"},
{street: "Горького ул", build: "49"},
{street: "Горького ул", build: "51"},
{street: "Горького ул", build: "53"},
{street: "Григорченкова ул", build: "1"},
{street: "Григорченкова ул", build: "3"},
{street: "Григорченкова ул", build: "31"},
{street: "Григорченкова ул", build: "31а"},
{street: "Григорченкова ул", build: "31б"},
{street: "Григорченкова ул", build: "33"},
{street: "Григорченкова ул", build: "33а"},
{street: "Григорченкова ул", build: "35"},
{street: "Григорченкова ул", build: "37"},
{street: "Григорченкова ул", build: "37а"},
{street: "Григорченкова ул", build: "39"},
{street: "Григорченкова ул", build: "43"},
{street: "Григорченкова ул", build: "51"},
{street: "Григорченкова ул", build: "53"},
{street: "Гризодубовой ул", build: "2"},
{street: "Демьяновская ул", build: "2А"},
{street: "Демьяновская ул", build: "4А"},
{street: "Днепровская ", build: "1А"},
{street: "Зварыгина ул", build: "1"},
{street: "Зварыгина ул", build: "10"},
{street: "Зварыгина ул", build: "10а"},
{street: "Зварыгина ул", build: "12"},
{street: "Зварыгина ул", build: "14"},
{street: "Зварыгина ул", build: "15"},
{street: "Зварыгина ул", build: "16"},
{street: "Зварыгина ул", build: "16а"},
{street: "Зварыгина ул", build: "18"},
{street: "Зварыгина ул", build: "2"},
{street: "Зварыгина ул", build: "20"},
{street: "Зварыгина ул", build: "22"},
{street: "Зварыгина ул", build: "4"},
{street: "Зварыгина ул", build: "4а"},
{street: "Зварыгина ул", build: "5"},
{street: "Зварыгина ул", build: "8"},
{street: "Зварыгина ул", build: "8а"},
{street: "Земцова ул", build: "10"},
{street: "Земцова ул", build: "3"},
{street: "Земцова ул", build: "3а"},
{street: "Земцова ул", build: "6а"},
{street: "Земцова ул", build: "7"},
{street: "Земцова ул", build: "8"},
{street: "Земцова ул", build: "8а"},
{street: "Зои Космодемьянской ул", build: "19"},
{street: "Зои Космодемьянской ул", build: "21"},
{street: "Зорина ул", build: "1"},
{street: "Зорина ул", build: "7Б"},
{street: "Им Мациенко ул", build: "3"},
{street: "Им Мациенко ул", build: "5"},
{street: "Иртышская ул", build: "11"},
{street: "Иртышская ул", build: "13"},
{street: "Калинина ул", build: "1"},
{street: "Кирова пр ", build: "1"},
{street: "Кирова пр ", build: "100"},
{street: "Кирова пр ", build: "100а"},
{street: "Кирова пр ", build: "100б"},
{street: "Кирова пр ", build: "102"},
{street: "Кирова пр ", build: "108"},
{street: "Кирова пр ", build: "108а"},
{street: "Кирова пр ", build: "108б"},
{street: "Кирова пр ", build: "110"},
{street: "Кирова пр ", build: "112"},
{street: "Кирова пр ", build: "114"},
{street: "Кирова пр ", build: "116"},
{street: "Кирова пр ", build: "120"},
{street: "Кирова пр ", build: "122"},
{street: "Кирова пр ", build: "124"},
{street: "Кирова пр ", build: "126"},
{street: "Кирова пр ", build: "16"},
{street: "Кирова пр ", build: "18"},
{street: "Кирова пр ", build: "1а"},
{street: "Кирова пр ", build: "2"},
{street: "Кирова пр ", build: "20"},
{street: "Кирова пр ", build: "21"},
{street: "Кирова пр ", build: "26"},
{street: "Кирова пр ", build: "28"},
{street: "Кирова пр ", build: "29"},
{street: "Кирова пр ", build: "30"},
{street: "Кирова пр ", build: "32"},
{street: "Кирова пр ", build: "34а"},
{street: "Кирова пр ", build: "34б"},
{street: "Кирова пр ", build: "38"},
{street: "Кирова пр ", build: "39"},
{street: "Кирова пр ", build: "42"},
{street: "Кирова пр ", build: "46"},
{street: "Кирова пр ", build: "47а"},
{street: "Кирова пр ", build: "47б"},
{street: "Кирова пр ", build: "48"},
{street: "Кирова пр ", build: "49"},
{street: "Кирова пр ", build: "5"},
{street: "Кирова пр ", build: "51"},
{street: "Кирова пр ", build: "51а"},
{street: "Кирова пр ", build: "51б"},
{street: "Кирова пр ", build: "52"},
{street: "Кирова пр ", build: "54"},
{street: "Кирова пр ", build: "58"},
{street: "Кирова пр ", build: "60"},
{street: "Кирова пр ", build: "62"},
{street: "Кирова пр ", build: "67"},
{street: "Кирова пр ", build: "69"},
{street: "Кирова пр ", build: "69а"},
{street: "Кирова пр ", build: "7"},
{street: "Кирова пр ", build: "71"},
{street: "Кирова пр ", build: "71а"},
{street: "Кирова пр ", build: "75"},
{street: "Кирова пр ", build: "75а"},
{street: "Кирова пр ", build: "77"},
{street: "Кирова пр ", build: "79"},
{street: "Кирова пр ", build: "79а"},
{street: "Кирова пр ", build: "81"},
{street: "Кирова пр ", build: "83"},
{street: "Кирова пр ", build: "83а"},
{street: "Кирова пр ", build: "87"},
{street: "Кирова пр ", build: "87а"},
{street: "Кирова пр ", build: "88"},
{street: "Кирова пр ", build: "88а"},
{street: "Кирова пр ", build: "89"},
{street: "Кирова пр ", build: "90"},
{street: "Кирова пр ", build: "90а"},
{street: "Кирова пр ", build: "91"},
{street: "Кирова пр ", build: "92"},
{street: "Кирова пр ", build: "93"},
{street: "Кирова пр ", build: "93а"},
{street: "Кирова пр ", build: "95"},
{street: "Кирова пр ", build: "96"},
{street: "Кирова пр ", build: "96а"},
{street: "Кирова пр ", build: "97"},
{street: "Кирова пр ", build: "98"},
{street: "Клюева Бульвар ", build: "3"},
{street: "Клюева Бульвар ", build: "4"},
{street: "Клюева Бульвар ", build: "5/1"},
{street: "Кольцова ул", build: "5"},
{street: "Кольцова ул", build: "6"},
{street: "Кольчугинский пр ", build: "3"},
{street: "Кольчугинский пр ", build: "5"},
{street: "Кольчугинский пр ", build: "5/3"},
{street: "Коростылева ул", build: "11"},
{street: "Коростылева ул", build: "12"},
{street: "Коростылева ул", build: "13"},
{street: "Коростылева ул", build: "17"},
{street: "Коростылева ул", build: "3"},
{street: "Коростылева ул", build: "7"},
{street: "Коростылева ул", build: "9"},
{street: "Красноармейская ул", build: "1"},
{street: "Крупина пер ", build: "20"},
{street: "Крупина пер ", build: "21"},
{street: "Крупина пер ", build: "29"},
{street: "Крупина пер ", build: "29А"},
{street: "Крупина пер ", build: "30"},
{street: "Крупина пер ", build: "32"},
{street: "Кузбасская ул", build: "108/1"},
{street: "Кузбасская ул", build: "108/2"},
{street: "Кузбасская ул", build: "108/3"},
{street: "Кузбасская ул", build: "110/1"},
{street: "Кузбасская ул", build: "110/3"},
{street: "Кузбасская ул", build: "112/3"},
{street: "Кузбасская ул", build: "114/1"},
{street: "Кузбасская ул", build: "120А"},
{street: "Кузбасская ул", build: "131А"},
{street: "Кузбасская ул", build: "131Б"},
{street: "Кузбасский пер ", build: "12"},
{street: "Кузбасский пер ", build: "12А"},
{street: "Кузбасский пер ", build: "12Б"},
{street: "Кузбасский пер ", build: "12В"},
{street: "Кузбасский пер ", build: "14"},
{street: "Кутузова ул", build: "1"},
{street: "Кутузова ул", build: "3"},
{street: "Кутузова ул", build: "4"},
{street: "Кутузова ул", build: "5"},
{street: "Кутузова ул", build: "6"},
{street: "Кутузова ул", build: "7"},
{street: "Левитана ул", build: "30"},
{street: "Левитана ул", build: "34"},
{street: "Левитана ул", build: "42"},
{street: "Ленина пр ", build: "1"},
{street: "Ленина пр ", build: "13а"},
{street: "Ленина пр ", build: "13б"},
{street: "Ленина пр ", build: "17"},
{street: "Ленина пр ", build: "19"},
{street: "Ленина пр ", build: "21"},
{street: "Ленина пр ", build: "21а"},
{street: "Ленина пр ", build: "23"},
{street: "Ленина пр ", build: "25"},
{street: "Ленина пр ", build: "26"},
{street: "Ленина пр ", build: "28"},
{street: "Ленина пр ", build: "29"},
{street: "Ленина пр ", build: "2б"},
{street: "Ленина пр ", build: "30"},
{street: "Ленина пр ", build: "31"},
{street: "Ленина пр ", build: "33"},
{street: "Ленина пр ", build: "37"},
{street: "Ленина пр ", build: "39"},
{street: "Ленина пр ", build: "4"},
{street: "Ленина пр ", build: "43б"},
{street: "Ленина пр ", build: "45"},
{street: "Ленина пр ", build: "47"},
{street: "Ленина пр ", build: "48"},
{street: "Ленина пр ", build: "48а"},
{street: "Ленина пр ", build: "49"},
{street: "Ленина пр ", build: "5"},
{street: "Ленина пр ", build: "50"},
{street: "Ленина пр ", build: "50а"},
{street: "Ленина пр ", build: "51"},
{street: "Ленина пр ", build: "53/1"},
{street: "Ленина пр ", build: "53/2"},
{street: "Ленина пр ", build: "53/3"},
{street: "Ленина пр ", build: "53а"},
{street: "Ленина пр ", build: "54"},
{street: "Ленина пр ", build: "55/1"},
{street: "Ленина пр ", build: "56"},
{street: "Ленина пр ", build: "57/1"},
{street: "Ленина пр ", build: "57/3"},
{street: "Ленина пр ", build: "57б"},
{street: "Ленина пр ", build: "58"},
{street: "Ленина пр ", build: "58а"},
{street: "Ленина пр ", build: "58б"},
{street: "Ленина пр ", build: "59/1"},
{street: "Ленина пр ", build: "59/2"},
{street: "Ленина пр ", build: "59/3"},
{street: "Ленина пр ", build: "6"},
{street: "Ленина пр ", build: "60"},
{street: "Ленина пр ", build: "60а"},
{street: "Ленина пр ", build: "61/1"},
{street: "Ленина пр ", build: "63/2"},
{street: "Ленина пр ", build: "63/3"},
{street: "Ленина пр ", build: "63/4"},
{street: "Ленина пр ", build: "65"},
{street: "Ленина пр ", build: "67/1"},
{street: "Ленина пр ", build: "67/2"},
{street: "Ленина пр ", build: "67/3"},
{street: "Ленина пр ", build: "67/4"},
{street: "Ленина пр ", build: "69"},
{street: "Ленина пр ", build: "70а"},
{street: "Ленина пр ", build: "71"},
{street: "Ленина пр ", build: "72а"},
{street: "Ленина пр ", build: "74"},
{street: "Ленина пр ", build: "75/2"},
{street: "Ленина пр ", build: "76"},
{street: "Ленина пр ", build: "76а"},
{street: "Ленина пр ", build: "78"},
{street: "Ленина пр ", build: "80"},
{street: "Ленина пр ", build: "80а"},
{street: "Ленина пр ", build: "82"},
{street: "Ленина пр ", build: "82/1"},
{street: "Ленина пр ", build: "84"},
{street: "Ленина пр ", build: "86"},
{street: "Ленина пр ", build: "88"},
{street: "Ленина пр ", build: "88/2"},
{street: "Ленина пр ", build: "90/1"},
{street: "Ленина пр ", build: "90/2"},
{street: "Ленская ул", build: "11"},
{street: "Ленская ул", build: "7"},
{street: "Ленская ул", build: "9"},
{street: "Ленский пер ", build: "1"},
{street: "Ленский пер ", build: "2"},
{street: "Ленский пер ", build: "3"},
{street: "Ленский пер ", build: "4"},
{street: "Ленский пер ", build: "5"},
{street: "Ленский пер ", build: "6"},
{street: "Лермонтова ул", build: "4"},
{street: "Лесной Городок ул", build: "1"},
{street: "Лесной Городок ул", build: "10"},
{street: "Лесной Городок ул", build: "11"},
{street: "Лесной Городок ул", build: "12"},
{street: "Лесной Городок ул", build: "13"},
{street: "Лесной Городок ул", build: "14"},
{street: "Лесной Городок ул", build: "15"},
{street: "Лесной Городок ул", build: "16"},
{street: "Лесной Городок ул", build: "17"},
{street: "Лесной Городок ул", build: "18"},
{street: "Лесной Городок ул", build: "19"},
{street: "Лесной Городок ул", build: "2"},
{street: "Лесной Городок ул", build: "20"},
{street: "Лесной Городок ул", build: "21"},
{street: "Лесной Городок ул", build: "22"},
{street: "Лесной Городок ул", build: "23"},
{street: "Лесной Городок ул", build: "24"},
{street: "Лесной Городок ул", build: "25"},
{street: "Лесной Городок ул", build: "27"},
{street: "Лесной Городок ул", build: "28"},
{street: "Лесной Городок ул", build: "29"},
{street: "Лесной Городок ул", build: "29а"},
{street: "Лесной Городок ул", build: "3"},
{street: "Лесной Городок ул", build: "4"},
{street: "Лесной Городок ул", build: "5"},
{street: "Лесной Городок ул", build: "6"},
{street: "Лесной Городок ул", build: "7"},
{street: "Лесной Городок ул", build: "8"},
{street: "Лесной Городок ул", build: "9"},
{street: "Ломоносова ул", build: "1"},
{street: "Ломоносова ул", build: "2"},
{street: "Ломоносова ул", build: "4"},
{street: "Ломоносова ул", build: "6"},
{street: "Менделеева ул", build: "1"},
{street: "Менделеева ул", build: "12"},
{street: "Менделеева ул", build: "14"},
{street: "Менделеева ул", build: "15"},
{street: "Менделеева ул", build: "18"},
{street: "Менделеева ул", build: "19"},
{street: "Менделеева ул", build: "20"},
{street: "Менделеева ул", build: "21"},
{street: "Менделеева ул", build: "22"},
{street: "Менделеева ул", build: "25"},
{street: "Менделеева ул", build: "3"},
{street: "Менделеева ул", build: "4"},
{street: "Менделеева ул", build: "5"},
{street: "Менделеева ул", build: "7"},
{street: "Микрорайон N7 ул", build: "1"},
{street: "Микрорайон N7 ул", build: "2"},
{street: "Микрорайон N7 ул", build: "3"},
{street: "Микрорайон N7 ул", build: "4"},
{street: "Микрорайон N7 ул", build: "5"},
{street: "Мусохранова ул", build: "1"},
{street: "Мусохранова ул", build: "7"},
{street: "Нахимова ул", build: "26"},
{street: "Нахимова ул", build: "30"},
{street: "Новокировский Проезд ул", build: "10а"},
{street: "Новокировский Проезд ул", build: "11"},
{street: "Новокировский Проезд ул", build: "12"},
{street: "Новокировский Проезд ул", build: "13"},
{street: "Новокировский Проезд ул", build: "14"},
{street: "Новокировский Проезд ул", build: "15"},
{street: "Новокировский Проезд ул", build: "16"},
{street: "Новокировский Проезд ул", build: "17"},
{street: "Новокировский Проезд ул", build: "18"},
{street: "Новокировский Проезд ул", build: "19"},
{street: "Новокировский Проезд ул", build: "20"},
{street: "Новокировский Проезд ул", build: "3"},
{street: "Новокировский Проезд ул", build: "3а"},
{street: "Новокировский Проезд ул", build: "4"},
{street: "Новокировский Проезд ул", build: "7а"},
{street: "Новокировский Проезд ул", build: "8"},
{street: "Новокировский Проезд ул", build: "9"},
{street: "Новокировский Проезд ул", build: "9а"},
{street: "Пирогова ул", build: "11"},
{street: "Пирогова ул", build: "11/2"},
{street: "Пирогова ул", build: "13"},
{street: "Пирогова ул", build: "14"},
{street: "Пирогова ул", build: "16"},
{street: "Пирогова ул", build: "18"},
{street: "Пирогова ул", build: "2"},
{street: "Пирогова ул", build: "2/3"},
{street: "Пирогова ул", build: "20"},
{street: "Пирогова ул", build: "22"},
{street: "Пирогова ул", build: "4"},
{street: "Пирогова ул", build: "4/1"},
{street: "Пирогова ул", build: "4/3"},
{street: "Пирогова ул", build: "4/4"},
{street: "Пирогова ул", build: "6"},
{street: "Пирогова ул", build: "6/4"},
{street: "Пирогова ул", build: "9"},
{street: "Пирогова ул", build: "9/1"},
{street: "Пушкина ул", build: "1"},
{street: "Пушкина ул", build: "10"},
{street: "Пушкина ул", build: "11"},
{street: "Пушкина ул", build: "11а"},
{street: "Пушкина ул", build: "12"},
{street: "Пушкина ул", build: "13"},
{street: "Пушкина ул", build: "14"},
{street: "Пушкина ул", build: "15"},
{street: "Пушкина ул", build: "19"},
{street: "Пушкина ул", build: "19а"},
{street: "Пушкина ул", build: "1а"},
{street: "Пушкина ул", build: "2"},
{street: "Пушкина ул", build: "21"},
{street: "Пушкина ул", build: "3"},
{street: "Пушкина ул", build: "3а"},
{street: "Пушкина ул", build: "4"},
{street: "Пушкина ул", build: "5"},
{street: "Пушкина ул", build: "6"},
{street: "Пушкина ул", build: "64/1"},
{street: "Пушкина ул", build: "66"},
{street: "Пушкина ул", build: "68"},
{street: "Пушкина ул", build: "70"},
{street: "Пушкина ул", build: "72"},
{street: "Пушкина ул", build: "74"},
{street: "Пушкина ул", build: "76"},
{street: "Пушкина ул", build: "8"},
{street: "Пушкина ул", build: "80"},
{street: "Пушкина ул", build: "82"},
{street: "Пушкина ул", build: "84"},
{street: "Пушкина ул", build: "88"},
{street: "Розы Люксембург ул", build: "21"},
{street: "Розы Люксембург ул", build: "27"},
{street: "Розы Люксембург ул", build: "29"},
{street: "Розы Люксембург ул", build: "37"},
{street: "Розы Люксембург ул", build: "39"},
{street: "Розы Люксембург ул", build: "41"},
{street: "Розы Люксембург ул", build: "43"},
{street: "Розы Люксембург ул", build: "47"},
{street: "Рядовой пер ", build: "10"},
{street: "Рядовой пер ", build: "11/1"},
{street: "Рядовой пер ", build: "6"},
{street: "Спасстанция ул", build: "14"},
{street: "Спасстанция ул", build: "16"},
{street: "Спасстанция ул", build: "20"},
{street: "Спасстанция ул", build: "24"},
{street: "Спасстанция ул", build: "28"},
{street: "Спасстанция ул", build: "2а"},
{street: "Спасстанция ул", build: "30"},
{street: "Спасстанция ул", build: "4"},
{street: "Спасстанция ул", build: "4а"},
{street: "Спасстанция ул", build: "6"},
{street: "Спасстанция ул", build: "8б"},
{street: "Суворова Проезд ", build: "1"},
{street: "Суворова Проезд ", build: "10"},
{street: "Суворова Проезд ", build: "2"},
{street: "Суворова Проезд ", build: "3"},
{street: "Суворова Проезд ", build: "4"},
{street: "Суворова Проезд ", build: "9"},
{street: "Суворова ул", build: "10"},
{street: "Суворова ул", build: "12/1"},
{street: "Суворова ул", build: "12/2"},
{street: "Суворова ул", build: "129"},
{street: "Суворова ул", build: "12а"},
{street: "Суворова ул", build: "14"},
{street: "Суворова ул", build: "16"},
{street: "Суворова ул", build: "215"},
{street: "Суворова ул", build: "234"},
{street: "Суворова ул", build: "236"},
{street: "Суворова ул", build: "236а"},
{street: "Суворова ул", build: "270"},
{street: "Суворова ул", build: "272"},
{street: "Суворова ул", build: "5"},
{street: "Суворова ул", build: "6"},
{street: "Суворова ул", build: "7"},
{street: "Суворова ул", build: "7А"},
{street: "Суворова ул", build: "8"},
{street: "Суворова ул", build: "9"},
{street: "Текстильщиков пр ", build: "1/1"},
{street: "Текстильщиков пр ", build: "10"},
{street: "Текстильщиков пр ", build: "11/1"},
{street: "Текстильщиков пр ", build: "11/2"},
{street: "Текстильщиков пр ", build: "12"},
{street: "Текстильщиков пр ", build: "14/1"},
{street: "Текстильщиков пр ", build: "14/2"},
{street: "Текстильщиков пр ", build: "14/3"},
{street: "Текстильщиков пр ", build: "2/1"},
{street: "Текстильщиков пр ", build: "3/1"},
{street: "Текстильщиков пр ", build: "3/2"},
{street: "Текстильщиков пр ", build: "4/1"},
{street: "Текстильщиков пр ", build: "4/2"},
{street: "Текстильщиков пр ", build: "5/1"},
{street: "Текстильщиков пр ", build: "6/1"},
{street: "Текстильщиков пр ", build: "7/1"},
{street: "Текстильщиков пр ", build: "7/2"},
{street: "Текстильщиков пр ", build: "7/3"},
{street: "Текстильщиков пр ", build: "7/4"},
{street: "Текстильщиков пр ", build: "8/1"},
{street: "Текстильщиков пр ", build: "9/1"},
{street: "Текстильщиков пр ", build: "9/2"},
{street: "Текстильщиков пр ", build: "9/3"},
{street: "Текстильщиков пр ", build: "9/4"},
{street: "Толбухина ул", build: "28"},
{street: "Толбухина ул", build: "28а"},
{street: "Толбухина ул", build: "32"},
{street: "Толбухина ул", build: "37"},
{street: "Толбухина ул", build: "43а"},
{street: "Топкинская ул", build: "10/1"},
{street: "Топкинская ул", build: "10/2"},
{street: "Топкинская ул", build: "14"},
{street: "Топкинская ул", build: "144/1"},
{street: "Топкинская ул", build: "144/2"},
{street: "Топкинская ул", build: "144/3"},
{street: "Топкинская ул", build: "148/1"},
{street: "Топкинская ул", build: "148/2"},
{street: "Топкинская ул", build: "148/3"},
{street: "Топкинская ул", build: "150/1"},
{street: "Топкинская ул", build: "153"},
{street: "Топкинская ул", build: "155"},
{street: "Топкинская ул", build: "156Б"},
{street: "Топкинская ул", build: "16"},
{street: "Топкинская ул", build: "160А"},
{street: "Топкинская ул", build: "18"},
{street: "Топкинская ул", build: "6/1"},
{street: "Топкинская ул", build: "6/2"},
{street: "Топкинская ул", build: "6/3"},
{street: "Трестовский пер ", build: "3"},
{street: "Трестовский пер ", build: "7"},
{street: "Трестовский пер ", build: "9"},
{street: "Туснолобовой ул", build: "27"},
{street: "Туснолобовой ул", build: "29"},
{street: "Туснолобовой ул", build: "31"},
{street: "Узловая ул", build: "1"},
{street: "Узловая ул", build: "3"},
{street: "Ульяновская ул", build: "3"},
{street: "Ульяновская ул", build: "4"},
{street: "Химиков Бульвар ", build: "10/1"},
{street: "Химиков Бульвар ", build: "10/2"},
{street: "Химиков Бульвар ", build: "10/3"},
{street: "Химиков Бульвар ", build: "12"},
{street: "Химиков Бульвар ", build: "3"},
{street: "Химиков Бульвар ", build: "3/1"},
{street: "Химиков Бульвар ", build: "4"},
{street: "Химиков Бульвар ", build: "5"},
{street: "Химиков Бульвар ", build: "6"},
{street: "Химиков Бульвар ", build: "7"},
{street: "Химиков Бульвар ", build: "7/2А"},
{street: "Химиков Бульвар ", build: "7/2Б"},
{street: "Химиков Бульвар ", build: "7/2В"},
{street: "Химиков Бульвар ", build: "7/3"},
{street: "Химиков Бульвар ", build: "7/4"},
{street: "Химиков Бульвар ", build: "8/1"},
{street: "Химиков Бульвар ", build: "9/1"},
{street: "Химиков Бульвар ", build: "9/2"},
{street: "Химиков Бульвар ", build: "9/3"},
{street: "Чекмарева ул", build: "13"},
{street: "Чекмарева ул", build: "17"},
{street: "Чекмарева ул", build: "19"},
{street: "Чекмарева ул", build: "21"},
{street: "Чекмарева ул", build: "23"},
{street: "Чекмарева ул", build: "28"},
{street: "Чекмарева ул", build: "28а"},
{street: "Чекмарева ул", build: "30"},
{street: "Чекмарева ул", build: "32"},
{street: "Чекмарева ул", build: "34"},
{street: "Чекмарева ул", build: "36"},
{street: "Шевцовой ул", build: "1"},
{street: "Шевцовой ул", build: "10"},
{street: "Шевцовой ул", build: "3"},
{street: "Шевцовой ул", build: "8"},
{street: "Шилина ул", build: "13"},
{street: "Шилина ул", build: "15"},
{street: "Шилина ул", build: "17"},
{street: "Шилина ул", build: "21"},
{street: "Шилина ул", build: "6"},
{street: "Шилина ул", build: "7"},
{street: "Шишлянникова ул", build: "1"},
{street: "Шишлянникова ул", build: "12"},
{street: "Шишлянникова ул", build: "14"},
{street: "Шишлянникова ул", build: "2"},
{street: "Шишлянникова ул", build: "3"},
{street: "Шишлянникова ул", build: "5а"},
{street: "Шишлянникова ул", build: "9"},
{street: "Энгельса ул", build: "1"},
{street: "Энгельса ул", build: "10"},
{street: "Энгельса ул", build: "5"},
{street: "Энгельса ул", build: "8"},
{street: "Юргинская ул", build: "10"},
{street: "Юргинская ул", build: "14"},
{street: "Юргинская ул", build: "4/1"},
{street: "Юргинская ул", build: "4/2"},
{street: "Юргинская ул", build: "6"},
{street: "Юргинская ул", build: "8"},
], streets: [{street: "7 Ноября ул"},
{street: "8 Марта ул"},
{street: "Абрамцева ул"},
{street: "Белинского ул"},
{street: "Васильева ул"},
{street: "Водопьянова пер "},
{street: "Вокзальная ул"},
{street: "Гагарина ул"},
{street: "Гастелло пер "},
{street: "Горького ул"},
{street: "Григорченкова ул"},
{street: "Гризодубовой ул"},
{street: "Демьяновская ул"},
{street: "Днепровская "},
{street: "Зварыгина ул"},
{street: "Земцова ул"},
{street: "Зои Космодемьянской ул"},
{street: "Зорина ул"},
{street: "Им Мациенко ул"},
{street: "Иртышская ул"},
{street: "Калинина ул"},
{street: "Кирова пр "},
{street: "Клюева Бульвар "},
{street: "Кольцова ул"},
{street: "Кольчугинский пр "},
{street: "Коростылева ул"},
{street: "Красноармейская ул"},
{street: "Крупина пер "},
{street: "Кузбасская ул"},
{street: "Кузбасский пер "},
{street: "Кутузова ул"},
{street: "Левитана ул"},
{street: "Ленина пр "},
{street: "Ленская ул"},
{street: "Ленский пер "},
{street: "Лермонтова ул"},
{street: "Лесной Городок ул"},
{street: "Ломоносова ул"},
{street: "Менделеева ул"},
{street: "Микрорайон N7 ул"},
{street: "Мусохранова ул"},
{street: "Нахимова ул"},
{street: "Новокировский Проезд ул"},
{street: "Пирогова ул"},
{street: "Пушкина ул"},
{street: "Розы Люксембург ул"},
{street: "Рядовой пер "},
{street: "Спасстанция ул"},
{street: "Суворова Проезд "},
{street: "Суворова ул"},
{street: "Текстильщиков пр "},
{street: "Толбухина ул"},
{street: "Топкинская ул"},
{street: "Трестовский пер "},
{street: "Туснолобовой ул"},
{street: "Узловая ул"},
{street: "Ульяновская ул"},
{street: "Химиков Бульвар "},
{street: "Чекмарева ул"},
{street: "Шевцовой ул"},
{street: "Шилина ул"},
{street: "Шишлянникова ул"},
{street: "Энгельса ул"},
{street: "Юргинская ул"},
] };
