city_streets["mariinsk"] = {builds: [{street: "1 Микрорайон ул", build: "1"},
{street: "27 Дивизии ул", build: "34"},
{street: "40 Лет Победы ул", build: "2"},
{street: "40 Лет Победы ул", build: "2Б"},
{street: "40 Лет Победы ул", build: "6"},
{street: "40 Лет Победы ул", build: "8А"},
{street: "50 Лет Октября ул", build: "105"},
{street: "50 Лет Октября ул", build: "71"},
{street: "50 Лет Октября ул", build: "71А"},
{street: "50 Лет Октября ул", build: "73"},
{street: "50 Лет Октября ул", build: "75"},
{street: "50 Лет Октября ул", build: "77"},
{street: "50 Лет Октября ул", build: "79"},
{street: "5-Й Микрорайон ", build: "10"},
{street: "5-Й Микрорайон ", build: "12"},
{street: "5-Й Микрорайон ", build: "4/1"},
{street: "5-Й Микрорайон ", build: "6"},
{street: "5-Й Микрорайон ", build: "8"},
{street: "Алтайская ул", build: "8"},
{street: "Амурская ул", build: "4А"},
{street: "Антибесская ул", build: "12"},
{street: "Базовый пер ", build: "1"},
{street: "Базовый пер ", build: "10/1"},
{street: "Базовый пер ", build: "1а"},
{street: "Базовый пер ", build: "3а"},
{street: "Базовый пер ", build: "6"},
{street: "Базовый пер ", build: "8"},
{street: "Веселая ул", build: "1"},
{street: "Веселая ул", build: "1а"},
{street: "Веселая ул", build: "4"},
{street: "Водопроводная ул", build: "2"},
{street: "Водопроводная ул", build: "2а"},
{street: "Водопроводный пер ", build: "4"},
{street: "Вокзальная ул", build: "2"},
{street: "Вокзальная ул", build: "20"},
{street: "Вокзальная ул", build: "22"},
{street: "Вокзальная ул", build: "24"},
{street: "Вокзальная ул", build: "2А"},
{street: "Вокзальная ул", build: "2Б"},
{street: "Вокзальная ул", build: "3"},
{street: "Добролюбова ул", build: "12"},
{street: "Добролюбова ул", build: "14"},
{street: "Добролюбова ул", build: "16"},
{street: "Дорожная ул", build: "11"},
{street: "Дорожная ул", build: "13"},
{street: "Дорожная ул", build: "15"},
{street: "Дорожная ул", build: "1в"},
{street: "Дорожная ул", build: "24"},
{street: "Дорожная ул", build: "26"},
{street: "Дорожная ул", build: "3"},
{street: "Дорожная ул", build: "5"},
{street: "Дорожная ул", build: "64"},
{street: "Дорожная ул", build: "7"},
{street: "Дорожная ул", build: "9"},
{street: "Достоевского ул", build: "10"},
{street: "Достоевского ул", build: "10А"},
{street: "Достоевского ул", build: "10Б"},
{street: "Достоевского ул", build: "14"},
{street: "Достоевского ул", build: "3"},
{street: "Достоевского ул", build: "4"},
{street: "Достоевского ул", build: "5"},
{street: "Достоевского ул", build: "6"},
{street: "Енисейская ул", build: "11"},
{street: "Енисейская ул", build: "13"},
{street: "Енисейская ул", build: "2"},
{street: "Енисейская ул", build: "3"},
{street: "Енисейская ул", build: "4"},
{street: "Енисейская ул", build: "5"},
{street: "Енисейская ул", build: "6"},
{street: "Енисейская ул", build: "7"},
{street: "Енисейская ул", build: "8"},
{street: "Енисейская ул", build: "9"},
{street: "Железнодорожная ул", build: "3"},
{street: "Железнодорожная ул", build: "3Б"},
{street: "К.Маркса ул", build: "17А"},
{street: "К.Маркса ул", build: "6"},
{street: "Кирпичная ул", build: "1а"},
{street: "Кирпичная ул", build: "3"},
{street: "Клубный пер ", build: "1б"},
{street: "Кольцова ул", build: "10"},
{street: "Кольцова ул", build: "20"},
{street: "Коммунистическая ул", build: "60"},
{street: "Коммунистическая ул", build: "83"},
{street: "Коммунистическая ул", build: "91"},
{street: "Котовского ул", build: "10"},
{street: "Котовского ул", build: "12"},
{street: "Котовского ул", build: "13"},
{street: "Котовского ул", build: "14"},
{street: "Котовского ул", build: "14А"},
{street: "Котовского ул", build: "15"},
{street: "Котовского ул", build: "16"},
{street: "Котовского ул", build: "16А"},
{street: "Котовского ул", build: "17"},
{street: "Котовского ул", build: "18"},
{street: "Котовского ул", build: "4Д"},
{street: "Котовского ул", build: "7"},
{street: "Котовского ул", build: "8"},
{street: "Котовского ул", build: "88"},
{street: "Ленина ул", build: "105"},
{street: "Ленина ул", build: "2"},
{street: "Ленина ул", build: "36"},
{street: "Ленина ул", build: "42"},
{street: "Ленина ул", build: "46"},
{street: "Ленина ул", build: "46А"},
{street: "Ленина ул", build: "46Б"},
{street: "Ленина ул", build: "47"},
{street: "Ленина ул", build: "48"},
{street: "Ленина ул", build: "49"},
{street: "Ленина ул", build: "51"},
{street: "Ленина ул", build: "77"},
{street: "Линейный пер ", build: "3"},
{street: "Линейный пер ", build: "4"},
{street: "Линейный пер ", build: "5"},
{street: "Линейный пер ", build: "6"},
{street: "Макаренко пер ", build: "1Б"},
{street: "Макаренко ул", build: "13"},
{street: "Макаренко ул", build: "15"},
{street: "Макаренко ул", build: "17"},
{street: "Макаренко ул", build: "19"},
{street: "Макаренко ул", build: "21"},
{street: "Макаренко ул", build: "23"},
{street: "Макаренко ул", build: "25"},
{street: "Макаренко ул", build: "27"},
{street: "Макаренко ул", build: "29"},
{street: "Макаренко ул", build: "34а"},
{street: "Макаренко ул", build: "7а"},
{street: "Макаренко ул", build: "9"},
{street: "Макаренко ул", build: "9А"},
{street: "Набережная ул", build: "124"},
{street: "Набережная ул", build: "126"},
{street: "Набережная ул", build: "128"},
{street: "Набережная ул", build: "132"},
{street: "Набережная ул", build: "136"},
{street: "Набережная ул", build: "140"},
{street: "Набережная ул", build: "142"},
{street: "Набережная ул", build: "149"},
{street: "Набережная ул", build: "151"},
{street: "Набережная ул", build: "153"},
{street: "Набережная ул", build: "157"},
{street: "Нагорная ул", build: "4а"},
{street: "Наумова пер ", build: "1а"},
{street: "Наумова ул", build: "10"},
{street: "Новая ул", build: "1а"},
{street: "Новая ул", build: "2"},
{street: "Новая ул", build: "2а"},
{street: "Ноградский пер ", build: "1"},
{street: "Ноградский пер ", build: "10"},
{street: "Ноградский пер ", build: "5"},
{street: "Ноградский пер ", build: "8"},
{street: "Островского ул", build: "2"},
{street: "Пальчикова ул", build: "1а"},
{street: "Пальчикова ул", build: "1б"},
{street: "Пальчикова ул", build: "1в"},
{street: "Пальчикова ул", build: "1г"},
{street: "Пальчикова ул", build: "1Ж"},
{street: "Пальчикова ул", build: "24"},
{street: "Пальчикова ул", build: "28Б"},
{street: "Пальчикова ул", build: "30"},
{street: "Пальчикова ул", build: "32а"},
{street: "Пальчикова ул", build: "34"},
{street: "Пальчикова ул", build: "36"},
{street: "Пальчикова ул", build: "64"},
{street: "Пальчикова ул", build: "77"},
{street: "Пальчикова ул", build: "8а"},
{street: "Покрышкина ул", build: "11"},
{street: "Покрышкина ул", build: "13"},
{street: "Покрышкина ул", build: "15"},
{street: "Покрышкина ул", build: "16"},
{street: "Покрышкина ул", build: "17"},
{street: "Покрышкина ул", build: "18"},
{street: "Покрышкина ул", build: "19"},
{street: "Покрышкина ул", build: "20"},
{street: "Покрышкина ул", build: "21"},
{street: "Покрышкина ул", build: "23"},
{street: "Покрышкина ул", build: "25"},
{street: "Покрышкина ул", build: "5"},
{street: "Покрышкина ул", build: "7"},
{street: "Покрышкина ул", build: "9"},
{street: "Рабочая ул", build: "11"},
{street: "Рабочая ул", build: "13"},
{street: "Романцова ул", build: "13"},
{street: "Романцова ул", build: "15"},
{street: "Романцова ул", build: "17"},
{street: "Романцова ул", build: "19"},
{street: "С.Лазо ул", build: "39Б"},
{street: "С.Лазо ул", build: "41Б"},
{street: "Сибиряков Гвардейцев ул", build: "1"},
{street: "Сибиряков Гвардейцев ул", build: "13"},
{street: "Сибиряков Гвардейцев ул", build: "2"},
{street: "Сибиряков Гвардейцев ул", build: "2А"},
{street: "Сибиряков Гвардейцев ул", build: "2В"},
{street: "Сибиряков Гвардейцев ул", build: "2Г"},
{street: "Сибиряков Гвардейцев ул", build: "3"},
{street: "Сибиряков Гвардейцев ул", build: "5"},
{street: "Советская ул", build: "1"},
{street: "Советская ул", build: "18"},
{street: "Советская ул", build: "2"},
{street: "Трудовая ул", build: "10"},
{street: "Тургенева ул", build: "31"},
{street: "Тургенева ул", build: "33"},
{street: "Тургенева ул", build: "35"},
{street: "Чкалова ул", build: "39"},
{street: "Чкалова ул", build: "41"},
{street: "Чкалова ул", build: "43"},
{street: "Чкалова ул", build: "45"},
{street: "Чкалова ул", build: "47"},
{street: "Чкалова ул", build: "49"},
{street: "Энгельса ул", build: "1"},
{street: "Энгельса ул", build: "2"},
{street: "Энгельса ул", build: "3"},
{street: "Энгельса ул", build: "4"},
{street: "Энгельса ул", build: "5"},
{street: "Энгельса ул", build: "7"},
{street: "Энгельса ул", build: "9"},
{street: "Юбилейная ул", build: "11"},
{street: "Юбилейная ул", build: "12"},
{street: "Юбилейная ул", build: "13"},
{street: "Юбилейная ул", build: "14"},
{street: "Юбилейная ул", build: "16а"},
{street: "Юбилейная ул", build: "18"},
{street: "Юбилейная ул", build: "18/1"},
{street: "Юбилейная ул", build: "18а"},
{street: "Юбилейная ул", build: "20а"},
{street: "Юбилейная ул", build: "24А"},
{street: "Юбилейная ул", build: "28А"},
{street: "Юбилейная ул", build: "28А/1"},
{street: "Юбилейная ул", build: "3Б"},
{street: "Юбилейная ул", build: "4а"},
{street: "Юбилейная ул", build: "4б"},
{street: "Юбилейная ул", build: "8"},
{street: "Юбилейная ул", build: "8а"},
{street: "Юбилейная ул", build: "8б"},
{street: "Южная ул", build: "3"},
{street: "Южная ул", build: "5А/2"},
{street: "Южная ул", build: "5А/1"},
], streets: [{street: "1 Микрорайон ул"},
{street: "27 Дивизии ул"},
{street: "40 Лет Победы ул"},
{street: "50 Лет Октября ул"},
{street: "5-Й Микрорайон "},
{street: "Алтайская ул"},
{street: "Амурская ул"},
{street: "Антибесская ул"},
{street: "Базовый пер "},
{street: "Веселая ул"},
{street: "Водопроводная ул"},
{street: "Водопроводный пер "},
{street: "Вокзальная ул"},
{street: "Добролюбова ул"},
{street: "Дорожная ул"},
{street: "Достоевского ул"},
{street: "Енисейская ул"},
{street: "Железнодорожная ул"},
{street: "К.Маркса ул"},
{street: "Кирпичная ул"},
{street: "Клубный пер "},
{street: "Кольцова ул"},
{street: "Коммунистическая ул"},
{street: "Котовского ул"},
{street: "Ленина ул"},
{street: "Линейный пер "},
{street: "Макаренко пер "},
{street: "Макаренко ул"},
{street: "Набережная ул"},
{street: "Нагорная ул"},
{street: "Наумова пер "},
{street: "Наумова ул"},
{street: "Новая ул"},
{street: "Ноградский пер "},
{street: "Островского ул"},
{street: "Пальчикова ул"},
{street: "Покрышкина ул"},
{street: "Рабочая ул"},
{street: "Романцова ул"},
{street: "С.Лазо ул"},
{street: "Сибиряков Гвардейцев ул"},
{street: "Советская ул"},
{street: "Трудовая ул"},
{street: "Тургенева ул"},
{street: "Чкалова ул"},
{street: "Энгельса ул"},
{street: "Юбилейная ул"},
{street: "Южная ул"},
] };
