city_streets["mejdurechensk"] = {builds: [{street: "50 Лет Комсомола пр ", build: "22"},
{street: "50 Лет Комсомола пр ", build: "23"},
{street: "50 Лет Комсомола пр ", build: "24"},
{street: "50 Лет Комсомола пр ", build: "44"},
{street: "50 Лет Комсомола пр ", build: "46"},
{street: "50 Лет Комсомола пр ", build: "48"},
{street: "50 Лет Комсомола пр ", build: "50"},
{street: "50 Лет Комсомола пр ", build: "52"},
{street: "Брянская ул", build: "11"},
{street: "Брянская ул", build: "12"},
{street: "Брянская ул", build: "12А"},
{street: "Брянская ул", build: "14"},
{street: "Брянская ул", build: "18"},
{street: "Брянская ул", build: "20"},
{street: "Брянская ул", build: "22"},
{street: "Брянская ул", build: "24"},
{street: "Брянская ул", build: "26"},
{street: "Брянская ул", build: "4"},
{street: "Брянская ул", build: "5"},
{street: "Брянская ул", build: "6"},
{street: "Брянская ул", build: "7"},
{street: "Брянская ул", build: "9"},
{street: "Весенняя ул", build: "10"},
{street: "Весенняя ул", build: "11"},
{street: "Весенняя ул", build: "12"},
{street: "Весенняя ул", build: "13"},
{street: "Весенняя ул", build: "20"},
{street: "Весенняя ул", build: "22"},
{street: "Весенняя ул", build: "3"},
{street: "Весенняя ул", build: "4"},
{street: "Весенняя ул", build: "5"},
{street: "Весенняя ул", build: "7"},
{street: "Весенняя ул", build: "8"},
{street: "Вокзальная ул", build: "66А"},
{street: "Вокзальная ул", build: "70"},
{street: "Гончаренко ул", build: "1"},
{street: "Гончаренко ул", build: "2"},
{street: "Гончаренко ул", build: "5"},
{street: "Дзержинского ул", build: "12"},
{street: "Дзержинского ул", build: "14"},
{street: "Дзержинского ул", build: "16"},
{street: "Дзержинского ул", build: "18"},
{street: "Дзержинского ул", build: "22"},
{street: "Дзержинского ул", build: "26"},
{street: "Дзержинского ул", build: "7"},
{street: "Карташова ул", build: "2"},
{street: "Карташова ул", build: "4"},
{street: "Коммунистический пр ", build: "10"},
{street: "Коммунистический пр ", build: "12"},
{street: "Коммунистический пр ", build: "14"},
{street: "Коммунистический пр ", build: "16"},
{street: "Коммунистический пр ", build: "18"},
{street: "Коммунистический пр ", build: "19"},
{street: "Коммунистический пр ", build: "20"},
{street: "Коммунистический пр ", build: "21"},
{street: "Коммунистический пр ", build: "22"},
{street: "Коммунистический пр ", build: "24"},
{street: "Коммунистический пр ", build: "25"},
{street: "Коммунистический пр ", build: "26"},
{street: "Коммунистический пр ", build: "27"},
{street: "Коммунистический пр ", build: "28"},
{street: "Коммунистический пр ", build: "29"},
{street: "Коммунистический пр ", build: "30"},
{street: "Коммунистический пр ", build: "31"},
{street: "Коммунистический пр ", build: "33"},
{street: "Коммунистический пр ", build: "36"},
{street: "Коммунистический пр ", build: "44"},
{street: "Коммунистический пр ", build: "6"},
{street: "Коммунистический пр ", build: "8"},
{street: "Космонавтов ул", build: "10"},
{street: "Космонавтов ул", build: "16"},
{street: "Космонавтов ул", build: "4"},
{street: "Космонавтов ул", build: "7"},
{street: "Космонавтов ул", build: "8"},
{street: "Космонавтов ул", build: "9"},
{street: "Кузнецкая ул", build: "4"},
{street: "Кузнецкая ул", build: "48"},
{street: "Кузнецкая ул", build: "5"},
{street: "Кузнецкая ул", build: "50"},
{street: "Лазо ул", build: "31"},
{street: "Лазо ул", build: "35"},
{street: "Лазо ул", build: "37"},
{street: "Лазо ул", build: "38"},
{street: "Лазо ул", build: "39"},
{street: "Лазо ул", build: "40"},
{street: "Лазо ул", build: "46"},
{street: "Лазо ул", build: "48"},
{street: "Лазо ул", build: "50"},
{street: "Лазо ул", build: "52"},
{street: "Лазо ул", build: "54"},
{street: "Лукиянова ул", build: "1"},
{street: "Лукиянова ул", build: "11"},
{street: "Лукиянова ул", build: "13"},
{street: "Лукиянова ул", build: "15"},
{street: "Лукиянова ул", build: "17"},
{street: "Лукиянова ул", build: "19"},
{street: "Лукиянова ул", build: "21"},
{street: "Лукиянова ул", build: "23"},
{street: "Лукиянова ул", build: "27"},
{street: "Лукиянова ул", build: "4А"},
{street: "Лукиянова ул", build: "5"},
{street: "Лукиянова ул", build: "6"},
{street: "Лукиянова ул", build: "7"},
{street: "Лукиянова ул", build: "9"},
{street: "Медиков Бульвар ", build: "10"},
{street: "Медиков Бульвар ", build: "12"},
{street: "Медиков Бульвар ", build: "14"},
{street: "Медиков Бульвар ", build: "18"},
{street: "Медиков Бульвар ", build: "8"},
{street: "Октябрьская ул", build: "14"},
{street: "Октябрьская ул", build: "20"},
{street: "Октябрьская ул", build: "27"},
{street: "Октябрьская ул", build: "29"},
{street: "Октябрьская ул", build: "31"},
{street: "Пушкина ул", build: "29"},
{street: "Пушкина ул", build: "34"},
{street: "Пушкина ул", build: "38"},
{street: "Пушкина ул", build: "69"},
{street: "Пушкина ул", build: "69А"},
{street: "Строителей пр ", build: "1"},
{street: "Строителей пр ", build: "19"},
{street: "Строителей пр ", build: "21"},
{street: "Строителей пр ", build: "25"},
{street: "Строителей пр ", build: "26"},
{street: "Строителей пр ", build: "28"},
{street: "Строителей пр ", build: "3"},
{street: "Строителей пр ", build: "30"},
{street: "Строителей пр ", build: "32"},
{street: "Строителей пр ", build: "33"},
{street: "Строителей пр ", build: "35"},
{street: "Строителей пр ", build: "37"},
{street: "Строителей пр ", build: "38"},
{street: "Строителей пр ", build: "39"},
{street: "Строителей пр ", build: "41"},
{street: "Строителей пр ", build: "43"},
{street: "Строителей пр ", build: "45"},
{street: "Строителей пр ", build: "47"},
{street: "Строителей пр ", build: "49"},
{street: "Строителей пр ", build: "51"},
{street: "Строителей пр ", build: "53"},
{street: "Строителей пр ", build: "55"},
{street: "Строителей пр ", build: "57"},
{street: "Строителей пр ", build: "61"},
{street: "Строителей пр ", build: "63"},
{street: "Строителей пр ", build: "67"},
{street: "Строителей пр ", build: "69"},
{street: "Строителей пр ", build: "71"},
{street: "Строителей пр ", build: "73"},
{street: "Строителей пр ", build: "9"},
{street: "Шахтеров пр ", build: "1"},
{street: "Шахтеров пр ", build: "11"},
{street: "Шахтеров пр ", build: "15"},
{street: "Шахтеров пр ", build: "17"},
{street: "Шахтеров пр ", build: "19"},
{street: "Шахтеров пр ", build: "21"},
{street: "Шахтеров пр ", build: "23"},
{street: "Шахтеров пр ", build: "25"},
{street: "Шахтеров пр ", build: "27"},
{street: "Шахтеров пр ", build: "29"},
{street: "Шахтеров пр ", build: "3"},
{street: "Шахтеров пр ", build: "31"},
{street: "Шахтеров пр ", build: "33"},
{street: "Шахтеров пр ", build: "35"},
{street: "Шахтеров пр ", build: "37"},
{street: "Шахтеров пр ", build: "39"},
{street: "Шахтеров пр ", build: "4"},
{street: "Шахтеров пр ", build: "43"},
{street: "Шахтеров пр ", build: "45"},
{street: "Шахтеров пр ", build: "47"},
{street: "Шахтеров пр ", build: "49"},
{street: "Шахтеров пр ", build: "51"},
{street: "Шахтеров пр ", build: "53"},
{street: "Шахтеров пр ", build: "55"},
{street: "Шахтеров пр ", build: "57"},
{street: "Шахтеров пр ", build: "61"},
{street: "Шахтеров пр ", build: "63"},
{street: "Шахтеров пр ", build: "7"},
{street: "Шахтеров пр ", build: "9"},
{street: "Юдина ул", build: "11"},
{street: "Юдина ул", build: "12"},
{street: "Юности ул", build: "3"},
{street: "Юности ул", build: "5"},
], streets: [{street: "50 Лет Комсомола пр "},
{street: "Брянская ул"},
{street: "Весенняя ул"},
{street: "Вокзальная ул"},
{street: "Гончаренко ул"},
{street: "Дзержинского ул"},
{street: "Карташова ул"},
{street: "Коммунистический пр "},
{street: "Космонавтов ул"},
{street: "Кузнецкая ул"},
{street: "Лазо ул"},
{street: "Лукиянова ул"},
{street: "Медиков Бульвар "},
{street: "Октябрьская ул"},
{street: "Пушкина ул"},
{street: "Строителей пр "},
{street: "Шахтеров пр "},
{street: "Юдина ул"},
{street: "Юности ул"},
] };
