city_streets["miski"] = {builds: [{street: "10-Й КВАРТАЛ ", build: "2"},
{street: "10-Й КВАРТАЛ ", build: "3"},
{street: "10-Й КВАРТАЛ ", build: " 1А"},
{street: "11-Й КВАРТАЛ ", build: "1"},
{street: "11-Й КВАРТАЛ ", build: "3"},
{street: "11-Й КВАРТАЛ ", build: "4"},
{street: "17-Й КВАРТАЛ ", build: "1"},
{street: "17-Й КВАРТАЛ ", build: "4"},
{street: "17-Й КВАРТАЛ ", build: "5"},
{street: "17-Й КВАРТАЛ ", build: "6"},
{street: "17-Й КВАРТАЛ ", build: "7"},
{street: "17-Й КВАРТАЛ ", build: "8"},
{street: "17-Й КВАРТАЛ ", build: "9"},
{street: "17-Й КВАРТАЛ ", build: "10"},
{street: "17-Й КВАРТАЛ ", build: "11"},
{street: "17-Й КВАРТАЛ ", build: "12"},
{street: "17-Й КВАРТАЛ ", build: "13"},
{street: "17-Й КВАРТАЛ ", build: "14"},
{street: "17-Й КВАРТАЛ ", build: "17"},
{street: "17-Й КВАРТАЛ ", build: "18"},
{street: "17-Й КВАРТАЛ ", build: "19"},
{street: "17-Й КВАРТАЛ ", build: "20"},
{street: "17-Й КВАРТАЛ ", build: " 21А"},
{street: "17-Й КВАРТАЛ ", build: " 21Б"},
{street: "18-Й КВАРТАЛ ", build: "1"},
{street: "18-Й КВАРТАЛ ", build: "2"},
{street: "18-Й КВАРТАЛ ", build: "3"},
{street: "18-Й КВАРТАЛ ", build: "4"},
{street: "18-Й КВАРТАЛ ", build: "5"},
{street: "18-Й КВАРТАЛ ", build: "6"},
{street: "18-Й КВАРТАЛ ", build: "18"},
{street: "18-Й КВАРТАЛ ", build: "19"},
{street: "18-Й КВАРТАЛ ", build: "20"},
{street: "18-Й КВАРТАЛ ", build: " 2А"},
{street: "18-Й КВАРТАЛ ", build: " 6А"},
{street: "4-Й КВАРТАЛ ", build: "6"},
{street: "4-Й КВАРТАЛ ", build: "12"},
{street: "4-Й КВАРТАЛ ", build: "13"},
{street: "4-Й КВАРТАЛ ", build: "14"},
{street: "4-Й КВАРТАЛ ", build: "16"},
{street: "50 ЛЕТ ПИОНЕРИИ УЛИЦА ", build: "2"},
{street: "50 ЛЕТ ПИОНЕРИИ УЛИЦА ", build: "4"},
{street: "50 ЛЕТ ПИОНЕРИИ УЛИЦА ", build: "6"},
{street: "50 ЛЕТ ПИОНЕРИИ УЛИЦА ", build: "8"},
{street: "8-Й КВАРТАЛ ", build: "4"},
{street: "8-Й КВАРТАЛ ", build: "5"},
{street: "8-Й КВАРТАЛ ", build: "6"},
{street: "9-Й КВАРТАЛ ", build: "1"},
{street: "9-Й КВАРТАЛ ", build: "2"},
{street: "9-Й КВАРТАЛ ", build: "3"},
{street: "9-Й КВАРТАЛ ", build: "4"},
{street: "9-Й КВАРТАЛ ", build: "6"},
{street: "9-Й КВАРТАЛ ", build: "7"},
{street: "9-Й КВАРТАЛ ", build: "8"},
{street: "9-Й КВАРТАЛ ", build: "9"},
{street: "9-Й КВАРТАЛ ", build: "10"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "5"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "7"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "15"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "21"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "22"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "23"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "24"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "25"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "27"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "28"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "29"},
{street: "ВАХРУШЕВА УЛИЦА ", build: "31"},
{street: "ВАХРУШЕВА УЛИЦА ", build: " 21А"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "1"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "5"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "7"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "11"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "13"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "17"},
{street: "ВОСТОЧНАЯ УЛИЦА ", build: "19"},
{street: "ВОСТОЧНАЯ УЛИЦА ", build: "20"},
{street: "ВОСТОЧНАЯ УЛИЦА ", build: "37"},
{street: "ГАГАРИНА УЛИЦА ", build: "3"},
{street: "ГАГАРИНА УЛИЦА ", build: "9"},
{street: "ГОРЬКОГО УЛИЦА ", build: "6"},
{street: "ГОРЬКОГО УЛИЦА ", build: "12"},
{street: "ГОРЬКОГО УЛИЦА ", build: "23"},
{street: "ГОРЬКОГО УЛИЦА ", build: "31"},
{street: "ГОРЬКОГО УЛИЦА ", build: "36"},
{street: "ГОРЬКОГО УЛИЦА ", build: "38"},
{street: "ГОРЬКОГО УЛИЦА ", build: "40"},
{street: "КОМАРОВА УЛИЦА ", build: "1"},
{street: "КОМАРОВА УЛИЦА ", build: "4"},
{street: "КОМАРОВА УЛИЦА ", build: "5"},
{street: "КОМАРОВА УЛИЦА ", build: "6"},
{street: "КОМАРОВА УЛИЦА ", build: "10"},
{street: "КОМАРОВА УЛИЦА ", build: "16"},
{street: "КОМАРОВА УЛИЦА ", build: "38"},
{street: "КОМАРОВА УЛИЦА ", build: "40"},
{street: "КУЗБАССКАЯ УЛИЦА ", build: "14"},
{street: "КУЗБАССКАЯ УЛИЦА ", build: "18"},
{street: "КУЗБАССКАЯ УЛИЦА ", build: "20"},
{street: "КУЗНЕЦКАЯ УЛИЦА ", build: "1"},
{street: "КУЗНЕЦКАЯ УЛИЦА ", build: "2"},
{street: "КУЗНЕЦКАЯ УЛИЦА ", build: "3"},
{street: "КУЗНЕЦКАЯ УЛИЦА ", build: "4"},
{street: "КУЗНЕЦКАЯ УЛИЦА ", build: "5"},
{street: "КУЗНЕЦКАЯ УЛИЦА ", build: "7"},
{street: "КУЗНЕЦКАЯ УЛИЦА ", build: "9"},
{street: "КУСУРГАШЕВА УЛИЦА ", build: "1"},
{street: "КУСУРГАШЕВА УЛИЦА ", build: "3"},
{street: "КУСУРГАШЕВА УЛИЦА ", build: "5"},
{street: "КУСУРГАШЕВА УЛИЦА ", build: "7"},
{street: "КУСУРГАШЕВА УЛИЦА ", build: "9"},
{street: "КУСУРГАШЕВА УЛИЦА ", build: "11"},
{street: "КУТУЗОВА УЛИЦА ", build: "15"},
{street: "КУТУЗОВА УЛИЦА ", build: "17"},
{street: "КУТУЗОВА УЛИЦА ", build: "21"},
{street: "КУЮКОВА УЛИЦА ", build: "4"},
{street: "КУЮКОВА УЛИЦА ", build: "6"},
{street: "ЛЕНИНА УЛИЦА ", build: "10"},
{street: "ЛЕНИНГРАДСКАЯ УЛИЦА ", build: "1"},
{street: "МИРА УЛИЦА ", build: "1"},
{street: "МИРА УЛИЦА ", build: "3"},
{street: "МИРА УЛИЦА ", build: "13"},
{street: "МИРА УЛИЦА ", build: "26"},
{street: "МИРА УЛИЦА ", build: "28"},
{street: "МИРА УЛИЦА ", build: "30"},
{street: "МИРА УЛИЦА ", build: "38"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "4"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "5"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "6"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "8"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "11"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "24"},
{street: "ОЛИМПИЙСКАЯ УЛИЦА ", build: "4"},
{street: "ОЛИМПИЙСКАЯ УЛИЦА ", build: "5"},
{street: "ОЛИМПИЙСКАЯ УЛИЦА ", build: "6"},
{street: "ОЛИМПИЙСКАЯ УЛИЦА ", build: "7"},
{street: "ОЛИМПИЙСКАЯ УЛИЦА ", build: "8"},
{street: "ОЛИМПИЙСКАЯ УЛИЦА ", build: "9"},
{street: "ОЛИМПИЙСКАЯ УЛИЦА ", build: "17"},
{street: "ПЕРВОМАЙСКАЯ УЛИЦА ", build: "9"},
{street: "ПЕРВОМАЙСКАЯ УЛИЦА ", build: "11"},
{street: "ПЕРВОМАЙСКАЯ УЛИЦА ", build: "26"},
{street: "ПЕРВОМАЙСКАЯ УЛИЦА ", build: "28"},
{street: "ПЕРВОМАЙСКАЯ УЛИЦА ", build: "29"},
{street: "ПЕРВОМАЙСКАЯ УЛИЦА ", build: "30"},
{street: "ПУШКИНА УЛИЦА ", build: "2"},
{street: "ПУШКИНА УЛИЦА ", build: "4"},
{street: "ПУШКИНА УЛИЦА ", build: "5"},
{street: "ПУШКИНА УЛИЦА ", build: "11"},
{street: "СЕРАФИМОВИЧА УЛИЦА ", build: "2"},
{street: "СЕРАФИМОВИЧА УЛИЦА ", build: "6"},
{street: "СЕРАФИМОВИЧА УЛИЦА ", build: "12"},
{street: "СЕРАФИМОВИЧА УЛИЦА ", build: "16"},
{street: "СЕРАФИМОВИЧА УЛИЦА ", build: " 6А"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "28"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "30"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "31"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "32"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "34"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "35"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "36"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "39"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "40"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "41"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "42"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "44"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "46"},
{street: "ТЕПЛИЧНЫЙ ПЕРЕУЛОК ", build: "2"},
{street: "ТЕПЛИЧНЫЙ ПЕРЕУЛОК ", build: "3"},
{street: "ТЕПЛИЧНЫЙ ПЕРЕУЛОК ", build: "4"},
{street: "ТЕПЛИЧНЫЙ ПЕРЕУЛОК ", build: "7"},
{street: "ТЕПЛИЧНЫЙ ПЕРЕУЛОК ", build: "12"},
{street: "ТЕПЛИЧНЫЙ ПЕРЕУЛОК ", build: " 5А"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: " 2А"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "20"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "59"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "61"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "63"},
{street: "ЭНЕРГЕТИКОВ УЛИЦА ", build: "8"},
{street: "ЭНЕРГЕТИКОВ УЛИЦА ", build: "13"},
{street: "ЭНЕРГЕТИКОВ УЛИЦА ", build: "14"},
{street: "ЮБИЛЕЙНЫЙ БУЛЬВАР ", build: "4"},
{street: "ЮБИЛЕЙНЫЙ БУЛЬВАР ", build: "9"},
], streets: [{street: "10-Й КВАРТАЛ "},
{street: "11-Й КВАРТАЛ "},
{street: "17-Й КВАРТАЛ "},
{street: "18-Й КВАРТАЛ "},
{street: "4-Й КВАРТАЛ "},
{street: "50 ЛЕТ ПИОНЕРИИ УЛИЦА "},
{street: "8-Й КВАРТАЛ "},
{street: "9-Й КВАРТАЛ "},
{street: "ВОСТОЧНАЯ УЛИЦА "},
{street: "КОМАРОВА УЛИЦА "},
{street: "КУСУРГАШЕВА УЛИЦА "},
{street: "КУЮКОВА УЛИЦА "},
{street: "ЛЕНИНГРАДСКАЯ УЛИЦА "},
{street: "НОГРАДСКАЯ УЛИЦА "},
{street: "ОЛИМПИЙСКАЯ УЛИЦА "},
{street: "СЕРАФИМОВИЧА УЛИЦА "},
{street: "ТЕПЛИЧНЫЙ ПЕРЕУЛОК "},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА "},
{street: "ЭНЕРГЕТИКОВ УЛИЦА "},
{street: "ЮБИЛЕЙНЫЙ БУЛЬВАР "},
] };
