city_streets["miski"] = {builds: [{street: "10-Й Квартал ", build: "1А"},
{street: "10-Й Квартал ", build: "2"},
{street: "10-Й Квартал ", build: "3"},
{street: "11-Й Квартал ", build: "1"},
{street: "11-Й Квартал ", build: "3"},
{street: "11-Й Квартал ", build: "4"},
{street: "17-Й Квартал ", build: "1"},
{street: "17-Й Квартал ", build: "10"},
{street: "17-Й Квартал ", build: "11"},
{street: "17-Й Квартал ", build: "12"},
{street: "17-Й Квартал ", build: "13"},
{street: "17-Й Квартал ", build: "14"},
{street: "17-Й Квартал ", build: "17"},
{street: "17-Й Квартал ", build: "18"},
{street: "17-Й Квартал ", build: "19"},
{street: "17-Й Квартал ", build: "20"},
{street: "17-Й Квартал ", build: "21А"},
{street: "17-Й Квартал ", build: "21Б"},
{street: "17-Й Квартал ", build: "4"},
{street: "17-Й Квартал ", build: "5"},
{street: "17-Й Квартал ", build: "6"},
{street: "17-Й Квартал ", build: "7"},
{street: "17-Й Квартал ", build: "8"},
{street: "17-Й Квартал ", build: "9"},
{street: "18-Й Квартал ", build: "1"},
{street: "18-Й Квартал ", build: "18"},
{street: "18-Й Квартал ", build: "19"},
{street: "18-Й Квартал ", build: "2"},
{street: "18-Й Квартал ", build: "20"},
{street: "18-Й Квартал ", build: "2А"},
{street: "18-Й Квартал ", build: "3"},
{street: "18-Й Квартал ", build: "4"},
{street: "18-Й Квартал ", build: "5"},
{street: "18-Й Квартал ", build: "6"},
{street: "18-Й Квартал ", build: "6А"},
{street: "4-Й Квартал ", build: "12"},
{street: "4-Й Квартал ", build: "13"},
{street: "4-Й Квартал ", build: "14"},
{street: "4-Й Квартал ", build: "16"},
{street: "4-Й Квартал ", build: "6"},
{street: "50 Лет Пионерии ул", build: "2"},
{street: "50 Лет Пионерии ул", build: "4"},
{street: "50 Лет Пионерии ул", build: "6"},
{street: "50 Лет Пионерии ул", build: "8"},
{street: "8-Й Квартал ", build: "4"},
{street: "8-Й Квартал ", build: "5"},
{street: "8-Й Квартал ", build: "6"},
{street: "9-Й Квартал ", build: "1"},
{street: "9-Й Квартал ", build: "10"},
{street: "9-Й Квартал ", build: "2"},
{street: "9-Й Квартал ", build: "3"},
{street: "9-Й Квартал ", build: "4"},
{street: "9-Й Квартал ", build: "6"},
{street: "9-Й Квартал ", build: "7"},
{street: "9-Й Квартал ", build: "8"},
{street: "9-Й Квартал ", build: "9"},
{street: "Вахрушева ул", build: "15"},
{street: "Вахрушева ул", build: "21"},
{street: "Вахрушева ул", build: "21А"},
{street: "Вахрушева ул", build: "22"},
{street: "Вахрушева ул", build: "23"},
{street: "Вахрушева ул", build: "24"},
{street: "Вахрушева ул", build: "25"},
{street: "Вахрушева ул", build: "27"},
{street: "Вахрушева ул", build: "28"},
{street: "Вахрушева ул", build: "29"},
{street: "Вахрушева ул", build: "31"},
{street: "Вахрушева ул", build: "5"},
{street: "Вахрушева ул", build: "7"},
{street: "Вокзальная ул", build: "1"},
{street: "Вокзальная ул", build: "11"},
{street: "Вокзальная ул", build: "13"},
{street: "Вокзальная ул", build: "17"},
{street: "Вокзальная ул", build: "5"},
{street: "Вокзальная ул", build: "7"},
{street: "Восточная ул", build: "19"},
{street: "Восточная ул", build: "20"},
{street: "Восточная ул", build: "37"},
{street: "Гагарина ул", build: "3"},
{street: "Гагарина ул", build: "9"},
{street: "Горького ул", build: "12"},
{street: "Горького ул", build: "23"},
{street: "Горького ул", build: "31"},
{street: "Горького ул", build: "36"},
{street: "Горького ул", build: "38"},
{street: "Горького ул", build: "40"},
{street: "Горького ул", build: "6"},
{street: "Комарова ул", build: "1"},
{street: "Комарова ул", build: "10"},
{street: "Комарова ул", build: "16"},
{street: "Комарова ул", build: "38"},
{street: "Комарова ул", build: "4"},
{street: "Комарова ул", build: "40"},
{street: "Комарова ул", build: "5"},
{street: "Комарова ул", build: "6"},
{street: "Кузбасская ул", build: "14"},
{street: "Кузбасская ул", build: "18"},
{street: "Кузбасская ул", build: "20"},
{street: "Кузнецкая ул", build: "1"},
{street: "Кузнецкая ул", build: "2"},
{street: "Кузнецкая ул", build: "3"},
{street: "Кузнецкая ул", build: "4"},
{street: "Кузнецкая ул", build: "5"},
{street: "Кузнецкая ул", build: "7"},
{street: "Кузнецкая ул", build: "9"},
{street: "Кусургашева ул", build: "1"},
{street: "Кусургашева ул", build: "11"},
{street: "Кусургашева ул", build: "3"},
{street: "Кусургашева ул", build: "5"},
{street: "Кусургашева ул", build: "7"},
{street: "Кусургашева ул", build: "9"},
{street: "Кутузова ул", build: "15"},
{street: "Кутузова ул", build: "17"},
{street: "Кутузова ул", build: "21"},
{street: "Куюкова ул", build: "4"},
{street: "Куюкова ул", build: "6"},
{street: "Ленина ул", build: "10"},
{street: "Ленинградская ул", build: "1"},
{street: "Мира ул", build: "1"},
{street: "Мира ул", build: "13"},
{street: "Мира ул", build: "26"},
{street: "Мира ул", build: "28"},
{street: "Мира ул", build: "3"},
{street: "Мира ул", build: "30"},
{street: "Мира ул", build: "38"},
{street: "Ноградская ул", build: "11"},
{street: "Ноградская ул", build: "24"},
{street: "Ноградская ул", build: "4"},
{street: "Ноградская ул", build: "5"},
{street: "Ноградская ул", build: "6"},
{street: "Ноградская ул", build: "8"},
{street: "Олимпийская ул", build: "17"},
{street: "Олимпийская ул", build: "4"},
{street: "Олимпийская ул", build: "5"},
{street: "Олимпийская ул", build: "6"},
{street: "Олимпийская ул", build: "7"},
{street: "Олимпийская ул", build: "8"},
{street: "Олимпийская ул", build: "9"},
{street: "Первомайская ул", build: "11"},
{street: "Первомайская ул", build: "26"},
{street: "Первомайская ул", build: "28"},
{street: "Первомайская ул", build: "29"},
{street: "Первомайская ул", build: "30"},
{street: "Первомайская ул", build: "9"},
{street: "Пушкина ул", build: "11"},
{street: "Пушкина ул", build: "2"},
{street: "Пушкина ул", build: "4"},
{street: "Пушкина ул", build: "5"},
{street: "Серафимовича ул", build: "12"},
{street: "Серафимовича ул", build: "16"},
{street: "Серафимовича ул", build: "2"},
{street: "Серафимовича ул", build: "6"},
{street: "Серафимовича ул", build: "6А"},
{street: "Советская ул", build: "28"},
{street: "Советская ул", build: "30"},
{street: "Советская ул", build: "31"},
{street: "Советская ул", build: "32"},
{street: "Советская ул", build: "34"},
{street: "Советская ул", build: "35"},
{street: "Советская ул", build: "36"},
{street: "Советская ул", build: "39"},
{street: "Советская ул", build: "40"},
{street: "Советская ул", build: "41"},
{street: "Советская ул", build: "42"},
{street: "Советская ул", build: "44"},
{street: "Советская ул", build: "46"},
{street: "Тепличный пер ", build: "12"},
{street: "Тепличный пер ", build: "2"},
{street: "Тепличный пер ", build: "3"},
{street: "Тепличный пер ", build: "4"},
{street: "Тепличный пер ", build: "5А"},
{street: "Тепличный пер ", build: "7"},
{street: "Транспортная ул", build: "2А"},
{street: "Центральная ул", build: "20"},
{street: "Центральная ул", build: "59"},
{street: "Центральная ул", build: "61"},
{street: "Центральная ул", build: "63"},
{street: "Энергетиков ул", build: "13"},
{street: "Энергетиков ул", build: "14"},
{street: "Энергетиков ул", build: "8"},
{street: "Юбилейный Бульвар ", build: "4"},
{street: "Юбилейный Бульвар ", build: "9"},
], streets: [{street: "10-Й Квартал "},
{street: "11-Й Квартал "},
{street: "17-Й Квартал "},
{street: "18-Й Квартал "},
{street: "4-Й Квартал "},
{street: "50 Лет Пионерии ул"},
{street: "8-Й Квартал "},
{street: "9-Й Квартал "},
{street: "Вахрушева ул"},
{street: "Вокзальная ул"},
{street: "Восточная ул"},
{street: "Гагарина ул"},
{street: "Горького ул"},
{street: "Комарова ул"},
{street: "Кузбасская ул"},
{street: "Кузнецкая ул"},
{street: "Кусургашева ул"},
{street: "Кутузова ул"},
{street: "Куюкова ул"},
{street: "Ленина ул"},
{street: "Ленинградская ул"},
{street: "Мира ул"},
{street: "Ноградская ул"},
{street: "Олимпийская ул"},
{street: "Первомайская ул"},
{street: "Пушкина ул"},
{street: "Серафимовича ул"},
{street: "Советская ул"},
{street: "Тепличный пер "},
{street: "Транспортная ул"},
{street: "Центральная ул"},
{street: "Энергетиков ул"},
{street: "Юбилейный Бульвар "},
] };
