city_streets["novokuzneck"] = {builds: [{street: "1 Мая ул", build: "10А"},
{street: "1 Мая ул", build: "13"},
{street: "1 Мая ул", build: "6"},
{street: "1 Мая ул", build: "8А"},
{street: "11 Гвардейской Армии ул", build: "1_ETTH"},
{street: "11 Гвардейской Армии ул", build: "11_ETTH"},
{street: "11 Гвардейской Армии ул", build: "13_ETTH"},
{street: "11 Гвардейской Армии ул", build: "15_ETTH"},
{street: "11 Гвардейской Армии ул", build: "17_ETTH"},
{street: "11 Гвардейской Армии ул", build: "2_ETTH"},
{street: "11 Гвардейской Армии ул", build: "3"},
{street: "11 Гвардейской Армии ул", build: "4_ETTH"},
{street: "11 Гвардейской Армии ул", build: "5_ETTH"},
{street: "11 Гвардейской Армии ул", build: "6_ETTH"},
{street: "11 Гвардейской Армии ул", build: "8_ETTH"},
{street: "25 Лет Октября ул", build: "1"},
{street: "25 Лет Октября ул", build: "2"},
{street: "25 Лет Октября ул", build: "21"},
{street: "40 Лет Влксм ул", build: "100"},
{street: "40 Лет Влксм ул", build: "102"},
{street: "40 Лет Влксм ул", build: "104"},
{street: "40 Лет Влксм ул", build: "106А"},
{street: "40 Лет Влксм ул", build: "106Б"},
{street: "40 Лет Влксм ул", build: "108"},
{street: "40 Лет Влксм ул", build: "114"},
{street: "40 Лет Влксм ул", build: "114А"},
{street: "40 Лет Влксм ул", build: "116"},
{street: "40 Лет Влксм ул", build: "116А"},
{street: "40 Лет Влксм ул", build: "116Б"},
{street: "40 Лет Влксм ул", build: "116В"},
{street: "40 Лет Влксм ул", build: "116Г"},
{street: "40 Лет Влксм ул", build: "116Д"},
{street: "40 Лет Влксм ул", build: "118"},
{street: "40 Лет Влксм ул", build: "120"},
{street: "40 Лет Влксм ул", build: "122"},
{street: "40 Лет Влксм ул", build: "124"},
{street: "40 Лет Влксм ул", build: "39"},
{street: "40 Лет Влксм ул", build: "42"},
{street: "40 Лет Влксм ул", build: "44"},
{street: "40 Лет Влксм ул", build: "44А"},
{street: "40 Лет Влксм ул", build: "46"},
{street: "40 Лет Влксм ул", build: "48"},
{street: "40 Лет Влксм ул", build: "50"},
{street: "40 Лет Влксм ул", build: "52"},
{street: "40 Лет Влксм ул", build: "54"},
{street: "40 Лет Влксм ул", build: "56"},
{street: "40 Лет Влксм ул", build: "58"},
{street: "40 Лет Влксм ул", build: "60"},
{street: "40 Лет Влксм ул", build: "62"},
{street: "40 Лет Влксм ул", build: "63"},
{street: "40 Лет Влксм ул", build: "64"},
{street: "40 Лет Влксм ул", build: "66"},
{street: "40 Лет Влксм ул", build: "68"},
{street: "40 Лет Влксм ул", build: "7"},
{street: "40 Лет Влксм ул", build: "70"},
{street: "40 Лет Влксм ул", build: "72"},
{street: "40 Лет Влксм ул", build: "76"},
{street: "40 Лет Влксм ул", build: "78"},
{street: "40 Лет Влксм ул", build: "80"},
{street: "40 Лет Влксм ул", build: "82"},
{street: "40 Лет Влксм ул", build: "86"},
{street: "40 Лет Влксм ул", build: "88"},
{street: "40 Лет Влксм ул", build: "90"},
{street: "40 Лет Влксм ул", build: "92"},
{street: "40 Лет Влксм ул", build: "96"},
{street: "40 Лет Победы ул", build: "1_ETTH"},
{street: "40 Лет Победы ул", build: "10"},
{street: "40 Лет Победы ул", build: "11_ETTH"},
{street: "40 Лет Победы ул", build: "12"},
{street: "40 Лет Победы ул", build: "13_ETTH"},
{street: "40 Лет Победы ул", build: "21_ETTH"},
{street: "40 Лет Победы ул", build: "23_ETTH"},
{street: "40 Лет Победы ул", build: "25_ETTH"},
{street: "40 Лет Победы ул", build: "27_ETTH"},
{street: "40 Лет Победы ул", build: "3_ETTH"},
{street: "40 Лет Победы ул", build: "4"},
{street: "40 Лет Победы ул", build: "5_ETTH"},
{street: "40 Лет Победы ул", build: "6"},
{street: "40 Лет Победы ул", build: "7_ETTH"},
{street: "40 Лет Победы ул", build: "8"},
{street: "Авиаторов пр ", build: "101_ETTH"},
{street: "Авиаторов пр ", build: "102_ETTH"},
{street: "Авиаторов пр ", build: "103_ETTH"},
{street: "Авиаторов пр ", build: "104_ETTH"},
{street: "Авиаторов пр ", build: "107_ETTH"},
{street: "Авиаторов пр ", build: "108_ETTH"},
{street: "Авиаторов пр ", build: "110_ETTH"},
{street: "Авиаторов пр ", build: "112_ETTH"},
{street: "Авиаторов пр ", build: "116_ETTH"},
{street: "Авиаторов пр ", build: "118_ETTH"},
{street: "Авиаторов пр ", build: "120_ETTH"},
{street: "Авиаторов пр ", build: "122_ETTH"},
{street: "Авиаторов пр ", build: "126_ETTH"},
{street: "Авиаторов пр ", build: "128_ETTH"},
{street: "Авиаторов пр ", build: "23"},
{street: "Авиаторов пр ", build: "25"},
{street: "Авиаторов пр ", build: "31_ETTH"},
{street: "Авиаторов пр ", build: "35_ETTH"},
{street: "Авиаторов пр ", build: "39_ETTH"},
{street: "Авиаторов пр ", build: "41_ETTH"},
{street: "Авиаторов пр ", build: "45_ETTH"},
{street: "Авиаторов пр ", build: "49_ETTH"},
{street: "Авиаторов пр ", build: "55_ETTH"},
{street: "Авиаторов пр ", build: "57_ETTH"},
{street: "Авиаторов пр ", build: "58"},
{street: "Авиаторов пр ", build: "61_ETTH"},
{street: "Авиаторов пр ", build: "63_ETTH"},
{street: "Авиаторов пр ", build: "64_ETTH"},
{street: "Авиаторов пр ", build: "66_ETTH"},
{street: "Авиаторов пр ", build: "67_ETTH"},
{street: "Авиаторов пр ", build: "68_ETTH"},
{street: "Авиаторов пр ", build: "69_ETTH"},
{street: "Авиаторов пр ", build: "70_ETTH"},
{street: "Авиаторов пр ", build: "71_ETTH"},
{street: "Авиаторов пр ", build: "73_ETTH"},
{street: "Авиаторов пр ", build: "75_ETTH"},
{street: "Авиаторов пр ", build: "76_ETTH"},
{street: "Авиаторов пр ", build: "78_ETTH"},
{street: "Авиаторов пр ", build: "80_ETTH"},
{street: "Авиаторов пр ", build: "81_ETTH"},
{street: "Авиаторов пр ", build: "82_ETTH"},
{street: "Авиаторов пр ", build: "83_ETTH"},
{street: "Авиаторов пр ", build: "84_ETTH"},
{street: "Авиаторов пр ", build: "85"},
{street: "Авиаторов пр ", build: "86_ETTH"},
{street: "Авиаторов пр ", build: "87"},
{street: "Авиаторов пр ", build: "89А"},
{street: "Авиаторов пр ", build: "89В"},
{street: "Авиаторов пр ", build: "89Г"},
{street: "Авиаторов пр ", build: "90_ETTH"},
{street: "Авиаторов пр ", build: "91_ETTH"},
{street: "Авиаторов пр ", build: "92_ETTH"},
{street: "Авиаторов пр ", build: "94_ETTH"},
{street: "Авиаторов пр ", build: "95_ETTH"},
{street: "Авиаторов пр ", build: "95А_ETTH"},
{street: "Авиаторов пр ", build: "97_ETTH"},
{street: "Авиаторов пр ", build: "98_ETTH"},
{street: "Авиаторов пр ", build: "98А_ETTH"},
{street: "Архитекторов пр ", build: "10_ETTH"},
{street: "Архитекторов пр ", build: "12_ETTH"},
{street: "Архитекторов пр ", build: "13_ETTH"},
{street: "Архитекторов пр ", build: "15_ETTH"},
{street: "Архитекторов пр ", build: "16_ETTH"},
{street: "Архитекторов пр ", build: "18_ETTH"},
{street: "Архитекторов пр ", build: "19_ETTH"},
{street: "Архитекторов пр ", build: "2_ETTH"},
{street: "Архитекторов пр ", build: "20_ETTH"},
{street: "Архитекторов пр ", build: "22_ETTH"},
{street: "Архитекторов пр ", build: "24_ETTH"},
{street: "Архитекторов пр ", build: "26А_ETTH"},
{street: "Архитекторов пр ", build: "27"},
{street: "Архитекторов пр ", build: "28_ETTH"},
{street: "Архитекторов пр ", build: "29_ETTH"},
{street: "Архитекторов пр ", build: "3_ETTH"},
{street: "Архитекторов пр ", build: "4_ETTH"},
{street: "Архитекторов пр ", build: "5_ETTH"},
{street: "Архитекторов пр ", build: "6_ETTH"},
{street: "Архитекторов пр ", build: "7_ETTH"},
{street: "Архитекторов пр ", build: "8_ETTH"},
{street: "Архитекторов пр ", build: "9_ETTH"},
{street: "Бардина пр ", build: "10_ETTH"},
{street: "Бардина пр ", build: "11"},
{street: "Бардина пр ", build: "13"},
{street: "Бардина пр ", build: "15"},
{street: "Бардина пр ", build: "16_ETTH"},
{street: "Бардина пр ", build: "18_ETTH"},
{street: "Бардина пр ", build: "20_ETTH"},
{street: "Бардина пр ", build: "22_ETTH"},
{street: "Бардина пр ", build: "24_ETTH"},
{street: "Бардина пр ", build: "3"},
{street: "Бардина пр ", build: "36"},
{street: "Бардина пр ", build: "38"},
{street: "Бардина пр ", build: "4"},
{street: "Бардина пр ", build: "40"},
{street: "Бардина пр ", build: "44"},
{street: "Бардина пр ", build: "5"},
{street: "Бардина пр ", build: "6_ETTH"},
{street: "Бардина пр ", build: "7"},
{street: "Бардина пр ", build: "8"},
{street: "Бардина пр ", build: "9"},
{street: "Батюшкова ул", build: "10_ETTH"},
{street: "Батюшкова ул", build: "11_ETTH"},
{street: "Батюшкова ул", build: "12_ETTH"},
{street: "Батюшкова ул", build: "13_ETTH"},
{street: "Батюшкова ул", build: "14_ETTH"},
{street: "Батюшкова ул", build: "15_ETTH"},
{street: "Батюшкова ул", build: "16_ETTH"},
{street: "Батюшкова ул", build: "17_ETTH"},
{street: "Батюшкова ул", build: "19_ETTH"},
{street: "Батюшкова ул", build: "2_ETTH"},
{street: "Батюшкова ул", build: "28_ETTH"},
{street: "Батюшкова ул", build: "2А_ETTH"},
{street: "Батюшкова ул", build: "4_ETTH"},
{street: "Батюшкова ул", build: "5_ETTH"},
{street: "Батюшкова ул", build: "5А_ETTH"},
{street: "Батюшкова ул", build: "6_ETTH"},
{street: "Батюшкова ул", build: "7_ETTH"},
{street: "Батюшкова ул", build: "8_ETTH"},
{street: "Батюшкова ул", build: "9_ETTH"},
{street: "Батюшкова ул", build: "9А_ETTH"},
{street: "Белана ул", build: "17"},
{street: "Белана ул", build: "19"},
{street: "Белана ул", build: "21"},
{street: "Белана ул", build: "35"},
{street: "Белана ул", build: "37"},
{street: "Белана ул", build: "3А"},
{street: "Белана ул", build: "3Б"},
{street: "Белана ул", build: "7"},
{street: "Белградская ул", build: "1"},
{street: "Белградская ул", build: "3"},
{street: "Белградская ул", build: "5"},
{street: "Белградская ул", build: "7"},
{street: "Березовая Роща ул", build: "18"},
{street: "Березовая Роща ул", build: "2"},
{street: "Березовая Роща ул", build: "20"},
{street: "Березовая Роща ул", build: "22"},
{street: "Березовая Роща ул", build: "24"},
{street: "Березовая Роща ул", build: "26"},
{street: "Березовая Роща ул", build: "28"},
{street: "Березовая Роща ул", build: "33"},
{street: "Березовая Роща ул", build: "34"},
{street: "Березовая Роща ул", build: "36"},
{street: "Березовая Роща ул", build: "38"},
{street: "Березовая Роща ул", build: "4"},
{street: "Березовая Роща ул", build: "40"},
{street: "Березовая Роща ул", build: "42"},
{street: "Березовая Роща ул", build: "44"},
{street: "Библиотечный Проезд ", build: "3"},
{street: "Библиотечный Проезд ", build: "7"},
{street: "Братьев Гаденовых ул", build: "10_ETTH"},
{street: "Братьев Гаденовых ул", build: "10А"},
{street: "Братьев Гаденовых ул", build: "11_ETTH"},
{street: "Братьев Гаденовых ул", build: "12_ETTH"},
{street: "Братьев Гаденовых ул", build: "8_ETTH"},
{street: "Братьев Гаденовых ул", build: "9_ETTH"},
{street: "Братьев Сизых ул", build: "1"},
{street: "Братьев Сизых ул", build: "10_ETTH"},
{street: "Братьев Сизых ул", build: "10А"},
{street: "Братьев Сизых ул", build: "11_ETTH"},
{street: "Братьев Сизых ул", build: "12_ETTH"},
{street: "Братьев Сизых ул", build: "14_ETTH"},
{street: "Братьев Сизых ул", build: "14Б"},
{street: "Братьев Сизых ул", build: "16_ETTH"},
{street: "Братьев Сизых ул", build: "18_ETTH"},
{street: "Братьев Сизых ул", build: "2"},
{street: "Братьев Сизых ул", build: "3"},
{street: "Братьев Сизых ул", build: "4"},
{street: "Братьев Сизых ул", build: "4Б"},
{street: "Братьев Сизых ул", build: "5"},
{street: "Братьев Сизых ул", build: "5_ETTH"},
{street: "Братьев Сизых ул", build: "6"},
{street: "Братьев Сизых ул", build: "7"},
{street: "Братьев Сизых ул", build: "7_ETTH"},
{street: "Братьев Сизых ул", build: "8"},
{street: "Братьев Сизых ул", build: "9_ETTH"},
{street: "Бугарева ул", build: "12_ETTH"},
{street: "Бугарева ул", build: "14_ETTH"},
{street: "Бугарева ул", build: "15_ETTH"},
{street: "Бугарева ул", build: "18_ETTH"},
{street: "Бугарева ул", build: "18А_ETTH"},
{street: "Бугарева ул", build: "19_ETTH"},
{street: "Бугарева ул", build: "20_ETTH"},
{street: "Бугарева ул", build: "20А_ETTH"},
{street: "Бугарева ул", build: "21_ETTH"},
{street: "Бугарева ул", build: "22_ETTH"},
{street: "Бугарева ул", build: "22А_ETTH"},
{street: "Бугарева ул", build: "23_ETTH"},
{street: "Бугарева ул", build: "24_ETTH"},
{street: "Бугарева ул", build: "24А_ETTH"},
{street: "Бугарева ул", build: "26_ETTH"},
{street: "Бугарева ул", build: "28_ETTH"},
{street: "Бульварный пер ", build: "2_ETTH"},
{street: "Бульварный пер ", build: "4_ETTH"},
{street: "Ватутина ул", build: "10"},
{street: "Ватутина ул", build: "11"},
{street: "Ватутина ул", build: "12"},
{street: "Ватутина ул", build: "14"},
{street: "Ватутина ул", build: "4"},
{street: "Ватутина ул", build: "8"},
{street: "Веры Соломиной ул", build: "11"},
{street: "Веры Соломиной ул", build: "15"},
{street: "Веры Соломиной ул", build: "19"},
{street: "Веры Соломиной ул", build: "22"},
{street: "Веры Соломиной ул", build: "23"},
{street: "Веры Соломиной ул", build: "25"},
{street: "Веры Соломиной ул", build: "26"},
{street: "Веры Соломиной ул", build: "27"},
{street: "Веры Соломиной ул", build: "28"},
{street: "Веры Соломиной ул", build: "30"},
{street: "Веры Соломиной ул", build: "31"},
{street: "Веры Соломиной ул", build: "32"},
{street: "Веры Соломиной ул", build: "33"},
{street: "Веры Соломиной ул", build: "34"},
{street: "Веры Соломиной ул", build: "35"},
{street: "Веры Соломиной ул", build: "39"},
{street: "Веры Соломиной ул", build: "41"},
{street: "Веры Соломиной ул", build: "6"},
{street: "Веры Соломиной ул", build: "8"},
{street: "Вокзальная ул", build: "11"},
{street: "Вокзальная ул", build: "15"},
{street: "Вокзальная ул", build: "21"},
{street: "Вокзальная ул", build: "21А"},
{street: "Вокзальная ул", build: "23"},
{street: "Вокзальная ул", build: "25"},
{street: "Вокзальная ул", build: "3"},
{street: "Вокзальная ул", build: "5"},
{street: "Вокзальная ул", build: "7"},
{street: "Вокзальная ул", build: "9"},
{street: "Воробьева ул", build: "13_ETTH"},
{street: "Воробьева ул", build: "14_ETTH"},
{street: "Воробьева ул", build: "15_ETTH"},
{street: "Воробьева ул", build: "3А_ETTH"},
{street: "Воробьева ул", build: "8_ETTH"},
{street: "Воровского ул", build: "11"},
{street: "Воровского ул", build: "13"},
{street: "Воровского ул", build: "7"},
{street: "Воровского ул", build: "9"},
{street: "Герцена ул", build: "3_ETTH"},
{street: "Герцена ул", build: "5_ETTH"},
{street: "Герцена ул", build: "7_ETTH"},
{street: "Глинки ул", build: "10_ETTH"},
{street: "Глинки ул", build: "13_ETTH"},
{street: "Глинки ул", build: "3_ETTH"},
{street: "Горьковская ул", build: "10А"},
{street: "Горьковская ул", build: "45"},
{street: "Горьковская ул", build: "56А"},
{street: "Горьковская ул", build: "60"},
{street: "Горьковская ул", build: "8"},
{street: "Грдины ул", build: "1_ETTH"},
{street: "Грдины ул", build: "10_ETTH"},
{street: "Грдины ул", build: "11_ETTH"},
{street: "Грдины ул", build: "12_ETTH"},
{street: "Грдины ул", build: "13_ETTH"},
{street: "Грдины ул", build: "14_ETTH"},
{street: "Грдины ул", build: "15_ETTH"},
{street: "Грдины ул", build: "16_ETTH"},
{street: "Грдины ул", build: "16А_ETTH"},
{street: "Грдины ул", build: "17_ETTH"},
{street: "Грдины ул", build: "18_ETTH"},
{street: "Грдины ул", build: "19_ETTH"},
{street: "Грдины ул", build: "22_ETTH"},
{street: "Грдины ул", build: "23_ETTH"},
{street: "Грдины ул", build: "26_ETTH"},
{street: "Грдины ул", build: "27_ETTH"},
{street: "Грдины ул", build: "28_ETTH"},
{street: "Грдины ул", build: "29_ETTH"},
{street: "Грдины ул", build: "3_ETTH"},
{street: "Грдины ул", build: "37_ETTH"},
{street: "Грдины ул", build: "4_ETTH"},
{street: "Грдины ул", build: "5_ETTH"},
{street: "Грдины ул", build: "6А_ETTH"},
{street: "Грдины ул", build: "7_ETTH"},
{street: "Грдины ул", build: "8_ETTH"},
{street: "Грдины ул", build: "9_ETTH"},
{street: "Грибоедова ул", build: "1_ETTH"},
{street: "Грибоедова ул", build: "2_ETTH"},
{street: "Грибоедова ул", build: "3_ETTH"},
{street: "Грибоедова ул", build: "4_ETTH"},
{street: "Грибоедова ул", build: "5_ETTH"},
{street: "День Шахтера ул", build: "10"},
{street: "День Шахтера ул", build: "10А"},
{street: "День Шахтера ул", build: "15"},
{street: "День Шахтера ул", build: "16"},
{street: "День Шахтера ул", build: "19"},
{street: "День Шахтера ул", build: "4"},
{street: "День Шахтера ул", build: "6"},
{street: "День Шахтера ул", build: "8"},
{street: "Дорстроевская ул", build: "1"},
{street: "Дорстроевская ул", build: "13"},
{street: "Дорстроевская ул", build: "15"},
{street: "Дорстроевская ул", build: "1А"},
{street: "Дорстроевская ул", build: "3"},
{street: "Дорстроевская ул", build: "3А"},
{street: "Дорстроевская ул", build: "7"},
{street: "Дорстроевская ул", build: "9"},
{street: "Дружбы пр ", build: "1_ETTH"},
{street: "Дружбы пр ", build: "10_ETTH"},
{street: "Дружбы пр ", build: "12_ETTH"},
{street: "Дружбы пр ", build: "13_ETTH"},
{street: "Дружбы пр ", build: "14_ETTH"},
{street: "Дружбы пр ", build: "15_ETTH"},
{street: "Дружбы пр ", build: "16_ETTH"},
{street: "Дружбы пр ", build: "17А_ETTH"},
{street: "Дружбы пр ", build: "17Б_ETTH"},
{street: "Дружбы пр ", build: "19_ETTH"},
{street: "Дружбы пр ", build: "1А_ETTH"},
{street: "Дружбы пр ", build: "2_ETTH"},
{street: "Дружбы пр ", build: "20_ETTH"},
{street: "Дружбы пр ", build: "20А_ETTH"},
{street: "Дружбы пр ", build: "21_ETTH"},
{street: "Дружбы пр ", build: "22_ETTH"},
{street: "Дружбы пр ", build: "28_ETTH"},
{street: "Дружбы пр ", build: "29_ETTH"},
{street: "Дружбы пр ", build: "3_ETTH"},
{street: "Дружбы пр ", build: "30_ETTH"},
{street: "Дружбы пр ", build: "31_ETTH"},
{street: "Дружбы пр ", build: "32_ETTH"},
{street: "Дружбы пр ", build: "33_ETTH"},
{street: "Дружбы пр ", build: "34_ETTH"},
{street: "Дружбы пр ", build: "35_ETTH"},
{street: "Дружбы пр ", build: "36_ETTH"},
{street: "Дружбы пр ", build: "37_ETTH"},
{street: "Дружбы пр ", build: "38_ETTH"},
{street: "Дружбы пр ", build: "40_ETTH"},
{street: "Дружбы пр ", build: "42_ETTH"},
{street: "Дружбы пр ", build: "43_ETTH"},
{street: "Дружбы пр ", build: "44_ETTH"},
{street: "Дружбы пр ", build: "45_ETTH"},
{street: "Дружбы пр ", build: "47_ETTH"},
{street: "Дружбы пр ", build: "48_ETTH"},
{street: "Дружбы пр ", build: "49_ETTH"},
{street: "Дружбы пр ", build: "4А_ETTH"},
{street: "Дружбы пр ", build: "5_ETTH"},
{street: "Дружбы пр ", build: "50_ETTH"},
{street: "Дружбы пр ", build: "51_ETTH"},
{street: "Дружбы пр ", build: "52_ETTH"},
{street: "Дружбы пр ", build: "53_ETTH"},
{street: "Дружбы пр ", build: "54_ETTH"},
{street: "Дружбы пр ", build: "55_ETTH"},
{street: "Дружбы пр ", build: "56_ETTH"},
{street: "Дружбы пр ", build: "57_ETTH"},
{street: "Дружбы пр ", build: "58_ETTH"},
{street: "Дружбы пр ", build: "59_ETTH"},
{street: "Дружбы пр ", build: "60_ETTH"},
{street: "Дружбы пр ", build: "61_ETTH"},
{street: "Дружбы пр ", build: "62_ETTH"},
{street: "Дружбы пр ", build: "63_ETTH"},
{street: "Дружбы пр ", build: "65_ETTH"},
{street: "Дружбы пр ", build: "69_ETTH"},
{street: "Дружбы пр ", build: "6А_ETTH"},
{street: "Дружбы пр ", build: "7_ETTH"},
{street: "Дружбы пр ", build: "8_ETTH"},
{street: "Дузенко ул", build: "10_ETTH"},
{street: "Дузенко ул", build: "12_ETTH"},
{street: "Дузенко ул", build: "16_ETTH"},
{street: "Дузенко ул", build: "18_ETTH"},
{street: "Дузенко ул", build: "20_ETTH"},
{street: "Дузенко ул", build: "21_ETTH"},
{street: "Дузенко ул", build: "21А"},
{street: "Дузенко ул", build: "21Б"},
{street: "Дузенко ул", build: "22_ETTH"},
{street: "Дузенко ул", build: "24_ETTH"},
{street: "Дузенко ул", build: "25_ETTH"},
{street: "Дузенко ул", build: "26_ETTH"},
{street: "Дузенко ул", build: "27_ETTH"},
{street: "Дузенко ул", build: "29_ETTH"},
{street: "Дузенко ул", build: "33А_ETTH"},
{street: "Дузенко ул", build: "35_ETTH"},
{street: "Дузенко ул", build: "37_ETTH"},
{street: "Дузенко ул", build: "39_ETTH"},
{street: "Дузенко ул", build: "41_ETTH"},
{street: "Дузенко ул", build: "41А_ETTH"},
{street: "Дузенко ул", build: "45_ETTH"},
{street: "Дузенко ул", build: "5А_ETTH"},
{street: "Дузенко ул", build: "6_ETTH"},
{street: "Екимова ул", build: "11_ETTH"},
{street: "Екимова ул", build: "12_ETTH"},
{street: "Екимова ул", build: "20_ETTH"},
{street: "Екимова ул", build: "26_ETTH"},
{street: "Екимова ул", build: "30_ETTH"},
{street: "Екимова ул", build: "32А_ETTH"},
{street: "Екимова ул", build: "32Б_ETTH"},
{street: "Екимова ул", build: "34_ETTH"},
{street: "Запорожская ул", build: "1_ETTH"},
{street: "Запорожская ул", build: "15_ETTH"},
{street: "Запорожская ул", build: "15А_ETTH"},
{street: "Запорожская ул", build: "21"},
{street: "Запорожская ул", build: "21А"},
{street: "Запорожская ул", build: "21Б"},
{street: "Запорожская ул", build: "23"},
{street: "Запорожская ул", build: "25"},
{street: "Запорожская ул", build: "29"},
{street: "Запорожская ул", build: "3_ETTH"},
{street: "Запорожская ул", build: "31"},
{street: "Запорожская ул", build: "33"},
{street: "Запорожская ул", build: "35"},
{street: "Запорожская ул", build: "39"},
{street: "Запорожская ул", build: "41"},
{street: "Запорожская ул", build: "43"},
{street: "Запорожская ул", build: "45"},
{street: "Запорожская ул", build: "47"},
{street: "Запорожская ул", build: "49"},
{street: "Запорожская ул", build: "5_ETTH"},
{street: "Запорожская ул", build: "51"},
{street: "Запорожская ул", build: "53"},
{street: "Запорожская ул", build: "57"},
{street: "Запорожская ул", build: "61"},
{street: "Запорожская ул", build: "69"},
{street: "Запорожская ул", build: "69А"},
{street: "Запорожская ул", build: "69Б"},
{street: "Запорожская ул", build: "7_ETTH"},
{street: "Запорожская ул", build: "73_ETTH"},
{street: "Запорожская ул", build: "73А_ETTH"},
{street: "Запорожская ул", build: "73Б_ETTH"},
{street: "Запорожская ул", build: "77_ETTH"},
{street: "Запорожская ул", build: "79_ETTH"},
{street: "Запорожская ул", build: "81_ETTH"},
{street: "Запорожская ул", build: "9_ETTH"},
{street: "Запсибовцев пр ", build: "10_ETTH"},
{street: "Запсибовцев пр ", build: "11_ETTH"},
{street: "Запсибовцев пр ", build: "12_ETTH"},
{street: "Запсибовцев пр ", build: "13_ETTH"},
{street: "Запсибовцев пр ", build: "15_ETTH"},
{street: "Запсибовцев пр ", build: "16_ETTH"},
{street: "Запсибовцев пр ", build: "19_ETTH"},
{street: "Запсибовцев пр ", build: "27_ETTH"},
{street: "Запсибовцев пр ", build: "3_ETTH"},
{street: "Запсибовцев пр ", build: "31_ETTH"},
{street: "Запсибовцев пр ", build: "35_ETTH"},
{street: "Запсибовцев пр ", build: "37_ETTH"},
{street: "Запсибовцев пр ", build: "39/96_ETTH"},
{street: "Запсибовцев пр ", build: "4_ETTH"},
{street: "Запсибовцев пр ", build: "5_ETTH"},
{street: "Запсибовцев пр ", build: "6_ETTH"},
{street: "Запсибовцев пр ", build: "8_ETTH"},
{street: "Звездова ул", build: "10"},
{street: "Звездова ул", build: "14"},
{street: "Звездова ул", build: "18"},
{street: "Звездова ул", build: "20"},
{street: "Звездова ул", build: "20_ETTH"},
{street: "Звездова ул", build: "22"},
{street: "Звездова ул", build: "22А"},
{street: "Звездова ул", build: "22Б"},
{street: "Звездова ул", build: "22Г"},
{street: "Звездова ул", build: "24"},
{street: "Звездова ул", build: "24А"},
{street: "Звездова ул", build: "24Б"},
{street: "Звездова ул", build: "24Г"},
{street: "Звездова ул", build: "26_ETTH"},
{street: "Звездова ул", build: "28_ETTH"},
{street: "Звездова ул", build: "30_ETTH"},
{street: "Звездова ул", build: "32_ETTH"},
{street: "Звездова ул", build: "42"},
{street: "Звездова ул", build: "44"},
{street: "Звездова ул", build: "46"},
{street: "Звездова ул", build: "48А_ETTH"},
{street: "Звездова ул", build: "50_ETTH"},
{street: "Звездова ул", build: "52_ETTH"},
{street: "Звездова ул", build: "54"},
{street: "Звездова ул", build: "54А"},
{street: "Звездова ул", build: "56"},
{street: "Звездова ул", build: "58"},
{street: "Звездова ул", build: "6"},
{street: "Звездова ул", build: "60"},
{street: "Звездова ул", build: "60А"},
{street: "Звездова ул", build: "62"},
{street: "Звездова ул", build: "62А"},
{street: "Звездова ул", build: "64"},
{street: "Звездова ул", build: "66"},
{street: "Звездова ул", build: "68"},
{street: "Звездова ул", build: "70"},
{street: "Звездова ул", build: "72"},
{street: "Звездова ул", build: "74"},
{street: "Звездова ул", build: "76"},
{street: "Звездова ул", build: "78"},
{street: "Звездова ул", build: "8"},
{street: "Зорге ул", build: "10_ETTH"},
{street: "Зорге ул", build: "14_ETTH"},
{street: "Зорге ул", build: "2_ETTH"},
{street: "Зорге ул", build: "22_ETTH"},
{street: "Зорге ул", build: "24_ETTH"},
{street: "Зорге ул", build: "26_ETTH"},
{street: "Зорге ул", build: "30_ETTH"},
{street: "Зорге ул", build: "32_ETTH"},
{street: "Зорге ул", build: "34_ETTH"},
{street: "Зорге ул", build: "34А_ETTH"},
{street: "Зорге ул", build: "4_ETTH"},
{street: "Зорге ул", build: "42_ETTH"},
{street: "Зорге ул", build: "44_ETTH"},
{street: "Зорге ул", build: "46_ETTH"},
{street: "Зорге ул", build: "48_ETTH"},
{street: "Зорге ул", build: "50_ETTH"},
{street: "Зорге ул", build: "6_ETTH"},
{street: "Зорге ул", build: "8_ETTH"},
{street: "Зыряновская ул", build: "46"},
{street: "Зыряновская ул", build: "48_ETTH"},
{street: "Зыряновская ул", build: "50"},
{street: "Зыряновская ул", build: "52_ETTH"},
{street: "Зыряновская ул", build: "54"},
{street: "Зыряновская ул", build: "56_ETTH"},
{street: "Зыряновская ул", build: "58"},
{street: "Зыряновская ул", build: "60_ETTH"},
{street: "Зыряновская ул", build: "74_ETTH"},
{street: "Зыряновская ул", build: "74Б"},
{street: "Зыряновская ул", build: "78_ETTH"},
{street: "Зыряновская ул", build: "80_ETTH"},
{street: "Зыряновская ул", build: "90_ETTH"},
{street: "Зыряновская ул", build: "92_ETTH"},
{street: "Зыряновская ул", build: "94_ETTH"},
{street: "Интернатная ул", build: "1"},
{street: "Интернатная ул", build: "1А"},
{street: "Интернатная ул", build: "3"},
{street: "Казарновского Проезд ", build: "1"},
{street: "Казарновского Проезд ", build: "2"},
{street: "Казарновского Проезд ", build: "3"},
{street: "Казарновского Проезд ", build: "4"},
{street: "Казарновского Проезд ", build: "5"},
{street: "Капитальная ул", build: "1"},
{street: "Капитальная ул", build: "10"},
{street: "Капитальная ул", build: "12"},
{street: "Капитальная ул", build: "14"},
{street: "Капитальная ул", build: "2"},
{street: "Капитальная ул", build: "3"},
{street: "Капитальная ул", build: "4"},
{street: "Капитальная ул", build: "5"},
{street: "Капитальная ул", build: "6"},
{street: "Капитальная ул", build: "8"},
{street: "Карла Маркса ул", build: "10А"},
{street: "Карла Маркса ул", build: "12"},
{street: "Карла Маркса ул", build: "14"},
{street: "Карла Маркса ул", build: "14А"},
{street: "Карла Маркса ул", build: "18"},
{street: "Карла Маркса ул", build: "3"},
{street: "Карла Маркса ул", build: "4"},
{street: "Карла Маркса ул", build: "7А_ETTH"},
{street: "Карла Маркса ул", build: "8"},
{street: "Карла Маркса ул", build: "8А"},
{street: "Кирова ул", build: "10"},
{street: "Кирова ул", build: "100_ETTH"},
{street: "Кирова ул", build: "101_ETTH"},
{street: "Кирова ул", build: "103"},
{street: "Кирова ул", build: "105"},
{street: "Кирова ул", build: "109"},
{street: "Кирова ул", build: "10А"},
{street: "Кирова ул", build: "111"},
{street: "Кирова ул", build: "113"},
{street: "Кирова ул", build: "115_ETTH"},
{street: "Кирова ул", build: "119_ETTH"},
{street: "Кирова ул", build: "12"},
{street: "Кирова ул", build: "12_ETTH"},
{street: "Кирова ул", build: "123_ETTH"},
{street: "Кирова ул", build: "127_ETTH"},
{street: "Кирова ул", build: "129_ETTH"},
{street: "Кирова ул", build: "13"},
{street: "Кирова ул", build: "15"},
{street: "Кирова ул", build: "16"},
{street: "Кирова ул", build: "17"},
{street: "Кирова ул", build: "18"},
{street: "Кирова ул", build: "21А"},
{street: "Кирова ул", build: "22"},
{street: "Кирова ул", build: "23"},
{street: "Кирова ул", build: "23А"},
{street: "Кирова ул", build: "24"},
{street: "Кирова ул", build: "25"},
{street: "Кирова ул", build: "25_ETTH"},
{street: "Кирова ул", build: "25А"},
{street: "Кирова ул", build: "26"},
{street: "Кирова ул", build: "27"},
{street: "Кирова ул", build: "28"},
{street: "Кирова ул", build: "29"},
{street: "Кирова ул", build: "2А"},
{street: "Кирова ул", build: "4"},
{street: "Кирова ул", build: "4А"},
{street: "Кирова ул", build: "5"},
{street: "Кирова ул", build: "50"},
{street: "Кирова ул", build: "51А_ETTH"},
{street: "Кирова ул", build: "52"},
{street: "Кирова ул", build: "54"},
{street: "Кирова ул", build: "56"},
{street: "Кирова ул", build: "57"},
{street: "Кирова ул", build: "59"},
{street: "Кирова ул", build: "6"},
{street: "Кирова ул", build: "60"},
{street: "Кирова ул", build: "61"},
{street: "Кирова ул", build: "62"},
{street: "Кирова ул", build: "64"},
{street: "Кирова ул", build: "65"},
{street: "Кирова ул", build: "67"},
{street: "Кирова ул", build: "6А"},
{street: "Кирова ул", build: "7"},
{street: "Кирова ул", build: "72_ETTH"},
{street: "Кирова ул", build: "73"},
{street: "Кирова ул", build: "74_ETTH"},
{street: "Кирова ул", build: "75"},
{street: "Кирова ул", build: "75_ETTH"},
{street: "Кирова ул", build: "76_ETTH"},
{street: "Кирова ул", build: "77"},
{street: "Кирова ул", build: "77_ETTH"},
{street: "Кирова ул", build: "78_ETTH"},
{street: "Кирова ул", build: "79_ETTH"},
{street: "Кирова ул", build: "8"},
{street: "Кирова ул", build: "80_ETTH"},
{street: "Кирова ул", build: "82_ETTH"},
{street: "Кирова ул", build: "84_ETTH"},
{street: "Кирова ул", build: "85_ETTH"},
{street: "Кирова ул", build: "87_ETTH"},
{street: "Кирова ул", build: "88_ETTH"},
{street: "Кирова ул", build: "89А_ETTH"},
{street: "Кирова ул", build: "90_ETTH"},
{street: "Кирова ул", build: "91_ETTH"},
{street: "Кирова ул", build: "92_ETTH"},
{street: "Кирова ул", build: "93_ETTH"},
{street: "Кирова ул", build: "94_ETTH"},
{street: "Кирова ул", build: "95_ETTH"},
{street: "Кирова ул", build: "97_ETTH"},
{street: "Кирова ул", build: "99_ETTH"},
{street: "Климасенко ул", build: "10/1_ETTH"},
{street: "Климасенко ул", build: "11/1_ETTH"},
{street: "Климасенко ул", build: "11/10_ETTH"},
{street: "Климасенко ул", build: "11/3_ETTH"},
{street: "Климасенко ул", build: "11/5_ETTH"},
{street: "Климасенко ул", build: "11/6_ETTH"},
{street: "Климасенко ул", build: "11/7_ETTH"},
{street: "Климасенко ул", build: "11/9_ETTH"},
{street: "Климасенко ул", build: "12/1_ETTH"},
{street: "Климасенко ул", build: "12/2_ETTH"},
{street: "Климасенко ул", build: "13_ETTH"},
{street: "Климасенко ул", build: "14/1_ETTH"},
{street: "Климасенко ул", build: "14/2_ETTH"},
{street: "Климасенко ул", build: "14/3_ETTH"},
{street: "Климасенко ул", build: "16/1_ETTH"},
{street: "Климасенко ул", build: "16/2_ETTH"},
{street: "Климасенко ул", build: "18/1_ETTH"},
{street: "Климасенко ул", build: "18/2_ETTH"},
{street: "Климасенко ул", build: "18/3_ETTH"},
{street: "Климасенко ул", build: "20/2_ETTH"},
{street: "Климасенко ул", build: "20/4_ETTH"},
{street: "Климасенко ул", build: "21/4_ETTH"},
{street: "Климасенко ул", build: "21/6_ETTH"},
{street: "Климасенко ул", build: "23_ETTH"},
{street: "Климасенко ул", build: "24/1_ETTH"},
{street: "Климасенко ул", build: "25_ETTH"},
{street: "Климасенко ул", build: "27_ETTH"},
{street: "Климасенко ул", build: "28_ETTH"},
{street: "Климасенко ул", build: "30_ETTH"},
{street: "Климасенко ул", build: "32_ETTH"},
{street: "Климасенко ул", build: "34_ETTH"},
{street: "Климасенко ул", build: "34А_ETTH"},
{street: "Климасенко ул", build: "9/2_ETTH"},
{street: "Климасенко ул", build: "9/5_ETTH"},
{street: "Клименко ул", build: "11"},
{street: "Клименко ул", build: "13"},
{street: "Клименко ул", build: "15"},
{street: "Клименко ул", build: "19"},
{street: "Клименко ул", build: "22"},
{street: "Клименко ул", build: "23"},
{street: "Клименко ул", build: "24"},
{street: "Клименко ул", build: "26"},
{street: "Клименко ул", build: "27"},
{street: "Клименко ул", build: "28/1"},
{street: "Клименко ул", build: "28/2"},
{street: "Клименко ул", build: "29"},
{street: "Клименко ул", build: "29/3"},
{street: "Клименко ул", build: "29/1"},
{street: "Клименко ул", build: "29/2"},
{street: "Клименко ул", build: "3"},
{street: "Клименко ул", build: "30"},
{street: "Клименко ул", build: "31"},
{street: "Клименко ул", build: "32"},
{street: "Клименко ул", build: "33"},
{street: "Клименко ул", build: "34"},
{street: "Клименко ул", build: "35"},
{street: "Клименко ул", build: "36"},
{street: "Клименко ул", build: "37"},
{street: "Клименко ул", build: "38"},
{street: "Клименко ул", build: "39"},
{street: "Клименко ул", build: "40/89"},
{street: "Клименко ул", build: "42"},
{street: "Клименко ул", build: "44"},
{street: "Клименко ул", build: "46"},
{street: "Клименко ул", build: "48"},
{street: "Клименко ул", build: "5"},
{street: "Клименко ул", build: "50"},
{street: "Клименко ул", build: "52"},
{street: "Клименко ул", build: "54"},
{street: "Клименко ул", build: "54А"},
{street: "Клименко ул", build: "56"},
{street: "Клименко ул", build: "58"},
{street: "Клименко ул", build: "60"},
{street: "Клименко ул", build: "62"},
{street: "Клименко ул", build: "6В"},
{street: "Клименко ул", build: "6Г"},
{street: "Клименко ул", build: "6Д"},
{street: "Клименко ул", build: "7"},
{street: "Клименко ул", build: "9"},
{street: "Конева ул", build: "11_ETTH"},
{street: "Конева ул", build: "13_ETTH"},
{street: "Конева ул", build: "2_ETTH"},
{street: "Конева ул", build: "5_ETTH"},
{street: "Конева ул", build: "7_ETTH"},
{street: "Конева ул", build: "9_ETTH"},
{street: "Косилова ул", build: "13"},
{street: "Космонавтов ул", build: "10_ETTH"},
{street: "Космонавтов ул", build: "12_ETTH"},
{street: "Космонавтов ул", build: "6_ETTH"},
{street: "Космонавтов ул", build: "8_ETTH"},
{street: "Косыгина ул", build: "11_ETTH"},
{street: "Косыгина ул", build: "13_ETTH"},
{street: "Косыгина ул", build: "21_ETTH"},
{street: "Косыгина ул", build: "25_ETTH"},
{street: "Косыгина ул", build: "27_ETTH"},
{street: "Косыгина ул", build: "29_ETTH"},
{street: "Косыгина ул", build: "3_ETTH"},
{street: "Косыгина ул", build: "31_ETTH"},
{street: "Косыгина ул", build: "35_ETTH"},
{street: "Косыгина ул", build: "35А_ETTH"},
{street: "Косыгина ул", build: "39_ETTH"},
{street: "Косыгина ул", build: "41_ETTH"},
{street: "Косыгина ул", build: "43_ETTH"},
{street: "Косыгина ул", build: "45_ETTH"},
{street: "Косыгина ул", build: "5_ETTH"},
{street: "Косыгина ул", build: "51_ETTH"},
{street: "Косыгина ул", build: "53_ETTH"},
{street: "Косыгина ул", build: "55_ETTH"},
{street: "Косыгина ул", build: "59_ETTH"},
{street: "Косыгина ул", build: "61_ETTH"},
{street: "Косыгина ул", build: "65_ETTH"},
{street: "Косыгина ул", build: "69_ETTH"},
{street: "Косыгина ул", build: "7_ETTH"},
{street: "Косыгина ул", build: "75_ETTH"},
{street: "Косыгина ул", build: "79_ETTH"},
{street: "Косыгина ул", build: "81_ETTH"},
{street: "Косыгина ул", build: "83_ETTH"},
{street: "Косыгина ул", build: "85_ETTH"},
{street: "Косыгина ул", build: "87_ETTH"},
{street: "Косыгина ул", build: "9_ETTH"},
{street: "Кузнецкстроевский пр ", build: "12"},
{street: "Кузнецкстроевский пр ", build: "13"},
{street: "Кузнецкстроевский пр ", build: "14"},
{street: "Кузнецкстроевский пр ", build: "15"},
{street: "Кузнецкстроевский пр ", build: "17"},
{street: "Кузнецкстроевский пр ", build: "18"},
{street: "Кузнецкстроевский пр ", build: "19"},
{street: "Кузнецкстроевский пр ", build: "21_ETTH"},
{street: "Кузнецкстроевский пр ", build: "22"},
{street: "Кузнецкстроевский пр ", build: "23"},
{street: "Кузнецкстроевский пр ", build: "24"},
{street: "Кузнецкстроевский пр ", build: "25"},
{street: "Кузнецкстроевский пр ", build: "26"},
{street: "Кузнецкстроевский пр ", build: "28"},
{street: "Кузнецкстроевский пр ", build: "30"},
{street: "Кузнецкстроевский пр ", build: "32А"},
{street: "Кузнецкстроевский пр ", build: "32Б"},
{street: "Кузнецкстроевский пр ", build: "34"},
{street: "Кузнецкстроевский пр ", build: "34А"},
{street: "Кузнецкстроевский пр ", build: "34Б"},
{street: "Кузнецкстроевский пр ", build: "36"},
{street: "Кузнецкстроевский пр ", build: "38"},
{street: "Кузнецкстроевский пр ", build: "40"},
{street: "Кузнецкстроевский пр ", build: "42"},
{street: "Кузнецкстроевский пр ", build: "44"},
{street: "Кузнецкстроевский пр ", build: "46"},
{street: "Кузнецкстроевский пр ", build: "48"},
{street: "Кузнецкстроевский пр ", build: "50"},
{street: "Кузнецкстроевский пр ", build: "52"},
{street: "Кузнецкстроевский пр ", build: "9_ETTH"},
{street: "Кузнецова ул", build: "11_ETTH"},
{street: "Кузнецова ул", build: "13_ETTH"},
{street: "Кузнецова ул", build: "15_ETTH"},
{street: "Кузнецова ул", build: "17_ETTH"},
{street: "Кузнецова ул", build: "19_ETTH"},
{street: "Кузнецова ул", build: "19А_ETTH"},
{street: "Кузнецова ул", build: "21_ETTH"},
{street: "Кузнецова ул", build: "23_ETTH"},
{street: "Кузнецова ул", build: "25_ETTH"},
{street: "Кузнецова ул", build: "27_ETTH"},
{street: "Кузнецова ул", build: "29_ETTH"},
{street: "Куйбышева ул", build: "1_ETTH"},
{street: "Куйбышева ул", build: "10_ETTH"},
{street: "Куйбышева ул", build: "11_ETTH"},
{street: "Куйбышева ул", build: "12_ETTH"},
{street: "Куйбышева ул", build: "13_ETTH"},
{street: "Куйбышева ул", build: "14_ETTH"},
{street: "Куйбышева ул", build: "15_ETTH"},
{street: "Куйбышева ул", build: "2_ETTH"},
{street: "Куйбышева ул", build: "3_ETTH"},
{street: "Куйбышева ул", build: "5_ETTH"},
{street: "Куйбышева ул", build: "7_ETTH"},
{street: "Куйбышева ул", build: "9_ETTH"},
{street: "Кулакова пер ", build: "4"},
{street: "Кулакова пер ", build: "6"},
{street: "Курако пр ", build: "10"},
{street: "Курако пр ", build: "12"},
{street: "Курако пр ", build: "17А"},
{street: "Курако пр ", build: "17Б"},
{street: "Курако пр ", build: "19Б"},
{street: "Курако пр ", build: "20"},
{street: "Курако пр ", build: "21_ETTH"},
{street: "Курако пр ", build: "22"},
{street: "Курако пр ", build: "23_ETTH"},
{street: "Курако пр ", build: "24"},
{street: "Курако пр ", build: "25_ETTH"},
{street: "Курако пр ", build: "26"},
{street: "Курако пр ", build: "27_ETTH"},
{street: "Курако пр ", build: "28"},
{street: "Курако пр ", build: "29_ETTH"},
{street: "Курако пр ", build: "30"},
{street: "Курако пр ", build: "31_ETTH"},
{street: "Курако пр ", build: "4"},
{street: "Курако пр ", build: "41_ETTH"},
{street: "Курако пр ", build: "43_ETTH"},
{street: "Курако пр ", build: "45_ETTH"},
{street: "Курако пр ", build: "8"},
{street: "Курбатова Проезд ", build: "1"},
{street: "Курбатова Проезд ", build: "2"},
{street: "Курбатова Проезд ", build: "4"},
{street: "Курбатова Проезд ", build: "6"},
{street: "Кутузова ул", build: "1"},
{street: "Кутузова ул", build: "10"},
{street: "Кутузова ул", build: "14"},
{street: "Кутузова ул", build: "16"},
{street: "Кутузова ул", build: "18_ETTH"},
{street: "Кутузова ул", build: "2"},
{street: "Кутузова ул", build: "24_ETTH"},
{street: "Кутузова ул", build: "26_ETTH"},
{street: "Кутузова ул", build: "27"},
{street: "Кутузова ул", build: "28_ETTH"},
{street: "Кутузова ул", build: "29"},
{street: "Кутузова ул", build: "3"},
{street: "Кутузова ул", build: "30_ETTH"},
{street: "Кутузова ул", build: "31_ETTH"},
{street: "Кутузова ул", build: "33"},
{street: "Кутузова ул", build: "36_ETTH"},
{street: "Кутузова ул", build: "38_ETTH"},
{street: "Кутузова ул", build: "40_ETTH"},
{street: "Кутузова ул", build: "42"},
{street: "Кутузова ул", build: "43_ETTH"},
{street: "Кутузова ул", build: "46_ETTH"},
{street: "Кутузова ул", build: "48_ETTH"},
{street: "Кутузова ул", build: "5"},
{street: "Кутузова ул", build: "50_ETTH"},
{street: "Кутузова ул", build: "56_ETTH"},
{street: "Кутузова ул", build: "58_ETTH"},
{street: "Кутузова ул", build: "6"},
{street: "Кутузова ул", build: "60_ETTH"},
{street: "Кутузова ул", build: "64_ETTH"},
{street: "Кутузова ул", build: "64А_ETTH"},
{street: "Кутузова ул", build: "70_ETTH"},
{street: "Кутузова ул", build: "72_ETTH"},
{street: "Кутузова ул", build: "74_ETTH"},
{street: "Кутузова ул", build: "76_ETTH"},
{street: "Кутузова ул", build: "8"},
{street: "Кутузова ул", build: "80_ETTH"},
{street: "Лазо ул", build: "1_ETTH"},
{street: "Лазо ул", build: "2_ETTH"},
{street: "Лазо ул", build: "22_ETTH"},
{street: "Лазо ул", build: "28_ETTH"},
{street: "Лазо ул", build: "32_ETTH"},
{street: "Лазо ул", build: "4_ETTH"},
{street: "Лазо ул", build: "5_ETTH"},
{street: "Лазо ул", build: "6_ETTH"},
{street: "Лазо ул", build: "7_ETTH"},
{street: "Лазо ул", build: "8А_ETTH"},
{street: "Ленина ул", build: "11_ETTH"},
{street: "Ленина ул", build: "13_ETTH"},
{street: "Ленина ул", build: "15_ETTH"},
{street: "Ленина ул", build: "17_ETTH"},
{street: "Ленина ул", build: "19_ETTH"},
{street: "Ленина ул", build: "21_ETTH"},
{street: "Ленина ул", build: "22_ETTH"},
{street: "Ленина ул", build: "23_ETTH"},
{street: "Ленина ул", build: "24_ETTH"},
{street: "Ленина ул", build: "25_ETTH"},
{street: "Ленина ул", build: "26_ETTH"},
{street: "Ленина ул", build: "27_ETTH"},
{street: "Ленина ул", build: "28_ETTH"},
{street: "Ленина ул", build: "29_ETTH"},
{street: "Ленина ул", build: "32_ETTH"},
{street: "Ленина ул", build: "33_ETTH"},
{street: "Ленина ул", build: "34_ETTH"},
{street: "Ленина ул", build: "35_ETTH"},
{street: "Ленина ул", build: "36_ETTH"},
{street: "Ленина ул", build: "38_ETTH"},
{street: "Ленина ул", build: "40_ETTH"},
{street: "Ленина ул", build: "43_ETTH"},
{street: "Ленина ул", build: "44_ETTH"},
{street: "Ленина ул", build: "47_ETTH"},
{street: "Ленина ул", build: "49_ETTH"},
{street: "Ленина ул", build: "53_ETTH"},
{street: "Ленина ул", build: "56_ETTH"},
{street: "Ленина ул", build: "68_ETTH"},
{street: "Ленина ул", build: "70_ETTH"},
{street: "Ленина ул", build: "71_ETTH"},
{street: "Ленина ул", build: "73_ETTH"},
{street: "Ленина ул", build: "74_ETTH"},
{street: "Ленина ул", build: "77_ETTH"},
{street: "Ленина ул", build: "78_ETTH"},
{street: "Ленина ул", build: "79_ETTH"},
{street: "Ленина ул", build: "81_ETTH"},
{street: "Ленина ул", build: "83_ETTH"},
{street: "Ленина ул", build: "84_ETTH"},
{street: "Ленина ул", build: "89_ETTH"},
{street: "Ленина ул", build: "9_ETTH"},
{street: "Ленина ул", build: "91_ETTH"},
{street: "Ленина ул", build: "95_ETTH"},
{street: "Луначарского ул", build: "10_ETTH"},
{street: "Луначарского ул", build: "12_ETTH"},
{street: "Луначарского ул", build: "14_ETTH"},
{street: "Луначарского ул", build: "2_ETTH"},
{street: "Луначарского ул", build: "4_ETTH"},
{street: "Луначарского ул", build: "6_ETTH"},
{street: "Луначарского ул", build: "8_ETTH"},
{street: "Маркшейдерская ул", build: "10"},
{street: "Маркшейдерская ул", build: "14"},
{street: "Маркшейдерская ул", build: "3Б"},
{street: "Маркшейдерская ул", build: "5А"},
{street: "Маркшейдерская ул", build: "5Б"},
{street: "Металлургов пр ", build: "10"},
{street: "Металлургов пр ", build: "12"},
{street: "Металлургов пр ", build: "13"},
{street: "Металлургов пр ", build: "14"},
{street: "Металлургов пр ", build: "15"},
{street: "Металлургов пр ", build: "17"},
{street: "Металлургов пр ", build: "2"},
{street: "Металлургов пр ", build: "23"},
{street: "Металлургов пр ", build: "25"},
{street: "Металлургов пр ", build: "27"},
{street: "Металлургов пр ", build: "29"},
{street: "Металлургов пр ", build: "3"},
{street: "Металлургов пр ", build: "30"},
{street: "Металлургов пр ", build: "31"},
{street: "Металлургов пр ", build: "32"},
{street: "Металлургов пр ", build: "33"},
{street: "Металлургов пр ", build: "34"},
{street: "Металлургов пр ", build: "35"},
{street: "Металлургов пр ", build: "36"},
{street: "Металлургов пр ", build: "37"},
{street: "Металлургов пр ", build: "38"},
{street: "Металлургов пр ", build: "39"},
{street: "Металлургов пр ", build: "4"},
{street: "Металлургов пр ", build: "5"},
{street: "Металлургов пр ", build: "6"},
{street: "Металлургов пр ", build: "8"},
{street: "Металлургов пр ", build: "9"},
{street: "Метелкина ул", build: "1_ETTH"},
{street: "Метелкина ул", build: "11_ETTH"},
{street: "Метелкина ул", build: "13_ETTH"},
{street: "Метелкина ул", build: "15_ETTH"},
{street: "Метелкина ул", build: "16_ETTH"},
{street: "Метелкина ул", build: "3_ETTH"},
{street: "Метелкина ул", build: "4"},
{street: "Метелкина ул", build: "9_ETTH"},
{street: "Микрорайон 13 ул", build: "1_ETTH"},
{street: "Микрорайон 13 ул", build: "10_ETTH"},
{street: "Микрорайон 13 ул", build: "11_ETTH"},
{street: "Микрорайон 13 ул", build: "12_ETTH"},
{street: "Микрорайон 13 ул", build: "14_ETTH"},
{street: "Микрорайон 13 ул", build: "16_ETTH"},
{street: "Микрорайон 13 ул", build: "17_ETTH"},
{street: "Микрорайон 13 ул", build: "17А_ETTH"},
{street: "Микрорайон 13 ул", build: "18_ETTH"},
{street: "Микрорайон 13 ул", build: "19_ETTH"},
{street: "Микрорайон 13 ул", build: "2_ETTH"},
{street: "Микрорайон 13 ул", build: "4_ETTH"},
{street: "Микрорайон 13 ул", build: "5_ETTH"},
{street: "Микрорайон 13 ул", build: "6_ETTH"},
{street: "Микрорайон 13 ул", build: "8_ETTH"},
{street: "Микрорайон 13 ул", build: "9_ETTH"},
{street: "Мира пр ", build: "10_ETTH"},
{street: "Мира пр ", build: "12_ETTH"},
{street: "Мира пр ", build: "14_ETTH"},
{street: "Мира пр ", build: "20_ETTH"},
{street: "Мира пр ", build: "22_ETTH"},
{street: "Мира пр ", build: "24_ETTH"},
{street: "Мира пр ", build: "26А_ETTH"},
{street: "Мира пр ", build: "32_ETTH"},
{street: "Мира пр ", build: "34_ETTH"},
{street: "Мира пр ", build: "36_ETTH"},
{street: "Мира пр ", build: "38_ETTH"},
{street: "Мира пр ", build: "42_ETTH"},
{street: "Мира пр ", build: "50"},
{street: "Мира пр ", build: "58"},
{street: "Мира пр ", build: "6_ETTH"},
{street: "Мира пр ", build: "8_ETTH"},
{street: "Мичурина ул", build: "10_ETTH"},
{street: "Мичурина ул", build: "12_ETTH"},
{street: "Мичурина ул", build: "13_ETTH"},
{street: "Мичурина ул", build: "14_ETTH"},
{street: "Мичурина ул", build: "15_ETTH"},
{street: "Мичурина ул", build: "15А_ETTH"},
{street: "Мичурина ул", build: "17_ETTH"},
{street: "Мичурина ул", build: "18_ETTH"},
{street: "Мичурина ул", build: "19_ETTH"},
{street: "Мичурина ул", build: "23_ETTH"},
{street: "Мичурина ул", build: "25_ETTH"},
{street: "Мичурина ул", build: "27_ETTH"},
{street: "Мичурина ул", build: "27А_ETTH"},
{street: "Мичурина ул", build: "3_ETTH"},
{street: "Мичурина ул", build: "31_ETTH"},
{street: "Мичурина ул", build: "33_ETTH"},
{street: "Мичурина ул", build: "33А_ETTH"},
{street: "Мичурина ул", build: "37_ETTH"},
{street: "Мичурина ул", build: "39_ETTH"},
{street: "Мичурина ул", build: "5_ETTH"},
{street: "Мичурина ул", build: "8_ETTH"},
{street: "Мичурина ул", build: "9_ETTH"},
{street: "Мурманская ул", build: "15_ETTH"},
{street: "Мурманская ул", build: "47_ETTH"},
{street: "Мурманская ул", build: "47/2_ETTH"},
{street: "Мурманская ул", build: "47/8_ETTH"},
{street: "Мурманская ул", build: "47/3_ETTH"},
{street: "Мурманская ул", build: "47/4_ETTH"},
{street: "Мурманская ул", build: "47/5_ETTH"},
{street: "Мурманская ул", build: "47/6_ETTH"},
{street: "Мурманская ул", build: "47/7_ETTH"},
{street: "Мурманская ул", build: "49/2_ETTH"},
{street: "Мурманская ул", build: "49/3_ETTH"},
{street: "Н.С.Ермакова пр ", build: "10"},
{street: "Н.С.Ермакова пр ", build: "11_ETTH"},
{street: "Н.С.Ермакова пр ", build: "14"},
{street: "Н.С.Ермакова пр ", build: "16"},
{street: "Н.С.Ермакова пр ", build: "18"},
{street: "Н.С.Ермакова пр ", build: "2"},
{street: "Н.С.Ермакова пр ", build: "22"},
{street: "Н.С.Ермакова пр ", build: "24"},
{street: "Н.С.Ермакова пр ", build: "28"},
{street: "Н.С.Ермакова пр ", build: "30"},
{street: "Н.С.Ермакова пр ", build: "34"},
{street: "Н.С.Ермакова пр ", build: "36"},
{street: "Н.С.Ермакова пр ", build: "6"},
{street: "Н.С.Ермакова пр ", build: "7_ETTH"},
{street: "Народная ул", build: "15_ETTH"},
{street: "Народная ул", build: "17_ETTH"},
{street: "Народная ул", build: "19_ETTH"},
{street: "Народная ул", build: "21_ETTH"},
{street: "Народная ул", build: "23_ETTH"},
{street: "Народная ул", build: "25_ETTH"},
{street: "Народная ул", build: "27А_ETTH"},
{street: "Народная ул", build: "29_ETTH"},
{street: "Народная ул", build: "3_ETTH"},
{street: "Народная ул", build: "31_ETTH"},
{street: "Народная ул", build: "33_ETTH"},
{street: "Народная ул", build: "35_ETTH"},
{street: "Народная ул", build: "37_ETTH"},
{street: "Народная ул", build: "5_ETTH"},
{street: "Народная ул", build: "7_ETTH"},
{street: "Новаторов ул", build: "10_ETTH"},
{street: "Новаторов ул", build: "11_ETTH"},
{street: "Новаторов ул", build: "12_ETTH"},
{street: "Новаторов ул", build: "13_ETTH"},
{street: "Новаторов ул", build: "14_ETTH"},
{street: "Новаторов ул", build: "15_ETTH"},
{street: "Новаторов ул", build: "3_ETTH"},
{street: "Новаторов ул", build: "4_ETTH"},
{street: "Новаторов ул", build: "5_ETTH"},
{street: "Новаторов ул", build: "6_ETTH"},
{street: "Новаторов ул", build: "6А_ETTH"},
{street: "Новаторов ул", build: "7_ETTH"},
{street: "Новаторов ул", build: "8_ETTH"},
{street: "Новаторов ул", build: "9_ETTH"},
{street: "Новобайдаевская ул", build: "1_ETTH"},
{street: "Новобайдаевская ул", build: "10_ETTH"},
{street: "Новобайдаевская ул", build: "11_ETTH"},
{street: "Новобайдаевская ул", build: "11А_ETTH"},
{street: "Новобайдаевская ул", build: "13_ETTH"},
{street: "Новобайдаевская ул", build: "14_ETTH"},
{street: "Новобайдаевская ул", build: "15_ETTH"},
{street: "Новобайдаевская ул", build: "16_ETTH"},
{street: "Новобайдаевская ул", build: "17_ETTH"},
{street: "Новобайдаевская ул", build: "18_ETTH"},
{street: "Новобайдаевская ул", build: "20_ETTH"},
{street: "Новобайдаевская ул", build: "4_ETTH"},
{street: "Новобайдаевская ул", build: "5_ETTH"},
{street: "Новобайдаевская ул", build: "6_ETTH"},
{street: "Новобайдаевская ул", build: "7_ETTH"},
{street: "Новобайдаевская ул", build: "8_ETTH"},
{street: "Новоселов ул", build: "11_ETTH"},
{street: "Новоселов ул", build: "12_ETTH"},
{street: "Новоселов ул", build: "13_ETTH"},
{street: "Новоселов ул", build: "14_ETTH"},
{street: "Новоселов ул", build: "15_ETTH"},
{street: "Новоселов ул", build: "18_ETTH"},
{street: "Новоселов ул", build: "20_ETTH"},
{street: "Новоселов ул", build: "22_ETTH"},
{street: "Новоселов ул", build: "24_ETTH"},
{street: "Новоселов ул", build: "25_ETTH"},
{street: "Новоселов ул", build: "26_ETTH"},
{street: "Новоселов ул", build: "27_ETTH"},
{street: "Новоселов ул", build: "28_ETTH"},
{street: "Новоселов ул", build: "30_ETTH"},
{street: "Новоселов ул", build: "31_ETTH"},
{street: "Новоселов ул", build: "32_ETTH"},
{street: "Новоселов ул", build: "34_ETTH"},
{street: "Новоселов ул", build: "35_ETTH"},
{street: "Новоселов ул", build: "35а_ETTH"},
{street: "Новоселов ул", build: "37_ETTH"},
{street: "Новоселов ул", build: "38_ETTH"},
{street: "Новоселов ул", build: "39_ETTH"},
{street: "Новоселов ул", build: "40_ETTH"},
{street: "Новоселов ул", build: "41_ETTH"},
{street: "Новоселов ул", build: "44_ETTH"},
{street: "Новоселов ул", build: "46_ETTH"},
{street: "Новоселов ул", build: "47_ETTH"},
{street: "Новоселов ул", build: "5_ETTH"},
{street: "Новоселов ул", build: "51_ETTH"},
{street: "Новоселов ул", build: "55_ETTH"},
{street: "Новоселов ул", build: "57_ETTH"},
{street: "Новоселов ул", build: "59_ETTH"},
{street: "Новоселов ул", build: "6_ETTH"},
{street: "Новоселов ул", build: "65_ETTH"},
{street: "Новоселов ул", build: "67_ETTH"},
{street: "Новоселов ул", build: "7_ETTH"},
{street: "Новоселов ул", build: "8_ETTH"},
{street: "Ноградская ул", build: "1_ETTH"},
{street: "Ноградская ул", build: "10"},
{street: "Ноградская ул", build: "11_ETTH"},
{street: "Ноградская ул", build: "12_ETTH"},
{street: "Ноградская ул", build: "13_ETTH"},
{street: "Ноградская ул", build: "14_ETTH"},
{street: "Ноградская ул", build: "15_ETTH"},
{street: "Ноградская ул", build: "17_ETTH"},
{street: "Ноградская ул", build: "19"},
{street: "Ноградская ул", build: "1А_ETTH"},
{street: "Ноградская ул", build: "21_ETTH"},
{street: "Ноградская ул", build: "3_ETTH"},
{street: "Ноградская ул", build: "4"},
{street: "Ноградская ул", build: "5_ETTH"},
{street: "Ноградская ул", build: "5А_ETTH"},
{street: "Ноградская ул", build: "7_ETTH"},
{street: "Ноградская ул", build: "8"},
{street: "Обнорского ул", build: "1_ETTH"},
{street: "Обнорского ул", build: "11_ETTH"},
{street: "Обнорского ул", build: "12_ETTH"},
{street: "Обнорского ул", build: "14_ETTH"},
{street: "Обнорского ул", build: "16_ETTH"},
{street: "Обнорского ул", build: "17_ETTH"},
{street: "Обнорского ул", build: "18_ETTH"},
{street: "Обнорского ул", build: "19_ETTH"},
{street: "Обнорского ул", build: "2_ETTH"},
{street: "Обнорского ул", build: "20_ETTH"},
{street: "Обнорского ул", build: "22_ETTH"},
{street: "Обнорского ул", build: "22А_ETTH"},
{street: "Обнорского ул", build: "24_ETTH"},
{street: "Обнорского ул", build: "26_ETTH"},
{street: "Обнорского ул", build: "28_ETTH"},
{street: "Обнорского ул", build: "3_ETTH"},
{street: "Обнорского ул", build: "30_ETTH"},
{street: "Обнорского ул", build: "31_ETTH"},
{street: "Обнорского ул", build: "32_ETTH"},
{street: "Обнорского ул", build: "34_ETTH"},
{street: "Обнорского ул", build: "36_ETTH"},
{street: "Обнорского ул", build: "38_ETTH"},
{street: "Обнорского ул", build: "4_ETTH"},
{street: "Обнорского ул", build: "42_ETTH"},
{street: "Обнорского ул", build: "44_ETTH"},
{street: "Обнорского ул", build: "46_ETTH"},
{street: "Обнорского ул", build: "48_ETTH"},
{street: "Обнорского ул", build: "5_ETTH"},
{street: "Обнорского ул", build: "50_ETTH"},
{street: "Обнорского ул", build: "54_ETTH"},
{street: "Обнорского ул", build: "56_ETTH"},
{street: "Обнорского ул", build: "58_ETTH"},
{street: "Обнорского ул", build: "6_ETTH"},
{street: "Обнорского ул", build: "60_ETTH"},
{street: "Обнорского ул", build: "64_ETTH"},
{street: "Обнорского ул", build: "66_ETTH"},
{street: "Обнорского ул", build: "68_ETTH"},
{street: "Обнорского ул", build: "70_ETTH"},
{street: "Обнорского ул", build: "72_ETTH"},
{street: "Обнорского ул", build: "8_ETTH"},
{street: "Обнорского ул", build: "80_ETTH"},
{street: "Обнорского ул", build: "9_ETTH"},
{street: "Октябрьский пр ", build: "10"},
{street: "Октябрьский пр ", build: "12"},
{street: "Октябрьский пр ", build: "13"},
{street: "Октябрьский пр ", build: "15"},
{street: "Октябрьский пр ", build: "16_ETTH"},
{street: "Октябрьский пр ", build: "17"},
{street: "Октябрьский пр ", build: "18_ETTH"},
{street: "Октябрьский пр ", build: "2"},
{street: "Октябрьский пр ", build: "20_ETTH"},
{street: "Октябрьский пр ", build: "21_ETTH"},
{street: "Октябрьский пр ", build: "22_ETTH"},
{street: "Октябрьский пр ", build: "22А_ETTH"},
{street: "Октябрьский пр ", build: "23_ETTH"},
{street: "Октябрьский пр ", build: "24_ETTH"},
{street: "Октябрьский пр ", build: "25_ETTH"},
{street: "Октябрьский пр ", build: "26_ETTH"},
{street: "Октябрьский пр ", build: "27_ETTH"},
{street: "Октябрьский пр ", build: "28_ETTH"},
{street: "Октябрьский пр ", build: "29_ETTH"},
{street: "Октябрьский пр ", build: "2А"},
{street: "Октябрьский пр ", build: "3"},
{street: "Октябрьский пр ", build: "30_ETTH"},
{street: "Октябрьский пр ", build: "31_ETTH"},
{street: "Октябрьский пр ", build: "32_ETTH"},
{street: "Октябрьский пр ", build: "33_ETTH"},
{street: "Октябрьский пр ", build: "34_ETTH"},
{street: "Октябрьский пр ", build: "35_ETTH"},
{street: "Октябрьский пр ", build: "36_ETTH"},
{street: "Октябрьский пр ", build: "37_ETTH"},
{street: "Октябрьский пр ", build: "37А_ETTH"},
{street: "Октябрьский пр ", build: "38_ETTH"},
{street: "Октябрьский пр ", build: "39_ETTH"},
{street: "Октябрьский пр ", build: "4"},
{street: "Октябрьский пр ", build: "40_ETTH"},
{street: "Октябрьский пр ", build: "41_ETTH"},
{street: "Октябрьский пр ", build: "42_ETTH"},
{street: "Октябрьский пр ", build: "43_ETTH"},
{street: "Октябрьский пр ", build: "44_ETTH"},
{street: "Октябрьский пр ", build: "45_ETTH"},
{street: "Октябрьский пр ", build: "46_ETTH"},
{street: "Октябрьский пр ", build: "47_ETTH"},
{street: "Октябрьский пр ", build: "48_ETTH"},
{street: "Октябрьский пр ", build: "5"},
{street: "Октябрьский пр ", build: "50_ETTH"},
{street: "Октябрьский пр ", build: "51_ETTH"},
{street: "Октябрьский пр ", build: "52_ETTH"},
{street: "Октябрьский пр ", build: "53_ETTH"},
{street: "Октябрьский пр ", build: "54_ETTH"},
{street: "Октябрьский пр ", build: "55_ETTH"},
{street: "Октябрьский пр ", build: "55А_ETTH"},
{street: "Октябрьский пр ", build: "56_ETTH"},
{street: "Октябрьский пр ", build: "57_ETTH"},
{street: "Октябрьский пр ", build: "58_ETTH"},
{street: "Октябрьский пр ", build: "59_ETTH"},
{street: "Октябрьский пр ", build: "5А"},
{street: "Октябрьский пр ", build: "6"},
{street: "Октябрьский пр ", build: "61_ETTH"},
{street: "Октябрьский пр ", build: "62_ETTH"},
{street: "Октябрьский пр ", build: "64_ETTH"},
{street: "Октябрьский пр ", build: "66_ETTH"},
{street: "Октябрьский пр ", build: "68_ETTH"},
{street: "Октябрьский пр ", build: "8"},
{street: "Олеко-Дундича ул", build: "11"},
{street: "Олеко-Дундича ул", build: "12"},
{street: "Олеко-Дундича ул", build: "13"},
{street: "Олеко-Дундича ул", build: "14"},
{street: "Олеко-Дундича ул", build: "15"},
{street: "Олеко-Дундича ул", build: "15А"},
{street: "Олеко-Дундича ул", build: "16"},
{street: "Олеко-Дундича ул", build: "2"},
{street: "Олеко-Дундича ул", build: "4"},
{street: "Олеко-Дундича ул", build: "7"},
{street: "Олеко-Дундича ул", build: "8"},
{street: "Олеко-Дундича ул", build: "9"},
{street: "Олимпийская ул", build: "12_ETTH"},
{street: "Олимпийская ул", build: "16_ETTH"},
{street: "Олимпийская ул", build: "22_ETTH"},
{street: "Олимпийская ул", build: "24_ETTH"},
{street: "Олимпийская ул", build: "4_ETTH"},
{street: "Олимпийская ул", build: "6_ETTH"},
{street: "Орджоникидзе ", build: "17_ETTH"},
{street: "Орджоникидзе ", build: "24А"},
{street: "Орджоникидзе ", build: "31"},
{street: "Орджоникидзе ", build: "33"},
{street: "П/Я 100 ул", build: "1_ETTH"},
{street: "П/Я 100 ул", build: "2_ETTH"},
{street: "Павловского ул", build: "10"},
{street: "Павловского ул", build: "12"},
{street: "Павловского ул", build: "13А"},
{street: "Павловского ул", build: "13Б"},
{street: "Павловского ул", build: "14"},
{street: "Павловского ул", build: "19_ETTH"},
{street: "Павловского ул", build: "21_ETTH"},
{street: "Павловского ул", build: "23_ETTH"},
{street: "Павловского ул", build: "29_ETTH"},
{street: "Павловского ул", build: "4"},
{street: "Пархоменко ул", build: "65_ETTH"},
{street: "Пархоменко ул", build: "71_ETTH"},
{street: "Пархоменко ул", build: "71А_ETTH"},
{street: "Пархоменко ул", build: "73_ETTH"},
{street: "Пархоменко ул", build: "74_ETTH"},
{street: "Пархоменко ул", build: "77_ETTH"},
{street: "Петракова ул", build: "45_ETTH"},
{street: "Петракова ул", build: "47_ETTH"},
{street: "Петракова ул", build: "49_ETTH"},
{street: "Петракова ул", build: "51_ETTH"},
{street: "Петракова ул", build: "53_ETTH"},
{street: "Петракова ул", build: "57_ETTH"},
{street: "Петракова ул", build: "61_ETTH"},
{street: "Петракова ул", build: "62_ETTH"},
{street: "Петракова ул", build: "62А_ETTH"},
{street: "Петракова ул", build: "64_ETTH"},
{street: "Петракова ул", build: "64А_ETTH"},
{street: "Петракова ул", build: "68_ETTH"},
{street: "Петракова ул", build: "70_ETTH"},
{street: "Петракова ул", build: "72_ETTH"},
{street: "Петракова ул", build: "74_ETTH"},
{street: "Петракова ул", build: "76_ETTH"},
{street: "Петракова ул", build: "78_ETTH"},
{street: "Пионерский пр ", build: "1"},
{street: "Пионерский пр ", build: "14"},
{street: "Пионерский пр ", build: "16"},
{street: "Пионерский пр ", build: "18"},
{street: "Пионерский пр ", build: "22"},
{street: "Пионерский пр ", build: "24"},
{street: "Пионерский пр ", build: "28"},
{street: "Пионерский пр ", build: "30"},
{street: "Пионерский пр ", build: "31"},
{street: "Пионерский пр ", build: "32"},
{street: "Пионерский пр ", build: "34"},
{street: "Пионерский пр ", build: "37"},
{street: "Пионерский пр ", build: "39"},
{street: "Пионерский пр ", build: "40"},
{street: "Пионерский пр ", build: "41"},
{street: "Пионерский пр ", build: "44"},
{street: "Пионерский пр ", build: "45"},
{street: "Пионерский пр ", build: "46"},
{street: "Пионерский пр ", build: "47"},
{street: "Пионерский пр ", build: "48"},
{street: "Пионерский пр ", build: "5"},
{street: "Пионерский пр ", build: "53"},
{street: "Пионерский пр ", build: "58"},
{street: "Пионерский пр ", build: "5А"},
{street: "Пионерский пр ", build: "6"},
{street: "Пионерский пр ", build: "60"},
{street: "Пионерский пр ", build: "62"},
{street: "Пионерский пр ", build: "64"},
{street: "Покрышкина ул", build: "10"},
{street: "Покрышкина ул", build: "11"},
{street: "Покрышкина ул", build: "12"},
{street: "Покрышкина ул", build: "13"},
{street: "Покрышкина ул", build: "14"},
{street: "Покрышкина ул", build: "15"},
{street: "Покрышкина ул", build: "17"},
{street: "Покрышкина ул", build: "19"},
{street: "Покрышкина ул", build: "21"},
{street: "Покрышкина ул", build: "22"},
{street: "Покрышкина ул", build: "23"},
{street: "Покрышкина ул", build: "24"},
{street: "Покрышкина ул", build: "25"},
{street: "Покрышкина ул", build: "26А"},
{street: "Покрышкина ул", build: "28"},
{street: "Покрышкина ул", build: "28А"},
{street: "Покрышкина ул", build: "7"},
{street: "Покрышкина ул", build: "8"},
{street: "Покрышкина ул", build: "9"},
{street: "Пржевальского ул", build: "1_ETTH"},
{street: "Пржевальского ул", build: "10_ETTH"},
{street: "Пржевальского ул", build: "11_ETTH"},
{street: "Пржевальского ул", build: "12_ETTH"},
{street: "Пржевальского ул", build: "13_ETTH"},
{street: "Пржевальского ул", build: "14_ETTH"},
{street: "Пржевальского ул", build: "16_ETTH"},
{street: "Пржевальского ул", build: "2_ETTH"},
{street: "Пржевальского ул", build: "20_ETTH"},
{street: "Пржевальского ул", build: "22_ETTH"},
{street: "Пржевальского ул", build: "24_ETTH"},
{street: "Пржевальского ул", build: "26_ETTH"},
{street: "Пржевальского ул", build: "3_ETTH"},
{street: "Пржевальского ул", build: "4_ETTH"},
{street: "Пржевальского ул", build: "5_ETTH"},
{street: "Пржевальского ул", build: "6_ETTH"},
{street: "Пржевальского ул", build: "7_ETTH"},
{street: "Пржевальского ул", build: "8_ETTH"},
{street: "Пржевальского ул", build: "9_ETTH"},
{street: "Пушкина ул", build: "15"},
{street: "Пушкина ул", build: "2"},
{street: "Пушкина ул", build: "23"},
{street: "Пушкина ул", build: "24"},
{street: "Пушкина ул", build: "27"},
{street: "Радищева ул", build: "10_ETTH"},
{street: "Радищева ул", build: "16"},
{street: "Радищева ул", build: "16_ETTH"},
{street: "Радищева ул", build: "18_ETTH"},
{street: "Радищева ул", build: "2_ETTH"},
{street: "Радищева ул", build: "20_ETTH"},
{street: "Радищева ул", build: "26_ETTH"},
{street: "Радищева ул", build: "2А"},
{street: "Радищева ул", build: "30_ETTH"},
{street: "Радищева ул", build: "32_ETTH"},
{street: "Радищева ул", build: "34_ETTH"},
{street: "Радищева ул", build: "36_ETTH"},
{street: "Радищева ул", build: "4_ETTH"},
{street: "Радищева ул", build: "6_ETTH"},
{street: "Разведчиков ул", build: "38_ETTH"},
{street: "Разведчиков ул", build: "40_ETTH"},
{street: "Разведчиков ул", build: "42_ETTH"},
{street: "Разведчиков ул", build: "44_ETTH"},
{street: "Разведчиков ул", build: "46А_ETTH"},
{street: "Разведчиков ул", build: "48_ETTH"},
{street: "Разведчиков ул", build: "50_ETTH"},
{street: "Разведчиков ул", build: "52"},
{street: "Разведчиков ул", build: "54_ETTH"},
{street: "Разведчиков ул", build: "56"},
{street: "Разведчиков ул", build: "58_ETTH"},
{street: "Разведчиков ул", build: "64"},
{street: "Разведчиков ул", build: "68"},
{street: "Разведчиков ул", build: "72_ETTH"},
{street: "Разведчиков ул", build: "76_ETTH"},
{street: "Разведчиков ул", build: "80_ETTH"},
{street: "Рокоссовского ул", build: "1_ETTH"},
{street: "Рокоссовского ул", build: "11_ETTH"},
{street: "Рокоссовского ул", build: "16"},
{street: "Рокоссовского ул", build: "17_ETTH"},
{street: "Рокоссовского ул", build: "18"},
{street: "Рокоссовского ул", build: "19"},
{street: "Рокоссовского ул", build: "19А"},
{street: "Рокоссовского ул", build: "19Б"},
{street: "Рокоссовского ул", build: "2_ETTH"},
{street: "Рокоссовского ул", build: "20"},
{street: "Рокоссовского ул", build: "21_ETTH"},
{street: "Рокоссовского ул", build: "23"},
{street: "Рокоссовского ул", build: "25"},
{street: "Рокоссовского ул", build: "27"},
{street: "Рокоссовского ул", build: "27_ETTH"},
{street: "Рокоссовского ул", build: "29"},
{street: "Рокоссовского ул", build: "29Б"},
{street: "Рокоссовского ул", build: "3_ETTH"},
{street: "Рокоссовского ул", build: "31"},
{street: "Рокоссовского ул", build: "31_ETTH"},
{street: "Рокоссовского ул", build: "33"},
{street: "Рокоссовского ул", build: "37"},
{street: "Рокоссовского ул", build: "37_ETTH"},
{street: "Рокоссовского ул", build: "4_ETTH"},
{street: "Рокоссовского ул", build: "7_ETTH"},
{street: "Рокоссовского ул", build: "8_ETTH"},
{street: "Рокоссовского ул", build: "9_ETTH"},
{street: "Свердлова ул", build: "12_ETTH"},
{street: "Свердлова ул", build: "2"},
{street: "Свердлова ул", build: "22"},
{street: "Свердлова ул", build: "24"},
{street: "Свердлова ул", build: "26"},
{street: "Свердлова ул", build: "28"},
{street: "Свердлова ул", build: "30"},
{street: "Свердлова ул", build: "8_ETTH"},
{street: "Севастопольская ул", build: "29"},
{street: "Сеченова ул", build: "11"},
{street: "Сеченова ул", build: "13"},
{street: "Сеченова ул", build: "15"},
{street: "Сеченова ул", build: "19"},
{street: "Сеченова ул", build: "19А"},
{street: "Сеченова ул", build: "21"},
{street: "Сеченова ул", build: "21А"},
{street: "Сеченова ул", build: "23"},
{street: "Сеченова ул", build: "24"},
{street: "Сеченова ул", build: "25А"},
{street: "Сеченова ул", build: "27"},
{street: "Сеченова ул", build: "3"},
{street: "Сеченова ул", build: "4"},
{street: "Сеченова ул", build: "5"},
{street: "Сеченова ул", build: "6"},
{street: "Сеченова ул", build: "7"},
{street: "Сеченова ул", build: "8"},
{street: "Сеченова ул", build: "9"},
{street: "Сибиряков-Гвардейцев ул", build: "18_ETTH"},
{street: "Сибиряков-Гвардейцев ул", build: "20_ETTH"},
{street: "Сибиряков-Гвардейцев ул", build: "22_ETTH"},
{street: "Сибиряков-Гвардейцев ул", build: "4_ETTH"},
{street: "Сибиряков-Гвардейцев ул", build: "6_ETTH"},
{street: "Сибиряков-Гвардейцев ул", build: "8_ETTH"},
{street: "Смирнова ул", build: "1_ETTH"},
{street: "Смирнова ул", build: "11_ETTH"},
{street: "Смирнова ул", build: "11А_ETTH"},
{street: "Смирнова ул", build: "12_ETTH"},
{street: "Смирнова ул", build: "13_ETTH"},
{street: "Смирнова ул", build: "14_ETTH"},
{street: "Смирнова ул", build: "15_ETTH"},
{street: "Смирнова ул", build: "17_ETTH"},
{street: "Смирнова ул", build: "3_ETTH"},
{street: "Смирнова ул", build: "8_ETTH"},
{street: "Советской Армии пр ", build: "12/40"},
{street: "Советской Армии пр ", build: "12А"},
{street: "Советской Армии пр ", build: "14"},
{street: "Советской Армии пр ", build: "16"},
{street: "Советской Армии пр ", build: "18"},
{street: "Советской Армии пр ", build: "28"},
{street: "Советской Армии пр ", build: "35_ETTH"},
{street: "Советской Армии пр ", build: "36"},
{street: "Советской Армии пр ", build: "37_ETTH"},
{street: "Советской Армии пр ", build: "39_ETTH"},
{street: "Советской Армии пр ", build: "41_ETTH"},
{street: "Советской Армии пр ", build: "43_ETTH"},
{street: "Советской Армии пр ", build: "45_ETTH"},
{street: "Советской Армии пр ", build: "47_ETTH"},
{street: "Советской Армии пр ", build: "51_ETTH"},
{street: "Советской Армии пр ", build: "52_ETTH"},
{street: "Советской Армии пр ", build: "53_ETTH"},
{street: "Советской Армии пр ", build: "54_ETTH"},
{street: "Советской Армии пр ", build: "55_ETTH"},
{street: "Советской Армии пр ", build: "56_ETTH"},
{street: "Советской Армии пр ", build: "58_ETTH"},
{street: "Советской Армии пр ", build: "60_ETTH"},
{street: "Советской Армии пр ", build: "62_ETTH"},
{street: "Спартака ул", build: "14"},
{street: "Спартака ул", build: "14Б_ETTH"},
{street: "Спартака ул", build: "18"},
{street: "Строителей пр ", build: "100_ETTH"},
{street: "Строителей пр ", build: "100А_ETTH"},
{street: "Строителей пр ", build: "104"},
{street: "Строителей пр ", build: "42_ETTH"},
{street: "Строителей пр ", build: "86_ETTH"},
{street: "Строителей пр ", build: "88_ETTH"},
{street: "Строителей пр ", build: "88Б"},
{street: "Строителей пр ", build: "90"},
{street: "Строителей пр ", build: "90Б_ETTH"},
{street: "Строителей пр ", build: "92_ETTH"},
{street: "Строителей пр ", build: "94_ETTH"},
{street: "Строителей пр ", build: "96_ETTH"},
{street: "Суворова ул", build: "2"},
{street: "Суворова ул", build: "3"},
{street: "Суворова ул", build: "4"},
{street: "Суворова ул", build: "5"},
{street: "Суворова ул", build: "6"},
{street: "Суворова ул", build: "8"},
{street: "Сусанина ул", build: "5"},
{street: "Тольятти ул", build: "1_ETTH"},
{street: "Тольятти ул", build: "10_ETTH"},
{street: "Тольятти ул", build: "15_ETTH"},
{street: "Тольятти ул", build: "16_ETTH"},
{street: "Тольятти ул", build: "17_ETTH"},
{street: "Тольятти ул", build: "18_ETTH"},
{street: "Тольятти ул", build: "19_ETTH"},
{street: "Тольятти ул", build: "2_ETTH"},
{street: "Тольятти ул", build: "21_ETTH"},
{street: "Тольятти ул", build: "23_ETTH"},
{street: "Тольятти ул", build: "25_ETTH"},
{street: "Тольятти ул", build: "26_ETTH"},
{street: "Тольятти ул", build: "28_ETTH"},
{street: "Тольятти ул", build: "29_ETTH"},
{street: "Тольятти ул", build: "30_ETTH"},
{street: "Тольятти ул", build: "31_ETTH"},
{street: "Тольятти ул", build: "32_ETTH"},
{street: "Тольятти ул", build: "34_ETTH"},
{street: "Тольятти ул", build: "3А_ETTH"},
{street: "Тольятти ул", build: "4_ETTH"},
{street: "Тольятти ул", build: "41"},
{street: "Тольятти ул", build: "42"},
{street: "Тольятти ул", build: "43"},
{street: "Тольятти ул", build: "44"},
{street: "Тольятти ул", build: "45"},
{street: "Тольятти ул", build: "45А"},
{street: "Тольятти ул", build: "46"},
{street: "Тольятти ул", build: "48"},
{street: "Тольятти ул", build: "5_ETTH"},
{street: "Тольятти ул", build: "51"},
{street: "Тольятти ул", build: "53"},
{street: "Тольятти ул", build: "58"},
{street: "Тольятти ул", build: "5Б_ETTH"},
{street: "Тольятти ул", build: "6_ETTH"},
{street: "Тольятти ул", build: "60"},
{street: "Тольятти ул", build: "62/1"},
{street: "Тольятти ул", build: "62/2"},
{street: "Тольятти ул", build: "62/5"},
{street: "Тольятти ул", build: "62/6"},
{street: "Тольятти ул", build: "64"},
{street: "Тольятти ул", build: "66"},
{street: "Тольятти ул", build: "68"},
{street: "Тольятти ул", build: "7_ETTH"},
{street: "Тольятти ул", build: "70"},
{street: "Тольятти ул", build: "72"},
{street: "Тольятти ул", build: "74"},
{street: "Тольятти ул", build: "76"},
{street: "Тольятти ул", build: "8_ETTH"},
{street: "Тореза ул", build: "10_ETTH"},
{street: "Тореза ул", build: "101"},
{street: "Тореза ул", build: "101А"},
{street: "Тореза ул", build: "103"},
{street: "Тореза ул", build: "103а"},
{street: "Тореза ул", build: "105"},
{street: "Тореза ул", build: "107"},
{street: "Тореза ул", build: "109"},
{street: "Тореза ул", build: "111"},
{street: "Тореза ул", build: "111а"},
{street: "Тореза ул", build: "113"},
{street: "Тореза ул", build: "115"},
{street: "Тореза ул", build: "117"},
{street: "Тореза ул", build: "119"},
{street: "Тореза ул", build: "12_ETTH"},
{street: "Тореза ул", build: "121"},
{street: "Тореза ул", build: "123"},
{street: "Тореза ул", build: "14_ETTH"},
{street: "Тореза ул", build: "16_ETTH"},
{street: "Тореза ул", build: "18_ETTH"},
{street: "Тореза ул", build: "2_ETTH"},
{street: "Тореза ул", build: "20_ETTH"},
{street: "Тореза ул", build: "22_ETTH"},
{street: "Тореза ул", build: "28"},
{street: "Тореза ул", build: "2А_ETTH"},
{street: "Тореза ул", build: "32"},
{street: "Тореза ул", build: "34"},
{street: "Тореза ул", build: "36"},
{street: "Тореза ул", build: "37"},
{street: "Тореза ул", build: "40"},
{street: "Тореза ул", build: "41"},
{street: "Тореза ул", build: "42"},
{street: "Тореза ул", build: "43"},
{street: "Тореза ул", build: "44"},
{street: "Тореза ул", build: "46"},
{street: "Тореза ул", build: "47"},
{street: "Тореза ул", build: "48"},
{street: "Тореза ул", build: "49"},
{street: "Тореза ул", build: "50"},
{street: "Тореза ул", build: "52"},
{street: "Тореза ул", build: "55"},
{street: "Тореза ул", build: "56"},
{street: "Тореза ул", build: "57"},
{street: "Тореза ул", build: "58"},
{street: "Тореза ул", build: "58А"},
{street: "Тореза ул", build: "6_ETTH"},
{street: "Тореза ул", build: "60"},
{street: "Тореза ул", build: "60А"},
{street: "Тореза ул", build: "61"},
{street: "Тореза ул", build: "63"},
{street: "Тореза ул", build: "64"},
{street: "Тореза ул", build: "65"},
{street: "Тореза ул", build: "67"},
{street: "Тореза ул", build: "68"},
{street: "Тореза ул", build: "70"},
{street: "Тореза ул", build: "72"},
{street: "Тореза ул", build: "73"},
{street: "Тореза ул", build: "74"},
{street: "Тореза ул", build: "75"},
{street: "Тореза ул", build: "76"},
{street: "Тореза ул", build: "78"},
{street: "Тореза ул", build: "78А"},
{street: "Тореза ул", build: "79"},
{street: "Тореза ул", build: "8_ETTH"},
{street: "Тореза ул", build: "80"},
{street: "Тореза ул", build: "82"},
{street: "Тореза ул", build: "83"},
{street: "Тореза ул", build: "84"},
{street: "Тореза ул", build: "85"},
{street: "Тореза ул", build: "86А"},
{street: "Тореза ул", build: "86Б"},
{street: "Тореза ул", build: "87"},
{street: "Тореза ул", build: "91"},
{street: "Тореза ул", build: "91б_ETTH"},
{street: "Тореза ул", build: "93"},
{street: "Тореза ул", build: "97"},
{street: "Транспортная ул", build: "103_ETTH"},
{street: "Транспортная ул", build: "103А_ETTH"},
{street: "Транспортная ул", build: "105_ETTH"},
{street: "Транспортная ул", build: "107_ETTH"},
{street: "Транспортная ул", build: "109_ETTH"},
{street: "Транспортная ул", build: "11_ETTH"},
{street: "Транспортная ул", build: "111_ETTH"},
{street: "Транспортная ул", build: "113_ETTH"},
{street: "Транспортная ул", build: "113А_ETTH"},
{street: "Транспортная ул", build: "113Б_ETTH"},
{street: "Транспортная ул", build: "115_ETTH"},
{street: "Транспортная ул", build: "117_ETTH"},
{street: "Транспортная ул", build: "119_ETTH"},
{street: "Транспортная ул", build: "121_ETTH"},
{street: "Транспортная ул", build: "123_ETTH"},
{street: "Транспортная ул", build: "125_ETTH"},
{street: "Транспортная ул", build: "127_ETTH"},
{street: "Транспортная ул", build: "129_ETTH"},
{street: "Транспортная ул", build: "13_ETTH"},
{street: "Транспортная ул", build: "131_ETTH"},
{street: "Транспортная ул", build: "133_ETTH"},
{street: "Транспортная ул", build: "21_ETTH"},
{street: "Транспортная ул", build: "23_ETTH"},
{street: "Транспортная ул", build: "25_ETTH"},
{street: "Транспортная ул", build: "27_ETTH"},
{street: "Транспортная ул", build: "3_ETTH"},
{street: "Транспортная ул", build: "31_ETTH"},
{street: "Транспортная ул", build: "33_ETTH"},
{street: "Транспортная ул", build: "35_ETTH"},
{street: "Транспортная ул", build: "41_ETTH"},
{street: "Транспортная ул", build: "43_ETTH"},
{street: "Транспортная ул", build: "45_ETTH"},
{street: "Транспортная ул", build: "49_ETTH"},
{street: "Транспортная ул", build: "49А_ETTH"},
{street: "Транспортная ул", build: "5_ETTH"},
{street: "Транспортная ул", build: "51_ETTH"},
{street: "Транспортная ул", build: "59_ETTH"},
{street: "Транспортная ул", build: "59А_ETTH"},
{street: "Транспортная ул", build: "61_ETTH"},
{street: "Транспортная ул", build: "65_ETTH"},
{street: "Транспортная ул", build: "67_ETTH"},
{street: "Транспортная ул", build: "69_ETTH"},
{street: "Транспортная ул", build: "7_ETTH"},
{street: "Транспортная ул", build: "71_ETTH"},
{street: "Транспортная ул", build: "73_ETTH"},
{street: "Транспортная ул", build: "75_ETTH"},
{street: "Транспортная ул", build: "77_ETTH"},
{street: "Транспортная ул", build: "79_ETTH"},
{street: "Транспортная ул", build: "81А_ETTH"},
{street: "Транспортная ул", build: "81Б_ETTH"},
{street: "Транспортная ул", build: "81В_ETTH"},
{street: "Транспортная ул", build: "9_ETTH"},
{street: "Транспортная ул", build: "93_ETTH"},
{street: "Транспортная ул", build: "93А_ETTH"},
{street: "Транспортная ул", build: "93Б_ETTH"},
{street: "Транспортная ул", build: "95_ETTH"},
{street: "Транспортная ул", build: "97_ETTH"},
{street: "Транспортная ул", build: "99_ETTH"},
{street: "Трестовский пер ", build: "1"},
{street: "Трестовский пер ", build: "10"},
{street: "Трестовский пер ", build: "12"},
{street: "Трестовский пер ", build: "2"},
{street: "Трестовский пер ", build: "4"},
{street: "Тузовского ул", build: "10"},
{street: "Тузовского ул", build: "11"},
{street: "Тузовского ул", build: "11А"},
{street: "Тузовского ул", build: "12"},
{street: "Тузовского ул", build: "24"},
{street: "Тузовского ул", build: "26"},
{street: "Тузовского ул", build: "28"},
{street: "Тузовского ул", build: "30"},
{street: "Тузовского ул", build: "32"},
{street: "Тузовского ул", build: "5"},
{street: "Тульская ул", build: "19_ETTH"},
{street: "Тульская ул", build: "21_ETTH"},
{street: "Фестивальная ул", build: "7А_ETTH"},
{street: "Филиппова ул", build: "12"},
{street: "Филиппова ул", build: "2"},
{street: "Филиппова ул", build: "4"},
{street: "Франкфурта ул", build: "12"},
{street: "Франкфурта ул", build: "15"},
{street: "Франкфурта ул", build: "17"},
{street: "Франкфурта ул", build: "19"},
{street: "Франкфурта ул", build: "20_ETTH"},
{street: "Франкфурта ул", build: "22_ETTH"},
{street: "Франкфурта ул", build: "25"},
{street: "Франкфурта ул", build: "4"},
{street: "Франкфурта ул", build: "5"},
{street: "Хитарова ул", build: "11"},
{street: "Хитарова ул", build: "18"},
{street: "Хитарова ул", build: "20"},
{street: "Хитарова ул", build: "22"},
{street: "Хитарова ул", build: "24"},
{street: "Хитарова ул", build: "26"},
{street: "Хитарова ул", build: "28"},
{street: "Хитарова ул", build: "34"},
{street: "Хитарова ул", build: "38"},
{street: "Циолковского ул", build: "1_ETTH"},
{street: "Циолковского ул", build: "11_ETTH"},
{street: "Циолковского ул", build: "13_ETTH"},
{street: "Циолковского ул", build: "15_ETTH"},
{street: "Циолковского ул", build: "19_ETTH"},
{street: "Циолковского ул", build: "2_ETTH"},
{street: "Циолковского ул", build: "21_ETTH"},
{street: "Циолковского ул", build: "25"},
{street: "Циолковского ул", build: "26_ETTH"},
{street: "Циолковского ул", build: "27"},
{street: "Циолковского ул", build: "28_ETTH"},
{street: "Циолковского ул", build: "29"},
{street: "Циолковского ул", build: "2А_ETTH"},
{street: "Циолковского ул", build: "3_ETTH"},
{street: "Циолковского ул", build: "30_ETTH"},
{street: "Циолковского ул", build: "32_ETTH"},
{street: "Циолковского ул", build: "33"},
{street: "Циолковского ул", build: "34_ETTH"},
{street: "Циолковского ул", build: "36_ETTH"},
{street: "Циолковского ул", build: "4_ETTH"},
{street: "Циолковского ул", build: "40_ETTH"},
{street: "Циолковского ул", build: "42_ETTH"},
{street: "Циолковского ул", build: "44_ETTH"},
{street: "Циолковского ул", build: "44А_ETTH"},
{street: "Циолковского ул", build: "46_ETTH"},
{street: "Циолковского ул", build: "48_ETTH"},
{street: "Циолковского ул", build: "5_ETTH"},
{street: "Циолковского ул", build: "50_ETTH"},
{street: "Циолковского ул", build: "51"},
{street: "Циолковского ул", build: "53"},
{street: "Циолковского ул", build: "54_ETTH"},
{street: "Циолковского ул", build: "55"},
{street: "Циолковского ул", build: "56_ETTH"},
{street: "Циолковского ул", build: "57"},
{street: "Циолковского ул", build: "58_ETTH"},
{street: "Циолковского ул", build: "60_ETTH"},
{street: "Циолковского ул", build: "61"},
{street: "Циолковского ул", build: "63"},
{street: "Циолковского ул", build: "66_ETTH"},
{street: "Циолковского ул", build: "68_ETTH"},
{street: "Циолковского ул", build: "7_ETTH"},
{street: "Циолковского ул", build: "70_ETTH"},
{street: "Циолковского ул", build: "72_ETTH"},
{street: "Циолковского ул", build: "74_ETTH"},
{street: "Циолковского ул", build: "76_ETTH"},
{street: "Циолковского ул", build: "9_ETTH"},
{street: "Чекалина ул", build: "10_ETTH"},
{street: "Чекалина ул", build: "12_ETTH"},
{street: "Чекалина ул", build: "14_ETTH"},
{street: "Чекалина ул", build: "15_ETTH"},
{street: "Чекалина ул", build: "16_ETTH"},
{street: "Чекалина ул", build: "4_ETTH"},
{street: "Челюскина ул", build: "1"},
{street: "Челюскина ул", build: "11"},
{street: "Челюскина ул", build: "17"},
{street: "Челюскина ул", build: "19"},
{street: "Челюскина ул", build: "22"},
{street: "Челюскина ул", build: "23"},
{street: "Челюскина ул", build: "24"},
{street: "Челюскина ул", build: "25"},
{street: "Челюскина ул", build: "28"},
{street: "Челюскина ул", build: "28А"},
{street: "Челюскина ул", build: "29"},
{street: "Челюскина ул", build: "30"},
{street: "Челюскина ул", build: "32"},
{street: "Челюскина ул", build: "33"},
{street: "Челюскина ул", build: "34"},
{street: "Челюскина ул", build: "37"},
{street: "Челюскина ул", build: "38"},
{street: "Челюскина ул", build: "39"},
{street: "Челюскина ул", build: "41А"},
{street: "Челюскина ул", build: "43"},
{street: "Челюскина ул", build: "46"},
{street: "Челюскина ул", build: "47"},
{street: "Челюскина ул", build: "48"},
{street: "Челюскина ул", build: "49"},
{street: "Челюскина ул", build: "50"},
{street: "Челюскина ул", build: "51А"},
{street: "Челюскина ул", build: "7"},
{street: "Челюскина ул", build: "9"},
{street: "Черемнова ул", build: "78_ETTH"},
{street: "Черноморская ул", build: "2_ETTH"},
{street: "Чернышова ул", build: "1_ETTH"},
{street: "Чернышова ул", build: "10_ETTH"},
{street: "Чернышова ул", build: "12А_ETTH"},
{street: "Чернышова ул", build: "14_ETTH"},
{street: "Чернышова ул", build: "16_ETTH"},
{street: "Чернышова ул", build: "18"},
{street: "Чернышова ул", build: "2_ETTH"},
{street: "Чернышова ул", build: "20"},
{street: "Чернышова ул", build: "20А"},
{street: "Чернышова ул", build: "3_ETTH"},
{street: "Чернышова ул", build: "4_ETTH"},
{street: "Чернышова ул", build: "6_ETTH"},
{street: "Чернышова ул", build: "8_ETTH"},
{street: "Черняховского ул", build: "1_ETTH"},
{street: "Черняховского ул", build: "3_ETTH"},
{street: "Шахтеров пр ", build: "1_ETTH"},
{street: "Шахтеров пр ", build: "10_ETTH"},
{street: "Шахтеров пр ", build: "12_ETTH"},
{street: "Шахтеров пр ", build: "14_ETTH"},
{street: "Шахтеров пр ", build: "15_ETTH"},
{street: "Шахтеров пр ", build: "16_ETTH"},
{street: "Шахтеров пр ", build: "17_ETTH"},
{street: "Шахтеров пр ", build: "18_ETTH"},
{street: "Шахтеров пр ", build: "19_ETTH"},
{street: "Шахтеров пр ", build: "2_ETTH"},
{street: "Шахтеров пр ", build: "20_ETTH"},
{street: "Шахтеров пр ", build: "21_ETTH"},
{street: "Шахтеров пр ", build: "23_ETTH"},
{street: "Шахтеров пр ", build: "24_ETTH"},
{street: "Шахтеров пр ", build: "25_ETTH"},
{street: "Шахтеров пр ", build: "26_ETTH"},
{street: "Шахтеров пр ", build: "27_ETTH"},
{street: "Шахтеров пр ", build: "28_ETTH"},
{street: "Шахтеров пр ", build: "29_ETTH"},
{street: "Шахтеров пр ", build: "3_ETTH"},
{street: "Шахтеров пр ", build: "30_ETTH"},
{street: "Шахтеров пр ", build: "31_ETTH"},
{street: "Шахтеров пр ", build: "32_ETTH"},
{street: "Шахтеров пр ", build: "32А_ETTH"},
{street: "Шахтеров пр ", build: "34_ETTH"},
{street: "Шахтеров пр ", build: "36_ETTH"},
{street: "Шахтеров пр ", build: "4_ETTH"},
{street: "Шахтеров пр ", build: "5_ETTH"},
{street: "Шахтеров пр ", build: "6_ETTH"},
{street: "Шахтеров пр ", build: "8_ETTH"},
{street: "Шахтеров пр ", build: "9_ETTH"},
{street: "Шахтостроительный пер ", build: "12"},
{street: "Шолохова ул", build: "1_ETTH"},
{street: "Шолохова ул", build: "13_ETTH"},
{street: "Шолохова ул", build: "17_ETTH"},
{street: "Шолохова ул", build: "3_ETTH"},
{street: "Шолохова ул", build: "5_ETTH"},
{street: "Шолохова ул", build: "7_ETTH"},
{street: "Шолохова ул", build: "9_ETTH"},
{street: "Шункова ул", build: "1_ETTH"},
{street: "Шункова ул", build: "10_ETTH"},
{street: "Шункова ул", build: "11_ETTH"},
{street: "Шункова ул", build: "12_ETTH"},
{street: "Шункова ул", build: "13_ETTH"},
{street: "Шункова ул", build: "14_ETTH"},
{street: "Шункова ул", build: "15_ETTH"},
{street: "Шункова ул", build: "16_ETTH"},
{street: "Шункова ул", build: "17_ETTH"},
{street: "Шункова ул", build: "18_ETTH"},
{street: "Шункова ул", build: "19_ETTH"},
{street: "Шункова ул", build: "1А_ETTH"},
{street: "Шункова ул", build: "2_ETTH"},
{street: "Шункова ул", build: "20_ETTH"},
{street: "Шункова ул", build: "20А_ETTH"},
{street: "Шункова ул", build: "21_ETTH"},
{street: "Шункова ул", build: "23_ETTH"},
{street: "Шункова ул", build: "24_ETTH"},
{street: "Шункова ул", build: "3_ETTH"},
{street: "Шункова ул", build: "4_ETTH"},
{street: "Шункова ул", build: "7_ETTH"},
{street: "Шункова ул", build: "9_ETTH"},
{street: "Энтузиастов ул", build: "13"},
{street: "Энтузиастов ул", build: "15"},
{street: "Энтузиастов ул", build: "17"},
{street: "Энтузиастов ул", build: "19"},
{street: "Энтузиастов ул", build: "23"},
{street: "Энтузиастов ул", build: "25"},
{street: "Энтузиастов ул", build: "27"},
{street: "Энтузиастов ул", build: "29"},
{street: "Энтузиастов ул", build: "3"},
{street: "Энтузиастов ул", build: "31"},
{street: "Энтузиастов ул", build: "33"},
{street: "Энтузиастов ул", build: "35"},
{street: "Энтузиастов ул", build: "37"},
{street: "Энтузиастов ул", build: "39"},
{street: "Энтузиастов ул", build: "45"},
{street: "Энтузиастов ул", build: "47"},
{street: "Энтузиастов ул", build: "49"},
{street: "Энтузиастов ул", build: "5"},
{street: "Энтузиастов ул", build: "51"},
{street: "Энтузиастов ул", build: "53"},
{street: "Энтузиастов ул", build: "57"},
{street: "Энтузиастов ул", build: "59"},
{street: "Энтузиастов ул", build: "6"},
{street: "Энтузиастов ул", build: "61"},
{street: "Энтузиастов ул", build: "63"},
{street: "Энтузиастов ул", build: "65"},
{street: "Энтузиастов ул", build: "7"},
{street: "Энтузиастов ул", build: "8"},
{street: "Юбилейная ул", build: "3"},
{street: "Юбилейная ул", build: "5"},
{street: "Юбилейная ул", build: "7"},
{street: "Ярославская ул", build: "1"},
{street: "Ярославская ул", build: "12"},
{street: "Ярославская ул", build: "14"},
{street: "Ярославская ул", build: "16"},
{street: "Ярославская ул", build: "18"},
{street: "Ярославская ул", build: "2"},
{street: "Ярославская ул", build: "20"},
{street: "Ярославская ул", build: "22"},
{street: "Ярославская ул", build: "22А"},
{street: "Ярославская ул", build: "24"},
{street: "Ярославская ул", build: "26"},
{street: "Ярославская ул", build: "28"},
{street: "Ярославская ул", build: "3"},
{street: "Ярославская ул", build: "30"},
{street: "Ярославская ул", build: "32"},
{street: "Ярославская ул", build: "34"},
{street: "Ярославская ул", build: "36"},
{street: "Ярославская ул", build: "36А"},
{street: "Ярославская ул", build: "38"},
{street: "Ярославская ул", build: "3А"},
{street: "Ярославская ул", build: "4"},
{street: "Ярославская ул", build: "40"},
{street: "Ярославская ул", build: "42"},
{street: "Ярославская ул", build: "44"},
{street: "Ярославская ул", build: "46"},
{street: "Ярославская ул", build: "48"},
{street: "Ярославская ул", build: "48А"},
{street: "Ярославская ул", build: "50"},
{street: "Ярославская ул", build: "54"},
{street: "Ярославская ул", build: "56А"},
{street: "Ярославская ул", build: "56Б"},
{street: "Ярославская ул", build: "56В"},
], streets: [{street: "1 Мая ул"},
{street: "11 Гвардейской Армии ул"},
{street: "25 Лет Октября ул"},
{street: "40 Лет Влксм ул"},
{street: "40 Лет Победы ул"},
{street: "Авиаторов пр "},
{street: "Архитекторов пр "},
{street: "Бардина пр "},
{street: "Батюшкова ул"},
{street: "Белана ул"},
{street: "Белградская ул"},
{street: "Березовая Роща ул"},
{street: "Библиотечный Проезд "},
{street: "Братьев Гаденовых ул"},
{street: "Братьев Сизых ул"},
{street: "Бугарева ул"},
{street: "Бульварный пер "},
{street: "Ватутина ул"},
{street: "Веры Соломиной ул"},
{street: "Вокзальная ул"},
{street: "Воробьева ул"},
{street: "Воровского ул"},
{street: "Герцена ул"},
{street: "Глинки ул"},
{street: "Горьковская ул"},
{street: "Грдины ул"},
{street: "Грибоедова ул"},
{street: "День Шахтера ул"},
{street: "Дорстроевская ул"},
{street: "Дружбы пр "},
{street: "Дузенко ул"},
{street: "Екимова ул"},
{street: "Запорожская ул"},
{street: "Запсибовцев пр "},
{street: "Звездова ул"},
{street: "Зорге ул"},
{street: "Зыряновская ул"},
{street: "Интернатная ул"},
{street: "Казарновского Проезд "},
{street: "Капитальная ул"},
{street: "Карла Маркса ул"},
{street: "Кирова ул"},
{street: "Климасенко ул"},
{street: "Клименко ул"},
{street: "Конева ул"},
{street: "Косилова ул"},
{street: "Космонавтов ул"},
{street: "Косыгина ул"},
{street: "Кузнецкстроевский пр "},
{street: "Кузнецова ул"},
{street: "Куйбышева ул"},
{street: "Кулакова пер "},
{street: "Курако пр "},
{street: "Курбатова Проезд "},
{street: "Кутузова ул"},
{street: "Лазо ул"},
{street: "Ленина ул"},
{street: "Луначарского ул"},
{street: "Маркшейдерская ул"},
{street: "Металлургов пр "},
{street: "Метелкина ул"},
{street: "Микрорайон 13 ул"},
{street: "Мира пр "},
{street: "Мичурина ул"},
{street: "Мурманская ул"},
{street: "Н.С.Ермакова пр "},
{street: "Народная ул"},
{street: "Новаторов ул"},
{street: "Новобайдаевская ул"},
{street: "Новоселов ул"},
{street: "Ноградская ул"},
{street: "Обнорского ул"},
{street: "Октябрьский пр "},
{street: "Олеко-Дундича ул"},
{street: "Олимпийская ул"},
{street: "Орджоникидзе "},
{street: "П/Я 100 ул"},
{street: "Павловского ул"},
{street: "Пархоменко ул"},
{street: "Петракова ул"},
{street: "Пионерский пр "},
{street: "Покрышкина ул"},
{street: "Пржевальского ул"},
{street: "Пушкина ул"},
{street: "Радищева ул"},
{street: "Разведчиков ул"},
{street: "Рокоссовского ул"},
{street: "Свердлова ул"},
{street: "Севастопольская ул"},
{street: "Сеченова ул"},
{street: "Сибиряков-Гвардейцев ул"},
{street: "Смирнова ул"},
{street: "Советской Армии пр "},
{street: "Спартака ул"},
{street: "Строителей пр "},
{street: "Суворова ул"},
{street: "Сусанина ул"},
{street: "Тольятти ул"},
{street: "Тореза ул"},
{street: "Транспортная ул"},
{street: "Трестовский пер "},
{street: "Тузовского ул"},
{street: "Тульская ул"},
{street: "Фестивальная ул"},
{street: "Филиппова ул"},
{street: "Франкфурта ул"},
{street: "Хитарова ул"},
{street: "Циолковского ул"},
{street: "Чекалина ул"},
{street: "Челюскина ул"},
{street: "Черемнова ул"},
{street: "Черноморская ул"},
{street: "Чернышова ул"},
{street: "Черняховского ул"},
{street: "Шахтеров пр "},
{street: "Шахтостроительный пер "},
{street: "Шолохова ул"},
{street: "Шункова ул"},
{street: "Энтузиастов ул"},
{street: "Юбилейная ул"},
{street: "Ярославская ул"},
] };
