city_streets["osinniki"] = {builds: [{street: "50 Лет Октября ул", build: "12"},
{street: "50 Лет Октября ул", build: "12а"},
{street: "50 Лет Октября ул", build: "14"},
{street: "50 Лет Октября ул", build: "14а"},
{street: "50 Лет Октября ул", build: "16"},
{street: "50 Лет Октября ул", build: "20"},
{street: "50 Лет Октября ул", build: "20а"},
{street: "50 Лет Октября ул", build: "22"},
{street: "50 Лет Октября ул", build: "22а"},
{street: "50 Лет Октября ул", build: "24"},
{street: "50 Лет Октября ул", build: "26"},
{street: "Гагарина ул", build: "20б"},
{street: "Ермака ул", build: "16А"},
{street: "Ефимова ул", build: "10"},
{street: "Ефимова ул", build: "10а"},
{street: "Ефимова ул", build: "10б"},
{street: "Ефимова ул", build: "11"},
{street: "Ефимова ул", build: "12"},
{street: "Ефимова ул", build: "12а"},
{street: "Ефимова ул", build: "14"},
{street: "Ефимова ул", build: "16"},
{street: "Ефимова ул", build: "18"},
{street: "Ефимова ул", build: "18/1"},
{street: "Ефимова ул", build: "18/2"},
{street: "Ефимова ул", build: "2"},
{street: "Ефимова ул", build: "20"},
{street: "Ефимова ул", build: "22"},
{street: "Ефимова ул", build: "24"},
{street: "Ефимова ул", build: "24/1"},
{street: "Ефимова ул", build: "24/2"},
{street: "Ефимова ул", build: "28"},
{street: "Ефимова ул", build: "30"},
{street: "Ефимова ул", build: "32"},
{street: "Ефимова ул", build: "34"},
{street: "Ефимова ул", build: "38"},
{street: "Ефимова ул", build: "4"},
{street: "Ефимова ул", build: "40"},
{street: "Ефимова ул", build: "40/1"},
{street: "Ефимова ул", build: "42"},
{street: "Ефимова ул", build: "44"},
{street: "Ефимова ул", build: "46"},
{street: "Ефимова ул", build: "48"},
{street: "Ефимова ул", build: "8/1"},
{street: "Ефимова ул", build: "8/2"},
{street: "Ефимова ул", build: "9"},
{street: "Кирова 1-Й пер ", build: "1"},
{street: "Кирова 2-Й пер ", build: "2"},
{street: "Кирова ул", build: "11"},
{street: "Кирова ул", build: "13"},
{street: "Кирова ул", build: "2"},
{street: "Кирова ул", build: "29"},
{street: "Кирова ул", build: "4"},
{street: "Кирова ул", build: "43"},
{street: "Кирова ул", build: "47"},
{street: "Кирова ул", build: "49"},
{street: "Кирова ул", build: "7"},
{street: "Кирова ул", build: "76/1"},
{street: "Кирова ул", build: "9"},
{street: "Комсомольский пер ", build: "2"},
{street: "Комсомольский пер ", build: "4"},
{street: "Комсомольский пер ", build: "6"},
{street: "Комсомольский пер ", build: "8"},
{street: "Королева ул", build: "11"},
{street: "Королева ул", build: "11/1"},
{street: "Королева ул", build: "3/1"},
{street: "Королева ул", build: "5/1"},
{street: "Королева ул", build: "7/1"},
{street: "Королева ул", build: "9/1"},
{street: "Ленина ул", build: "56"},
{street: "Ленина ул", build: "60"},
{street: "Ленина ул", build: "62"},
{street: "Победы ул", build: "21"},
{street: "Победы ул", build: "21а"},
{street: "Победы ул", build: "21б"},
{street: "Победы ул", build: "23"},
{street: "Победы ул", build: "25"},
{street: "Победы ул", build: "27"},
{street: "Победы ул", build: "29"},
{street: "Победы ул", build: "29а"},
{street: "Победы ул", build: "35а"},
{street: "Победы ул", build: "36"},
{street: "Победы ул", build: "37"},
{street: "Победы ул", build: "37а"},
{street: "Победы ул", build: "39а"},
{street: "Победы ул", build: "40"},
{street: "Победы ул", build: "41"},
{street: "Победы ул", build: "42"},
{street: "Победы ул", build: "44"},
{street: "Победы ул", build: "46"},
{street: "Победы ул", build: "48"},
{street: "Победы ул", build: "50"},
{street: "Победы ул", build: "52"},
{street: "Революции ул", build: "19"},
{street: "Революции ул", build: "21"},
{street: "Революции ул", build: "23"},
{street: "Революции ул", build: "27"},
{street: "Революции ул", build: "29"},
{street: "Революции ул", build: "31"},
{street: "Революции ул", build: "31/1"},
{street: "Революции ул", build: "33"},
{street: "Революции ул", build: "35"},
{street: "Революции ул", build: "39"},
{street: "Советская ул", build: "10"},
{street: "Советская ул", build: "12"},
{street: "Студенческая ул", build: "13/1"},
], streets: [{street: "50 Лет Октября ул"},
{street: "Гагарина ул"},
{street: "Ермака ул"},
{street: "Ефимова ул"},
{street: "Кирова 1-Й пер "},
{street: "Кирова 2-Й пер "},
{street: "Кирова ул"},
{street: "Комсомольский пер "},
{street: "Королева ул"},
{street: "Ленина ул"},
{street: "Победы ул"},
{street: "Революции ул"},
{street: "Советская ул"},
{street: "Студенческая ул"},
] };
