city_streets["osinniki"] = {builds: [{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "12"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "14"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "16"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "20"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "22"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "24"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: "26"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 12а"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 14а"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 20а"},
{street: "50 ЛЕТ ОКТЯБРЯ УЛИЦА ", build: " 22а"},
{street: "ГАГАРИНА УЛИЦА ", build: " 20б"},
{street: "ЕРМАКА УЛИЦА ", build: " 16А"},
{street: "ЕФИМОВА УЛИЦА ", build: "2"},
{street: "ЕФИМОВА УЛИЦА ", build: "4"},
{street: "ЕФИМОВА УЛИЦА ", build: "9"},
{street: "ЕФИМОВА УЛИЦА ", build: "10"},
{street: "ЕФИМОВА УЛИЦА ", build: "11"},
{street: "ЕФИМОВА УЛИЦА ", build: "12"},
{street: "ЕФИМОВА УЛИЦА ", build: "14"},
{street: "ЕФИМОВА УЛИЦА ", build: "16"},
{street: "ЕФИМОВА УЛИЦА ", build: "18"},
{street: "ЕФИМОВА УЛИЦА ", build: "20"},
{street: "ЕФИМОВА УЛИЦА ", build: "22"},
{street: "ЕФИМОВА УЛИЦА ", build: "24"},
{street: "ЕФИМОВА УЛИЦА ", build: "28"},
{street: "ЕФИМОВА УЛИЦА ", build: "30"},
{street: "ЕФИМОВА УЛИЦА ", build: "32"},
{street: "ЕФИМОВА УЛИЦА ", build: "34"},
{street: "ЕФИМОВА УЛИЦА ", build: "38"},
{street: "ЕФИМОВА УЛИЦА ", build: "40"},
{street: "ЕФИМОВА УЛИЦА ", build: "42"},
{street: "ЕФИМОВА УЛИЦА ", build: "44"},
{street: "ЕФИМОВА УЛИЦА ", build: "46"},
{street: "ЕФИМОВА УЛИЦА ", build: "48"},
{street: "ЕФИМОВА УЛИЦА ", build: " 10а"},
{street: "ЕФИМОВА УЛИЦА ", build: " 10б"},
{street: "ЕФИМОВА УЛИЦА ", build: " 12а"},
{street: "ЕФИМОВА УЛИЦА ", build: " 18/1"},
{street: "ЕФИМОВА УЛИЦА ", build: " 18/2"},
{street: "ЕФИМОВА УЛИЦА ", build: " 24/1"},
{street: "ЕФИМОВА УЛИЦА ", build: " 24/2"},
{street: "ЕФИМОВА УЛИЦА ", build: " 40/1"},
{street: "ЕФИМОВА УЛИЦА ", build: " 8/1"},
{street: "ЕФИМОВА УЛИЦА ", build: " 8/2"},
{street: "КИРОВА 1-Й ПЕРЕУЛОК ", build: "1"},
{street: "КИРОВА 2-Й ПЕРЕУЛОК ", build: "2"},
{street: "КИРОВА УЛИЦА ", build: "2"},
{street: "КИРОВА УЛИЦА ", build: "4"},
{street: "КИРОВА УЛИЦА ", build: "7"},
{street: "КИРОВА УЛИЦА ", build: "9"},
{street: "КИРОВА УЛИЦА ", build: "11"},
{street: "КИРОВА УЛИЦА ", build: "13"},
{street: "КИРОВА УЛИЦА ", build: "29"},
{street: "КИРОВА УЛИЦА ", build: "43"},
{street: "КИРОВА УЛИЦА ", build: "47"},
{street: "КИРОВА УЛИЦА ", build: "49"},
{street: "КИРОВА УЛИЦА ", build: " 76/1"},
{street: "КОМСОМОЛЬСКИЙ ПЕРЕУЛОК ", build: "2"},
{street: "КОМСОМОЛЬСКИЙ ПЕРЕУЛОК ", build: "4"},
{street: "КОМСОМОЛЬСКИЙ ПЕРЕУЛОК ", build: "6"},
{street: "КОМСОМОЛЬСКИЙ ПЕРЕУЛОК ", build: "8"},
{street: "КОРОЛЕВА УЛИЦА ", build: "11"},
{street: "КОРОЛЕВА УЛИЦА ", build: " 11/1"},
{street: "КОРОЛЕВА УЛИЦА ", build: " 3/1"},
{street: "КОРОЛЕВА УЛИЦА ", build: " 5/1"},
{street: "КОРОЛЕВА УЛИЦА ", build: " 7/1"},
{street: "КОРОЛЕВА УЛИЦА ", build: " 9/1"},
{street: "ЛЕНИНА УЛИЦА ", build: "56"},
{street: "ЛЕНИНА УЛИЦА ", build: "60"},
{street: "ЛЕНИНА УЛИЦА ", build: "62"},
{street: "ПОБЕДЫ УЛИЦА ", build: "21"},
{street: "ПОБЕДЫ УЛИЦА ", build: "23"},
{street: "ПОБЕДЫ УЛИЦА ", build: "25"},
{street: "ПОБЕДЫ УЛИЦА ", build: "27"},
{street: "ПОБЕДЫ УЛИЦА ", build: "29"},
{street: "ПОБЕДЫ УЛИЦА ", build: "36"},
{street: "ПОБЕДЫ УЛИЦА ", build: "37"},
{street: "ПОБЕДЫ УЛИЦА ", build: "40"},
{street: "ПОБЕДЫ УЛИЦА ", build: "41"},
{street: "ПОБЕДЫ УЛИЦА ", build: "42"},
{street: "ПОБЕДЫ УЛИЦА ", build: "44"},
{street: "ПОБЕДЫ УЛИЦА ", build: "46"},
{street: "ПОБЕДЫ УЛИЦА ", build: "48"},
{street: "ПОБЕДЫ УЛИЦА ", build: "50"},
{street: "ПОБЕДЫ УЛИЦА ", build: "52"},
{street: "ПОБЕДЫ УЛИЦА ", build: " 21а"},
{street: "ПОБЕДЫ УЛИЦА ", build: " 21б"},
{street: "ПОБЕДЫ УЛИЦА ", build: " 29а"},
{street: "ПОБЕДЫ УЛИЦА ", build: " 35а"},
{street: "ПОБЕДЫ УЛИЦА ", build: " 37а"},
{street: "ПОБЕДЫ УЛИЦА ", build: " 39а"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "19"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "21"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "23"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "27"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "29"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "31"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "33"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "35"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: "39"},
{street: "РЕВОЛЮЦИИ УЛИЦА ", build: " 31/1"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "10"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "12"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: " 13/1"},
], streets: [{street: "ЕРМАКА УЛИЦА "},
{street: "ЕФИМОВА УЛИЦА "},
{street: "КИРОВА 1-Й ПЕРЕУЛОК "},
{street: "КИРОВА 2-Й ПЕРЕУЛОК "},
{street: "КОМСОМОЛЬСКИЙ ПЕРЕУЛОК "},
{street: "КОРОЛЕВА УЛИЦА "},
{street: "РЕВОЛЮЦИИ УЛИЦА "},
] };
