city_streets["polysaevo"] = {builds: [{street: "Автодорожная ул", build: "25"},
{street: "Автодорожная ул", build: "29"},
{street: "Анжерская ул", build: "4"},
{street: "Бажова ул", build: "3"},
{street: "Бажова ул", build: "5"},
{street: "Бажова ул", build: "7"},
{street: "Бакинская ул", build: "1"},
{street: "Бакинская ул", build: "14"},
{street: "Бакинская ул", build: "16"},
{street: "Бакинская ул", build: "18"},
{street: "Бакинская ул", build: "1а"},
{street: "Бакинская ул", build: "3"},
{street: "Бакинская ул", build: "3а"},
{street: "Бакинская ул", build: "5"},
{street: "Бакинская ул", build: "6"},
{street: "Бакинская ул", build: "8"},
{street: "Волжская ул", build: "13"},
{street: "Волжская ул", build: "13а"},
{street: "Волжская ул", build: "15"},
{street: "Волжская ул", build: "3"},
{street: "Жукова ул", build: "10"},
{street: "Жукова ул", build: "4"},
{street: "Жукова ул", build: "6"},
{street: "Жукова ул", build: "8"},
{street: "Иркутская ул", build: "2"},
{street: "Иркутская ул", build: "4"},
{street: "Иркутская ул", build: "4А"},
{street: "Иркутская ул", build: "6"},
{street: "Иркутская ул", build: "8"},
{street: "Конституции ул", build: "11А"},
{street: "Космонавтов ул", build: "36А"},
{street: "Космонавтов ул", build: "37"},
{street: "Космонавтов ул", build: "38А"},
{street: "Космонавтов ул", build: "39"},
{street: "Космонавтов ул", build: "39А"},
{street: "Космонавтов ул", build: "43"},
{street: "Космонавтов ул", build: "45"},
{street: "Космонавтов ул", build: "47"},
{street: "Космонавтов ул", build: "51"},
{street: "Космонавтов ул", build: "53"},
{street: "Космонавтов ул", build: "57"},
{street: "Космонавтов ул", build: "61"},
{street: "Космонавтов ул", build: "62"},
{street: "Космонавтов ул", build: "63"},
{street: "Космонавтов ул", build: "65"},
{street: "Космонавтов ул", build: "65а"},
{street: "Космонавтов ул", build: "67"},
{street: "Космонавтов ул", build: "68"},
{street: "Космонавтов ул", build: "71"},
{street: "Космонавтов ул", build: "73"},
{street: "Космонавтов ул", build: "75"},
{street: "Космонавтов ул", build: "77/1"},
{street: "Космонавтов ул", build: "77/2"},
{street: "Космонавтов ул", build: "77/3"},
{street: "Космонавтов ул", build: "77а"},
{street: "Космонавтов ул", build: "78"},
{street: "Космонавтов ул", build: "80"},
{street: "Космонавтов ул", build: "82"},
{street: "Космонавтов ул", build: "82А"},
{street: "Космонавтов ул", build: "84"},
{street: "Космонавтов ул", build: "88"},
{street: "Космонавтов ул", build: "88а"},
{street: "Космонавтов ул", build: "90"},
{street: "Космонавтов ул", build: "90а"},
{street: "Космонавтов ул", build: "92"},
{street: "Космонавтов ул", build: "92а"},
{street: "Космонавтов ул", build: "94"},
{street: "Космонавтов ул", build: "94/1"},
{street: "Космонавтов ул", build: "98"},
{street: "Кремлевская ул", build: "1"},
{street: "Кремлевская ул", build: "2"},
{street: "Кремлевская ул", build: "21"},
{street: "Крупской ул", build: "102"},
{street: "Крупской ул", build: "108"},
{street: "Крупской ул", build: "110"},
{street: "Крупской ул", build: "112"},
{street: "Крупской ул", build: "114"},
{street: "Крупской ул", build: "116"},
{street: "Крупской ул", build: "118"},
{street: "Крупской ул", build: "126"},
{street: "Крупской ул", build: "130"},
{street: "Крупской ул", build: "64"},
{street: "Крупской ул", build: "66"},
{street: "Крупской ул", build: "68"},
{street: "Крупской ул", build: "70"},
{street: "Крупской ул", build: "72"},
{street: "Крупской ул", build: "74"},
{street: "Крупской ул", build: "76"},
{street: "Крупской ул", build: "80"},
{street: "Крупской ул", build: "84"},
{street: "Крупской ул", build: "86"},
{street: "Крупской ул", build: "92"},
{street: "Крупской ул", build: "98"},
{street: "Молодежная ул", build: "17"},
{street: "Молодежная ул", build: "19"},
{street: "Молодежная ул", build: "31"},
{street: "Молодогвардейцев ул", build: "26"},
{street: "Молодогвардейцев ул", build: "28"},
{street: "Победы ул", build: "1"},
{street: "Победы ул", build: "2"},
{street: "Победы ул", build: "3"},
{street: "Победы ул", build: "4"},
{street: "Победы ул", build: "5"},
{street: "Победы ул", build: "6"},
{street: "Покрышкина ул", build: "1"},
{street: "Покрышкина ул", build: "11"},
{street: "Покрышкина ул", build: "17"},
{street: "Покрышкина ул", build: "3"},
{street: "Покрышкина ул", build: "5"},
{street: "Покрышкина ул", build: "7"},
{street: "Покрышкина ул", build: "9"},
{street: "Прокопьевская ул", build: "19"},
{street: "Республиканская ул", build: "1"},
{street: "Республиканская ул", build: "11"},
{street: "Республиканская ул", build: "2"},
{street: "Республиканская ул", build: "3"},
{street: "Республиканская ул", build: "4"},
{street: "Республиканская ул", build: "6"},
{street: "Республиканская ул", build: "9"},
{street: "Свердлова ул", build: "3"},
{street: "Свердлова ул", build: "5"},
{street: "Свердлова ул", build: "7"},
{street: "Свердлова ул", build: "9"},
{street: "Севастопольская ул", build: "50"},
{street: "Техническая ул", build: "15"},
{street: "Техническая ул", build: "17"},
{street: "Техническая ул", build: "9"},
{street: "Техническая ул", build: "9/1"},
{street: "Токарева ул", build: "20"},
{street: "Читинская ул", build: "35"},
{street: "Читинская ул", build: "37"},
{street: "Читинская ул", build: "39"},
{street: "Читинская ул", build: "39А"},
{street: "Читинская ул", build: "41"},
{street: "Шукшина ул", build: "20"},
{street: "Шукшина ул", build: "24"},
{street: "Шукшина ул", build: "25"},
{street: "Шукшина ул", build: "26"},
{street: "Шукшина ул", build: "27"},
{street: "Шукшина ул", build: "30"},
{street: "Шукшина ул", build: "31"},
{street: "Шукшина ул", build: "32"},
{street: "Шукшина ул", build: "33"},
{street: "Шукшина ул", build: "36"},
{street: "Ягодная ул", build: "1"},
{street: "Ягодная ул", build: "2"},
{street: "Ягодная ул", build: "3"},
{street: "Ягодная ул", build: "4"},
], streets: [{street: "Автодорожная ул"},
{street: "Анжерская ул"},
{street: "Бажова ул"},
{street: "Бакинская ул"},
{street: "Волжская ул"},
{street: "Жукова ул"},
{street: "Иркутская ул"},
{street: "Конституции ул"},
{street: "Космонавтов ул"},
{street: "Кремлевская ул"},
{street: "Крупской ул"},
{street: "Молодежная ул"},
{street: "Молодогвардейцев ул"},
{street: "Победы ул"},
{street: "Покрышкина ул"},
{street: "Прокопьевская ул"},
{street: "Республиканская ул"},
{street: "Свердлова ул"},
{street: "Севастопольская ул"},
{street: "Техническая ул"},
{street: "Токарева ул"},
{street: "Читинская ул"},
{street: "Шукшина ул"},
{street: "Ягодная ул"},
] };
