city_streets["prokopievsk"] = {builds: [{street: "10-Й МИКРОРАЙОН ", build: "1"},
{street: "10-Й МИКРОРАЙОН ", build: "2"},
{street: "10-Й МИКРОРАЙОН ", build: "3"},
{street: "10-Й МИКРОРАЙОН ", build: "4"},
{street: "10-Й МИКРОРАЙОН ", build: "5"},
{street: "10-Й МИКРОРАЙОН ", build: "6"},
{street: "10-Й МИКРОРАЙОН ", build: "7"},
{street: "10-Й МИКРОРАЙОН ", build: "8"},
{street: "10-Й МИКРОРАЙОН ", build: "9"},
{street: "10-Й МИКРОРАЙОН ", build: "10"},
{street: "10-Й МИКРОРАЙОН ", build: "11"},
{street: "10-Й МИКРОРАЙОН ", build: "12"},
{street: "10-Й МИКРОРАЙОН ", build: "13"},
{street: "10-Й МИКРОРАЙОН ", build: "14"},
{street: "10-Й МИКРОРАЙОН ", build: "15"},
{street: "10-Й МИКРОРАЙОН ", build: "16"},
{street: "10-Й МИКРОРАЙОН ", build: "17"},
{street: "10-Й МИКРОРАЙОН ", build: "18"},
{street: "10-Й МИКРОРАЙОН ", build: "19"},
{street: "10-Й МИКРОРАЙОН ", build: "20"},
{street: "10-Й МИКРОРАЙОН ", build: "21"},
{street: "10-Й МИКРОРАЙОН ", build: "22"},
{street: "10-Й МИКРОРАЙОН ", build: "23"},
{street: "10-Й МИКРОРАЙОН ", build: "24"},
{street: "10-Й МИКРОРАЙОН ", build: "25"},
{street: "10-Й МИКРОРАЙОН ", build: "26"},
{street: "10-Й МИКРОРАЙОН ", build: "27"},
{street: "10-Й МИКРОРАЙОН ", build: "28"},
{street: "10-Й МИКРОРАЙОН ", build: "29"},
{street: "10-Й МИКРОРАЙОН ", build: "30"},
{street: "10-Й МИКРОРАЙОН ", build: "31"},
{street: "10-Й МИКРОРАЙОН ", build: "52"},
{street: "10-Й МИКРОРАЙОН ", build: " 12А"},
{street: "10-Й МИКРОРАЙОН ", build: " 16А"},
{street: "10-Й МИКРОРАЙОН ", build: " 18А"},
{street: "10-Й МИКРОРАЙОН ", build: " 25А"},
{street: "10-Й МИКРОРАЙОН ", build: " 46А"},
{street: "10-Й МИКРОРАЙОН ", build: " 6А"},
{street: "2-Я КИРПИЧНАЯ УЛИЦА ", build: "5"},
{street: "2-Я КИРПИЧНАЯ УЛИЦА ", build: "7"},
{street: "2-Я КИРПИЧНАЯ УЛИЦА ", build: " 7А"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "3"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "6"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "7"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "12"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "13"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "15"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "17"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "22"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "24"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: "28"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: " 20Б"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: " 22А"},
{street: "2-Я КОКСОВАЯ УЛИЦА ", build: " 5А"},
{street: "2-Я ПОЛЕВОДЧЕСКАЯ УЛИЦА ", build: "22"},
{street: "АЗОВСКАЯ УЛИЦА ", build: " 11А"},
{street: "АЗОВСКАЯ УЛИЦА ", build: " 12/1"},
{street: "АЗОВСКАЯ УЛИЦА ", build: " 12/2"},
{street: "АЗОВСКАЯ УЛИЦА ", build: " 12/3"},
{street: "АРТЕМА УЛИЦА ", build: "3"},
{street: "АРТЕМА УЛИЦА ", build: "4"},
{street: "АРТЕМА УЛИЦА ", build: "5"},
{street: "АРТЕМА УЛИЦА ", build: "7"},
{street: "АРТЕМА УЛИЦА ", build: "10"},
{street: "АРТЕМА УЛИЦА ", build: "11"},
{street: "АРТЕМА УЛИЦА ", build: "13"},
{street: "АРТЕМА УЛИЦА ", build: " 18 2"},
{street: "АРТЕМА УЛИЦА ", build: " 18А/1"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "110"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "113"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "115"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "117"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "119"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "127"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "129"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "131"},
{street: "БАРГУЗИНСКАЯ УЛИЦА ", build: "133"},
{street: "БЕРЕГОВАЯ УЛИЦА ", build: "14"},
{street: "БЕРЕГОВАЯ УЛИЦА ", build: "20"},
{street: "ВЕРШИНИНА УЛИЦА ", build: "6"},
{street: "ВЕРШИНИНА УЛИЦА ", build: "7"},
{street: "ВЕРШИНИНА УЛИЦА ", build: "8"},
{street: "ВЕРШИНИНА УЛИЦА ", build: "9"},
{street: "ВЕРШИНИНА УЛИЦА ", build: "10"},
{street: "ВЕРШИНИНА УЛИЦА ", build: "11"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "14"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "15"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "17"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "30"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "32"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "33"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "36"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "38"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "39"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "41"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "44"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "49"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "50"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "51"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "52"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "53"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "54"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: "55"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: " 17А"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: " 17Б"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: " 35 1"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: " 35 2"},
{street: "ВОКЗАЛЬНАЯ УЛИЦА ", build: " 37А"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: "8"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: "14"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: "16"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: "18"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: "20"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: "22"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: " 12А"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: " 16А"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: " 20А"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: " 20Б"},
{street: "ВОЛЖСКАЯ УЛИЦА ", build: " 9А"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "1"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "3"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "4"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "5"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "9"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "10"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "11"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "12"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "13"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "14"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "16"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "17"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "18"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "20"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "21"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "23"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "25"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "27"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "29"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "31"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "33"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "35"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "37"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "39"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "41"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "45"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: "47"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: " 1А"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: " 20А"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: " 29А"},
{street: "ГАГАРИНА ПРОСПЕКТ ", build: " 31А"},
{street: "ГАЙДАРА УЛИЦА ", build: "2"},
{street: "ГАЙДАРА УЛИЦА ", build: "3"},
{street: "ГАЙДАРА УЛИЦА ", build: "4"},
{street: "ГАЙДАРА УЛИЦА ", build: "5"},
{street: "ГАЙДАРА УЛИЦА ", build: "6"},
{street: "ГАЙДАРА УЛИЦА ", build: "7"},
{street: "ГАЙДАРА УЛИЦА ", build: "9"},
{street: "ГАЙДАРА УЛИЦА ", build: "10"},
{street: "ГАЙДАРА УЛИЦА ", build: "11"},
{street: "ГАЙДАРА УЛИЦА ", build: "13"},
{street: "ГАЙДАРА УЛИЦА ", build: "14"},
{street: "ГАЙДАРА УЛИЦА ", build: "15"},
{street: "ГАЙДАРА УЛИЦА ", build: "16"},
{street: "ГАЙДАРА УЛИЦА ", build: "18"},
{street: "ГАЙДАРА УЛИЦА ", build: "20"},
{street: "ГАЙДАРА УЛИЦА ", build: "24"},
{street: "ГАЙДАРА УЛИЦА ", build: "26"},
{street: "ГАЙДАРА УЛИЦА ", build: "28"},
{street: "ГАЙДАРА УЛИЦА ", build: "30"},
{street: "ГАЙДАРА УЛИЦА ", build: "32"},
{street: "ГАЙДАРА УЛИЦА ", build: "34"},
{street: "ГАЙДАРА УЛИЦА ", build: "38"},
{street: "ГАЙДАРА УЛИЦА ", build: "42"},
{street: "ГАЙДАРА УЛИЦА ", build: "44"},
{street: "ГАЙДАРА УЛИЦА ", build: "46"},
{street: "ГАЙДАРА УЛИЦА ", build: "48"},
{street: "ГАЙДАРА УЛИЦА ", build: "50"},
{street: "ГАЙДАРА УЛИЦА ", build: "54"},
{street: "ГАЙДАРА УЛИЦА ", build: "56"},
{street: "ГАЙДАРА УЛИЦА ", build: " 3А"},
{street: "ГАЙДАРА УЛИЦА ", build: " 5А"},
{street: "ГАЙДАРА УЛИЦА ", build: " 6 А"},
{street: "ГОМЕЛЬСКАЯ УЛИЦА ", build: "61"},
{street: "ГОМЕЛЬСКАЯ УЛИЦА ", build: "63"},
{street: "ГОРБУНОВА УЛИЦА ", build: "3"},
{street: "ГОРБУНОВА УЛИЦА ", build: "4"},
{street: "ГОРБУНОВА УЛИЦА ", build: "7"},
{street: "ГОРБУНОВА УЛИЦА ", build: "8"},
{street: "ГОРНЯЦКАЯ УЛИЦА ", build: "1"},
{street: "ГОРНЯЦКАЯ УЛИЦА ", build: "3"},
{street: "ГОРНЯЦКАЯ УЛИЦА ", build: "5"},
{street: "ГОРНЯЦКАЯ УЛИЦА ", build: "6"},
{street: "ГОРОДСКАЯ УЛИЦА ", build: "124"},
{street: "ГОРОДСКАЯ УЛИЦА ", build: "126"},
{street: "ГОРОДСКАЯ УЛИЦА ", build: "128"},
{street: "ГОРОДСКАЯ УЛИЦА ", build: "130"},
{street: "ГОРОДСКАЯ УЛИЦА ", build: "134"},
{street: "ГОРОДСКАЯ УЛИЦА ", build: "139"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: "24"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: "26"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: "28"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: "30"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: " 16А"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: " 16Б"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: " 22А"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: " 22Б"},
{street: "ГРИБОЕДОВА УЛИЦА ", build: " 26А"},
{street: "ЕСЕНИНА УЛИЦА ", build: "4"},
{street: "ЕСЕНИНА УЛИЦА ", build: "6"},
{street: "ЕСЕНИНА УЛИЦА ", build: "92"},
{street: "ЕСЕНИНА УЛИЦА ", build: "94"},
{street: "ЕСЕНИНА УЛИЦА ", build: "100"},
{street: "ЕСЕНИНА УЛИЦА ", build: "102"},
{street: "ЕСЕНИНА УЛИЦА ", build: "104"},
{street: "ЕСЕНИНА УЛИЦА ", build: "106"},
{street: "ЕСЕНИНА УЛИЦА ", build: " 76/1 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "10 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "14 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "18 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "20 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "22 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "24 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "26 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "28 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "30 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "32 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "36 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "38 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "40 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "42 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "44 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "54 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "56 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "58 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "62 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "68 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "70 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "74 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "76 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "78 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "80 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "82 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "84 (ETTH)"},
{street: "ЕСЕНИНА УЛИЦА ", build: "90 (ETTH)"},
{street: "ЖИТОМИРСКАЯ УЛИЦА ", build: "47"},
{street: "ЖИТОМИРСКАЯ УЛИЦА ", build: "49"},
{street: "ЖИТОМИРСКАЯ УЛИЦА ", build: "53"},
{street: "ЖИТОМИРСКАЯ УЛИЦА ", build: "55"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "2"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "3"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "5"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "7"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "8"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "9"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "10"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "11"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "13"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "16"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "17"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "18"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "19"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: "20"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: " 12/1"},
{street: "ЖОЛТОВСКОГО УЛИЦА ", build: " 12/2"},
{street: "ЗАВОДСКОЙ ПЕРЕУЛОК ", build: "1"},
{street: "ЗАВОДСКОЙ ПЕРЕУЛОК ", build: "3"},
{street: "ЗАВОДСКОЙ ПЕРЕУЛОК ", build: "4"},
{street: "ЗАВОДСКОЙ ПЕРЕУЛОК ", build: "5"},
{street: "ЗАВОДСКОЙ ПЕРЕУЛОК ", build: "6"},
{street: "ЗАВОДСКОЙ ПЕРЕУЛОК ", build: "7"},
{street: "ЗВЕНИГОРОДСКАЯ УЛИЦА ", build: "1"},
{street: "ЗОИ КОСМОДЕМЬЯНСКОЙ УЛИЦА ", build: "60"},
{street: "ЗОИ КОСМОДЕМЬЯНСКОЙ УЛИЦА ", build: "62"},
{street: "ЗОИ КОСМОДЕМЬЯНСКОЙ УЛИЦА ", build: "64"},
{street: "ЗОИ КОСМОДЕМЬЯНСКОЙ УЛИЦА ", build: "66"},
{street: "ЗОИ КОСМОДЕМЬЯНСКОЙ УЛИЦА ", build: "70"},
{street: "ЗОИ КОСМОДЕМЬЯНСКОЙ УЛИЦА ", build: "72"},
{street: "ЗОИ КОСМОДЕМЬЯНСКОЙ УЛИЦА ", build: "74"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "1"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "3"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "5"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "7"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "9"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "11"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "13"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "14"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "17"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "56"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "60"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "62"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "63"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "64"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "67"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "69"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "72"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "76"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "78"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "82"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "84"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "86"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "88"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "90"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "92"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "94"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "96"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "97"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "98"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "99"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "100"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "102"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "103"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "105"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "107"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "109"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 109/2"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 17А"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 1А"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 3А"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 5А"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 65/1"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 65/2"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 84А"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: " 88А"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "24 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "25 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "26 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "29 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "31 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "35 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "36 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "37 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "39 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "42 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "44 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "46 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "48 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "50 (ETTH)"},
{street: "ИНСТИТУТСКАЯ УЛИЦА ", build: "52 (ETTH)"},
{street: "КАЛИНИНА УЛИЦА ", build: "2"},
{street: "КАРЛА ЛИБКНЕХТА УЛИЦА ", build: "5"},
{street: "КАРЛА ЛИБКНЕХТА УЛИЦА ", build: "6"},
{street: "КАРЛА ЛИБКНЕХТА УЛИЦА ", build: "7"},
{street: "КАРЛА ЛИБКНЕХТА УЛИЦА ", build: "8"},
{street: "КАРЛА ЛИБКНЕХТА УЛИЦА ", build: "10"},
{street: "КАРЛА ЛИБКНЕХТА УЛИЦА ", build: " 7А"},
{street: "КВАРТАЛ 1 МЖК УЛИЦА ", build: "4"},
{street: "КВАРТАЛ 1 МЖК УЛИЦА ", build: "5"},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА ", build: "2"},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА ", build: "3"},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА ", build: "4"},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА ", build: "5"},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА ", build: "6"},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА ", build: "7"},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА ", build: "8"},
{street: "КИРПИЧНАЯ УЛИЦА ", build: "3"},
{street: "КИРПИЧНАЯ УЛИЦА ", build: "5"},
{street: "КОКСОВАЯ УЛИЦА ", build: "24"},
{street: "КОКСОВАЯ УЛИЦА ", build: "30"},
{street: "КОКСОВАЯ УЛИЦА ", build: "32"},
{street: "КОКСОВАЯ УЛИЦА ", build: "34"},
{street: "КОКСОВАЯ УЛИЦА ", build: "36"},
{street: "КОКСОВАЯ УЛИЦА ", build: "38"},
{street: "КОКСОВАЯ УЛИЦА ", build: "40"},
{street: "КОКСОВАЯ УЛИЦА ", build: "42"},
{street: "КОКСОВАЯ УЛИЦА ", build: "43"},
{street: "КОКСОВАЯ УЛИЦА ", build: "45"},
{street: "КОКСОВАЯ УЛИЦА ", build: " 26А"},
{street: "КОКСОВАЯ УЛИЦА ", build: " 26Б"},
{street: "КОКСОВАЯ УЛИЦА ", build: " 28А"},
{street: "КОКСОВЫЙ ПЕРЕУЛОК ", build: "1"},
{street: "КОКСОВЫЙ ПЕРЕУЛОК ", build: "21"},
{street: "КОКСОВЫЙ ПЕРЕУЛОК ", build: " 16Б"},
{street: "КОММУНАЛЬНАЯ УЛИЦА ", build: "1"},
{street: "КОММУНАЛЬНАЯ УЛИЦА ", build: "2"},
{street: "КОММУНАЛЬНАЯ УЛИЦА ", build: "3"},
{street: "КОММУНАЛЬНАЯ УЛИЦА ", build: "4"},
{street: "КОММУНАЛЬНАЯ УЛИЦА ", build: "5"},
{street: "КОММУНАЛЬНАЯ УЛИЦА ", build: "7"},
{street: "КОММУНАЛЬНАЯ УЛИЦА ", build: " 5А"},
{street: "КОМСОМОЛЬСКАЯ УЛИЦА ", build: "1"},
{street: "КОМСОМОЛЬСКАЯ УЛИЦА ", build: "3"},
{street: "КОМСОМОЛЬСКАЯ УЛИЦА ", build: "6"},
{street: "КОМСОМОЛЬСКАЯ УЛИЦА ", build: "7"},
{street: "КОМСОМОЛЬСКАЯ УЛИЦА ", build: "8"},
{street: "КОСМОНАВТА ВОЛЫНОВА УЛИЦА ", build: "5"},
{street: "КОСМОНАВТА ВОЛЫНОВА УЛИЦА ", build: "7"},
{street: "КОСМОНАВТА ВОЛЫНОВА УЛИЦА ", build: "13"},
{street: "КОСМОНАВТА ВОЛЫНОВА УЛИЦА ", build: " 11А"},
{street: "КОСМОНАВТА ВОЛЫНОВА УЛИЦА ", build: " 17А"},
{street: "КРАСНОКАМСКАЯ УЛИЦА ", build: "7"},
{street: "КРУПСКОЙ УЛИЦА ", build: "4"},
{street: "КРУПСКОЙ УЛИЦА ", build: "6"},
{street: "КРУПСКОЙ УЛИЦА ", build: "8"},
{street: "КРУПСКОЙ УЛИЦА ", build: "10"},
{street: "КРУПСКОЙ УЛИЦА ", build: "18"},
{street: "КРУПСКОЙ УЛИЦА ", build: "20"},
{street: "КРУПСКОЙ УЛИЦА ", build: "22"},
{street: "КУСТАРНАЯ УЛИЦА ", build: "22"},
{street: "КУСТАРНАЯ УЛИЦА ", build: "31"},
{street: "КУСТАРНАЯ УЛИЦА ", build: "33"},
{street: "КУСТАРНАЯ УЛИЦА ", build: " 21А"},
{street: "КУСТАРНАЯ УЛИЦА ", build: " 22А"},
{street: "КУЧИНА УЛИЦА ", build: "2"},
{street: "КУЧИНА УЛИЦА ", build: "4"},
{street: "КУЧИНА УЛИЦА ", build: "6"},
{street: "КУЧИНА УЛИЦА ", build: "8"},
{street: "КУЧИНА УЛИЦА ", build: "10"},
{street: "КУЧИНА УЛИЦА ", build: "12"},
{street: "КУЧИНА УЛИЦА ", build: "14"},
{street: "КУЧИНА УЛИЦА ", build: "16"},
{street: "КУЧИНА УЛИЦА ", build: "18"},
{street: "КУЧИНА УЛИЦА ", build: "20"},
{street: "КУЧИНА УЛИЦА ", build: "22"},
{street: "КУЧИНА УЛИЦА ", build: "24"},
{street: "КУЧИНА УЛИЦА ", build: "26"},
{street: "КУЧИНА УЛИЦА ", build: "28"},
{street: "КУЧИНА УЛИЦА ", build: "32"},
{street: "КУЧИНА УЛИЦА ", build: "34"},
{street: "КУЧИНА УЛИЦА ", build: " 24А"},
{street: "КУЧИНА УЛИЦА ", build: " 6А"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "18"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "20"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "22"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "24"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "26"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "28"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "30"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "34"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "35"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: "38"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: " 20А"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: " 22А"},
{street: "ЛАТВИЙСКАЯ УЛИЦА ", build: " 28А"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "1"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "2"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "3"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "6"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "7"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "8"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "9"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "10"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "11"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "12"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "13"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "14"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "15"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "16"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "19"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "20"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "21"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "22"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "23"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "25"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "26"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "27"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "28"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "29"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "30"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "31"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "33"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "35"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "37"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "39"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "41"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "43"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "45"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: "47"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: " 23А"},
{street: "ЛЕНИНА ПРОСПЕКТ ", build: " 23Б"},
{street: "ЛУНАЧАРСКОГО УЛИЦА ", build: "10"},
{street: "ЛУНАЧАРСКОГО УЛИЦА ", build: "11"},
{street: "МАРТЕХОВА УЛИЦА ", build: "1"},
{street: "МАРТЕХОВА УЛИЦА ", build: "3"},
{street: "МАРТЕХОВА УЛИЦА ", build: "4"},
{street: "МАРТЕХОВА УЛИЦА ", build: "5"},
{street: "МАРТЕХОВА УЛИЦА ", build: "6"},
{street: "МАРТЕХОВА УЛИЦА ", build: "7"},
{street: "МАРТЕХОВА УЛИЦА ", build: "9"},
{street: "МАРТЕХОВА УЛИЦА ", build: "11"},
{street: "МАРТЕХОВА УЛИЦА ", build: "13"},
{street: "МАРТЕХОВА УЛИЦА ", build: "15"},
{street: "МАРТЕХОВА УЛИЦА ", build: " 11А"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "2"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "3"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "5"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "6"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "8"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "11"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "12"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "16"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "17"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "18"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "19"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "20"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "21"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: "22"},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА ", build: " 14А"},
{street: "МЕНЖИНСКОГО УЛИЦА ", build: "3"},
{street: "МЕНЖИНСКОГО УЛИЦА ", build: "6"},
{street: "МЕНЖИНСКОГО УЛИЦА ", build: "8"},
{street: "МЕНЖИНСКОГО УЛИЦА ", build: "10"},
{street: "МЕНЖИНСКОГО УЛИЦА ", build: "11"},
{street: "МУРМАНСКАЯ УЛИЦА ", build: "35"},
{street: "МУРМАНСКАЯ УЛИЦА ", build: "43"},
{street: "МУРМАНСКАЯ УЛИЦА ", build: "47"},
{street: "Н.ОСИПОВА УЛИЦА ", build: "49"},
{street: "Н.ОСИПОВА УЛИЦА ", build: "51"},
{street: "Н.ОСИПОВА УЛИЦА ", build: " 49А"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "1"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "2"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "3"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "5"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "6"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "8"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "10"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "13"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "15"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "28"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "30"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: " 2А"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "18 (ETTH)"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "20 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "3"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "4"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "5"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "6"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "7"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "8"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "13"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "15"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "16"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "17"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "18"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "19"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "20"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "21"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "22"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "23"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "24"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "27"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "29"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "31"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "33"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "34"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "35"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "36"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "37"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "39"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "41"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "43"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "45"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "47"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "49"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "51"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "57"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "59"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "61"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "63"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "67"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "69"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "71"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "73"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "75"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "77"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "79"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 15 А"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 16А"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 19 А"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 24А"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 2А"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 3 А"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 44/1 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 48/1 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: " 49А"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "40 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "42 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "44 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "46 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "48 (ETTH)"},
{street: "ОБРУЧЕВА УЛИЦА ", build: "56 (ETTH)"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "1"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "2"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "3"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "4"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "5"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "6"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "8"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "9"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "10"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "11"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "12"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "13"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "14"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "15"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "16"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: "17"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: " 12А"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: " 16А"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: " 2А"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: " 3А"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: " 4А"},
{street: "ОРЕНБУРГСКАЯ УЛИЦА ", build: " 5А"},
{street: "ПАВЛОВА УЛИЦА ", build: "5"},
{street: "ПАВЛОВА УЛИЦА ", build: "6"},
{street: "ПАВЛОВА УЛИЦА ", build: "7"},
{street: "ПАРКОВАЯ УЛИЦА ", build: "280"},
{street: "ПАРКОВАЯ УЛИЦА ", build: "282"},
{street: "ПАРКОВАЯ УЛИЦА ", build: " 280А"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "2"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "3"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "5"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "6"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "7"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "8"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "9"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "10"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "14"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "16"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "18"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "22"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "24"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "26"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "28"},
{street: "ПЕТРЕНКО УЛИЦА ", build: "30"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "35"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "38"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "39"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "40"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "41"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "42"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "43"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "44"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "47"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "46 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "48 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "50 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "52 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "54 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "56 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "58 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "60 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "62 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "64 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "66 (ETTH)"},
{street: "ПИОНЕРСКАЯ УЛИЦА ", build: "68 (ETTH)"},
{street: "ПЛАНЕРНАЯ УЛИЦА ", build: "8"},
{street: "ПЛАНЕРНАЯ УЛИЦА ", build: "10"},
{street: "ПЛАНЕРНАЯ УЛИЦА ", build: "12"},
{street: "ПОДОЛЬСКАЯ УЛИЦА ", build: "10"},
{street: "ПОЖАРНАЯ УЛИЦА ", build: "31"},
{street: "ПОЛЕВОДЧЕСКАЯ УЛИЦА ", build: "37"},
{street: "ПРОКОПЬЕВСКАЯ УЛИЦА ", build: "1"},
{street: "ПРОКОПЬЕВСКАЯ УЛИЦА ", build: "71"},
{street: "ПРОКОПЬЕВСКАЯ УЛИЦА ", build: "73"},
{street: "ПРОКОПЬЕВСКАЯ УЛИЦА ", build: "125"},
{street: "ПРОКОПЬЕВСКАЯ УЛИЦА ", build: "160"},
{street: "ПРОКОПЬЕВСКАЯ УЛИЦА ", build: "162"},
{street: "ПРОЛЕТАРСКАЯ УЛИЦА ", build: "1"},
{street: "ПРОЛЕТАРСКАЯ УЛИЦА ", build: "2"},
{street: "ПРОЛЕТАРСКАЯ УЛИЦА ", build: "3"},
{street: "РАЗВЕДЧИКОВ УЛИЦА ", build: "4"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "27"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "29"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "31"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "36"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "38"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "40"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "42"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "44"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "46"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "48"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "50"},
{street: "РОССИЙСКАЯ УЛИЦА ", build: "52"},
{street: "РУДНИЧНАЯ УЛИЦА ", build: "1"},
{street: "РУДНИЧНАЯ УЛИЦА ", build: "4"},
{street: "РУДНИЧНАЯ УЛИЦА ", build: "5"},
{street: "РУДНИЧНАЯ УЛИЦА ", build: "8"},
{street: "РУДНИЧНАЯ УЛИЦА ", build: " 1А"},
{street: "САФОНОВСКАЯ УЛИЦА ", build: "3"},
{street: "СЕЛИВАНОВА УЛИЦА ", build: "2"},
{street: "СЕЛИВАНОВА УЛИЦА ", build: "3"},
{street: "СЕЛИВАНОВА УЛИЦА ", build: "4"},
{street: "СЕЛИВАНОВА УЛИЦА ", build: "5"},
{street: "СЕЛИВАНОВА УЛИЦА ", build: "6"},
{street: "СЕРОВА УЛИЦА ", build: " 1А"},
{street: "СОВЕТОВ УЛИЦА ", build: "3"},
{street: "СОВЕТОВ УЛИЦА ", build: "5"},
{street: "СОВЕТОВ УЛИЦА ", build: "7"},
{street: "СОВЕТОВ УЛИЦА ", build: "8"},
{street: "СОВЕТОВ УЛИЦА ", build: "10"},
{street: "СОВЕТОВ УЛИЦА ", build: "11"},
{street: "СОВЕТОВ УЛИЦА ", build: "12"},
{street: "СОВЕТОВ УЛИЦА ", build: "19"},
{street: "СОВЕТОВ УЛИЦА ", build: "20"},
{street: "СОВЕТОВ УЛИЦА ", build: "21"},
{street: "СОВЕТОВ УЛИЦА ", build: "24"},
{street: "СОВЕТОВ УЛИЦА ", build: "25"},
{street: "СОВЕТОВ УЛИЦА ", build: "26"},
{street: "СОВЕТОВ УЛИЦА ", build: " 9А 1"},
{street: "СОВЕТОВ УЛИЦА ", build: " 9А 2"},
{street: "СОВЕТОВ УЛИЦА ", build: " 9А 3"},
{street: "СОЦИАЛИСТИЧЕСКАЯ УЛИЦА ", build: "3"},
{street: "СОЦИАЛИСТИЧЕСКАЯ УЛИЦА ", build: "5"},
{street: "СОЦИАЛИСТИЧЕСКАЯ УЛИЦА ", build: "7"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "3"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "5"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "7"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "8"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "9"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "10"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "11"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "12"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "13"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "15"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "16"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "18"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "19"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "20"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "21"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "22"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "23"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "24"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "25"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "26"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "27"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "28"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "31"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "32"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "33"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "35"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "37"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "39"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "40"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "41"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "42"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "43"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "44"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "45"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "46"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "47"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "48"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "49"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "50"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "51"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "52"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "53"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "54"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "56"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "57"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "58"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "60"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "62"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "64"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "66"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "68"},
{street: "СОЮЗНАЯ УЛИЦА ", build: " 65А (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "63 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "65 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "67 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "69 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "71 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "73 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "75 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "76 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "77 (ETTH)"},
{street: "СОЮЗНАЯ УЛИЦА ", build: "79 (ETTH)"},
{street: "СТАРТОВАЯ УЛИЦА ", build: "10"},
{street: "СТАРТОВАЯ УЛИЦА ", build: " 10А"},
{street: "СТАРТОВАЯ УЛИЦА ", build: " 12А"},
{street: "СТАРТОВЫЙ ПЕРЕУЛОК ", build: "14"},
{street: "СТАРТОВЫЙ ПЕРЕУЛОК ", build: "16"},
{street: "СТАРТОВЫЙ ПЕРЕУЛОК ", build: " 14А"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "3"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "5"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "85"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "87"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "89"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "91"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: " 15/1 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: " 47/1 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: " 47/2 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: " 67А (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: " 85А/1"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: " 85А/2"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "13 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "17 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "19 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "21 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "27 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "29 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "31 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "33 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "35 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "37 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "39 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "41 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "43 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "45 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "47 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "49 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "57 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "59 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "61 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "63 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "67 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "69 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "71 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "73 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "75 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "77 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "79 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "81 (ETTH)"},
{street: "СТРОИТЕЛЕЙ ПРОСПЕКТ ", build: "83 (ETTH)"},
{street: "СТУДЕНЧЕСКАЯ УЛИЦА ", build: "44 (ETTH)"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "1"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "15"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "21"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "23"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "30"},
{street: "ТРАНСПОРТНАЯ УЛИЦА ", build: "32"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "1"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "3"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "5"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "7"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "9"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "11"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "13"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "15"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "17"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: "19"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: " 9А 1"},
{street: "ТЮЛЕНИНА УЛИЦА ", build: " 9А 2"},
{street: "УРАЛЬСКАЯ УЛИЦА ", build: " 1А"},
{street: "УЧИТЕЛЬСКАЯ УЛИЦА ", build: "34"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "3"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "4"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "5"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "6"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: "10"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: " 4А"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: " 7А 1"},
{street: "ЦЕНТРАЛЬНАЯ УЛИЦА ", build: " 7А 2"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "1"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "3"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "4"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "6"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "7"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "8"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "9"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "10"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "11"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "13"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "15"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "16"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "17"},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА ", build: "18"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "1"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "2"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "8"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "9"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "10"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "11"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "13"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "16"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "17"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "18"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "20"},
{street: "ЧЕРНЫХ УЛИЦА ", build: "22"},
{street: "ЧЕРНЫХ УЛИЦА ", build: " 18А"},
{street: "ЧЕРНЫХ УЛИЦА ", build: " 22А"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "2"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "6"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "11"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "13"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "15"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "21"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "37"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "39"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "45"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "47"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "51"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "63"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: "65"},
{street: "ШАХТЕРОВ ПРОСПЕКТ ", build: " 13А"},
{street: "ШАХТОСТРОЕВСКАЯ УЛИЦА ", build: "1"},
{street: "ШИШКИНА УЛИЦА ", build: "3"},
{street: "ШИШКИНА УЛИЦА ", build: "5"},
{street: "ШИШКИНА УЛИЦА ", build: "11"},
{street: "ШИШКИНА УЛИЦА ", build: "12"},
{street: "ШИШКИНА УЛИЦА ", build: "13"},
{street: "ШИШКИНА УЛИЦА ", build: "14"},
{street: "ШИШКИНА УЛИЦА ", build: "15"},
{street: "ШИШКИНА УЛИЦА ", build: "16"},
{street: "ШИШКИНА УЛИЦА ", build: "17"},
{street: "ШИШКИНА УЛИЦА ", build: "18"},
{street: "ШИШКИНА УЛИЦА ", build: "19"},
{street: "ШИШКИНА УЛИЦА ", build: "22"},
{street: "ШИШКИНА УЛИЦА ", build: "27"},
{street: "ШИШКИНА УЛИЦА ", build: "29"},
{street: "ШИШКИНА УЛИЦА ", build: "31"},
{street: "ШИШКИНА УЛИЦА ", build: "32"},
{street: "ШИШКИНА УЛИЦА ", build: "33"},
{street: "ШИШКИНА УЛИЦА ", build: "35"},
{street: "ШИШКИНА УЛИЦА ", build: "37"},
{street: "ШИШКИНА УЛИЦА ", build: "40"},
{street: "ШИШКИНА УЛИЦА ", build: "41"},
{street: "ШИШКИНА УЛИЦА ", build: "43"},
{street: "ШИШКИНА УЛИЦА ", build: "44"},
{street: "ШИШКИНА УЛИЦА ", build: "45"},
{street: "ШИШКИНА УЛИЦА ", build: "46"},
{street: "ШИШКИНА УЛИЦА ", build: "48"},
{street: "ШИШКИНА УЛИЦА ", build: "50"},
{street: "ШИШКИНА УЛИЦА ", build: "52"},
{street: "ШИШКИНА УЛИЦА ", build: " 15А"},
{street: "ШИШКИНА УЛИЦА ", build: " 39А"},
{street: "ШИШКИНА УЛИЦА ", build: "25 (ETTH)"},
{street: "ЮРЭСОВСКАЯ УЛИЦА ", build: "8"},
{street: "ЮРЭСОВСКАЯ УЛИЦА ", build: "10"},
{street: "ЮРЭСОВСКАЯ УЛИЦА ", build: "13"},
{street: "ЮРЭСОВСКАЯ УЛИЦА ", build: " 12А"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "1"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "2"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "3"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "4"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "5"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "6"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "8"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "10"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "11"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "12"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "13"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "15"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "16"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "17"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "18"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "22"},
{street: "ЯВОРСКОГО УЛИЦА ", build: "24"},
{street: "ЯВОРСКОГО УЛИЦА ", build: " 12А"},
{street: "ЯВОРСКОГО УЛИЦА ", build: " 12Б"},
{street: "ЯВОРСКОГО УЛИЦА ", build: " 1А"},
], streets: [{street: "10-Й МИКРОРАЙОН "},
{street: "2-Я КИРПИЧНАЯ УЛИЦА "},
{street: "2-Я КОКСОВАЯ УЛИЦА "},
{street: "2-Я ПОЛЕВОДЧЕСКАЯ УЛИЦА "},
{street: "АЗОВСКАЯ УЛИЦА "},
{street: "АРТЕМА УЛИЦА "},
{street: "БАРГУЗИНСКАЯ УЛИЦА "},
{street: "БЕРЕГОВАЯ УЛИЦА "},
{street: "ВЕРШИНИНА УЛИЦА "},
{street: "ГАГАРИНА ПРОСПЕКТ "},
{street: "ГАЙДАРА УЛИЦА "},
{street: "ГОМЕЛЬСКАЯ УЛИЦА "},
{street: "ГОРБУНОВА УЛИЦА "},
{street: "ГОРНЯЦКАЯ УЛИЦА "},
{street: "ГОРОДСКАЯ УЛИЦА "},
{street: "ЖИТОМИРСКАЯ УЛИЦА "},
{street: "ЖОЛТОВСКОГО УЛИЦА "},
{street: "ЗАВОДСКОЙ ПЕРЕУЛОК "},
{street: "ЗВЕНИГОРОДСКАЯ УЛИЦА "},
{street: "ИНСТИТУТСКАЯ УЛИЦА "},
{street: "КАРЛА ЛИБКНЕХТА УЛИЦА "},
{street: "КВАРТАЛ 1 МЖК УЛИЦА "},
{street: "КВАРТАЛ СЕВЕРНЫЙ УЛИЦА "},
{street: "КОКСОВАЯ УЛИЦА "},
{street: "КОКСОВЫЙ ПЕРЕУЛОК "},
{street: "КОММУНАЛЬНАЯ УЛИЦА "},
{street: "КОСМОНАВТА ВОЛЫНОВА УЛИЦА "},
{street: "КРАСНОКАМСКАЯ УЛИЦА "},
{street: "КУСТАРНАЯ УЛИЦА "},
{street: "КУЧИНА УЛИЦА "},
{street: "ЛАТВИЙСКАЯ УЛИЦА "},
{street: "МАРТЕХОВА УЛИЦА "},
{street: "МЕЖДУНАРОДНАЯ УЛИЦА "},
{street: "МЕНЖИНСКОГО УЛИЦА "},
{street: "Н.ОСИПОВА УЛИЦА "},
{street: "ОБРУЧЕВА УЛИЦА "},
{street: "ОРЕНБУРГСКАЯ УЛИЦА "},
{street: "ПАВЛОВА УЛИЦА "},
{street: "ПЕТРЕНКО УЛИЦА "},
{street: "ПЛАНЕРНАЯ УЛИЦА "},
{street: "ПОДОЛЬСКАЯ УЛИЦА "},
{street: "ПОЖАРНАЯ УЛИЦА "},
{street: "ПОЛЕВОДЧЕСКАЯ УЛИЦА "},
{street: "РОССИЙСКАЯ УЛИЦА "},
{street: "РУДНИЧНАЯ УЛИЦА "},
{street: "САФОНОВСКАЯ УЛИЦА "},
{street: "СЕЛИВАНОВА УЛИЦА "},
{street: "СЕРОВА УЛИЦА "},
{street: "СОВЕТОВ УЛИЦА "},
{street: "СОЦИАЛИСТИЧЕСКАЯ УЛИЦА "},
{street: "СОЮЗНАЯ УЛИЦА "},
{street: "СТАРТОВАЯ УЛИЦА "},
{street: "СТАРТОВЫЙ ПЕРЕУЛОК "},
{street: "ТЮЛЕНИНА УЛИЦА "},
{street: "УРАЛЬСКАЯ УЛИЦА "},
{street: "УЧИТЕЛЬСКАЯ УЛИЦА "},
{street: "ЧЕРНИГОВСКАЯ УЛИЦА "},
{street: "ЧЕРНЫХ УЛИЦА "},
{street: "ШАХТОСТРОЕВСКАЯ УЛИЦА "},
{street: "ШИШКИНА УЛИЦА "},
{street: "ЮРЭСОВСКАЯ УЛИЦА "},
{street: "ЯВОРСКОГО УЛИЦА "},
] };
