city_streets["prokopievsk"] = {builds: [{street: "10-Й Микрорайон ", build: "1"},
{street: "10-Й Микрорайон ", build: "10"},
{street: "10-Й Микрорайон ", build: "11"},
{street: "10-Й Микрорайон ", build: "12"},
{street: "10-Й Микрорайон ", build: "12А"},
{street: "10-Й Микрорайон ", build: "13"},
{street: "10-Й Микрорайон ", build: "14"},
{street: "10-Й Микрорайон ", build: "15"},
{street: "10-Й Микрорайон ", build: "16"},
{street: "10-Й Микрорайон ", build: "16А"},
{street: "10-Й Микрорайон ", build: "17"},
{street: "10-Й Микрорайон ", build: "18"},
{street: "10-Й Микрорайон ", build: "18А"},
{street: "10-Й Микрорайон ", build: "19"},
{street: "10-Й Микрорайон ", build: "2"},
{street: "10-Й Микрорайон ", build: "20"},
{street: "10-Й Микрорайон ", build: "21"},
{street: "10-Й Микрорайон ", build: "22"},
{street: "10-Й Микрорайон ", build: "23"},
{street: "10-Й Микрорайон ", build: "24"},
{street: "10-Й Микрорайон ", build: "25"},
{street: "10-Й Микрорайон ", build: "25А"},
{street: "10-Й Микрорайон ", build: "26"},
{street: "10-Й Микрорайон ", build: "27"},
{street: "10-Й Микрорайон ", build: "28"},
{street: "10-Й Микрорайон ", build: "29"},
{street: "10-Й Микрорайон ", build: "3"},
{street: "10-Й Микрорайон ", build: "30"},
{street: "10-Й Микрорайон ", build: "31"},
{street: "10-Й Микрорайон ", build: "4"},
{street: "10-Й Микрорайон ", build: "46А"},
{street: "10-Й Микрорайон ", build: "5"},
{street: "10-Й Микрорайон ", build: "52"},
{street: "10-Й Микрорайон ", build: "6"},
{street: "10-Й Микрорайон ", build: "6А"},
{street: "10-Й Микрорайон ", build: "7"},
{street: "10-Й Микрорайон ", build: "8"},
{street: "10-Й Микрорайон ", build: "9"},
{street: "2-Я Кирпичная ул", build: "5"},
{street: "2-Я Кирпичная ул", build: "7"},
{street: "2-Я Кирпичная ул", build: "7А"},
{street: "2-Я Коксовая ул", build: "12"},
{street: "2-Я Коксовая ул", build: "13"},
{street: "2-Я Коксовая ул", build: "15"},
{street: "2-Я Коксовая ул", build: "17"},
{street: "2-Я Коксовая ул", build: "20Б"},
{street: "2-Я Коксовая ул", build: "22"},
{street: "2-Я Коксовая ул", build: "22А"},
{street: "2-Я Коксовая ул", build: "24"},
{street: "2-Я Коксовая ул", build: "28"},
{street: "2-Я Коксовая ул", build: "3"},
{street: "2-Я Коксовая ул", build: "5А"},
{street: "2-Я Коксовая ул", build: "6"},
{street: "2-Я Коксовая ул", build: "7"},
{street: "2-Я Полеводческая ул", build: "22"},
{street: "Азовская ул", build: "11А"},
{street: "Азовская ул", build: "12/1"},
{street: "Азовская ул", build: "12/2"},
{street: "Азовская ул", build: "12/3"},
{street: "Артема ул", build: "10"},
{street: "Артема ул", build: "11"},
{street: "Артема ул", build: "13"},
{street: "Артема ул", build: "18/2"},
{street: "Артема ул", build: "18А/1"},
{street: "Артема ул", build: "3"},
{street: "Артема ул", build: "4"},
{street: "Артема ул", build: "5"},
{street: "Артема ул", build: "7"},
{street: "Баргузинская ул", build: "110"},
{street: "Баргузинская ул", build: "113"},
{street: "Баргузинская ул", build: "115"},
{street: "Баргузинская ул", build: "117"},
{street: "Баргузинская ул", build: "119"},
{street: "Баргузинская ул", build: "127"},
{street: "Баргузинская ул", build: "129"},
{street: "Баргузинская ул", build: "131"},
{street: "Баргузинская ул", build: "133"},
{street: "Береговая ул", build: "14"},
{street: "Береговая ул", build: "20"},
{street: "Вершинина ул", build: "10"},
{street: "Вершинина ул", build: "11"},
{street: "Вершинина ул", build: "6"},
{street: "Вершинина ул", build: "7"},
{street: "Вершинина ул", build: "8"},
{street: "Вершинина ул", build: "9"},
{street: "Вокзальная ул", build: "14"},
{street: "Вокзальная ул", build: "15"},
{street: "Вокзальная ул", build: "17"},
{street: "Вокзальная ул", build: "17А"},
{street: "Вокзальная ул", build: "17Б"},
{street: "Вокзальная ул", build: "30"},
{street: "Вокзальная ул", build: "32"},
{street: "Вокзальная ул", build: "33"},
{street: "Вокзальная ул", build: "35/1"},
{street: "Вокзальная ул", build: "35/2"},
{street: "Вокзальная ул", build: "36"},
{street: "Вокзальная ул", build: "37А"},
{street: "Вокзальная ул", build: "38"},
{street: "Вокзальная ул", build: "39"},
{street: "Вокзальная ул", build: "41"},
{street: "Вокзальная ул", build: "44"},
{street: "Вокзальная ул", build: "49"},
{street: "Вокзальная ул", build: "50"},
{street: "Вокзальная ул", build: "51"},
{street: "Вокзальная ул", build: "52"},
{street: "Вокзальная ул", build: "53"},
{street: "Вокзальная ул", build: "54"},
{street: "Вокзальная ул", build: "55"},
{street: "Волжская ул", build: "12А"},
{street: "Волжская ул", build: "14"},
{street: "Волжская ул", build: "16"},
{street: "Волжская ул", build: "16А"},
{street: "Волжская ул", build: "18"},
{street: "Волжская ул", build: "20"},
{street: "Волжская ул", build: "20А"},
{street: "Волжская ул", build: "20Б"},
{street: "Волжская ул", build: "22"},
{street: "Волжская ул", build: "8"},
{street: "Волжская ул", build: "9А"},
{street: "Гагарина пр ", build: "1"},
{street: "Гагарина пр ", build: "10"},
{street: "Гагарина пр ", build: "11"},
{street: "Гагарина пр ", build: "12"},
{street: "Гагарина пр ", build: "13"},
{street: "Гагарина пр ", build: "14"},
{street: "Гагарина пр ", build: "16"},
{street: "Гагарина пр ", build: "17"},
{street: "Гагарина пр ", build: "18"},
{street: "Гагарина пр ", build: "1А"},
{street: "Гагарина пр ", build: "20"},
{street: "Гагарина пр ", build: "20А"},
{street: "Гагарина пр ", build: "21"},
{street: "Гагарина пр ", build: "23"},
{street: "Гагарина пр ", build: "25"},
{street: "Гагарина пр ", build: "27"},
{street: "Гагарина пр ", build: "29"},
{street: "Гагарина пр ", build: "29А"},
{street: "Гагарина пр ", build: "3"},
{street: "Гагарина пр ", build: "31"},
{street: "Гагарина пр ", build: "31А"},
{street: "Гагарина пр ", build: "33"},
{street: "Гагарина пр ", build: "35"},
{street: "Гагарина пр ", build: "37"},
{street: "Гагарина пр ", build: "39"},
{street: "Гагарина пр ", build: "4"},
{street: "Гагарина пр ", build: "41"},
{street: "Гагарина пр ", build: "45"},
{street: "Гагарина пр ", build: "47"},
{street: "Гагарина пр ", build: "5"},
{street: "Гагарина пр ", build: "9"},
{street: "Гайдара ул", build: "10"},
{street: "Гайдара ул", build: "11"},
{street: "Гайдара ул", build: "13"},
{street: "Гайдара ул", build: "14"},
{street: "Гайдара ул", build: "15"},
{street: "Гайдара ул", build: "16"},
{street: "Гайдара ул", build: "18"},
{street: "Гайдара ул", build: "2"},
{street: "Гайдара ул", build: "20"},
{street: "Гайдара ул", build: "24"},
{street: "Гайдара ул", build: "26"},
{street: "Гайдара ул", build: "28"},
{street: "Гайдара ул", build: "3"},
{street: "Гайдара ул", build: "30"},
{street: "Гайдара ул", build: "32"},
{street: "Гайдара ул", build: "34"},
{street: "Гайдара ул", build: "38"},
{street: "Гайдара ул", build: "3А"},
{street: "Гайдара ул", build: "4"},
{street: "Гайдара ул", build: "42"},
{street: "Гайдара ул", build: "44"},
{street: "Гайдара ул", build: "46"},
{street: "Гайдара ул", build: "48"},
{street: "Гайдара ул", build: "5"},
{street: "Гайдара ул", build: "50"},
{street: "Гайдара ул", build: "54"},
{street: "Гайдара ул", build: "56"},
{street: "Гайдара ул", build: "5А"},
{street: "Гайдара ул", build: "6"},
{street: "Гайдара ул", build: "6А"},
{street: "Гайдара ул", build: "7"},
{street: "Гайдара ул", build: "9"},
{street: "Гомельская ул", build: "61"},
{street: "Гомельская ул", build: "63"},
{street: "Горбунова ул", build: "3"},
{street: "Горбунова ул", build: "4"},
{street: "Горбунова ул", build: "7"},
{street: "Горбунова ул", build: "8"},
{street: "Горняцкая ул", build: "1"},
{street: "Горняцкая ул", build: "3"},
{street: "Горняцкая ул", build: "5"},
{street: "Горняцкая ул", build: "6"},
{street: "Городская ул", build: "124"},
{street: "Городская ул", build: "126"},
{street: "Городская ул", build: "128"},
{street: "Городская ул", build: "130"},
{street: "Городская ул", build: "134"},
{street: "Городская ул", build: "139"},
{street: "Грибоедова ул", build: "16А"},
{street: "Грибоедова ул", build: "16Б"},
{street: "Грибоедова ул", build: "22А"},
{street: "Грибоедова ул", build: "22Б"},
{street: "Грибоедова ул", build: "24"},
{street: "Грибоедова ул", build: "26"},
{street: "Грибоедова ул", build: "26А"},
{street: "Грибоедова ул", build: "28"},
{street: "Грибоедова ул", build: "30"},
{street: "Есенина ул", build: "10_ETTH"},
{street: "Есенина ул", build: "100"},
{street: "Есенина ул", build: "102"},
{street: "Есенина ул", build: "104"},
{street: "Есенина ул", build: "106"},
{street: "Есенина ул", build: "14_ETTH"},
{street: "Есенина ул", build: "18_ETTH"},
{street: "Есенина ул", build: "20_ETTH"},
{street: "Есенина ул", build: "22_ETTH"},
{street: "Есенина ул", build: "24_ETTH"},
{street: "Есенина ул", build: "26_ETTH"},
{street: "Есенина ул", build: "28_ETTH"},
{street: "Есенина ул", build: "30_ETTH"},
{street: "Есенина ул", build: "32_ETTH"},
{street: "Есенина ул", build: "36_ETTH"},
{street: "Есенина ул", build: "38_ETTH"},
{street: "Есенина ул", build: "4"},
{street: "Есенина ул", build: "40_ETTH"},
{street: "Есенина ул", build: "42_ETTH"},
{street: "Есенина ул", build: "44_ETTH"},
{street: "Есенина ул", build: "54_ETTH"},
{street: "Есенина ул", build: "56_ETTH"},
{street: "Есенина ул", build: "58_ETTH"},
{street: "Есенина ул", build: "6"},
{street: "Есенина ул", build: "62_ETTH"},
{street: "Есенина ул", build: "68_ETTH"},
{street: "Есенина ул", build: "70_ETTH"},
{street: "Есенина ул", build: "74_ETTH"},
{street: "Есенина ул", build: "76_ETTH"},
{street: "Есенина ул", build: "76/1_ETTH"},
{street: "Есенина ул", build: "78_ETTH"},
{street: "Есенина ул", build: "80_ETTH"},
{street: "Есенина ул", build: "82_ETTH"},
{street: "Есенина ул", build: "84_ETTH"},
{street: "Есенина ул", build: "90_ETTH"},
{street: "Есенина ул", build: "92"},
{street: "Есенина ул", build: "94"},
{street: "Житомирская ул", build: "47"},
{street: "Житомирская ул", build: "49"},
{street: "Житомирская ул", build: "53"},
{street: "Житомирская ул", build: "55"},
{street: "Жолтовского ул", build: "10"},
{street: "Жолтовского ул", build: "11"},
{street: "Жолтовского ул", build: "12/1"},
{street: "Жолтовского ул", build: "12/2"},
{street: "Жолтовского ул", build: "13"},
{street: "Жолтовского ул", build: "16"},
{street: "Жолтовского ул", build: "17"},
{street: "Жолтовского ул", build: "18"},
{street: "Жолтовского ул", build: "19"},
{street: "Жолтовского ул", build: "2"},
{street: "Жолтовского ул", build: "20"},
{street: "Жолтовского ул", build: "3"},
{street: "Жолтовского ул", build: "5"},
{street: "Жолтовского ул", build: "7"},
{street: "Жолтовского ул", build: "8"},
{street: "Жолтовского ул", build: "9"},
{street: "Заводской пер ", build: "1"},
{street: "Заводской пер ", build: "3"},
{street: "Заводской пер ", build: "4"},
{street: "Заводской пер ", build: "5"},
{street: "Заводской пер ", build: "6"},
{street: "Заводской пер ", build: "7"},
{street: "Звенигородская ул", build: "1"},
{street: "Зои Космодемьянской ул", build: "60"},
{street: "Зои Космодемьянской ул", build: "62"},
{street: "Зои Космодемьянской ул", build: "64"},
{street: "Зои Космодемьянской ул", build: "66"},
{street: "Зои Космодемьянской ул", build: "70"},
{street: "Зои Космодемьянской ул", build: "72"},
{street: "Зои Космодемьянской ул", build: "74"},
{street: "Институтская ул", build: "1"},
{street: "Институтская ул", build: "100"},
{street: "Институтская ул", build: "102"},
{street: "Институтская ул", build: "103"},
{street: "Институтская ул", build: "105"},
{street: "Институтская ул", build: "107"},
{street: "Институтская ул", build: "109"},
{street: "Институтская ул", build: "109/2"},
{street: "Институтская ул", build: "11"},
{street: "Институтская ул", build: "13"},
{street: "Институтская ул", build: "14"},
{street: "Институтская ул", build: "17"},
{street: "Институтская ул", build: "17А"},
{street: "Институтская ул", build: "1А"},
{street: "Институтская ул", build: "24_ETTH"},
{street: "Институтская ул", build: "25_ETTH"},
{street: "Институтская ул", build: "26_ETTH"},
{street: "Институтская ул", build: "29_ETTH"},
{street: "Институтская ул", build: "3"},
{street: "Институтская ул", build: "31_ETTH"},
{street: "Институтская ул", build: "35_ETTH"},
{street: "Институтская ул", build: "36_ETTH"},
{street: "Институтская ул", build: "37_ETTH"},
{street: "Институтская ул", build: "39_ETTH"},
{street: "Институтская ул", build: "3А"},
{street: "Институтская ул", build: "42_ETTH"},
{street: "Институтская ул", build: "44_ETTH"},
{street: "Институтская ул", build: "46_ETTH"},
{street: "Институтская ул", build: "48_ETTH"},
{street: "Институтская ул", build: "5"},
{street: "Институтская ул", build: "50_ETTH"},
{street: "Институтская ул", build: "52_ETTH"},
{street: "Институтская ул", build: "56"},
{street: "Институтская ул", build: "5А"},
{street: "Институтская ул", build: "60"},
{street: "Институтская ул", build: "62"},
{street: "Институтская ул", build: "63"},
{street: "Институтская ул", build: "64"},
{street: "Институтская ул", build: "65/1"},
{street: "Институтская ул", build: "65/2"},
{street: "Институтская ул", build: "67"},
{street: "Институтская ул", build: "69"},
{street: "Институтская ул", build: "7"},
{street: "Институтская ул", build: "72"},
{street: "Институтская ул", build: "76"},
{street: "Институтская ул", build: "78"},
{street: "Институтская ул", build: "82"},
{street: "Институтская ул", build: "84"},
{street: "Институтская ул", build: "84А"},
{street: "Институтская ул", build: "86"},
{street: "Институтская ул", build: "88"},
{street: "Институтская ул", build: "88А"},
{street: "Институтская ул", build: "9"},
{street: "Институтская ул", build: "90"},
{street: "Институтская ул", build: "92"},
{street: "Институтская ул", build: "94"},
{street: "Институтская ул", build: "96"},
{street: "Институтская ул", build: "97"},
{street: "Институтская ул", build: "98"},
{street: "Институтская ул", build: "99"},
{street: "Калинина ул", build: "2"},
{street: "Карла Либкнехта ул", build: "10"},
{street: "Карла Либкнехта ул", build: "5"},
{street: "Карла Либкнехта ул", build: "6"},
{street: "Карла Либкнехта ул", build: "7"},
{street: "Карла Либкнехта ул", build: "7А"},
{street: "Карла Либкнехта ул", build: "8"},
{street: "Квартал 1 Мжк ул", build: "4"},
{street: "Квартал 1 Мжк ул", build: "5"},
{street: "Квартал Северный ул", build: "2"},
{street: "Квартал Северный ул", build: "3"},
{street: "Квартал Северный ул", build: "4"},
{street: "Квартал Северный ул", build: "5"},
{street: "Квартал Северный ул", build: "6"},
{street: "Квартал Северный ул", build: "7"},
{street: "Квартал Северный ул", build: "8"},
{street: "Кирпичная ул", build: "3"},
{street: "Кирпичная ул", build: "5"},
{street: "Коксовая ул", build: "24"},
{street: "Коксовая ул", build: "26А"},
{street: "Коксовая ул", build: "26Б"},
{street: "Коксовая ул", build: "28А"},
{street: "Коксовая ул", build: "30"},
{street: "Коксовая ул", build: "32"},
{street: "Коксовая ул", build: "34"},
{street: "Коксовая ул", build: "36"},
{street: "Коксовая ул", build: "38"},
{street: "Коксовая ул", build: "40"},
{street: "Коксовая ул", build: "42"},
{street: "Коксовая ул", build: "43"},
{street: "Коксовая ул", build: "45"},
{street: "Коксовый пер ", build: "1"},
{street: "Коксовый пер ", build: "16Б"},
{street: "Коксовый пер ", build: "21"},
{street: "Коммунальная ул", build: "1"},
{street: "Коммунальная ул", build: "2"},
{street: "Коммунальная ул", build: "3"},
{street: "Коммунальная ул", build: "4"},
{street: "Коммунальная ул", build: "5"},
{street: "Коммунальная ул", build: "5А"},
{street: "Коммунальная ул", build: "7"},
{street: "Комсомольская ул", build: "1"},
{street: "Комсомольская ул", build: "3"},
{street: "Комсомольская ул", build: "6"},
{street: "Комсомольская ул", build: "7"},
{street: "Комсомольская ул", build: "8"},
{street: "Космонавта Волынова ул", build: "11А"},
{street: "Космонавта Волынова ул", build: "13"},
{street: "Космонавта Волынова ул", build: "17А"},
{street: "Космонавта Волынова ул", build: "5"},
{street: "Космонавта Волынова ул", build: "7"},
{street: "Краснокамская ул", build: "7"},
{street: "Крупской ул", build: "10"},
{street: "Крупской ул", build: "18"},
{street: "Крупской ул", build: "20"},
{street: "Крупской ул", build: "22"},
{street: "Крупской ул", build: "4"},
{street: "Крупской ул", build: "6"},
{street: "Крупской ул", build: "8"},
{street: "Кустарная ул", build: "21А"},
{street: "Кустарная ул", build: "22"},
{street: "Кустарная ул", build: "22А"},
{street: "Кустарная ул", build: "31"},
{street: "Кустарная ул", build: "33"},
{street: "Кучина ул", build: "10"},
{street: "Кучина ул", build: "12"},
{street: "Кучина ул", build: "14"},
{street: "Кучина ул", build: "16"},
{street: "Кучина ул", build: "18"},
{street: "Кучина ул", build: "2"},
{street: "Кучина ул", build: "20"},
{street: "Кучина ул", build: "22"},
{street: "Кучина ул", build: "24"},
{street: "Кучина ул", build: "24А"},
{street: "Кучина ул", build: "26"},
{street: "Кучина ул", build: "28"},
{street: "Кучина ул", build: "32"},
{street: "Кучина ул", build: "34"},
{street: "Кучина ул", build: "4"},
{street: "Кучина ул", build: "6"},
{street: "Кучина ул", build: "6А"},
{street: "Кучина ул", build: "8"},
{street: "Латвийская ул", build: "18"},
{street: "Латвийская ул", build: "20"},
{street: "Латвийская ул", build: "20А"},
{street: "Латвийская ул", build: "22"},
{street: "Латвийская ул", build: "22А"},
{street: "Латвийская ул", build: "24"},
{street: "Латвийская ул", build: "26"},
{street: "Латвийская ул", build: "28"},
{street: "Латвийская ул", build: "28А"},
{street: "Латвийская ул", build: "30"},
{street: "Латвийская ул", build: "34"},
{street: "Латвийская ул", build: "35"},
{street: "Латвийская ул", build: "38"},
{street: "Ленина пр ", build: "1"},
{street: "Ленина пр ", build: "10"},
{street: "Ленина пр ", build: "11"},
{street: "Ленина пр ", build: "12"},
{street: "Ленина пр ", build: "13"},
{street: "Ленина пр ", build: "14"},
{street: "Ленина пр ", build: "15"},
{street: "Ленина пр ", build: "16"},
{street: "Ленина пр ", build: "19"},
{street: "Ленина пр ", build: "2"},
{street: "Ленина пр ", build: "20"},
{street: "Ленина пр ", build: "21"},
{street: "Ленина пр ", build: "22"},
{street: "Ленина пр ", build: "23"},
{street: "Ленина пр ", build: "23А"},
{street: "Ленина пр ", build: "23Б"},
{street: "Ленина пр ", build: "25"},
{street: "Ленина пр ", build: "26"},
{street: "Ленина пр ", build: "27"},
{street: "Ленина пр ", build: "28"},
{street: "Ленина пр ", build: "29"},
{street: "Ленина пр ", build: "3"},
{street: "Ленина пр ", build: "30"},
{street: "Ленина пр ", build: "31"},
{street: "Ленина пр ", build: "33"},
{street: "Ленина пр ", build: "35"},
{street: "Ленина пр ", build: "37"},
{street: "Ленина пр ", build: "39"},
{street: "Ленина пр ", build: "41"},
{street: "Ленина пр ", build: "43"},
{street: "Ленина пр ", build: "45"},
{street: "Ленина пр ", build: "47"},
{street: "Ленина пр ", build: "6"},
{street: "Ленина пр ", build: "7"},
{street: "Ленина пр ", build: "8"},
{street: "Ленина пр ", build: "9"},
{street: "Луначарского ул", build: "10"},
{street: "Луначарского ул", build: "11"},
{street: "Мартехова ул", build: "1"},
{street: "Мартехова ул", build: "11"},
{street: "Мартехова ул", build: "11А"},
{street: "Мартехова ул", build: "13"},
{street: "Мартехова ул", build: "15"},
{street: "Мартехова ул", build: "3"},
{street: "Мартехова ул", build: "4"},
{street: "Мартехова ул", build: "5"},
{street: "Мартехова ул", build: "6"},
{street: "Мартехова ул", build: "7"},
{street: "Мартехова ул", build: "9"},
{street: "Международная ул", build: "11"},
{street: "Международная ул", build: "12"},
{street: "Международная ул", build: "14А"},
{street: "Международная ул", build: "16"},
{street: "Международная ул", build: "17"},
{street: "Международная ул", build: "18"},
{street: "Международная ул", build: "19"},
{street: "Международная ул", build: "2"},
{street: "Международная ул", build: "20"},
{street: "Международная ул", build: "21"},
{street: "Международная ул", build: "22"},
{street: "Международная ул", build: "3"},
{street: "Международная ул", build: "5"},
{street: "Международная ул", build: "6"},
{street: "Международная ул", build: "8"},
{street: "Менжинского ул", build: "10"},
{street: "Менжинского ул", build: "11"},
{street: "Менжинского ул", build: "3"},
{street: "Менжинского ул", build: "6"},
{street: "Менжинского ул", build: "8"},
{street: "Мурманская ул", build: "35"},
{street: "Мурманская ул", build: "43"},
{street: "Мурманская ул", build: "47"},
{street: "Н.Осипова ул", build: "49"},
{street: "Н.Осипова ул", build: "49А"},
{street: "Н.Осипова ул", build: "51"},
{street: "Ноградская ул", build: "1"},
{street: "Ноградская ул", build: "10"},
{street: "Ноградская ул", build: "13"},
{street: "Ноградская ул", build: "15"},
{street: "Ноградская ул", build: "18_ETTH"},
{street: "Ноградская ул", build: "2"},
{street: "Ноградская ул", build: "20_ETTH"},
{street: "Ноградская ул", build: "28"},
{street: "Ноградская ул", build: "2А"},
{street: "Ноградская ул", build: "3"},
{street: "Ноградская ул", build: "30"},
{street: "Ноградская ул", build: "5"},
{street: "Ноградская ул", build: "6"},
{street: "Ноградская ул", build: "8"},
{street: "Обручева ул", build: "13"},
{street: "Обручева ул", build: "15"},
{street: "Обручева ул", build: "15А"},
{street: "Обручева ул", build: "16"},
{street: "Обручева ул", build: "16А"},
{street: "Обручева ул", build: "17"},
{street: "Обручева ул", build: "18"},
{street: "Обручева ул", build: "19"},
{street: "Обручева ул", build: "19А"},
{street: "Обручева ул", build: "20"},
{street: "Обручева ул", build: "21"},
{street: "Обручева ул", build: "22"},
{street: "Обручева ул", build: "23"},
{street: "Обручева ул", build: "24"},
{street: "Обручева ул", build: "24А"},
{street: "Обручева ул", build: "27"},
{street: "Обручева ул", build: "29"},
{street: "Обручева ул", build: "2А"},
{street: "Обручева ул", build: "3"},
{street: "Обручева ул", build: "3А"},
{street: "Обручева ул", build: "31"},
{street: "Обручева ул", build: "33"},
{street: "Обручева ул", build: "34"},
{street: "Обручева ул", build: "35"},
{street: "Обручева ул", build: "36"},
{street: "Обручева ул", build: "37"},
{street: "Обручева ул", build: "39"},
{street: "Обручева ул", build: "4"},
{street: "Обручева ул", build: "40_ETTH"},
{street: "Обручева ул", build: "41"},
{street: "Обручева ул", build: "42_ETTH"},
{street: "Обручева ул", build: "43"},
{street: "Обручева ул", build: "44_ETTH"},
{street: "Обручева ул", build: "44/1_ETTH"},
{street: "Обручева ул", build: "45"},
{street: "Обручева ул", build: "46_ETTH"},
{street: "Обручева ул", build: "47"},
{street: "Обручева ул", build: "48_ETTH"},
{street: "Обручева ул", build: "48/1_ETTH"},
{street: "Обручева ул", build: "49"},
{street: "Обручева ул", build: "49А"},
{street: "Обручева ул", build: "5"},
{street: "Обручева ул", build: "51"},
{street: "Обручева ул", build: "56_ETTH"},
{street: "Обручева ул", build: "57"},
{street: "Обручева ул", build: "59"},
{street: "Обручева ул", build: "6"},
{street: "Обручева ул", build: "61"},
{street: "Обручева ул", build: "63"},
{street: "Обручева ул", build: "67"},
{street: "Обручева ул", build: "69"},
{street: "Обручева ул", build: "7"},
{street: "Обручева ул", build: "71"},
{street: "Обручева ул", build: "73"},
{street: "Обручева ул", build: "75"},
{street: "Обручева ул", build: "77"},
{street: "Обручева ул", build: "79"},
{street: "Обручева ул", build: "8"},
{street: "Оренбургская ул", build: "1"},
{street: "Оренбургская ул", build: "10"},
{street: "Оренбургская ул", build: "11"},
{street: "Оренбургская ул", build: "12"},
{street: "Оренбургская ул", build: "12А"},
{street: "Оренбургская ул", build: "13"},
{street: "Оренбургская ул", build: "14"},
{street: "Оренбургская ул", build: "15"},
{street: "Оренбургская ул", build: "16"},
{street: "Оренбургская ул", build: "16А"},
{street: "Оренбургская ул", build: "17"},
{street: "Оренбургская ул", build: "2"},
{street: "Оренбургская ул", build: "2А"},
{street: "Оренбургская ул", build: "3"},
{street: "Оренбургская ул", build: "3А"},
{street: "Оренбургская ул", build: "4"},
{street: "Оренбургская ул", build: "4А"},
{street: "Оренбургская ул", build: "5"},
{street: "Оренбургская ул", build: "5А"},
{street: "Оренбургская ул", build: "6"},
{street: "Оренбургская ул", build: "8"},
{street: "Оренбургская ул", build: "9"},
{street: "Павлова ул", build: "5"},
{street: "Павлова ул", build: "6"},
{street: "Павлова ул", build: "7"},
{street: "Парковая ул", build: "280"},
{street: "Парковая ул", build: "280А"},
{street: "Парковая ул", build: "282"},
{street: "Петренко ул", build: "10"},
{street: "Петренко ул", build: "14"},
{street: "Петренко ул", build: "16"},
{street: "Петренко ул", build: "18"},
{street: "Петренко ул", build: "2"},
{street: "Петренко ул", build: "22"},
{street: "Петренко ул", build: "24"},
{street: "Петренко ул", build: "26"},
{street: "Петренко ул", build: "28"},
{street: "Петренко ул", build: "3"},
{street: "Петренко ул", build: "30"},
{street: "Петренко ул", build: "5"},
{street: "Петренко ул", build: "6"},
{street: "Петренко ул", build: "7"},
{street: "Петренко ул", build: "8"},
{street: "Петренко ул", build: "9"},
{street: "Пионерская ул", build: "35"},
{street: "Пионерская ул", build: "38"},
{street: "Пионерская ул", build: "39"},
{street: "Пионерская ул", build: "40"},
{street: "Пионерская ул", build: "41"},
{street: "Пионерская ул", build: "42"},
{street: "Пионерская ул", build: "43"},
{street: "Пионерская ул", build: "44"},
{street: "Пионерская ул", build: "46_ETTH"},
{street: "Пионерская ул", build: "47"},
{street: "Пионерская ул", build: "48_ETTH"},
{street: "Пионерская ул", build: "50_ETTH"},
{street: "Пионерская ул", build: "52_ETTH"},
{street: "Пионерская ул", build: "54_ETTH"},
{street: "Пионерская ул", build: "56_ETTH"},
{street: "Пионерская ул", build: "58_ETTH"},
{street: "Пионерская ул", build: "60_ETTH"},
{street: "Пионерская ул", build: "62_ETTH"},
{street: "Пионерская ул", build: "64_ETTH"},
{street: "Пионерская ул", build: "66_ETTH"},
{street: "Пионерская ул", build: "68_ETTH"},
{street: "Планерная ул", build: "10"},
{street: "Планерная ул", build: "12"},
{street: "Планерная ул", build: "8"},
{street: "Подольская ул", build: "10"},
{street: "Пожарная ул", build: "31"},
{street: "Прокопьевская ул", build: "1"},
{street: "Прокопьевская ул", build: "125"},
{street: "Прокопьевская ул", build: "160"},
{street: "Прокопьевская ул", build: "162"},
{street: "Прокопьевская ул", build: "71"},
{street: "Прокопьевская ул", build: "73"},
{street: "Пролетарская ул", build: "1"},
{street: "Пролетарская ул", build: "2"},
{street: "Пролетарская ул", build: "3"},
{street: "Разведчиков ул", build: "4"},
{street: "Российская ул", build: "27"},
{street: "Российская ул", build: "29"},
{street: "Российская ул", build: "31"},
{street: "Российская ул", build: "36"},
{street: "Российская ул", build: "38"},
{street: "Российская ул", build: "40"},
{street: "Российская ул", build: "42"},
{street: "Российская ул", build: "44"},
{street: "Российская ул", build: "46"},
{street: "Российская ул", build: "48"},
{street: "Российская ул", build: "50"},
{street: "Российская ул", build: "52"},
{street: "Рудничная ул", build: "1"},
{street: "Рудничная ул", build: "1А"},
{street: "Рудничная ул", build: "4"},
{street: "Рудничная ул", build: "5"},
{street: "Рудничная ул", build: "8"},
{street: "Сафоновская ул", build: "3"},
{street: "Селиванова ул", build: "2"},
{street: "Селиванова ул", build: "3"},
{street: "Селиванова ул", build: "4"},
{street: "Селиванова ул", build: "5"},
{street: "Селиванова ул", build: "6"},
{street: "Серова ул", build: "1А"},
{street: "Советов ул", build: "10"},
{street: "Советов ул", build: "11"},
{street: "Советов ул", build: "12"},
{street: "Советов ул", build: "19"},
{street: "Советов ул", build: "20"},
{street: "Советов ул", build: "21"},
{street: "Советов ул", build: "24"},
{street: "Советов ул", build: "25"},
{street: "Советов ул", build: "26"},
{street: "Советов ул", build: "3"},
{street: "Советов ул", build: "5"},
{street: "Советов ул", build: "7"},
{street: "Советов ул", build: "8"},
{street: "Советов ул", build: "9А/1"},
{street: "Советов ул", build: "9А/2"},
{street: "Советов ул", build: "9А/3"},
{street: "Социалистическая ул", build: "3"},
{street: "Социалистическая ул", build: "5"},
{street: "Социалистическая ул", build: "7"},
{street: "Союзная ул", build: "10"},
{street: "Союзная ул", build: "11"},
{street: "Союзная ул", build: "12"},
{street: "Союзная ул", build: "13"},
{street: "Союзная ул", build: "15"},
{street: "Союзная ул", build: "16"},
{street: "Союзная ул", build: "18"},
{street: "Союзная ул", build: "19"},
{street: "Союзная ул", build: "20"},
{street: "Союзная ул", build: "21"},
{street: "Союзная ул", build: "22"},
{street: "Союзная ул", build: "23"},
{street: "Союзная ул", build: "24"},
{street: "Союзная ул", build: "25"},
{street: "Союзная ул", build: "26"},
{street: "Союзная ул", build: "27"},
{street: "Союзная ул", build: "28"},
{street: "Союзная ул", build: "3"},
{street: "Союзная ул", build: "31"},
{street: "Союзная ул", build: "32"},
{street: "Союзная ул", build: "33"},
{street: "Союзная ул", build: "35"},
{street: "Союзная ул", build: "37"},
{street: "Союзная ул", build: "39"},
{street: "Союзная ул", build: "40"},
{street: "Союзная ул", build: "41"},
{street: "Союзная ул", build: "42"},
{street: "Союзная ул", build: "43"},
{street: "Союзная ул", build: "44"},
{street: "Союзная ул", build: "45"},
{street: "Союзная ул", build: "46"},
{street: "Союзная ул", build: "47"},
{street: "Союзная ул", build: "48"},
{street: "Союзная ул", build: "49"},
{street: "Союзная ул", build: "5"},
{street: "Союзная ул", build: "50"},
{street: "Союзная ул", build: "51"},
{street: "Союзная ул", build: "52"},
{street: "Союзная ул", build: "53"},
{street: "Союзная ул", build: "54"},
{street: "Союзная ул", build: "56"},
{street: "Союзная ул", build: "57"},
{street: "Союзная ул", build: "58"},
{street: "Союзная ул", build: "60"},
{street: "Союзная ул", build: "62"},
{street: "Союзная ул", build: "63_ETTH"},
{street: "Союзная ул", build: "64"},
{street: "Союзная ул", build: "65_ETTH"},
{street: "Союзная ул", build: "65А_ETTH"},
{street: "Союзная ул", build: "66"},
{street: "Союзная ул", build: "67_ETTH"},
{street: "Союзная ул", build: "68"},
{street: "Союзная ул", build: "69_ETTH"},
{street: "Союзная ул", build: "7"},
{street: "Союзная ул", build: "71_ETTH"},
{street: "Союзная ул", build: "73_ETTH"},
{street: "Союзная ул", build: "75_ETTH"},
{street: "Союзная ул", build: "76_ETTH"},
{street: "Союзная ул", build: "77_ETTH"},
{street: "Союзная ул", build: "79_ETTH"},
{street: "Союзная ул", build: "8"},
{street: "Союзная ул", build: "9"},
{street: "Стартовая ул", build: "10"},
{street: "Стартовая ул", build: "10А"},
{street: "Стартовая ул", build: "12А"},
{street: "Стартовый пер ", build: "14"},
{street: "Стартовый пер ", build: "14А"},
{street: "Стартовый пер ", build: "16"},
{street: "Стартовый пер ", build: "9"},
{street: "Строителей пр ", build: "13_ETTH"},
{street: "Строителей пр ", build: "15/1_ETTH"},
{street: "Строителей пр ", build: "17_ETTH"},
{street: "Строителей пр ", build: "19_ETTH"},
{street: "Строителей пр ", build: "21_ETTH"},
{street: "Строителей пр ", build: "27_ETTH"},
{street: "Строителей пр ", build: "29_ETTH"},
{street: "Строителей пр ", build: "3"},
{street: "Строителей пр ", build: "31_ETTH"},
{street: "Строителей пр ", build: "33_ETTH"},
{street: "Строителей пр ", build: "35_ETTH"},
{street: "Строителей пр ", build: "37_ETTH"},
{street: "Строителей пр ", build: "39_ETTH"},
{street: "Строителей пр ", build: "41_ETTH"},
{street: "Строителей пр ", build: "43_ETTH"},
{street: "Строителей пр ", build: "45_ETTH"},
{street: "Строителей пр ", build: "47_ETTH"},
{street: "Строителей пр ", build: "47/1_ETTH"},
{street: "Строителей пр ", build: "47/2_ETTH"},
{street: "Строителей пр ", build: "49_ETTH"},
{street: "Строителей пр ", build: "5"},
{street: "Строителей пр ", build: "57_ETTH"},
{street: "Строителей пр ", build: "59_ETTH"},
{street: "Строителей пр ", build: "61_ETTH"},
{street: "Строителей пр ", build: "63_ETTH"},
{street: "Строителей пр ", build: "67_ETTH"},
{street: "Строителей пр ", build: "67А_ETTH"},
{street: "Строителей пр ", build: "69_ETTH"},
{street: "Строителей пр ", build: "71_ETTH"},
{street: "Строителей пр ", build: "73_ETTH"},
{street: "Строителей пр ", build: "75_ETTH"},
{street: "Строителей пр ", build: "77_ETTH"},
{street: "Строителей пр ", build: "79_ETTH"},
{street: "Строителей пр ", build: "81_ETTH"},
{street: "Строителей пр ", build: "83_ETTH"},
{street: "Строителей пр ", build: "85"},
{street: "Строителей пр ", build: "85А/1"},
{street: "Строителей пр ", build: "85А/2"},
{street: "Строителей пр ", build: "87"},
{street: "Строителей пр ", build: "89"},
{street: "Строителей пр ", build: "91"},
{street: "Студенческая ул", build: "44_ETTH"},
{street: "Транспортная ул", build: "1"},
{street: "Транспортная ул", build: "15"},
{street: "Транспортная ул", build: "21"},
{street: "Транспортная ул", build: "23"},
{street: "Транспортная ул", build: "30"},
{street: "Транспортная ул", build: "32"},
{street: "Тюленина ул", build: "1"},
{street: "Тюленина ул", build: "11"},
{street: "Тюленина ул", build: "13"},
{street: "Тюленина ул", build: "15"},
{street: "Тюленина ул", build: "17"},
{street: "Тюленина ул", build: "19"},
{street: "Тюленина ул", build: "3"},
{street: "Тюленина ул", build: "5"},
{street: "Тюленина ул", build: "7"},
{street: "Тюленина ул", build: "9"},
{street: "Тюленина ул", build: "9А/1"},
{street: "Тюленина ул", build: "9А/2"},
{street: "Уральская ул", build: "1А"},
{street: "Учительская ул", build: "34"},
{street: "Центральная ул", build: "10"},
{street: "Центральная ул", build: "3"},
{street: "Центральная ул", build: "4"},
{street: "Центральная ул", build: "4А"},
{street: "Центральная ул", build: "5"},
{street: "Центральная ул", build: "6"},
{street: "Центральная ул", build: "7А/1"},
{street: "Центральная ул", build: "7А/2"},
{street: "Черниговская ул", build: "1"},
{street: "Черниговская ул", build: "10"},
{street: "Черниговская ул", build: "11"},
{street: "Черниговская ул", build: "13"},
{street: "Черниговская ул", build: "15"},
{street: "Черниговская ул", build: "16"},
{street: "Черниговская ул", build: "17"},
{street: "Черниговская ул", build: "18"},
{street: "Черниговская ул", build: "3"},
{street: "Черниговская ул", build: "4"},
{street: "Черниговская ул", build: "6"},
{street: "Черниговская ул", build: "7"},
{street: "Черниговская ул", build: "8"},
{street: "Черниговская ул", build: "9"},
{street: "Черных ул", build: "1"},
{street: "Черных ул", build: "10"},
{street: "Черных ул", build: "11"},
{street: "Черных ул", build: "13"},
{street: "Черных ул", build: "16"},
{street: "Черных ул", build: "17"},
{street: "Черных ул", build: "18"},
{street: "Черных ул", build: "18А"},
{street: "Черных ул", build: "2"},
{street: "Черных ул", build: "20"},
{street: "Черных ул", build: "22"},
{street: "Черных ул", build: "22А"},
{street: "Черных ул", build: "8"},
{street: "Черных ул", build: "9"},
{street: "Шахтеров пр ", build: "11"},
{street: "Шахтеров пр ", build: "13"},
{street: "Шахтеров пр ", build: "13А"},
{street: "Шахтеров пр ", build: "15"},
{street: "Шахтеров пр ", build: "2"},
{street: "Шахтеров пр ", build: "21"},
{street: "Шахтеров пр ", build: "37"},
{street: "Шахтеров пр ", build: "39"},
{street: "Шахтеров пр ", build: "45"},
{street: "Шахтеров пр ", build: "47"},
{street: "Шахтеров пр ", build: "51"},
{street: "Шахтеров пр ", build: "6"},
{street: "Шахтеров пр ", build: "63"},
{street: "Шахтеров пр ", build: "65"},
{street: "Шахтостроевская ул", build: "1"},
{street: "Шишкина ул", build: "11"},
{street: "Шишкина ул", build: "12"},
{street: "Шишкина ул", build: "13"},
{street: "Шишкина ул", build: "14"},
{street: "Шишкина ул", build: "15"},
{street: "Шишкина ул", build: "15А"},
{street: "Шишкина ул", build: "16"},
{street: "Шишкина ул", build: "17"},
{street: "Шишкина ул", build: "18"},
{street: "Шишкина ул", build: "19"},
{street: "Шишкина ул", build: "22"},
{street: "Шишкина ул", build: "25_ETTH"},
{street: "Шишкина ул", build: "27"},
{street: "Шишкина ул", build: "29"},
{street: "Шишкина ул", build: "3"},
{street: "Шишкина ул", build: "31"},
{street: "Шишкина ул", build: "32"},
{street: "Шишкина ул", build: "33"},
{street: "Шишкина ул", build: "35"},
{street: "Шишкина ул", build: "37"},
{street: "Шишкина ул", build: "39А"},
{street: "Шишкина ул", build: "40"},
{street: "Шишкина ул", build: "41"},
{street: "Шишкина ул", build: "43"},
{street: "Шишкина ул", build: "44"},
{street: "Шишкина ул", build: "45"},
{street: "Шишкина ул", build: "46"},
{street: "Шишкина ул", build: "48"},
{street: "Шишкина ул", build: "5"},
{street: "Шишкина ул", build: "50"},
{street: "Шишкина ул", build: "52"},
{street: "Юрэсовская ул", build: "10"},
{street: "Юрэсовская ул", build: "12А"},
{street: "Юрэсовская ул", build: "13"},
{street: "Юрэсовская ул", build: "8"},
{street: "Яворского ул", build: "1"},
{street: "Яворского ул", build: "10"},
{street: "Яворского ул", build: "11"},
{street: "Яворского ул", build: "12"},
{street: "Яворского ул", build: "12А"},
{street: "Яворского ул", build: "12Б"},
{street: "Яворского ул", build: "13"},
{street: "Яворского ул", build: "15"},
{street: "Яворского ул", build: "16"},
{street: "Яворского ул", build: "17"},
{street: "Яворского ул", build: "18"},
{street: "Яворского ул", build: "1А"},
{street: "Яворского ул", build: "2"},
{street: "Яворского ул", build: "22"},
{street: "Яворского ул", build: "24"},
{street: "Яворского ул", build: "3"},
{street: "Яворского ул", build: "4"},
{street: "Яворского ул", build: "5"},
{street: "Яворского ул", build: "6"},
{street: "Яворского ул", build: "8"},
], streets: [{street: "10-Й Микрорайон "},
{street: "2-Я Кирпичная ул"},
{street: "2-Я Коксовая ул"},
{street: "2-Я Полеводческая ул"},
{street: "Азовская ул"},
{street: "Артема ул"},
{street: "Баргузинская ул"},
{street: "Береговая ул"},
{street: "Вершинина ул"},
{street: "Вокзальная ул"},
{street: "Волжская ул"},
{street: "Гагарина пр "},
{street: "Гайдара ул"},
{street: "Гомельская ул"},
{street: "Горбунова ул"},
{street: "Горняцкая ул"},
{street: "Городская ул"},
{street: "Грибоедова ул"},
{street: "Есенина ул"},
{street: "Житомирская ул"},
{street: "Жолтовского ул"},
{street: "Заводской пер "},
{street: "Звенигородская ул"},
{street: "Зои Космодемьянской ул"},
{street: "Институтская ул"},
{street: "Калинина ул"},
{street: "Карла Либкнехта ул"},
{street: "Квартал 1 Мжк ул"},
{street: "Квартал Северный ул"},
{street: "Кирпичная ул"},
{street: "Коксовая ул"},
{street: "Коксовый пер "},
{street: "Коммунальная ул"},
{street: "Комсомольская ул"},
{street: "Космонавта Волынова ул"},
{street: "Краснокамская ул"},
{street: "Крупской ул"},
{street: "Кустарная ул"},
{street: "Кучина ул"},
{street: "Латвийская ул"},
{street: "Ленина пр "},
{street: "Луначарского ул"},
{street: "Мартехова ул"},
{street: "Международная ул"},
{street: "Менжинского ул"},
{street: "Мурманская ул"},
{street: "Н.Осипова ул"},
{street: "Ноградская ул"},
{street: "Обручева ул"},
{street: "Оренбургская ул"},
{street: "Павлова ул"},
{street: "Парковая ул"},
{street: "Петренко ул"},
{street: "Пионерская ул"},
{street: "Планерная ул"},
{street: "Подольская ул"},
{street: "Пожарная ул"},
{street: "Прокопьевская ул"},
{street: "Пролетарская ул"},
{street: "Разведчиков ул"},
{street: "Российская ул"},
{street: "Рудничная ул"},
{street: "Сафоновская ул"},
{street: "Селиванова ул"},
{street: "Серова ул"},
{street: "Советов ул"},
{street: "Социалистическая ул"},
{street: "Союзная ул"},
{street: "Стартовая ул"},
{street: "Стартовый пер "},
{street: "Строителей пр "},
{street: "Студенческая ул"},
{street: "Транспортная ул"},
{street: "Тюленина ул"},
{street: "Уральская ул"},
{street: "Учительская ул"},
{street: "Центральная ул"},
{street: "Черниговская ул"},
{street: "Черных ул"},
{street: "Шахтеров пр "},
{street: "Шахтостроевская ул"},
{street: "Шишкина ул"},
{street: "Юрэсовская ул"},
{street: "Яворского ул"},
] };
