city_streets["taiga"] = {builds: [{street: "40 Лет Октября ул", build: "1"},
{street: "40 Лет Октября ул", build: "11"},
{street: "40 Лет Октября ул", build: "2"},
{street: "40 Лет Октября ул", build: "25"},
{street: "40 Лет Октября ул", build: "27"},
{street: "40 Лет Октября ул", build: "29"},
{street: "40 Лет Октября ул", build: "29а"},
{street: "40 Лет Октября ул", build: "32"},
{street: "40 Лет Октября ул", build: "33"},
{street: "40 Лет Октября ул", build: "4"},
{street: "40 Лет Октября ул", build: "9"},
{street: "А Квартал ", build: "11"},
{street: "А Квартал ", build: "12"},
{street: "А Квартал ", build: "14"},
{street: "А Квартал ", build: "5Б"},
{street: "А Квартал ", build: "6"},
{street: "А Квартал ", build: "7"},
{street: "Восточная ул", build: "76"},
{street: "Восточная ул", build: "78"},
{street: "Восточная ул", build: "82"},
{street: "Восточная ул", build: "84"},
{street: "Кирова пр ", build: "11"},
{street: "Кирова пр ", build: "13"},
{street: "Кирова пр ", build: "32"},
{street: "Кирова пр ", build: "33"},
{street: "Кирова пр ", build: "34"},
{street: "Кирова пр ", build: "36"},
{street: "Кирова пр ", build: "36а"},
{street: "Кирова пр ", build: "38а"},
{street: "Кирова пр ", build: "40"},
{street: "Кирова пр ", build: "40а"},
{street: "Кирова пр ", build: "41"},
{street: "Кирова пр ", build: "6"},
{street: "Кирова пр ", build: "71"},
{street: "Кирова пр ", build: "74"},
{street: "Ключевая ул", build: "1"},
{street: "Ключевая ул", build: "3"},
{street: "Ключевая ул", build: "46"},
{street: "Ключевая ул", build: "5"},
{street: "Лермонтова ул", build: "10"},
{street: "Лермонтова ул", build: "11"},
{street: "Лермонтова ул", build: "12"},
{street: "Лермонтова ул", build: "13"},
{street: "Лермонтова ул", build: "14"},
{street: "Лермонтова ул", build: "15"},
{street: "Лермонтова ул", build: "16"},
{street: "Лермонтова ул", build: "17"},
{street: "Маслова ул", build: "2"},
{street: "Мира ул", build: "1"},
{street: "Мира ул", build: "1А"},
{street: "Мира ул", build: "2"},
{street: "Мира ул", build: "2а"},
{street: "Мира ул", build: "3"},
{street: "Мира ул", build: "3В"},
{street: "Мира ул", build: "4"},
{street: "Мира ул", build: "5"},
{street: "Мира ул", build: "5А"},
{street: "Мира ул", build: "8"},
{street: "Никитина ул", build: "19а"},
{street: "Октябрьская ул", build: "14"},
{street: "Октябрьская ул", build: "37"},
{street: "Октябрьская ул", build: "38"},
{street: "Октябрьская ул", build: "39"},
{street: "Октябрьская ул", build: "53"},
{street: "Октябрьская ул", build: "55"},
{street: "Октябрьская ул", build: "57"},
{street: "Почтовая ул", build: "70"},
{street: "Почтовая ул", build: "95"},
{street: "Почтовая ул", build: "97"},
{street: "Привокзальная ул", build: "11а"},
{street: "Проектная ул", build: "2"},
{street: "Савинова ул", build: "10"},
{street: "Савинова ул", build: "6"},
{street: "Савинова ул", build: "8"},
{street: "Советская ул", build: "68"},
{street: "Советская ул", build: "78"},
{street: "Строительная ул", build: "1"},
{street: "Строительная ул", build: "22"},
{street: "Строительная ул", build: "24"},
{street: "Строительная ул", build: "3"},
{street: "Строительная ул", build: "45"},
{street: "Строительная ул", build: "47"},
{street: "Строительная ул", build: "9"},
{street: "Тилемзейгера ул", build: "10а"},
{street: "Тилемзейгера ул", build: "19"},
{street: "Чкалова ул", build: "1"},
{street: "Щетинкина ул", build: "22"},
{street: "Щетинкина ул", build: "56"},
{street: "Щетинкина ул", build: "58"},
{street: "Щетинкина ул", build: "60"},
{street: "Щетинкина ул", build: "62"},
{street: "Щетинкина ул", build: "63"},
{street: "Щетинкина ул", build: "68а"},
{street: "Щетинкина ул", build: "68б"},
{street: "Щетинкина ул", build: "70"},
{street: "Щетинкина ул", build: "72"},
{street: "Щетинкина ул", build: "74"},
{street: "Щетинкина ул", build: "77"},
], streets: [{street: "40 Лет Октября ул"},
{street: "А Квартал "},
{street: "Восточная ул"},
{street: "Кирова пр "},
{street: "Ключевая ул"},
{street: "Лермонтова ул"},
{street: "Маслова ул"},
{street: "Мира ул"},
{street: "Никитина ул"},
{street: "Октябрьская ул"},
{street: "Почтовая ул"},
{street: "Привокзальная ул"},
{street: "Проектная ул"},
{street: "Савинова ул"},
{street: "Советская ул"},
{street: "Строительная ул"},
{street: "Тилемзейгера ул"},
{street: "Чкалова ул"},
{street: "Щетинкина ул"},
] };
