city_streets["tashtagol"] = {builds: [{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "1"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "4"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "7"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "8"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "10"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "12"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "14"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "16"},
{street: "18 ПАРТСЪЕЗДА УЛИЦА ", build: "17"},
{street: "8 МАРТА УЛИЦА ", build: "1"},
{street: "8 МАРТА УЛИЦА ", build: "2"},
{street: "8 МАРТА УЛИЦА ", build: "3"},
{street: "8 МАРТА УЛИЦА ", build: "4"},
{street: "АРТЕМА УЛИЦА ", build: "9"},
{street: "АРТЕМА УЛИЦА ", build: "11"},
{street: "АРТЕМА УЛИЦА ", build: "13"},
{street: "КИСЛОРОДНАЯ УЛИЦА ", build: " 10А"},
{street: "КИСЛОРОДНАЯ УЛИЦА ", build: " 9А"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "2"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "3"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "12"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "14"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "22"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "23"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: "24"},
{street: "КОММУНИСТИЧЕСКАЯ УЛИЦА ", build: " 11А"},
{street: "ЛЕНИНА УЛИЦА ", build: "14"},
{street: "ЛЕНИНА УЛИЦА ", build: "17"},
{street: "ЛЕНИНА УЛИЦА ", build: "19"},
{street: "ЛЕНИНА УЛИЦА ", build: "26"},
{street: "ЛЕНИНА УЛИЦА ", build: "38"},
{street: "ЛЕНИНА УЛИЦА ", build: "48"},
{street: "ЛЕНИНА УЛИЦА ", build: "50"},
{street: "ЛЕНИНА УЛИЦА ", build: "54"},
{street: "ЛЕНИНА УЛИЦА ", build: "56"},
{street: "ЛЕНИНА УЛИЦА ", build: "62"},
{street: "ЛЕНИНА УЛИЦА ", build: "66"},
{street: "ЛЕНИНА УЛИЦА ", build: "68"},
{street: "ЛЕНИНА УЛИЦА ", build: "70"},
{street: "ЛЕНИНА УЛИЦА ", build: "72"},
{street: "ЛЕНИНА УЛИЦА ", build: "74"},
{street: "ЛЕНИНА УЛИЦА ", build: "76"},
{street: "ЛЕНИНА УЛИЦА ", build: "78"},
{street: "ЛЕНИНА УЛИЦА ", build: "80"},
{street: "ЛЕНИНА УЛИЦА ", build: "82"},
{street: "ЛЕНИНА УЛИЦА ", build: "84"},
{street: "ЛЕНИНА УЛИЦА ", build: " 26а"},
{street: "МАКАРЕНКО УЛИЦА ", build: "2"},
{street: "МАКАРЕНКО УЛИЦА ", build: "4"},
{street: "МАКАРЕНКО УЛИЦА ", build: "6"},
{street: "МАКАРЕНКО УЛИЦА ", build: "8"},
{street: "МАКАРЕНКО УЛИЦА ", build: "10"},
{street: "МАКАРЕНКО УЛИЦА ", build: "12"},
{street: "МАКАРЕНКО УЛИЦА ", build: "14"},
{street: "МИРА УЛИЦА ", build: "31"},
{street: "МИРА УЛИЦА ", build: "33"},
{street: "МИРА УЛИЦА ", build: "35"},
{street: "МИРА УЛИЦА ", build: "37"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "3"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "4"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "5"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "6"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "8"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "13"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "14"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "15"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "16"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "17"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "18"},
{street: "НОГРАДСКАЯ УЛИЦА ", build: "25"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "7"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "9"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "11"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "12"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "13"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "15"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "17"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "18"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "21"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "22"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "27"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "29"},
{street: "ПОСПЕЛОВА УЛИЦА ", build: "33"},
{street: "РОМАНА АРЕФЬЕВА УЛИЦА ", build: "16"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "28"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "34"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "36"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "38"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: "137"},
{street: "СОВЕТСКАЯ УЛИЦА ", build: " 2Б"},
{street: "СПОРТИВНАЯ УЛИЦА ", build: "4"},
{street: "СУВОРОВА УЛИЦА ", build: "21"},
{street: "СУВОРОВА УЛИЦА ", build: "23"},
{street: "ШКОЛЬНАЯ УЛИЦА ", build: "12"},
{street: "ШКОЛЬНАЯ УЛИЦА ", build: "14"},
{street: "ШКОЛЬНАЯ УЛИЦА ", build: "16"},
{street: "ШКОЛЬНАЯ УЛИЦА ", build: "31"},
{street: "ЮБИЛЕЙНАЯ УЛИЦА ", build: "3"},
{street: "ЮБИЛЕЙНАЯ УЛИЦА ", build: "6"},
], streets: [{street: "18 ПАРТСЪЕЗДА УЛИЦА "},
{street: "КИСЛОРОДНАЯ УЛИЦА "},
{street: "ПОСПЕЛОВА УЛИЦА "},
{street: "РОМАНА АРЕФЬЕВА УЛИЦА "},
{street: "СПОРТИВНАЯ УЛИЦА "},
] };
