city_streets["tashtagol"] = {builds: [{street: "18 Партсъезда ул", build: "1"},
{street: "18 Партсъезда ул", build: "10"},
{street: "18 Партсъезда ул", build: "12"},
{street: "18 Партсъезда ул", build: "14"},
{street: "18 Партсъезда ул", build: "16"},
{street: "18 Партсъезда ул", build: "17"},
{street: "18 Партсъезда ул", build: "4"},
{street: "18 Партсъезда ул", build: "7"},
{street: "18 Партсъезда ул", build: "8"},
{street: "8 Марта ул", build: "1"},
{street: "8 Марта ул", build: "2"},
{street: "8 Марта ул", build: "3"},
{street: "8 Марта ул", build: "4"},
{street: "Артема ул", build: "11"},
{street: "Артема ул", build: "13"},
{street: "Артема ул", build: "9"},
{street: "Кислородная ул", build: "10А"},
{street: "Кислородная ул", build: "9А"},
{street: "Коммунистическая ул", build: "11А"},
{street: "Коммунистическая ул", build: "12"},
{street: "Коммунистическая ул", build: "14"},
{street: "Коммунистическая ул", build: "2"},
{street: "Коммунистическая ул", build: "22"},
{street: "Коммунистическая ул", build: "23"},
{street: "Коммунистическая ул", build: "24"},
{street: "Коммунистическая ул", build: "3"},
{street: "Ленина ул", build: "14"},
{street: "Ленина ул", build: "17"},
{street: "Ленина ул", build: "19"},
{street: "Ленина ул", build: "26"},
{street: "Ленина ул", build: "26а"},
{street: "Ленина ул", build: "38"},
{street: "Ленина ул", build: "48"},
{street: "Ленина ул", build: "50"},
{street: "Ленина ул", build: "54"},
{street: "Ленина ул", build: "56"},
{street: "Ленина ул", build: "62"},
{street: "Ленина ул", build: "66"},
{street: "Ленина ул", build: "68"},
{street: "Ленина ул", build: "70"},
{street: "Ленина ул", build: "72"},
{street: "Ленина ул", build: "74"},
{street: "Ленина ул", build: "76"},
{street: "Ленина ул", build: "78"},
{street: "Ленина ул", build: "80"},
{street: "Ленина ул", build: "82"},
{street: "Ленина ул", build: "84"},
{street: "Макаренко ул", build: "10"},
{street: "Макаренко ул", build: "12"},
{street: "Макаренко ул", build: "14"},
{street: "Макаренко ул", build: "2"},
{street: "Макаренко ул", build: "4"},
{street: "Макаренко ул", build: "6"},
{street: "Макаренко ул", build: "8"},
{street: "Мира ул", build: "31"},
{street: "Мира ул", build: "33"},
{street: "Мира ул", build: "35"},
{street: "Мира ул", build: "37"},
{street: "Ноградская ул", build: "13"},
{street: "Ноградская ул", build: "14"},
{street: "Ноградская ул", build: "15"},
{street: "Ноградская ул", build: "16"},
{street: "Ноградская ул", build: "17"},
{street: "Ноградская ул", build: "18"},
{street: "Ноградская ул", build: "25"},
{street: "Ноградская ул", build: "3"},
{street: "Ноградская ул", build: "4"},
{street: "Ноградская ул", build: "5"},
{street: "Ноградская ул", build: "6"},
{street: "Ноградская ул", build: "8"},
{street: "Поспелова ул", build: "11"},
{street: "Поспелова ул", build: "12"},
{street: "Поспелова ул", build: "13"},
{street: "Поспелова ул", build: "15"},
{street: "Поспелова ул", build: "17"},
{street: "Поспелова ул", build: "18"},
{street: "Поспелова ул", build: "21"},
{street: "Поспелова ул", build: "22"},
{street: "Поспелова ул", build: "27"},
{street: "Поспелова ул", build: "29"},
{street: "Поспелова ул", build: "33"},
{street: "Поспелова ул", build: "7"},
{street: "Поспелова ул", build: "9"},
{street: "Советская ул", build: "137"},
{street: "Советская ул", build: "28"},
{street: "Советская ул", build: "2Б"},
{street: "Советская ул", build: "34"},
{street: "Советская ул", build: "36"},
{street: "Советская ул", build: "38"},
{street: "Спортивная ул", build: "4"},
{street: "Суворова ул", build: "21"},
{street: "Суворова ул", build: "23"},
{street: "Школьная ул", build: "12"},
{street: "Школьная ул", build: "14"},
{street: "Школьная ул", build: "16"},
{street: "Школьная ул", build: "31"},
{street: "Юбилейная ул", build: "3"},
{street: "Юбилейная ул", build: "6"},
], streets: [{street: "18 Партсъезда ул"},
{street: "8 Марта ул"},
{street: "Артема ул"},
{street: "Кислородная ул"},
{street: "Коммунистическая ул"},
{street: "Ленина ул"},
{street: "Макаренко ул"},
{street: "Мира ул"},
{street: "Ноградская ул"},
{street: "Поспелова ул"},
{street: "Советская ул"},
{street: "Спортивная ул"},
{street: "Суворова ул"},
{street: "Школьная ул"},
{street: "Юбилейная ул"},
] };
