city_streets["urga"] = {builds: [{street: "Волгоградская ул", build: "1"},
{street: "Волгоградская ул", build: "22"},
{street: "Волгоградская ул", build: "22а"},
{street: "Волгоградская ул", build: "22б"},
{street: "Волгоградская ул", build: "25"},
{street: "Волгоградская ул", build: "27"},
{street: "Волгоградская ул", build: "5"},
{street: "Волгоградская ул", build: "7"},
{street: "Исайченко ул", build: "13"},
{street: "Исайченко ул", build: "17"},
{street: "Исайченко ул", build: "19"},
{street: "Исайченко ул", build: "3"},
{street: "Исайченко ул", build: "5"},
{street: "Исайченко ул", build: "7"},
{street: "Кирова ул", build: "12"},
{street: "Кирова ул", build: "16"},
{street: "Кирова ул", build: "18"},
{street: "Кирова ул", build: "20"},
{street: "Кирова ул", build: "20а"},
{street: "Кирова ул", build: "22"},
{street: "Кирова ул", build: "24"},
{street: "Кирова ул", build: "25"},
{street: "Кирова ул", build: "26"},
{street: "Кирова ул", build: "27"},
{street: "Кирова ул", build: "28"},
{street: "Кирова ул", build: "29"},
{street: "Кирова ул", build: "37"},
{street: "Кирова ул", build: "39"},
{street: "Кирова ул", build: "41"},
{street: "Кирова ул", build: "43"},
{street: "Кирова ул", build: "9"},
{street: "Комсомольская ул", build: "2"},
{street: "Комсомольская ул", build: "21"},
{street: "Комсомольская ул", build: "23"},
{street: "Комсомольская ул", build: "27"},
{street: "Комсомольская ул", build: "4"},
{street: "Комсомольская ул", build: "6"},
{street: "Комсомольская ул", build: "8"},
{street: "Краматорская ул", build: "2"},
{street: "Краматорская ул", build: "2а"},
{street: "Краматорская ул", build: "2б"},
{street: "Кузбасский пр ", build: "14"},
{street: "Кузбасский пр ", build: "18а"},
{street: "Ленинградская ул", build: "33"},
{street: "Ленинградская ул", build: "35"},
{street: "Ленинградская ул", build: "36"},
{street: "Ленинградская ул", build: "38"},
{street: "Ленинградская ул", build: "40"},
{street: "Ленинградская ул", build: "42"},
{street: "Ленинградская ул", build: "46"},
{street: "Ленинградская ул", build: "48"},
{street: "Ленинградская ул", build: "50"},
{street: "Ленинградская ул", build: "52"},
{street: "Ленинградская ул", build: "58"},
{street: "Ленинградская ул", build: "60"},
{street: "Леонова ул", build: "6"},
{street: "Леонова ул", build: "6а"},
{street: "Леонова ул", build: "8"},
{street: "Леонова ул", build: "8а"},
{street: "Максименко ул", build: "10"},
{street: "Максименко ул", build: "11"},
{street: "Максименко ул", build: "2"},
{street: "Максименко ул", build: "22"},
{street: "Максименко ул", build: "24"},
{street: "Максименко ул", build: "3"},
{street: "Максименко ул", build: "4"},
{street: "Максименко ул", build: "5"},
{street: "Максименко ул", build: "6"},
{street: "Максименко ул", build: "7"},
{street: "Максименко ул", build: "8"},
{street: "Максименко ул", build: "9"},
{street: "Машиностроителей ул", build: "10"},
{street: "Машиностроителей ул", build: "12"},
{street: "Машиностроителей ул", build: "16"},
{street: "Машиностроителей ул", build: "22"},
{street: "Машиностроителей ул", build: "30"},
{street: "Машиностроителей ул", build: "45"},
{street: "Машиностроителей ул", build: "49"},
{street: "Машиностроителей ул", build: "51"},
{street: "Машиностроителей ул", build: "53"},
{street: "Машиностроителей ул", build: "55а"},
{street: "Машиностроителей ул", build: "57"},
{street: "Металлургов Бульвар ", build: "1"},
{street: "Металлургов Бульвар ", build: "2"},
{street: "Металлургов Бульвар ", build: "4"},
{street: "Металлургов Бульвар ", build: "5"},
{street: "Мира ул", build: "1"},
{street: "Мира ул", build: "13"},
{street: "Мира ул", build: "13а"},
{street: "Мира ул", build: "15"},
{street: "Мира ул", build: "15а"},
{street: "Мира ул", build: "17"},
{street: "Мира ул", build: "3"},
{street: "Мира ул", build: "3а"},
{street: "Мира ул", build: "5"},
{street: "Мира ул", build: "5а"},
{street: "Мира ул", build: "7а"},
{street: "Московская ул", build: "10"},
{street: "Московская ул", build: "18"},
{street: "Московская ул", build: "2"},
{street: "Московская ул", build: "30"},
{street: "Московская ул", build: "31"},
{street: "Московская ул", build: "35"},
{street: "Московская ул", build: "36"},
{street: "Московская ул", build: "37"},
{street: "Московская ул", build: "37а"},
{street: "Московская ул", build: "39"},
{street: "Московская ул", build: "4"},
{street: "Московская ул", build: "40"},
{street: "Московская ул", build: "41"},
{street: "Московская ул", build: "42"},
{street: "Московская ул", build: "43"},
{street: "Московская ул", build: "44"},
{street: "Московская ул", build: "46"},
{street: "Московская ул", build: "4а"},
{street: "Московская ул", build: "51"},
{street: "Московская ул", build: "6"},
{street: "Московская ул", build: "6а"},
{street: "Московская ул", build: "8"},
{street: "Никитина ул", build: "28"},
{street: "Никитина ул", build: "28а"},
{street: "Никитина ул", build: "36"},
{street: "Никитина ул", build: "38"},
{street: "Никитина ул", build: "73"},
{street: "Никитина ул", build: "75"},
{street: "Павлова ул", build: "1"},
{street: "Павлова ул", build: "12"},
{street: "Павлова ул", build: "14"},
{street: "Павлова ул", build: "16"},
{street: "Павлова ул", build: "3"},
{street: "Павлова ул", build: "5"},
{street: "Победы пр ", build: "1"},
{street: "Победы пр ", build: "10"},
{street: "Победы пр ", build: "10а"},
{street: "Победы пр ", build: "10б"},
{street: "Победы пр ", build: "11"},
{street: "Победы пр ", build: "12"},
{street: "Победы пр ", build: "12а"},
{street: "Победы пр ", build: "12Б"},
{street: "Победы пр ", build: "14"},
{street: "Победы пр ", build: "14а"},
{street: "Победы пр ", build: "16"},
{street: "Победы пр ", build: "16а"},
{street: "Победы пр ", build: "16б"},
{street: "Победы пр ", build: "17"},
{street: "Победы пр ", build: "18"},
{street: "Победы пр ", build: "19"},
{street: "Победы пр ", build: "2"},
{street: "Победы пр ", build: "21"},
{street: "Победы пр ", build: "23"},
{street: "Победы пр ", build: "25"},
{street: "Победы пр ", build: "27"},
{street: "Победы пр ", build: "28Б"},
{street: "Победы пр ", build: "29"},
{street: "Победы пр ", build: "2а"},
{street: "Победы пр ", build: "3"},
{street: "Победы пр ", build: "31"},
{street: "Победы пр ", build: "32б"},
{street: "Победы пр ", build: "38"},
{street: "Победы пр ", build: "38а"},
{street: "Победы пр ", build: "40а"},
{street: "Победы пр ", build: "41"},
{street: "Победы пр ", build: "43"},
{street: "Победы пр ", build: "45"},
{street: "Победы пр ", build: "47"},
{street: "Победы пр ", build: "49"},
{street: "Победы пр ", build: "4а"},
{street: "Победы пр ", build: "5"},
{street: "Победы пр ", build: "51"},
{street: "Победы пр ", build: "53"},
{street: "Победы пр ", build: "6а"},
{street: "Победы пр ", build: "7"},
{street: "Победы пр ", build: "8а"},
{street: "Победы пр ", build: "8б"},
{street: "Победы пр ", build: "9"},
{street: "Строительная ул", build: "16"},
{street: "Строительная ул", build: "17"},
{street: "Строительная ул", build: "18"},
{street: "Строительная ул", build: "19"},
{street: "Строительная ул", build: "20"},
{street: "Строительная ул", build: "21"},
{street: "Строительная ул", build: "22"},
{street: "Строительная ул", build: "24"},
{street: "Строительная ул", build: "25"},
{street: "Строительная ул", build: "27"},
{street: "Строительная ул", build: "29"},
{street: "Строительная ул", build: "31"},
{street: "Строительная ул", build: "33"},
{street: "Строительная ул", build: "37"},
{street: "Строительная ул", build: "39"},
{street: "Строительная ул", build: "41"},
{street: "Строительная ул", build: "43"},
{street: "Строительная ул", build: "45"},
{street: "Строительная ул", build: "47"},
{street: "Строительная ул", build: "49"},
{street: "Тургенева ул", build: "39"},
{street: "Тургенева ул", build: "41"},
{street: "Тургенева ул", build: "43"},
{street: "Тургенева ул", build: "45"},
{street: "Тургенева ул", build: "47"},
{street: "Тургенева ул", build: "49"},
{street: "Тургенева ул", build: "51"},
{street: "Тургенева ул", build: "53"},
{street: "Тургенева ул", build: "55"},
{street: "Тургенева ул", build: "57"},
{street: "Тургенева ул", build: "61"},
{street: "Тургенева ул", build: "63"},
{street: "Фестивальная ул", build: "1"},
{street: "Фестивальная ул", build: "11"},
{street: "Фестивальная ул", build: "12"},
{street: "Фестивальная ул", build: "1а"},
{street: "Фестивальная ул", build: "1б"},
{street: "Фестивальная ул", build: "2а"},
{street: "Фестивальная ул", build: "3"},
{street: "Фестивальная ул", build: "4"},
{street: "Фестивальная ул", build: "4а"},
{street: "Фестивальная ул", build: "4б"},
{street: "Фестивальная ул", build: "4в"},
{street: "Фестивальная ул", build: "9"},
], streets: [{street: "Волгоградская ул"},
{street: "Исайченко ул"},
{street: "Кирова ул"},
{street: "Комсомольская ул"},
{street: "Краматорская ул"},
{street: "Кузбасский пр "},
{street: "Ленинградская ул"},
{street: "Леонова ул"},
{street: "Максименко ул"},
{street: "Машиностроителей ул"},
{street: "Металлургов Бульвар "},
{street: "Мира ул"},
{street: "Московская ул"},
{street: "Никитина ул"},
{street: "Павлова ул"},
{street: "Победы пр "},
{street: "Строительная ул"},
{street: "Тургенева ул"},
{street: "Фестивальная ул"},
] };
